### ISSUE TITLE
Import UK OER Programme Projects

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1000]
The UK OER Programme was pretty well documented: 
http://www.webarchive.org.uk/wayback/archive/20140614021531/http://www.jisc.ac.uk/whatwedo/programmes/elearning/oer.aspx
The side links to all/most included projects. Individual projects are well documented:
http://www.webarchive.org.uk/wayback/archive/20140614073412/http://www.jisc.ac.uk/whatwedo/programmes/elearning/oer2/csapopencascade.aspx

We should analyse, if we could import these data as well. @philboeselager @acka47 could you have a look at this?

@drrobertfarrow: What do you think about this?

**Comment by drrobertfarrow** [comment]
I have asked Katy to import this data!
