### ISSUE TITLE
Strategy for fake accounts

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1001]
Sometime we have registration of users which doesn't seem to be serious and sometimes may be spam.
For example at the moment Lisa:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Person#urn:uuid:d11d6d6f-de4b-4c41-962d-6ec9798795e6
I will mail to her next week and ask why she uses a address in Berlin and a pin in the nowhere. Maybe she is really interested, maybe not.

I think we should collect some thoughts on our strategy for "fake account". First suggestion: First name and last name should be obligatory for saving a personal profile.

**Comment by formimkontext** [comment]
You are right, we should think about a strategy for fake accounts. But in this case, i can tell you that Lisa is a real person. I told her about the project and she might be interested in what we are doing.

**Comment by trugwaldsaenger** [comment]
Yes, Lisa is real - I contacted her on Xing last year!

**Comment by karindr** [comment]
OK, so I will ask her about adding a last name and and about her strange pin in the middle of nowhere-

What do you think about my suggestion: First name and last name should be obligatory for saving a personal profile.

@literarymachine is this complicated to realise?

**Comment by acka47** [comment]
> @literarymachine is this complicated to realise?

As we currently only have one "full name" field (which isn't required) this would mean a change in the data model. Regarding the global character of the OER world map the current approach seems to be the best choice, see e.g. https://www.w3.org/International/questions/qa-personal-names.

Also, we can't make people submit their correct full names and location. Obviously, Lisa wants to have an anonymous account and doesn't like to share her location. She probably won't add her real last name when last names are obligatory. Thus, I don't see how we can improve this from the side of data model and web form.

**Comment by karindr** [comment]
OK, I see the implications. This would be no good way.

But I like the idea to encourage the users to enter their real full name although we can't "force" them to. What do you think about changing the text behind the questionmark-button from "Your full name" to "Please enter your full name."?
