### ISSUE TITLE
Implement statistics dashboard

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1003]
Statistics should be displayed in a customizable dashboard. As a first approach, this will be based on [Kibana](https://www.elastic.co/products/kibana).

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/assets/html/dashboard.html

**Comment by karindr** [comment]
Very interesting!

@literarymachine: There is action instead of project and article instead of story in the "Entries by Type" section.

**Comment by literarymachine** [comment]
> @literarymachine: There is action instead of project and article instead of story in the "Entries by Type" section.

Right, I'll add the aliases we use in the rest of the OER World Map front end!
