### ISSUE TITLE
Add abbreviation to titles of entries

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1007]
Also, rename "Alternate Name" to "Abbreviation".

**Comment by acka47** [comment]
To make this clear: Is this about using `schema:alternateName` for abbreviations only or do we want to have an additional `abbreviation` field besides the alternate name?

**Comment by acka47** [comment]
I already thought about adding an "abbreviation" field in the past, see https://github.com/hbz/oerworldmap/issues/29#issuecomment-111415897 and already formulated an issue asking to add such a property to schema.org. Let me know if I shall open such an issue over there:

> ### Add property "abbreviatedName"

> An additional property `abbreviatedName` would be useful in order to mark up an abbreviation like it is often added in parentheses along with an official name of an organization, product etc., e.g. "United Nations (UN)", "Volkswagen (VW)" or "Playstation 4 (PS4)". Currently, there only exists the [`alternateName`](http://schema.org/alternateName) which can be used for abbreviations but covers more than these.

> This should be a subproperty of `alternateName` used on type `Thing` with expected values of type Text. Possible description: "An abbreviated name for the thing. For example, UN, VW, PS4."

**Comment by literarymachine** [comment]
> To make this clear: Is this about using schema:alternateName for abbreviations only or do we want to have an additional abbreviation field besides the alternate name?

This is about using `schema:alternateName` for abbreviations.

**Comment by karindr** [comment]
That's good.

When it is deployed to production we habe to look for cases with double abbreviations appearing in the title. We will have to fix these cases manually.

**Comment by acka47** [comment]
Also, there are some entries where `alternateName` doesn't contain an abbreviation.

**Comment by literarymachine** [comment]
> Also, there are some entries where alternateName doesn't contain an abbreviation.

Ok. So should I take `alternateName` for abbreviations now, or not?

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=hbz&filter.about.%40type=Organization#urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a

**Comment by acka47** [comment]
No changes to see. It is still called "alternate name" on beta.

**Comment by literarymachine** [comment]
> No changes to see. It is still called "alternate name" on beta.

This is not about the field name, but about the abbreviation (`alternateName`) being added to the title in brackets. Compare to https://oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a

**Comment by acka47** [comment]
I understand. But it also says in the original issues comment:

> Also, rename "Alternate Name" to "Abbreviation".

I just noted in https://github.com/hbz/oerworldmap/issues/482#issuecomment-288350223:

> I noticed one thing that has to be improved: the alternate name is currently shown in brackets in the heading as well as later as single field. The second should be removed.

As soon as the abbreviation is only displayed in brackets behind the actual title, the label has only to be replaced in the editing form.

**Comment by literarymachine** [comment]
> Also, rename "Alternate Name" to "Abbreviation".

Fixed on beta.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
+1
