### ISSUE TITLE
(Minor) errors in template for personal profile

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1015]
The new fields in the template for the personal profile are missing correct help text displayed when the mouse is hovering the question mark button. there should be at the field:
Organizer of: "Enter events that you are organizing."
Presenter at: "Enter events that you are speaking at.
Attending: "Enter events that you are attending."

I fond this phenomenon in one of the other templates too but I did not notice where. Maybe you could look at this systematically?

**Comment by literarymachine** [comment]
> Maybe you could look at this systematically?

@acka47 please check https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties for this.
