### ISSUE TITLE
Contact Person for organisations, behaviour of the field

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1020]
I tested on beta: You can enter a contact person by entering a name even if this person is not registered on the map, but the name is not displayed then and there is no error message or any reaction on this.

Shouldn't we be able to name people here who aren't registered on the map? We can't register these people but the information that there is a contact person and who it is is interesting.

**Comment by literarymachine** [comment]
> You can enter a contact person by entering a name even if this person is not registered on the map, but the name is not displayed then and there is no error message or any reaction on this.

This field functions as all other fields that *link* to another entry: if you don't select one of the options that are presented, nothing is saved.

> Shouldn't we be able to name people here who aren't registered on the map? We can't register these people but the information that there is a contact person and who it is is interesting.

So far our policy has been that people have to put themselves on the map. I think anything else will bring problems regarding privacy. What do you think @trugwaldsaenger?

**Comment by karindr** [comment]
To make it clear I don't suggest to create profiles for these peoples. I think it may be useful to  be able to mention the name on the organisations profile. Should we ask our legal adviser whether mentioning somebody as contact person is an privacy issue?

**Comment by literarymachine** [comment]
>  Should we ask our legal adviser whether mentioning somebody as contact person is an privacy issue?

Yes. I don't think that it is in general very different to mention someone by clear name in another profile than it would be to create a profile page.

Also, pinging @acka47 on how we would integrate a contact person by name, not reference, into our data model.

**Comment by karindr** [comment]
As an example for an interesting project with a contact person:
http://openmedproject.eu/contact/

**Comment by acka47** [comment]
Related to https://github.com/hbz/oerworldmap/issues/1635

**Comment by trugwaldsaenger** [comment]
I will try to ask our legal advisor ASAP.

**Comment by literarymachine** [comment]
Against our privacy policy, closing.
