### ISSUE TITLE
Enhancing entering the localization on the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1021]
(There was feedback from a user working on his profile that pointed me on this problem.)
At the moment for entering location there are a drop down field, a text, a map and a lot of fields to type in.

- Some people will begin by reading the text, that’s ok.
- Some people will start by clicking on the map (me ;-), nothing happens, so they may read the text, ok.
- Some people will see the drop down field on the top and will drop it down and will start entering an address by copying it in. Doesn’t work, will read text, ok. Will type in, works, ok. 
- Some people will see the fields pre-filled with “Address”, “Zip”, “City” and will start to fill in their information here, but will get no automatic coordinates, not ok.

Summarized: I think we should hide the fields pre-filled with “Address”, “Zip”, “City” for the start and only give the opportunity to see them if somebody needs to enter additional information like missing house numbers and so on maybe with a button named for example “Refine the address”.

**Comment by literarymachine** [comment]
Fixed by new UI.
