### ISSUE TITLE
Add subject fields to search index

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1022]
As discussed with @acka47 we should add the subject classification (and the levels of education classification) to the search index, if not included yet.

**Comment by literarymachine** [comment]
@philboeselager the field is indexed, like all fields are. But we need to add `about.about.name.@value` and `about.audience.name.@value` to the fields in `conf/search.conf`.

**Comment by philboeselager** [comment]
@literarymachine Given the [last commit](https://github.com/hbz/oerworldmap/commit/359522170176859cab340ebf6a5f3088890899c0), the framer reduces the `audience` to its ID, which is an URL in this case. How would reconfigure it to let all `audience` data pass?
