### ISSUE TITLE
Improve search experience

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1024]
I talked with @trugwaldsaenger about that we need to think about improving search in general. He already opened a very specific issue regarding search improvement, see #1022. Another particular thing he mentioned was that a search gives too many results which makes orientation hard. This ticket addresses the general issue of search improvement and will probably result in a number of sub issues.

As far as I understand, you can influence search from two different sides: query and indexing.

## Querying

Regarding the queries, we currently seem to use [fuzzy search](https://www.elastic.co/guide/en/elasticsearch/guide/current/fuzzy-query.html) features (included with https://github.com/hbz/oerworldmap/pull/752?) which for are responsible for example that I get 375 results for [querying "Pohl"](https://oerworldmap.org/resource/?q=pohl) although the string "Pohl" actually only occurs on one entry. I think we could improve in this end by limiting the fuzzy search featured without disabling support for stripping accents (#684) and the like (#605).

## Indexing

Generally, these are the questions to be answered for indexing each field, right?

1. include it at all?
2. analyzed or not_analyzed?
2.a. if analyzed, which analyzer?
3. how much boosting?

## How to proceed?

I already pointed to some possible improvements for querying above re. fuzzy earch. Please let us know if we should be more concrete and what information you need for improving search from the query side.

Regarding the indexing, I think we should first clarify which fields should be included and if they are analyzed or not and then we can discuss boosting. Here are my first thoughts.

- Exclude from search: 
  - `email`
  - all information inherited from other world map entitites, with exception of those of type `Concept` (see #1022) (This means, for example, that persons working for hbz are only listed as result for [query "hbz"](https://oerworldmap.org/resource/?q=hbz) if they have written the string somewhere in their bio  – as is currently the case.) 
- URLs: set as not_analyzed (it seems to be like this already)

I think it would make sense to include all other fields. What do other think?

**Comment by literarymachine** [comment]
> I already pointed to some possible improvements for querying above re. fuzzy earch. Please let us know if we should be more concrete and what information you need for improving search from the query side.

I think it would make a lot of sense if you could actually provide some examples of which results you would expect for a given search. If we tune the index or or the actual query to deliver the required results is an implementation detail you need not necessarily worry about. That being said, actual small tickets defining single use cases - such as #1022 - would make more sense than this general issue here.

**Comment by acka47** [comment]
Done, see #1025 and #1026. Closing.
