### ISSUE TITLE
Limit fuzzy search

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1025]
As noted in #1024 searches give far too much results. E.g. a [search for "Pohl"](https://oerworldmap.org/resource/?q=pohl) gives 375 results although the string "Pohl" actually only occurs on one entry. We should remove results from the list that come up when deleting a character from the search string.

**Comment by philboeselager** [comment]
Re-check when #1100 is merged and deployed.

**Comment by philboeselager** [comment]
Re-check when #1179 is merged and deployed. (#1100 is obsolete.)

**Comment by literarymachine** [comment]
>  E.g. a [search for "Pohl"](https://oerworldmap.org/resource/?q=pohl) gives 375 results although the string "Pohl" actually only occurs on one entry.

Fixed on production.
