### ISSUE TITLE
Search over all fields with few exceptions

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1027]
We should basically offer search over all of the fields. I collected exceptions to this rule in #1024:

> - Exclude from search: 
>    - `email`
>    - all information inherited from other world map entitites, with exception of those of type `Concept` (see #1022) ...
>   - URLs: set as not_analyzed (it seems to be like this already)

**Comment by literarymachine** [comment]
Closing since #1024 and #1022 are resolved.
