### ISSUE TITLE
Strange results for searching for "Universität"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1029]
When searching for "Universität" (to find the German universities) I get a list of all universities but not the "Universitäten" on the top. Is this ok? I don't think so. See (my browser language is English):
![image](https://cloud.githubusercontent.com/assets/18674205/22019981/2b95d656-dcb6-11e6-9ff1-a9daaf80ec60.png)

**Comment by acka47** [comment]
This is probably related to #1025.

**Comment by literarymachine** [comment]
> This is probably related to #1025.

I don't think so. If you switch you browser to German, you will see that the search results make sense:

![screenshot from 2017-01-17 14-46-03](https://cloud.githubusercontent.com/assets/149825/22022840/e4a6df98-dcc3-11e6-8e53-d7179583c962.png)

The background is that the resources' names etc are indexed and searched in all languages, but the results are displayed in the currently set language.

**Comment by karindr** [comment]
I am not wondering why the names of the German universities are displayed in English, that's clear. But I assumed that the entries with "Universität" in one of the name fields would be before the other without "Universität" in one of the name fields. I don't understand why for example Université Numérique Juridique Francophone is displayed nearly at the top. There is no German translation for its name in the entry.

Maybe it is related to #1025 as @acka47 thinks?

**Comment by philboeselager** [comment]
> But I assumed that the entries with "Universität" in one of the name fields would be before the other without "Universität" in one of the name fields. I don't understand why for example Université Numérique Juridique Francophone is displayed nearly at the top.

In general, our search algorithm is a "multidimensional" one. There is no such strict rule as "It appears in the title as a whole word, therefore it's got to be on top." It is all about different weights of different kinds of matching. Matching aspects are:

- length of field to be searched in
- number of hits over all fields
- weights of matched fields

Furthermore, we use search helpers as truncated words. Searching for "Universität" reveals hits for "Universit", "Universi", "Univers" and so on. We use this mechanism to make benefit of auto completion.

**Comment by philboeselager** [comment]
... Nonetheless, we might make progress in the sense of stricter search results, if we modify the index as follows:

	"title_analyzer": {
	    "filter": [
		"title_filter",
		"asciifolding_preserve_original",
		"autocomplete_filter",
		"lowercase"
	    ], ...
	}

	"title_analyzer": {
	    "filter": [
		"title_filter",
		"asciifolding_preserve_original",
		"lowercase"
	    ], ...
	}

and use `title_search_analyzer` as follows:

	<field>: { ...
		"@value": {
		  "fields": {
			"simple_tokenized": {
			  "search_analyzer": "standard",
			  "type": "string",
			  "analyzer": "simple"
			},
			"variations": {
			  "search_analyzer": "title_search_analyzer",
			  "type": "string",
			  "analyzer": "title_analyzer"
			},
			"@value": {
			  "type": "string"
			}
		  },
		  "type": "multi_field"
		}, ...
	    }
	}

@literarymachine Do you think this is a way to go?

**Comment by literarymachine** [comment]
> Do you think this is a way to go?

Honestly, I can't tell by looking at the configuration. Maybe a test case could clear this up, but also maybe we just have to boost the `name` field a bit further.

**Comment by philboeselager** [comment]
I've modified the ES mapping as a solution for this issue, see https://github.com/hbz/oerworldmap/commit/6cd66d2ba1f1ec905616b90ea46daccd0e9016a1, tested by https://github.com/hbz/oerworldmap/commit/555646ee4121f3d96f975a4b89b93af7d4a94224. When searching for "Universität", only items containing this whole exact term will be returned using this mapping. If you want to get hits for universities of different countries, you can still search for "Universit" for example.
I don't see any real downside - does anyone?

**Comment by philboeselager** [comment]
After having talked to @karindr it appeared to be better not to exclude "University" from the result list. Therefore, I've implemented a solution, that features exact hits stronger, but leaves similar words in the result list. Implemented in https://github.com/hbz/oerworldmap/pull/1104 .
