### ISSUE TITLE
Add field for telephone number  to personal profile

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1030]
If I understand it right in the schema.json
https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json
there is already "telephone" for "Person". We need to have a field in the template to enter the number and have it displayed in the personal profile.

Would it be very complicated to establish a checkbox there whether the person wants the number to be displayed or not? Background is that @trugwaldsaenger wants to generate a distribution list for all people connected to OERinfo-Stelle with telephone numbers but not all people may be willing to publish their number.

**Comment by literarymachine** [comment]
> Would it be very complicated to establish a checkbox there whether the person wants the number to be displayed or not?

Field-level visibility will indeed need some thought and is not implemented from one day to the next. Also, this would require an update to our privacy section which currently states that all information is (a) optionals and (b) public.
