### ISSUE TITLE
"Funded by" is displayed  on projects profile even when it is empty

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1031]
I think this is a bug, isn't it?

(There is a similar behaviour for "Available language" for services. But in the case of this I would not change the behaviour because it makes the people enter the languages in 90 % of the entries and that is really good!)

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:3bae094b-39d7-4ad1-9e5f-9599367edc96

**Comment by acka47** [comment]
Is it already deployed on production? I can't reproduce the original bug. Anyway, +1.
