### ISSUE TITLE
Translation of interface

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1034]
Would it be easy to provide a strings file to translate the interface to other languages? We could to portuguese and get help for spanish.

**Comment by literarymachine** [comment]
> Would it be easy to provide a strings file to translate the interface to other languages?

In general, yes! But we have #761 in the pipeline due to some residual strings that are unfortunately still hard coded. Also, the translation of the static pages ("About" etc) is already enabled, but some documentation is missing. We are planning to translate the site to German soon, I'll ping you here everything for a smooth translation is in place!

> We could to portuguese and get help for spanish.

That would be fantastic, thanks!

**Comment by literarymachine** [comment]
@tamielbr we finally made everything ready for translation! The process is described in the [README](https://github.com/hbz/oerworldmap#localizations). As for the `*.properties` files, they are translated using https://crowdin.com/. @acka47 and @karindr know more about the details!

**Comment by tamielbr** [comment]
Thanks! I will take a look at this as soon as I can.

**Comment by tamielbr** [comment]
Started with the 3 existing ``_pt`` files. Can you have a look and see if we should move with pushing them?

**Comment by literarymachine** [comment]
> Started with the 3 existing _pt files. Can you have a look and see if we should move with pushing them?

@acka47 can you take a look and assist @tamielbr with crowdin and all of that?

**Comment by acka47** [comment]
I must have overlooked this. Sorry for the belated answer. 

Yes, we are doing all the translation stuff on CrowdIn by now, see https://crowdin.com/project/oerworldmap.

Please login to CrowdIn (create an account first or login with GitHub, Twitter etc.) and use their interface for translation. You can select Portuguese and then start translating strings from the different files. It is quite intuitive I think. Let me know if you have any questions.

**Comment by acka47** [comment]
Closing this ticket as @tamielbr has already done a lot of translations at CrowdIn, see https://crowdin.com/profile/tamiel/activity.
