### ISSUE TITLE
Insert Text in the welcome window (homepage)

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1038]
"Announcement" formatted as heading like "Currently on the Map" below " More Statistics – Recent Additions" and then as standard paragraph:

```html
Please contribute to a better understanding of the OER movement and take part in the <a href="http://fluidsurveys.com/s/rcoer-stakeholdersurvey/">OER stakeholder survey</a> from<a href="http://www.col.org/”>Commonwealth of Learning (COL)</a>. For more information on the survey visit <a href="http://rcoer.col.org/”>OER Regional Consultations</a>.
```

((Ich bin jetzt im Wochenende, falls es Fragen gibt, wendet euch bitte an @trugwaldsaenger.))

**Comment by literarymachine** [comment]
On beta, since #908 is fixed you might have to open a new private / incognito window.

**Comment by acka47** [comment]
It looks like desired by the actual issue text. I am not sure that this will attract much attention. A frame and/or another background colour would help. Just my 2 cents...

**Comment by trugwaldsaenger** [comment]
>  I am not sure that this will attract much attention. A frame and/or another background colour would help. Just my 2 cents...

Good point. I think we could include a horizontal line like the one on the top of the box between the Statistics and the announcement. We also could experiment with using colour, e.g. we could show the background or the headline in green. Maybe @j0hj0h or @formimkontext can help us here? Anyhow I would think that we can move the announcement to production and do the refinements later...

**Comment by trugwaldsaenger** [comment]
Maybe something like +++Announcement+++ would work as well...
