### ISSUE TITLE
Formalize a schedule for blog updates

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#104]
We didn't manage to make the blog schedule we agreed for Open Education Week, and it's easy for all of us to find more pressing things to do than blog but we should build momentum and interest through regular updates.

I think that the suggestion of each writing updates after the team meeting is a good one, but risks bunching all the posts too close together so it may be better to schedule them for publication at different times.

My initial suggestion would be that Jan and myself aim to blog twice per month and other team members aim to publish every six weeks - but we should discuss this and the decision obviously rests with Jan.

**Comment by acka47** [comment]
The topic of writing more blog posts, journal articles etc comes up again anda again. I guess we won't get this sorted out unless we have somebody solely responsible for writing/marketing or all of us have more time for the world map work. Closing.
