### ISSUE TITLE
Reduce indexing time

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1044]
See e.g. #1042. Reducing the scope of documents that are re-indexed after a commit from two to one link levels. This will also reduce the size of the indexed documents significantly, but we have to double check in the front-end, the filters and the stats that this does not break anything.

**Comment by literarymachine** [comment]
See e.g.

https://oerworldmap.org/resource/urn:uuid:abc8c7e9-4738-433c-8550-7af52996085e.json

vs

https://beta.oerworldmap.org/resource/urn:uuid:abc8c7e9-4738-433c-8550-7af52996085e.json

**Comment by acka47** [comment]
I like. +1 (I only briefly checked whether filters are broken. It looks ok to me.)
