### ISSUE TITLE
Saving is sometimes slow so some people save their entries several times

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1045]
We had the case of a person saving his entry seven times. As he said, the template seemed not to react and so he hit the save button again and again. Since we have to remove the entries ourselves, it would be better to have a spinner displayed that shows that the website is working.

**Comment by literarymachine** [comment]
@j0hj0h please add the spinner while a form is being saved.

**Comment by literarymachine** [comment]
On beta, where the saving times should also be better now.

**Comment by karindr** [comment]
Tested with https://beta.oerworldmap.org/resource/urn:uuid:f7493175-38cb-4a9a-9372-575c6e1cce58. Yes it is faster now ant the entry is shown very quickly in the background so one knows it has been saved. Spinner is shown for some time. To me it seems ok.
