### ISSUE TITLE
Give editing rights to people at the moment of their registration

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1048]
As a visitor of the OER World Map I did some research for organisations and services on the map. Then I decide to register to the map to be part of the community and to contribute to the network. When I have registered myself I want to start editing my organisations/projects entry or add an entry. I want to start right now. I don’t want to wait maybe till after the weekend that somebody I wrote a mail to gives editing rights to me. On Monday I am working on something else and maybe I will not come back to the map and contribute like I wanted to.

**Comment by acka47** [comment]
I recently talked to @trugwaldsaenger and he was actually fine with giving every logged in user editing rights to the whole data (except other user's profiles). I always was in favour of this. So, let's open this up!

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/ all registered users can now add & edit entries.

**Comment by acka47** [comment]
Works like a charm. +1 Thanks!
