### ISSUE TITLE
Why do some entry field in the templates stay yellow?

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1050]
Maybe this is part of the browser side reaction, but I don't understand why it happens. For example see:
![image](https://cloud.githubusercontent.com/assets/18674205/22328929/12d1e122-e3bf-11e6-8236-7e1785cbbdee.png)

**Comment by literarymachine** [comment]
This is indeed your browser, the yellow indicates that you have entered that information into that field before.

**Comment by karindr** [comment]
OK. Thanks.
