### ISSUE TITLE
geografic centring shifts pins

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1052]
This is how the OER World Map looks in Califonia:

_
![shiftet pins](https://cloud.githubusercontent.com/assets/6639965/22349254/4234279a-e40f-11e6-98c7-bec05bcc49d3.PNG)

As you can see, all the pins are on the right side. Can we change this?

**Comment by literarymachine** [comment]
> Can we change this?

Yes, how would you like it to be? Should they simply repeat?

**Comment by trugwaldsaenger** [comment]
I think we should avoid putting pins to the map twice. I guess the best thing would be to order them symmetrical, so that the same amount of degrees longitude are covered on the left from the center as are on the right.

**Comment by j0hj0h** [comment]
But why should we avoid having them on each repetition? On most screens there wan't be any doublings visible anyway and if so ... if Italy appears again, it's logical, that the pins do as well – no?

Beside from that, having them repeated just means to change one line, as far as I see. The other solution is more complicate.

**Comment by karindr** [comment]
If the pins were duplicated we have to make sure that they aren't counted twice when clicking on "Search as I move the map". (But maybe this is technically totally separated anyway.)

**Comment by j0hj0h** [comment]
This shouldn't be a problem. The pins actually are only ones on the map. It's just a configuration option of the mapping library to display them repeatedly.

**Comment by trugwaldsaenger** [comment]
If there is no problem with the counting of the pins, I guess we should give it a chance and activate the repeated display - so please go ahead and change the line!

**Comment by j0hj0h** [comment]
The placemarks are repeated now (parameter `wrapX : true` for the vector source). @literarymachine I don't remember, which commit this happened ... so I manually assign it to @trugwaldsaenger

**Comment by literarymachine** [comment]
> I guess we should give it a chance and activate the repeated display - so please go ahead and change the line!

Fixed in the new UI.
