### ISSUE TITLE
Possibility to search what an editor created and edited

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1058]
We as administrators want to see what a person created and edited on the World Map. There should be a possibility to enter the name of an editor and then get a list of what he or she has done best starting with the latest contributions. This also could be a possibility to track down what a Spammer has done if we have one.

**Comment by literarymachine** [comment]
> There should be a possibility to enter the name of an editor and then get a list of what he or she has done best starting with the latest contributions.

You can already query for this using the email address of the account: https://oerworldmap.org/resource/?q=author:karin.driesen@hbz-nrw.de&sort=dateCreated:DESC

**Comment by karindr** [comment]
Really nice! 
But why is for example "OERcamp Ost" missing? This was also created by me, see:
https://oerworldmap.org/log/urn:uuid:7b0c8f88-379c-4103-8154-7177ceeebf43#892762b41fd4fb4c10eb50637ef21c3fee25f70c..f117b6627b24140ce5b3ce765942dbbedbfb0f1a

**Comment by literarymachine** [comment]
> This was also created by me, see:
https://oerworldmap.org/log/urn:uuid:7b0c8f88-379c-4103-8154-7177ceeebf43#892762b41fd4fb4c10eb50637ef21c3fee25f70c..f117b6627b24140ce5b3ce765942dbbedbfb0f1a

Currently, the `author` is always the person who last edited a resource, which in this case is someone else. The original author information is not lost, but it is not indexed at the moment. Once #1036 is merged, we will be able to differentiate between the author and the last contributor in the above query.

**Comment by karindr** [comment]
OK.
