### ISSUE TITLE
Add description text to iCal export

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1061]
The iCal export for https://beta.oerworldmap.org/resource/urn:uuid:abc8c7e9-4738-433c-8550-7af52996085e looks like this:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:https://oerworldmap.org/
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
GEO:52.5125;13.37828
LOCATION:In den Ministergärten 8;10117;Berlin;DE.BE;DE
URL:http://open-educational-resources.de/16/
UID:urn:uuid:abc8c7e9-4738-433c-8550-7af52996085e
ORGANIZER;CN="J&K - Jöran und Konsorten":MAILTO:info@joeran.de
DTSTART:20160228T000000
DTEND:20160301T235959
DTSTAMP:20170202T132025Z
CLASS:PUBLIC
SUMMARY:
END:VEVENT
END:VCALENDAR
```

What is missing, is the data from the `description` field which could be added in the iCal `SUMMARY`.

**Comment by acka47** [comment]
> What is missing, is the data from the `description` field which could be added in the iCal `SUMMARY`.

There actually is a `DESCRIPTION` field in iCal which is probably the better place to put the info.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:abc8c7e9-4738-433c-8550-7af52996085e.ics

**Comment by acka47** [comment]
+1
