### ISSUE TITLE
Failed to save comments

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1063]
I just tried to comment on following entry twice: 
https://oerworldmap.org/resource/urn:uuid:2ea2ab4b-9e73-447b-8c6b-be8ca9faa58f
Both times the comment was not saved, all content was lost.

**Comment by literarymachine** [comment]
Probably due to #1060

**Comment by literarymachine** [comment]
Comments do not fail to save, it is a matter of display; see https://oerworldmap.org/resource/urn:uuid:2ea2ab4b-9e73-447b-8c6b-be8ca9faa58f.json where two `comment` are referenced by `@id`:

https://oerworldmap.org/resource/urn:uuid:f1f27164-4ddd-4730-b9ec-5f6a24eac916.json
https://oerworldmap.org/resource/urn:uuid:9258ec74-d08b-43d2-98cd-033c9f2c67e1.json

**Comment by literarymachine** [comment]
Deployed to production, see https://oerworldmap.org/resource/urn:uuid:2ea2ab4b-9e73-447b-8c6b-be8ca9faa58f
