### ISSUE TITLE
Services show logos instead of license icon

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1064]
See: https://oerworldmap.org/resource/?q=&filter.about.keywords=textbooks#urn:uuid:0850cf11-287f-48d6-93c4-d3b8b1ce197d
![logo-issue](https://cloud.githubusercontent.com/assets/6639965/22569065/73cabbd4-e996-11e6-84ba-b6f261eb0347.PNG)

**Comment by literarymachine** [comment]
Due to #1060

**Comment by literarymachine** [comment]
Deployed to production, see https://oerworldmap.org/resource/urn:uuid:0850cf11-287f-48d6-93c4-d3b8b1ce197d
