### ISSUE TITLE
Couple profile creation to user registration

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1067]
The creation of a personal profile should be a fixed part of the registration process.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org where the initial profile creation is now part of the sign up process:

![screenshot from 2017-02-06 13 34 09](https://cloud.githubusercontent.com/assets/149825/22647376/67e1352c-ec71-11e6-963e-724547640616.png)

**Comment by acka47** [comment]
This is good for the start. I am not sure whether we should adjust the text of the registration confirmation:

![registration-confirmation](https://cloud.githubusercontent.com/assets/160292/22648035/ed391fd4-ec74-11e6-8865-49f978aa3585.png)

Instead of 

> Afterwards you may edit your personal profile using the drop down menu in the upper right corner.

we could write something like:

> Afterwards, please add more information to your personal profile using the drop down menu in the upper right corner.

We probably have to adjust the wording anyway during https://github.com/hbz/oerworldmap/milestone/15 – e.g. to take into account that people can add/edit any resources right from the start after registration.

**Comment by acka47** [comment]
I just noticed that the sentence "Leave you email address and choose a password to setup your profile on the OER World Map." has to be adjusted. 

Also, I just discussed via chat with @literarymachine the following problem: All fields are obilgatory (name, country, email address) and will be automatically added to the personal profile. But our current [privacy policy](https://oerworldmap.org/imprint) says that "no information is mandatory" but one may "publish any further information" including e-mail address.

So, we basically can not make this mandatory without adjusting the Terms and Conditions (see #1068). If we want to populate the personal profile with the registration soon, we will have to find an easy way to comply with the privacy policy. I think this can be done by not showing the email in the public profile automatically and by adjusting the registration form e.g. something like this:

> #### Register
> No account yet? Leave yourname, country and email address and choose a password to setup your account and an initial profile on the OER World Map.
> Your name (to be shown in your public profile)
> Your country (to be shown in your public profile)
> Your email address (for registration purposes, not to be shown on your profile)

**Comment by acka47** [comment]
@trugwaldsaenger I promised @literarymachine that on Thursday we will discuss this and decide on a solution.

**Comment by trugwaldsaenger** [comment]
> Also, I just discussed via chat with @literarymachine the following problem: All fields are obilgatory (name, country, email address) and will be automatically added to the personal profile. But our current privacy policy says that "no information is mandatory" but one may "publish any further information" including e-mail address.

Good point. Nevertheless I`m not sure if this is completly true. In order to register, it is necessary to include your name and your mail address, thats correct. And this information willl be reused for the automatic creation of the profile. But since you can always delete this information in your profile, it is not really mandatory for the profile, isn`t it?

I think we will find a way to handle this in our terms and conditions...

**Comment by literarymachine** [comment]
> I think we will find a way to handle this in our terms and conditions...

The question is before or after I deploy this?

**Comment by literarymachine** [comment]
Add a checkbox to the email field on the registration form "Add to profile", default checked.

**Comment by acka47** [comment]
We discussed that people should go to their profile page after their _first_ login. @literarymachine, please have a look how much time this would take to implement.

**Comment by literarymachine** [comment]
> We discussed that people should go to their profile page after their first login.

This is not trivial to do, because we don't have access to the relevant logs from within our application at the moment. With 799055c9841b82680cf2f31bb19cb4fd4d755f74 on beta I implemented a similar yet much simpler alternative. The login button that is shown after clicking the verification link from the email redirects to the profile page. The normal login button redirects to where the user came from (fixing #789).

**Comment by karindr** [comment]
Sounds reasonable.

**Comment by acka47** [comment]
Works as expected. +1 with one additional request: Add a "public" to the checkbox text so that it reads: "Add email address to public profile"

**Comment by literarymachine** [comment]
> Works as expected. +1 with one additional request: Add a "public" to the checkbox text so that it reads: "Add email address to public profile"

On beta
