### ISSUE TITLE
Refine and rename Terms and Conditions

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1068]
Re. https://oerworldmap.org/imprint which should be renamed to something like "Terms and Conditions" and information on licensing etc. should be added.

**Comment by literarymachine** [comment]
This is the issue for simply updating the text on https://oerworldmap.org/imprint

**Comment by acka47** [comment]
The table of content is broken at https://beta.oerworldmap.org/imprint. Compare with https://github.com/hbz/oerworldmap/blob/15-termsAndConditions/public/pages/Imprint.md where the ToC has sub-numbering.

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
The ToC looks ok now. Unfortunately, clicking on a link in the ToC I don't jump to the exact position I want but am a bit off – which is quite confusing. any idea why this is so?

**Comment by literarymachine** [comment]
>  Unfortunately, clicking on a link in the ToC I don't jump to the exact position I want but am a bit off – which is quite confusing. any idea why this is so?

I assume it has to do with the fixed header. Right, @j0hj0h?
