### ISSUE TITLE
Change text on empty profiles

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1071]
There are some questions as consequence of the new rights management  #1048 :
•	The upper part of the list where we gave editing rights is not showing the actual rights. Is that right? If this is right we only need this list to give administration rights (which we seldom will do, I think) and to find people who registered but did not create a profile. Is this right?
•	The users that have registered before the change have still no editing rights or did all registered persons get editing rights?
•	There has to be some changes in the “Contribute”-page, the FAQ page and the FAQ for Editors page in the wiki. I suggest to wait ca. 2 weeks to see if we will change back to restricting editing rights again or not, agreed?

**Comment by literarymachine** [comment]
> The upper part of the list where we gave editing rights is not showing the actual rights. Is that right? If this is right we only need this list to give administration rights (which we seldom will do, I think) and to find people who registered but did not create a profile. Is this right?

Yes. Finding users that did not create a profile probably won't be an issue any longer after #1067 is implemented.

> The users that have registered before the change have still no editing rights or did all registered persons get editing rights?

All registered users now have editing rights.

**Comment by karindr** [comment]
OK, understood.
Concerning #1067 we have to look at the static pages also if the registration process is mentioned there.
I change this from question to enhancement then.

**Comment by karindr** [comment]
The text above the template for the personal profile has to be changed too. In the moment there is:
"This is your personal profile. We appreciate very much if you want to share information about yourself with the OER community. If you want to enter data about an organization, service or something else, please write to info@oerworldmap.org to request editing rights."
Maybe we can skip completely or something like:
"This is your personal profile. We appreciate very much that you want to share information about yourself with the OER community."

**Comment by literarymachine** [comment]
> Maybe we can skip completely or something like

Given the fact that after #1067 is in place the personal profile will never be empty after registration, I think we could skip this completely. What do you think, @karindr and @acka47?

**Comment by karindr** [comment]
I think the suggested short version is still useful to encourage the users to share more information about themselves than name and country.

**Comment by acka47** [comment]
I would like to somehow encourage people to add more information. I doubt that more text is the best way to reach this goal so we might skip it completely. 

It's hard to say for me what measure will successfully make people add more information. Probably the best way to encourage this is by making profiles look nice and be useful. It will look nicer as soon as we have implemented single-resource view on a whole page (is there an issue for this) and it will be more useful when I can share bookmarks and my publications...

**Comment by literarymachine** [comment]
> I think the suggested short version is still useful to encourage the users to share more information about themselves than name and country.

Under which circumstances should the note be shown then? As stated above, profiles are usually not empty any more, so currently the note won't be displayed anyways.

**Comment by karindr** [comment]
I think it would be useful when you come to your profile for the first time (by the link from the registration email).

**Comment by literarymachine** [comment]
> I would like to somehow encourage people to add more information. I doubt that more text is the best way to reach this goal so we might skip it completely.

+1

**Comment by dobladov** [comment]
Fixed in the new UI with the following message

**Comment by karindr** [comment]
This is OK. (The link to change the information appears only if you have administration rights, so it is OK too.)

**Comment by karindr** [comment]
By the way, this text does not appear in crowdin so it can't be translated.
