### ISSUE TITLE
Add "Organizer of" (Event)-field to template for organisations

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1075]
This field is there in the personal profile template, it should be there in the organisations too.

**Comment by literarymachine** [comment]
@acka47 all you have to do is set `hidden=false` at https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Organization/edit.mustache#L51

**Comment by acka47** [comment]
Thanks, @literarymachine. Did this and also added the description text.
