### ISSUE TITLE
Create common base schema for JSON LD resources

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#108]

**Comment by philboeselager** [comment]
@literarymachine Can you please specify / clarify? I'm not sure about the goal. Thanks.

**Comment by literarymachine** [comment]
@philboeselager Basically, one can [combine JSON schemas](http://spacetelescope.github.io/understanding-json-schema/reference/combining.html). This would enable us to e.g. create a schema for JSON-LD (everything having a type and an optional ID) and then combine that with the properties of our actual classes. I have to admit, this sounds great in theory. Having had a closer look, it might not be that great in practice. For example, when combining schemas like described above, the [validator we use](https://github.com/fge/json-schema-validator) is quite cryprtic in its error reports, stating something along the lines of "One of the schemas contraints was not satisfied" (I don't recall exactly and can't check right now what the exact error was). It may be more pragmatic to just stick with what we have, even if it imposes a certain degree of redundancy.

**Comment by literarymachine** [comment]
I just saw that [json-schema-validator](https://github.com/fge/json-schema-validator) is looking for a new maintainer. Is this something we should consider? Having browsed through the code once or twice I must say it does appear to be quite complex...

**Comment by philboeselager** [comment]
I saw that already, but I do not match the criteria at all, as it is said: "Please contact me personally if you are interested. Ideally, you should be equally committed to this project **and** JSON Schema as a whole." I also do not know s.o. personally who has already committed to either JSV or JSON Schema. Do you?

**Comment by literarymachine** [comment]
Nope. Let's see how deep our committment becomes in the course of this project. Closing this ticket for now.
