### ISSUE TITLE
Recent additions list shows ID numbers instead of names

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1080]
See:
![image](https://cloud.githubusercontent.com/assets/18674205/22776895/c10ed824-eeb1-11e6-9884-2795afba894b.png)

**Comment by karindr** [comment]
It is the same on beta. I often work with this list even on beta. @literarymachine, could you please fix it?

**Comment by literarymachine** [comment]
Now also deployed to https://beta.oerworldmap.org/feed/
