### ISSUE TITLE
Implement basic HTML Form for Organization type

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#109]
Task for #29.

**Comment by acka47** [comment]
`sameAs` is missing in the web form. It is in the JSON schema, though: https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L639-L645

**Comment by acka47** [comment]
Also, `countryChampionFor` is missing. It is also already in the JSON schema: https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L688-L693

**Comment by literarymachine** [comment]
> Also, countryChampionFor is missing.

Fixed on beta & production.
