### ISSUE TITLE
Service connected to organisation is not found by country filter while organisation is

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1096]
This is the organisation:
https://oerworldmap.org/resource/?q=&filter.about.location.address.addressCountry=SE#urn:uuid:7129b006-aeff-4e9e-9a1b-3de25e7f3d50
This is the service:
https://oerworldmap.org/resource/urn:uuid:05a3084d-de9c-4a8d-82ed-074edd0d1d09

**Comment by karindr** [comment]
Same for Karlstad University and OER Sverige.

**Comment by literarymachine** [comment]
Fixed and deployed to production, see https://oerworldmap.org/resource/?q=&filter.about.location.address.addressCountry=SE where the `UR Skola` Service is now in the list.
