### ISSUE TITLE
Interne Links mit Sprungmarken und Ankern

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1097]
Ich möchte in einer Story auf beta als Test für production Links mit Sprungmarken und Ankern einsetzen. Das funktioniert eigentlich auch, aber es gibt eine Fehlermeldung. Was ist das Problem, wie kann ich interne Links umsetzen?
Die Links gehen von der (1) hinter der ersten Überschrift auf die erste Fußnote und von dem Return-Zeichen in der ersten Fußnote zurück zur (1) bei folgender Story:
https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Article#sverd
![image](https://cloud.githubusercontent.com/assets/18674205/23164255/7fcf88b6-f836-11e6-846e-b40999724682.png)

**Comment by literarymachine** [comment]
Momentan sind die Hashes der Listen-internen Navigation vorbehalten. Soll heißen, bei der URL https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Article#sverd wird versucht, eine Ressource mit der ID `sverd` zu laden und anzuzeigen, die natürlich nicht existiert.

Ein umfangreiches Refactoring des Front-Ends wird hier Abhilfe schaffen; das dauert aber noch ein bisschen. Leider ist eine Umsetzung im momentanen Front-End nicht ganz einfach zu machen.

**Comment by karindr** [comment]
OK, dann denke ich mir etwas anderes aus. Aber auf lange Sicht wäre es sinnvoll in Stories Sprungmarken verwenden zu können.

**Comment by j0hj0h** [comment]
@literarymachine ... es wäre ja auch möglich, den article content zu parsen und sprunglinks ein eigenes behaviour zu geben. Also sowas:

`<a href="#sverd" data-behaviour="jump-to-column-fragment">...</a>`

**Comment by literarymachine** [comment]
> es wäre ja auch möglich, den article content zu parsen und sprunglinks ein eigenes behaviour zu geben. 

Machbar ist das alles auf jeden Fall; die Frage ist, ob es in der momentanen Front-End-Version noch Sinn macht.

**Comment by karindr** [comment]
Ich habe mich für den aktuellen Artikel arrangiert. Wann plant ihr denn den Wechsel?

**Comment by literarymachine** [comment]
> Ich habe mich für den aktuellen Artikel arrangiert. Wann plant ihr denn den Wechsel?

Das kommt ganz darauf an, was an der momentan Version erst alles noch gemacht werden soll / muss. Siehe z.B. https://github.com/hbz/oerworldmap/issues/875#issuecomment-281650787.

**Comment by karindr** [comment]
Ende April finde ich ok. Bis dahin können wir uns ohne Sprungmarken behelfen. 

Und wie transferieren wir jetzt dieses Issue zum neuen UI?

**Comment by literarymachine** [comment]
> Und wie transferieren wir jetzt dieses Issue zum neuen UI?

Es bleibt einfach offen, bis es implementiert ist, würde ich sagen.

**Comment by karindr** [comment]
+1

**Comment by karindr** [comment]
Betrifft das eigentlich auch die statischen Seiten, also beispielsweise die FAQ?
https://oerworldmap.org/FAQ
Hier würde sich eine Liste der Fragen vorab mit Sprunglinks nach unten zu Fragen und Antworten anbieten wie auf der "FAQ for editors":
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors
Diese Seite soll ja auch eine statische Seite auf oerworldmap.de werden ( #905).

**Comment by karindr** [comment]
To be able to link to sections of the static pages would be very helpful for better explaining to the users, for example from definitions of the entry types to sections on the contribute page.

**Comment by literarymachine** [comment]
You can do that, e.g. https://oerworldmap.org/imprint#privacy

Or am I missing something?

**Comment by karindr** [comment]
Interesting. The structure of the imprint page was something I wanted to have for the FAQ page. I think I was told that we can't add such links and anchors because of some problems in our workflow (see above). If we can do this now it is great. How can I add it to the static pages and where have they gone? (I can start doing this not before next week, so no hurry!).

**Comment by literarymachine** [comment]
> I think I was told that we can't add such links and anchors because of some problems in our workflow (see above). 

I think that was never the case for the static pages but only for sections in entries such as stories.

> How can I add it to the static pages and where have they gone?

Take a look at https://github.com/hbz/oerworldmap-ui/edit/master/docs/imprint.md.
