### ISSUE TITLE
Country filter is limited to current selection

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#1101]
Whenn i am searching for ressources by using the country filter, the filter dropdown list is now limited the current selection. see: https://oerworldmap.org/resource/?q=&filter.about.location.address.addressCountry=AU

I can not add another country to the selection before i deactivated the current filter selection. This is a exclusive country filter problem and should be solved.

**Comment by literarymachine** [comment]
See https://oerworldmap.org/resource/?filter.feature.properties.location.address.addressCountry=AU
