### ISSUE TITLE
Link to external web pages as country reports

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1103]
See https://github.com/hbz/oerworldmap/issues/875#issuecomment-281286158

**Comment by acka47** [comment]
A combination of #479 and #609 would do the job, I think.

**Comment by literarymachine** [comment]
> A combination of #479 and #609 would do the job, I think.

So all `mentionedIn` for a country would be treated as a country report?

**Comment by acka47** [comment]
I just think a generic approach for all resources –  not only countries – should be considered as a solution. It might make more sense to use something narrower like `mainEntityOfPage` instead of `mentionedIn`. But we should first think about whether we want to link other resources than "country reports" to a country in the future...

**Comment by literarymachine** [comment]
> I just think a generic approach for all resources – not only countries – should be considered as a solution.

Yes, but I think that for country reports using #1032 is also a good way to go. With #1032 we want to implement an "internal" representation of external links anyways, and we could then also use those to link to external resource using "mentionedIn" because we have the resource (with title, url etc) in our database.

**Comment by literarymachine** [comment]
On beta bookmarks for external web pages can now be added, tagged with `countryreport:xy` and thus used as country reports:

![screenshot from 2017-03-02 16-13-23](https://cloud.githubusercontent.com/assets/149825/23513652/14b948ce-ff65-11e6-88f5-c12aef53a34e.png)

![screenshot from 2017-03-02 16-22-09](https://cloud.githubusercontent.com/assets/149825/23513657/197ce532-ff65-11e6-8047-236a03623308.png)

![screenshot from 2017-03-02 16-23-27](https://cloud.githubusercontent.com/assets/149825/23513662/1ec0dc7e-ff65-11e6-8671-738058632754.png)

**Comment by acka47** [comment]
+1 This solution looks fine to me. If this is deployed, we should add automatic archiving of the bookmarked links as well "link decoration" to make the references more stable. See also http://robustlinks.mementoweb.org/about/.

**Comment by karindr** [comment]
+1 This is a good solution!

The description section is also great to put a teaser in there!

See also #1110.
