### ISSUE TITLE
Order of events should start with the latest and go on to the oldest entries

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1111]
Jan and I agree that it looks very strange when you search for events and as first event you get events from 2013. It would be best to sort the events anti-chronological by default so you automatically get actual events as first.

Later on it would be nice to be able to change the way the events are sorted:

- chronological
- starting at a fixed month and year
- only show a chosen period

**Comment by karindr** [comment]
Nice that #1111 comes from Cologne ;-)

**Comment by trugwaldsaenger** [comment]
+1

**Comment by acka47** [comment]
Also add an option to filter upcoming events.

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/issues/27#issuecomment-267321204

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?filter.about.%40type=Event

Also on beta, attended events are now in reverse chronological order in the profile, see e.g. 
https://beta.oerworldmap.org/resource/urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf

> Also add an option to filter upcoming events as solution for #28.

This will be done with #28 and out of scope for this issue.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
