### ISSUE TITLE
Sharing story on facebook with more than one logo shows random logo

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1112]
I tested the sharing button on the new country report for Sweden:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Article#urn:uuid:c466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0
There is more than one picture in this article used in the way the logo normally is used and one out of the middle is shown. This is not very nice. See:
![image](https://cloud.githubusercontent.com/assets/18674205/23608337/357607f8-0269-11e7-9628-aaeb8f623883.png)

The other country report for Sweden has a kind of title picture this is shown very nice, see:
![image](https://cloud.githubusercontent.com/assets/18674205/23608282/fed5c4e0-0268-11e7-8146-e67418c5187c.png)

Do you have a solution to avoid the first case?

**Comment by karindr** [comment]
I tested it with a blog post from our blog. Maybe the biggest picture is chosen if there is no such thing as a featured image. 
![image](https://cloud.githubusercontent.com/assets/18674205/23647575/d363448c-0316-11e7-8b5d-876edc747961.png)

**Comment by literarymachine** [comment]
On production, the image used should now always be the image from the `image` field in the input template.

**Comment by karindr** [comment]
At the moment for the first case nothing has changed. This would be a case for the new images from @formimkontext, I think?

**Comment by dobladov** [comment]
> This would be a case for the new images from @formimkontext, I think?

When we have the default image from @formimkontext this case will be fixed for resources without images.

**Comment by karindr** [comment]
My test case is https://oerworldmap.org/resource/urn%3Auuid%3Ac466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0#view which does not work at the moment, see #1586.

**Comment by literarymachine** [comment]
> My test case is https://oerworldmap.org/resource/urn%3Auuid%3Ac466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0#view which does not work at the moment, see #1586.

See https://github.com/hbz/oerworldmap/issues/1586#issuecomment-400206065, there is nothing we can do about other people's server configuration. Can you use another test case and check if we can close this issue?

**Comment by dobladov** [comment]
In the new UI we always show this "oer world map" image in case there is no logo present. Closing

![image](https://user-images.githubusercontent.com/1938043/43712805-b8f5d800-9977-11e8-9a21-fc66856c435c.png)
