### ISSUE TITLE
Github Icon/Link in header got lost

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1118]
The github icon, which was right beneath the facebook and the twitter icon in the header got lost. I would include it again, since I used it quite often and I think it is brings valuable information for people, who are used to use Github.

**Comment by literarymachine** [comment]
@j0hj0h removed it on purpose after feedback from Hans. We can discuss this at the upcoming team meeting.

**Comment by dobladov** [comment]
We have the GitHub link now in the new header. closing

![image](https://user-images.githubusercontent.com/1938043/43710437-ee69ffc8-996f-11e8-9657-2eeb4dc2b7ab.png)
