### ISSUE TITLE
Refine Search Result "OERInfo"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1119]
Some time ago I searched for "[OERInfo](https://oerworldmap.org/resource/?q=OERinfo)". At that time the two most important results:

- https://oerworldmap.org/resource/urn:uuid:efed6ca2-b228-480f-be03-090a19de7b42
- https://oerworldmap.org/resource/urn:uuid:3f11cdbd-a74a-4aa4-83b3-b4148bfdbe82

appeart as the first hits, which was pretty fine. 

Now things have changed. The OER Info Richtlinie ranks somewhere between 20 and 30, though it includes "OERInfo" in its alternate name and as a tag. Many other results, which included "OERInfo" only as a tag are ranked higher.  I think the "alternate name" was included in the search ranking before. Could it be, that we lost it?

**Comment by acka47** [comment]
There are two tickets that will probably help here: #1026 #1120.

**Comment by philboeselager** [comment]
> There are two tickets that will probably help here: #1026 #1120.

That's a good hint @acka47 . Otherwise we would probably tend to "over-tweak" our search algorithm...
