### ISSUE TITLE
Autocomplete feature for cities/countries and zoom to cities/countries

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1123]
Hey, great work.

One suggestion: I think for the user it would be more convenient if there is an autocomplete feature for city names and country names which clearly indicates that the search term is correct.

One example for the city "Bonn" in germany
1. "Bonn" does not get the correct results, but user only discovers it when he/she checks the result list
2. "Bonn, Germany" works, but it is unclear for the user if he got it right, because there is no zoom to the city 
3. "Bonn, Deutschland" does not work, but that is another issue regarding translation I guess.

I think the usability of google maps should be the goal here to make it really easy to use (if a user wants to search for results in a specific city or countries). 

Best regards!

**Comment by philboeselager** [comment]
@literarymachine Do you already have a plan for approaching this issue? Please let me know...

**Comment by literarymachine** [comment]
> Do you already have a plan for approaching this issue?

I was thinking the following, reordering the fields like this:

- Country (drop-down, as is)
- City (autocompletion text input against Pelias API, with selected country preset)
- Street address (autocompletion text inpupt against Pelias API, with selected country and city preset)
- Mini map with pin

All of this will happen in the front end.

**Comment by philboeselager** [comment]
> All of this will happen in the front end.

+1 ;-)

**Comment by dobladov** [comment]
The current implementation covers the functionality required, please reopen if we need a different approach.
![image](https://user-images.githubusercontent.com/1938043/50149882-aa8d3980-02bc-11e9-9f96-684b0c26b883.png)
