### ISSUE TITLE
Implement lighthouse / like action

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1128]
As a user of the OER World Map I want to express that I like an `Organization`, `Service` or `Project` by pressing a lighthouse button on the corresponding profile.

**Comment by trugwaldsaenger** [comment]
Quality criteria:

- only logged in users can set a lighthouse
- by clicking on the lighthouse filter, it should be possible to display only the 30 (number has to be discussed) most highly ranked entries on the map. Ideally the number of lighthouses should be somehow visualized, so that it is easy to identify the highest ranked lighthouses.
- lighthouses can be "unset"

Extensions for later iterations:
- allowing to rank search result lists according to lighthouses
- restrict the result to the lighthouses set by a configurable group of people.

**Comment by literarymachine** [comment]
> only logged in users can set a lighthouse
> lighthouses can be "unset"

A first version of this is deployed to https://beta.oerworldmap.org/. Lacking a lighthouse icon, I used a star which can be found in the upper right corner near the "edit"-icon. Click it once to set, click it again to unset.

> by clicking on the lighthouse filter, it should be possible to display only the 30 (number has to be discussed) most highly ranked entries on the map.

There is no filter yet, but you can see a pie chart of ["Most liked"](https://beta.oerworldmap.org/aggregation/#about.object.@id) resources. Note that currently individual "LikeActions" show up in the result list with their `UUID` which is not pretty and will obviously be changed.

>  Ideally the number of lighthouses should be somehow visualized, so that it is easy to identify the highest ranked lighthouses.

Not entirely sure what you mean, maybe we should discuss this with @formimkontext at the upcoming team meeting.

**Comment by formimkontext** [comment]
First draft of a single resource view with the integrated lighthouse-icon below the subline, close to the im-a-meber-button. Pictures showing static and active state of the lighthouse- and action-button. 

Why don’t add the "most liked" option to the order dropdown which will be placed behind the number of entities shown above the result list?

![20170511-singleresource organization-lighthouse-1](https://cloud.githubusercontent.com/assets/15141949/26112451/3a32ea1e-3a58-11e7-8f5c-06baaac50d73.png)
![20170511-singleresource organization-lighthouse-2](https://cloud.githubusercontent.com/assets/15141949/26112439/3670af24-3a58-11e7-8c39-6aea3586f412.png)

**Comment by karindr** [comment]
Should't it be "Add me as member" changing ti "I am a member" on the button (or did I miss this)? Like on and off?

@formimkontext I like the little lighthouse and I like the yellow. Have you tried to use the yellow as light beam to each side?

**Comment by karindr** [comment]
I like the idea to be able to order the result list by "most liked".

**Comment by formimkontext** [comment]
I’m not sure about the wording. Have we defined it allready?

@karindr Yes, i tried to show lightbeams but i think the current solution is stronger and working better as an on/of switch.

**Comment by karindr** [comment]
OK, now I understand that the two icons would be used both, yellow is I liked it and white if I did not liked it. Then the full yellow is better, that's right.

I would prefer different texts for the member button instead of changing the colour of the button. It is clearer.

**Comment by trugwaldsaenger** [comment]
Great guys, looks promising!

> I’m not sure about the wording. Have we defined it allready?

We have agreed on the lighthouse as a symbol. "Most liked" certainly is a bit tricky. Maybe we could speak of "widest shining lighthouse".

**Comment by literarymachine** [comment]
Basic functionality as discussed via email is now on https://beta.oerworldmap.org, UI not complete yet. "Likes" and "Lighhouses" are expressed using a thumbs-up resp light-bulb icon when viewing a resource:

![screenshot from 2017-09-21 12-54-42](https://user-images.githubusercontent.com/149825/30692508-1f98f968-9ecc-11e7-8a7c-80c8b28fa902.png)

Likes are a simple on/off switch, Lighthouses require a description. You can get a list of liked and lighthoused entries using the corresponding buttons on the map:

![screenshot from 2017-09-21 12-57-10](https://user-images.githubusercontent.com/149825/30692577-6647bca0-9ecc-11e7-87bb-a1379cfc36d0.png)

**Comment by karindr** [comment]
Today setting likes on beta was very, very slow! I tested the Hewlett Foundation.

At the moment I don't see any possibility to see the descriptions people wrote for the lighthouses. Is there a way?

At the first glance I thought the orange icons were for setting the likes/lighthouses. In my opinion the row of orange icons gets to long, too much not so clear icons in a row.

**Comment by formimkontext** [comment]
> At the first glance I thought the orange icons were for setting the likes/lighthouses. In my opinion the row of orange icons gets to long, too much not so clear icons in a row.

Shouldn’t those buttons be part of the filter-section. Activating the button narrows down the result – so they are some kind of filter element, right?

**Comment by literarymachine** [comment]
> At the moment I don't see any possibility to see the descriptions people wrote for the lighthouses. Is there a way?

Ah, right! Currently you can only see your own description if you wrote one for a lighthouse. We'll have to change that! @formimkontext do you have an idea for a UI element? I guess we could just show the lighthouse descriptions just like comments below the entry...

> At the first glance I thought the orange icons were for setting the likes/lighthouses. In my opinion the row of orange icons gets to long, too much not so clear icons in a row.

Yes, I just put them there because AFAIK we did not have another concept yet.

> Activating the button narrows down the result – so they are some kind of filter element, right?

It narrows down the results, but more importantly it orders them by the amount of lighthouses / likes.

**Comment by karindr** [comment]
I like the idea of putting the buttons to the filters. We can explain in a mouse over text that the change the order of the resultlist too.

**Comment by literarymachine** [comment]
> Activating the button narrows down the result – so they are some kind of filter element, right?

As said in https://github.com/hbz/oerworldmap/issues/1128#issuecomment-341052599, the lighthouse count is more a search order than a filter. So I would like to keep the orange buttons as an interim solution for now integrate it to the filter section when implementing #946 in the new UI.

> At the moment I don't see any possibility to see the descriptions people wrote for the lighthouses. Is there a way?

The descriptions are now available above the comments, below the item information.

Also, the lighthouse now has a corresponding icon, see e.g. https://beta.oerworldmap.org/resource/?filter.about.objectIn.@type=LighthouseAction&sort=like_count:DESC#urn:uuid:29056e88-727b-407e-b00a-16df279ac506

Can we deploy this as a first version?

**Comment by trugwaldsaenger** [comment]
Look pretty nice, many thanks!
Two comments:

1) When setting a lighthouse, you are asked to give a short comment. On the comment template, it says "Lighthouse Service" and "Description" (the following questionmark icon does not provide any comment). I think we should make this a bit more helpfull, maybe by giving a concrete work instruction: "Please tell us, what makes this entry an lighthouse."

2)  When you click on the lighthouse buttom, you receive a list of entries filtered by lighthouses, but you do not get the numbers of lighthouses in the list, so logic might be hard to understand. Can we add the numbers in the list?

**Comment by karindr** [comment]
I agree to Jan, that the texts in the template should be more specific.

I assume only admins can see the little trash symbol near the comments and are able to delete comments from other people. Is that right?

The title above the lighthouse comments is not clear so far, suggestion: Title ”Lighthouse Comments” and this text: “Read why this service/project etc. is considered to be a lighthouse service/project etc:”

After these minor changes I assume it can be put on production. The following things can be done later:

There is no hint, that you have to be logged in to be able to like or ‚lighthouse‘ an entry. A phrase like “You have to be logged in to add a like/lighthouse” as mouse over would be useful. 

Is there a possibility to create a connection between the lighthouse symbol (the one with the number) to the comments below, because the comments are the point what is different between lighthouses and likes.

When a like or lighthouse is being set there is a lot of zooming on the map which is completely not necessary. Maybe it can be turned off.

**Comment by literarymachine** [comment]
> When setting a lighthouse, you are asked to give a short comment. On the comment template, it says "Lighthouse Service" and "Description" (the following questionmark icon does not provide any comment). I think we should make this a bit more helpfull, maybe by giving a concrete work instruction: "Please tell us, what makes this entry an lighthouse."

On beta.

> When you click on the lighthouse buttom, you receive a list of entries filtered by lighthouses, but you do not get the numbers of lighthouses in the list, so logic might be hard to understand. Can we add the numbers in the list?

On beta.

> I assume only admins can see the little trash symbol near the comments and are able to delete comments from other people. Is that right?

Yes, feel free to make a second non-admin account on beta to test stuff like this.

> The title above the lighthouse comments is not clear so far, suggestion: Title ”Lighthouse Comments” and this text: “Read why this service/project etc. is considered to be a lighthouse service/project etc:”

On beta.

> There is no hint, that you have to be logged in to be able to like or ‚lighthouse‘ an entry. A phrase like “You have to be logged in to add a like/lighthouse” as mouse over would be useful.

On beta.

**Comment by trugwaldsaenger** [comment]
Looks pretty good to me! If @karindr does not find any new issues, we can put it to production tomorrow!

**Comment by trugwaldsaenger** [comment]
Two comments for the next iteration:

1) I think we have discussed the position of the likehouse bottom. I think it should be just over the list, close to the bottom, which will allow alphabetical order of the list. 

2) At the moment it seems not to work in combination with the filters. In the next iteration we should bring this together, so that we can see, eg. which services received the most lighthouses...

**Comment by karindr** [comment]
Only one point: There is still a lightbulb in the orange button, not a lighthouse. All other things are ok.

**Comment by trugwaldsaenger** [comment]
+1 We should fix this. Many thanks @karindr.  Looking forward to see it on production!

**Comment by literarymachine** [comment]
> Only one point: There is still a lightbulb in the orange button, not a lighthouse. All other things are ok.

On beta. I can deploy this in the afternoon, but it will require a ~10 Minute downtime.

> Looking forward to see it on production!

Maybe a short blog post about this new feature would be appropriate?

**Comment by trugwaldsaenger** [comment]
Perfect! Please go ahead and deploy! I also think that a blog post is a good idea - allready working on it!

**Comment by karindr** [comment]
It will take a bit of time to have the German translation (I can do the translation on Monday when the new sentences appear on crowdin, afterwards it the translation has to be deploid).

**Comment by trugwaldsaenger** [comment]
@literarymachine, do you think that we could add lighthouses to the "recently updated section"?

**Comment by literarymachine** [comment]
This should be expanded to all types except `Person`.

**Comment by literarymachine** [comment]
> do you think that we could add lighthouses to the "recently updated section"?

Do you mean the [feed](https://oerworldmap.org/feed/)? Not without some additional thought, e.g. a `LighthouseAction` itself does not have a name to show as a title. But I think something like *Max Mustermann starred OER World Map* or *John Doe marked OER World Map as a lighthouse Service* would are good examples of what @j0hj0h and @formimkontext envision as entries for a timeline à la Facebook.

**Comment by trugwaldsaenger** [comment]
> John Doe marked OER World Map as a lighthouse Service

This sounds like a reasonable solution to me.
