### ISSUE TITLE
Add field "displayName" to be used when the official name is too long

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1133]

**Comment by karindr** [comment]
I think this is only relevant for projects and we should only add it in the project template. Otherwise the templates become overloaded.

**Comment by acka47** [comment]
It probably makes sense for organizations as well, see e.g. ["FWU Institut für Film und Bild in Wissenschaft und Unterricht gemeinnützige GmbH"](https://oerworldmap.org/resource/urn:uuid:eafff7d6-4a74-46c1-8502-55ec2b8d44c8).

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:682cb933-5d4e-4fef-a2a3-c91ecc25067a

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
