### ISSUE TITLE
Link hasthag to twitter feed

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1137]
E.g. `#osc2017` at https://oerworldmap.org/resource/urn:uuid:1995eed2-3ca5-42a3-8de8-fa9cbbc2cfec should be linked to https://twitter.com/search?q=%23osc2017.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=about.hashtag:*#urn:uuid:6dd760a6-d841-4e24-be46-04e2a2c3ff5b

**Comment by karindr** [comment]
+1 Really good idea!

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
Great idea, very cool. I always thought about including the twitter line into the profile, just linking it is much easier!
