### ISSUE TITLE
Can't add subjects on beta

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1140]
For this service:
https://beta.oerworldmap.org/resource/?q=test&filter.about.%40type=Service#urn:uuid:1a780c44-2b25-4159-a6fb-d9aac4c7a9d0

The data you entered is invalid

We are working hard on better error reporting. But until that is done, you are unfortunately stuck with this:
com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance failed to match all required schemas (matched only 1 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Service/properties/about/items"}
    instance: {"pointer":"/about/3"}
    domain: "validation"
    keyword: "allOf"
    matched: 1
    nrSchemas: 2
    reports: {"/definitions/Service/properties/about/items/allOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Link"},"instance":{"pointer":"/about/3"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@id\",\"@type\"])","required":["@id","@type"],"missing":["@id","@type"]}],"/definitions/Service/properties/about/items/allOf/1":[]}
error: instance failed to match all required schemas (matched only 1 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Service/properties/about/items"}
    instance: {"pointer":"/about/5"}
    domain: "validation"
    keyword: "allOf"
    matched: 1
    nrSchemas: 2
    reports: {"/definitions/Service/properties/about/items/allOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Link"},"instance":{"pointer":"/about/5"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@id\",\"@type\"])","required":["@id","@type"],"missing":["@id","@type"]}],"/definitions/Service/properties/about/items/allOf/1":[]}
error: instance failed to match all required schemas (matched only 1 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Service/properties/about/items"}
    instance: {"pointer":"/about/6"}
    domain: "validation"
    keyword: "allOf"
    matched: 1
    nrSchemas: 2
    reports: {"/definitions/Service/properties/about/items/allOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Link"},"instance":{"pointer":"/about/6"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@id\",\"@type\"])","required":["@id","@type"],"missing":["@id","@type"]}],"/definitions/Service/properties/about/items/allOf/1":[]}
error: instance failed to match all required schemas (matched only 1 out of 2)
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Service/properties/about/items"}
    instance: {"pointer":"/about/7"}
    domain: "validation"
    keyword: "allOf"
    matched: 1
    nrSchemas: 2
    reports: {"/definitions/Service/properties/about/items/allOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/Link"},"instance":{"pointer":"/about/7"},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"@id\",\"@type\"])","required":["@id","@type"],"missing":["@id","@type"]}],"/definitions/Service/properties/about/items/allOf/1":[]}
---  END MESSAGES  ---
{
  "image" : "https://oerworldmap.files.wordpress.com/2016/09/screen-shot-2016-09-01-at-18-07-45.png",
  "audience" : [ {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Pre-Primary Education",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/isced/1997/level0"
  } ],
  "keywords" : [ "keyword" ],
  "availableChannel" : [ {
    "serviceUrl" : "http://url.org/",
    "availableLanguage" : [ "ak" ]
  } ],
  "endDate" : "2000-02-02",
  "@type" : "Service",
  "about" : [ {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Personal services",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n101"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Generic programmes and qualifications",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n00"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Travel, tourism and leisure",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n1015"
  }, { }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Language acquisition \\u2013 Gaelic",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n0231-ga"
  }, { }, { }, { }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Accounting and taxation",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n0411"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Training for pre-school teachers",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n0112"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Education",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n01"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Business and administration",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n041"
  }, {
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Language acquisition",
      "@language" : "en"
    } ],
    "@id" : "https://w3id.org/class/esc/n0231"
  } ],
  "description" : [ {
    "@value" : "description Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    "@language" : "en"
  } ],
  "alternateName" : [ {
    "@value" : "alternateName",
    "@language" : "en"
  } ],
  "@context" : "https://oerworldmap.org/assets/json/context.json",
  "license" : [ {
    "image" : "http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png",
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Creative Commons Attribution Non-Commercial Share-Alike",
      "@language" : "en"
    } ],
    "@id" : "https://github.com/hbz/oerworldmap/public/json/licenses.json#by-nc-sa"
  }, {
    "image" : "http://mirrors.creativecommons.org/presskit/buttons/88x31/png/cc-zero.png",
    "@type" : "Concept",
    "name" : [ {
      "@value" : "Creative Commons Public Domain Dedication",
      "@language" : "en"
    } ],
    "@id" : "https://github.com/hbz/oerworldmap/public/json/licenses.json#cc0"
  } ],
  "mentionedIn" : [ {
    "image" : "https://oerworldmap.files.wordpress.com/2016/12/hbz-herbst_16-1080507.jpg?w=624",
    "@type" : "Article",
    "name" : [ {
      "@value" : "Test-Story-Struktur(Title)",
      "@language" : "en"
    } ],
    "location" : {
      "geo" : {
        "lon" : 9.431148,
        "lat" : 52.435492
      },
      "address" : {
        "addressCountry" : "DE",
        "streetAddress" : "Tulpenstraße 2",
        "postalCode" : 31515,
        "addressLocality" : "Wunstorf",
        "addressRegion" : "DE.NI"
      }
    },
    "@id" : "urn:uuid:cec05306-4646-46d6-becc-6d1877438059"
  } ],
  "provider" : [ {
    "image" : "https://oerworldmap.files.wordpress.com/2016/09/screen-shot-2016-09-01-at-18-07-45.png",
    "@type" : "Organization",
    "name" : [ {
      "@value" : "Test-Orga-Struktur name",
      "@language" : "en"
    } ],
    "location" : {
      "geo" : {
        "lon" : 6.954131,
        "lat" : 50.969041
      },
      "address" : {
        "addressCountry" : "DE",
        "streetAddress" : "Usambarastr. 9",
        "postalCode" : 50733,
        "addressLocality" : "Köln",
        "addressRegion" : "DE.NW"
      }
    },
    "@id" : "urn:uuid:eb803f73-bbaf-422e-9c53-db7462680212"
  }, {
    "image" : "https://oerworldmap.org/assets/images/Karin-Driesen-130.jpg",
    "@type" : "Person",
    "name" : [ {
      "@value" : "Test-Person_Struktur (Karin Driesen)",
      "@language" : "en"
    } ],
    "location" : {
      "geo" : {
        "lon" : 6.935474,
        "lat" : 50.934082
      },
      "address" : {
        "addressCountry" : "DE",
        "streetAddress" : "Jülicher Straße 6",
        "postalCode" : 50674,
        "addressLocality" : "Köln ",
        "addressRegion" : "DE.NW"
      }
    },
    "@id" : "urn:uuid:701c2bae-c918-45af-85dd-7805ad83ccab"
  } ],
  "member" : [ {
    "image" : "https://oerworldmap.files.wordpress.com/2016/09/screen-shot-2016-09-01-at-18-07-45.png",
    "@type" : "Organization",
    "name" : [ {
      "@value" : "Test-Orga-Struktur name",
      "@language" : "en"
    } ],
    "location" : {
      "geo" : {
        "lon" : 6.954131,
        "lat" : 50.969041
      },
      "address" : {
        "addressCountry" : "DE",
        "streetAddress" : "Usambarastr. 9",
        "postalCode" : 50733,
        "addressLocality" : "Köln",
        "addressRegion" : "DE.NW"
      }
    },
    "@id" : "urn:uuid:eb803f73-bbaf-422e-9c53-db7462680212"
  } ],
  "name" : [ {
    "@value" : "Test-Service-Struktur name",
    "@language" : "en"
  } ],
  "location" : {
    "geo" : {
      "lon" : 6.935474,
      "lat" : 50.934082
    },
    "address" : {
      "streetAddress" : "Jülicher Straße 6 ",
      "postalCode" : 50733,
      "addressLocality" : "Köln",
      "addressRegion" : "DE.NW"
    }
  },
  "@id" : "urn:uuid:1a780c44-2b25-4159-a6fb-d9aac4c7a9d0",
  "affiliate" : [ {
    "image" : "https://oerworldmap.org/assets/images/Karin-Driesen-130.jpg",
    "@type" : "Person",
    "name" : [ {
      "@value" : "Test-Person_Struktur (Karin Driesen)",
      "@language" : "en"
    } ],
    "location" : {
      "geo" : {
        "lon" : 6.935474,
        "lat" : 50.934082
      },
      "address" : {
        "addressCountry" : "DE",
        "streetAddress" : "Jülicher Straße 6",
        "postalCode" : 50674,
        "addressLocality" : "Köln ",
        "addressRegion" : "DE.NW"
      }
    },
    "@id" : "urn:uuid:701c2bae-c918-45af-85dd-7805ad83ccab"
  } ],
  "email" : "email@xx.org",
  "startDate" : "2000-01-01",
  "sameAs" : [ "https://twitter.com/test-service" ]
}

**Comment by literarymachine** [comment]
Note to self: this seems to be an issue only if a subject from the third level is added without any parent subject having been added before.

**Comment by karindr** [comment]
That is new. It always worked also without parent subject.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:e6f63d1b-987e-454d-bd6c-e2fc0ae2f6e0

**Comment by acka47** [comment]
+1
