### ISSUE TITLE
CSV export of search results provides broken tables

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1142]
If you export a search result list into CSV, the resulting lists are broken in both Excel and Calc. As discussed with @philboeselager this migth be caused by semicolons, which are used as seperators and occur in some of the description texts.

**Comment by philboeselager** [comment]
As, amongst others, [this answer](http://stackoverflow.com/a/8501818) suggests it is the best and correct way to use quotation marks around columns with non-delimiting semicolons. I'm going to implement that.

**Comment by literarymachine** [comment]
Fixed in #1150.
