### ISSUE TITLE
Provide continental export of data

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1143]
Tel asked for an export of data for the Americas. As soon as #1142 is solved, we for sure could provide this manually by exporting the data country by country and copy it to one table. Are there any more comfortable ways to approach this task?

**Comment by literarymachine** [comment]
> Are there any more comfortable ways to approach this task?

Yes. There is now reason to do this country by country; you can simply select all countries you want from the country filter drop down:

https://oerworldmap.org/resource/?q=&filter.about.location.address.addressCountry=AR,CL,PE,EC,CO,VE,GF,SR,BR,BO,PY,UY

Then export as CSV.

**Comment by trugwaldsaenger** [comment]
Great, thanks for this answer, very helpful! Closing the issue!
