### ISSUE TITLE
Strange search results for Open University

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1145]
"The Open University" is shown at place 13
![image](https://cloud.githubusercontent.com/assets/18674205/24394260/994c4024-139b-11e7-8216-63b080c99c81.png)
Maybe put more weight on the title? But I think this result is not to bad, because when I search vor "Open University" in quotation marks it is the first.

**Comment by philboeselager** [comment]
@karindr Do you agree that this is basically the same issue as #1119? If so, I would like to leave this ticket until #1119 is solved and deployed, and then re-check.

**Comment by karindr** [comment]
OK

**Comment by philboeselager** [comment]
Searching for `Open University` now results in The Open University being ranked 7th.
Searching for `"Open University"` or `"The Open University"` results in The Open University being ranked 2nd.

While the first query (without quotes) only searches for resources containing one or both terms, the second one (within quotes) searches for the exact query string.

@karindr Is this behaviour sufficiently satisfying?

**Comment by karindr** [comment]
+1
