### ISSUE TITLE
Sort filters for audience/grade level

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1146]
The order should be same as in the template and in presentation for the services:

 Pre-Primary Education
 Primary education or first stage of basic education
 Lower secondary education or second stage of basic education
 Upper secondary education
 Post-secondary non-tertiary education
 First stage of tertiary education
 Second stage of tertiary education

**Comment by trugwaldsaenger** [comment]
+1

**Comment by karindr** [comment]
this is done so I close this issue
