### ISSUE TITLE
Add calendar with optional time widget to forms

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1151]
For example for https://oerworldmap.org/resource/urn:uuid:16e19f26-2b21-45fe-9d02-43fa5f0daf5c it would be great to add a concrete time as this is a 1-hour call.

**Comment by karindr** [comment]
This would be useful for a lot of webinars too, because you don't have to check a second webpage then.

**Comment by literarymachine** [comment]
> it would be great to add a concrete time as this is a 1-hour call.

This is actually possible, just append the time (and optionally a timezone offset) to the date, resulting in the following format: `2017-03-29T12:00:00-04:00`: https://oerworldmap.org/resource/urn:uuid:16e19f26-2b21-45fe-9d02-43fa5f0daf5c

Admittedly, this is not very user friendly. So let's keep this issue open until we have a widget that makes this easier.

**Comment by literarymachine** [comment]
See also #1397

**Comment by literarymachine** [comment]
See https://nosir.github.io/cleave.js/
