### ISSUE TITLE
Enable iCal import

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1152]
When adding an event I should have the possibility to pre-populate the editing form by importing an iCal event. Example iCal URL: [March OpenCon community call](https://www.addevent.com/create/?service=ICAL&dstart=29-03-2017%2012%3A00%3A00&dend=29-03-2017%2013%3A00%3A00&dzone=15&dsum=March%20OpenCon%20Community%20Call&ddesc=OpenCon%20community%20calls%20give%20a%20chance%20for%20you%20to%20learn%20what%C2%B4s%20happening%20in%20open%20research%20and%20education%20around%20the%20world%2C%20share%20what%20you%C2%B4re%20doing%20and%20find%20collaborators%20and%20opportunities.%26amp%3Bnbsp%3B%20Call...&dorga=Joe&dorgaem=joe%40sparcopen.org&dateformat=DD%2FMM%2FYYYY&reference=http://www.opencon2017.org/march_2017_community_call).

**Comment by acka47** [comment]
Duplicate of #1106. Closing.

**Comment by philboeselager** [comment]
It's not exactly a duplicate, but the solution should provide both ways to add events anyway, so OK to close this issue,
