### ISSUE TITLE
Recently added event can't be viewed as HTML

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1154]
It's strange as there was no error message when saving the entry: https://oerworldmap.org/resource/urn:uuid:16e19f26-2b21-45fe-9d02-43fa5f0daf5c

**Comment by literarymachine** [comment]
@j0hj0h this is a problem with the handlebars moment helper; `precisions_max is undefined`.

**Comment by literarymachine** [comment]
Fixed and deployed to production: https://oerworldmap.org/resource/urn:uuid:16e19f26-2b21-45fe-9d02-43fa5f0daf5c
