### ISSUE TITLE
Show chosen tags, countries and so on  above the result list

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1155]
As Jan did in his Blogpost
https://oerworldmap.wordpress.com/2017/03/20/open-education-week-2017-making-sense-of-the-oer-world-map-through-the-use-of-folksonomies/
links to filtered lists can be very useful. They will be even more useful if the visitor easily can see what filters are set in what way, in this example if the chosen tag would be shown.

**Comment by literarymachine** [comment]
> They will be even more useful it the visitor easily can see what filters are set in what way, in this example if the chosen tag would be shown.

While maybe not very prominent, you can currently see this. The corresponding filters are darker than unused ones, and the chosen values can be seen when dropping the filter down.

**Comment by karindr** [comment]
Yes, I can see this. But a visitor coming from the article and being the first time on the map should be able to see and understand it at the first glance.

**Comment by acka47** [comment]
I agree that this is hidden very good. It would be grat to somehow unfoled the tag button in the UI showing the chosen tags right over the result list.

**Comment by formimkontext** [comment]
We could show all chosen tags like in the draft below. Do you think, this section should be shown by default, as soon as a filter is set?

![20170911-showchosentags-1](https://user-images.githubusercontent.com/15141949/30282004-45edccd4-9714-11e7-93d1-87527e401a50.png)

**Comment by karindr** [comment]
I think the dark blue is very good to see and I like the list of chosen tags (which you can cklick away with the little x). 

Maybe there should be a kind of a headline "Tags". If other points from drop down filter lists are chosen (maybe a country and a language) all these chosen points should be shown in some way.

**Comment by karindr** [comment]
Sorry just understood that for the filters in the lower part there can be chosen only one point and this is shown on the filter itself. So there remains only the chosen country to be shown which is very important.

**Comment by dobladov** [comment]
Fixed with https://github.com/hbz/oerworldmap-ui/pull/344, closing
