### ISSUE TITLE
Chosen filters should change their colour stronger

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1156]
Sometimes when you return to the map after a while you don't realize that a filter is set because the colours are to close. When you link to filtered lists it is the same for visitors. It should be very clear which filters are set.

**Comment by literarymachine** [comment]
Is this an alternative for #1155?

**Comment by karindr** [comment]
This is about the filters you click at (entry types) here another colour will be enough.  #1155 is about the filters where you chose one ore more words from a list (country, tags and so on, these chosen word should be shown.

**Comment by acka47** [comment]
I agree. We should either improve the "button pressed" look of the button or chose a color for a pressed button that differs stronger from the rest.

**Comment by formimkontext** [comment]
I think we will improve this with some bigger ui modifications and colour changes.

**Comment by karindr** [comment]
Done with the new UI
