### ISSUE TITLE
Piwik opt-out broken in Safari

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1158]
As reported offline.

**Comment by literarymachine** [comment]
@j0hj0h or @formimkontext can one of you osx folks confirm that piwik opt-out at https://oerworldmap.org/imprint is not working?

**Comment by formimkontext** [comment]
Using Safari 8.0.3 the setting ist opt-in on default. I can opt-out manually.

**Comment by j0hj0h** [comment]
Tested in Safari 7.1 and 9.1 ... opt-out works. Maybe the reporter blocked cookies?
