### ISSUE TITLE
Jump to the beginning of the form if an error occurs

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1160]
… before or after the save button. 
When you try to save the entry and the error message is shown you don’t see it for all templates (except for publication which is very short) because the end of the template is show on the screen and you have to scroll up to see the error message. First time you think there is no message and try to save again and again.

**Comment by literarymachine** [comment]
> When you try to save the entry and the error message is shown you don’t see it for all templates (except for publication which is very short) because the end of the template is show on the screen and you have to scroll up to see the error message.

This is actually a small bug; the behavior should be to jump to the beginning of the form if an error occurs.

**Comment by literarymachine** [comment]
On beta

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
