### ISSUE TITLE
Order of event in months is not correct

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1162]
see:
![image](https://cloud.githubusercontent.com/assets/18674205/24606361/1bfb3f40-186d-11e7-9cdf-55ac9051895d.png)

**Comment by literarymachine** [comment]
I don't get it. Where is the error here? With #1111 we wanted reverse chronological order of events, which seems correct to me:

![screenshot from 2017-04-03 13-47-58](https://cloud.githubusercontent.com/assets/149825/24607932/69551b1a-1874-11e7-8527-e9fac1772eac.png)

**Comment by karindr** [comment]
Look at April:
1. 3. April
2. 20. April
3. 5. April
This order does not make sens, does it?

**Comment by literarymachine** [comment]
> This order does not make sens, does it?

No, not at all! I misread the issue as being about the order of the months, not days. Sorry about that!
