### ISSUE TITLE
Split server

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#1163]
DOD:

- Production and beta instances run on different machines.
- Elasticsearch node is cloned on second machine.
- Both ES nodes work in a cluster.
- Both servers are upgraded.

**Comment by literarymachine** [comment]
> Both ES nodes work in a cluster.

This is the only remaining issue here, right?

**Comment by philboeselager** [comment]
Elasticsearch runs in cluster mode now, production being "master node" and beta being "data node". `curl '<ip>:9200/_cat/indices?v'` shows indices for our application and kibana of both, production and beta data, on both machines.
To be able to switch immedeately between two servers, we would have to mirror our triples data, too.

Closing this issue.

**Comment by literarymachine** [comment]
This broke our Kibana: https://oerworldmap.org/kibana/app/kibana#?_g=()

**Comment by literarymachine** [comment]
Fixed by configuration.
