### ISSUE TITLE
Refactor map

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1165]
As discussed in the [team meeting](https://oerworldmap.wordpress.com/2017/03/28/first-team-meeting-2017-berlin/), the map will be refactored. Pins will no longer be clustered, but get styled to have more of a cloud-like appearance:

![Map](https://oerworldmap.files.wordpress.com/2017/03/draft_heatmap.jpeg)

Besides that, automatic zooming and panning will be reduced to a minimum.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by acka47** [comment]
It's much better without the clusters. I am not sure whether the coloring is the best choice. A bit more contrast might be good. Anyway, +1.

**Comment by philboeselager** [comment]
> A bit more contrast might be good. Anyway, +1.

+1

**Comment by literarymachine** [comment]
Also with this PR we have a new export format: [GeoJSON](https://beta.oerworldmap.org/resource.geojson). You can test it by selecting the raw GeoJSON and dragging it [here](https://developers.google.com/maps/documentation/javascript/examples/layer-data-dragndrop?hl=de).

**Comment by literarymachine** [comment]
Zooming into high levels lets pins disappear, e.g. https://beta.oerworldmap.org/resource/urn:uuid:497e84a4-2691-4648-9340-694ec053aeac

**Comment by literarymachine** [comment]
Aggregation popover is persisted, try clicking e.g. on the highlighted pin here: https://beta.oerworldmap.org/resource/urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf

**Comment by karindr** [comment]
In consequence of the smaller size of the dot compared to the pins and circles from the map before the blue colour is not striking enough for the dots. When you have a first look at the map showing the whole world you nearly notice the dots.

As second point I recommend to change the presentation to a classic pin (shaped like a drop upside down) at the moment when an entry is chosen.

**Comment by literarymachine** [comment]
> In consequence of the smaller size of the dot compared to the pins and circles from the map before the blue colour is not striking enough for the dots. When you have a first look at the map showing the whole world you nearly notice the dots.
>
> As second point I recommend to change the presentation to a classic pin (shaped like a drop upside down) at the moment when an entry is chosen.

@formimkontext @j0hj0h can you maybe look into the details of the map design a bit next week? I'll be AFK.

**Comment by formimkontext** [comment]
Working on the map design i would like to discuss some general questions:

Does the scale of the heatmap have to remain stepless or may we switch to a scale with maybe five or six levels? A reduced number of levels would still give a review about the stuation but make the handling of the map easier. 

Talking about the heatmap i recommend to switch to "entries per inhabitants" on default. OER are made by people for people, so they should be our first reference. Furthermore, by showing the value of entries refered to the inhabitants we give more informatione to the user, while indexing absolute numbers of entries is just redundant information. 

Do we agree on the fact, that the main task of the map is to locate entries / resources in order to review and compare the use and currency of OER, but is neither route planning nor infrastructure information?

**Comment by j0hj0h** [comment]
@literarymachine issue with disappearing pins fixed, the one with the persistent modal (which you could not reproduce) probably as well.

**Comment by philboeselager** [comment]
> Does the scale of the heatmap have to remain stepless or may we switch to a scale with maybe five or six levels? A reduced number of levels would still give a review about the stuation but make the handling of the map easier.

Are we talking about performance? If so, a number of 16 or 32 levels would result in a nearby continuous look and should not be expensive in terms of performance.

> Talking about the heatmap i recommend to switch to "entries per inhabitants" on default.

I like it both ways. Anyway, it looks more "fair", so +1.

The language aspect remains the most interesting quasi-geo filter. (For example, Spanish is an official language in 21 countries. I can use OERs of other countries, but I can only use OERs of languages that I understand, as long as autotranslation is not on a "99%" level.). Mapping languages to countries is complicated, but we might find ways to support this visually.

> Do we agree on the fact, that the main task of the map is to locate entries / resources in order to review and compare the use and currency of OER, but is neither route planning nor infrastructure information?

I'm not sure what is meant by currency here, but yes: locating / reviewing / comparing is on focus. Route planning is not. Which infrastructure information do you have in mind?
