### ISSUE TITLE
Set up open refine reconciliation endpoint

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1170]
This would make things easier for tasks like https://github.com/hbz/oerworldmap/issues/256#issuecomment-291818767. We already did this for lobid-organisations, see https://github.com/hbz/lobid-organisations/commit/baf30899dc7af32843e8590d6f2008f75e7bd0c5. However, I think we used the `q` parameter there for the queries (didn't we @fsteeg?). ~~As reconciliation exclusively is done via names, we should only query the name and alternateName fields for reconciliation.~~ (Edit: Forget what I said there.)

**Comment by fsteeg** [comment]
> I think we used the q parameter there for the queries (didn't we @fsteeg?).

Yes, it uses a `queryStringQuery` internally, see:
https://github.com/hbz/lobid-organisations/blob/master/app/controllers/Reconcile.java#L95

**Comment by philboeselager** [comment]
[Current](https://github.com/hbz/oerworldmap/commit/a86302915c358ed958a6c045cbdacff1439032ca) response is something like:

    {"q0":{"result":[{"id":"urn:uuid:51acd69e-2224-43bc-a1d2-204bffa4664a","match":false,"name":"fachlehrerseite.de","score":36.84899,"type":"Service"}]},"q1":{"result":[{"id":"urn:uuid:31eb5b9e-ba64-4b3d-b1f0-d7d7feb42411","match":true,"name":"herr-kalt Unterrichtsmaterialien","score":73.57027,"type":"Service"}]},"q2":{"result":[{"id":"urn:uuid:01910221-e00f-4dfb-97a3-8afcbacebe89","match":true,"name":"Open Osmosis","score":12.986828,"type":"Service"},{"id":"urn:uuid:ad56fa6b-fb06-4c9e-adec-16adf31ab3f7","match":false,"name":"Open Osmosis Initiative","score":6.233678,"type":"Action"}]},"q3":{"result":[]},"q4":{"result":[{"id":"urn:uuid:c3069db7-971f-4d4e-a557-86a0dab62a1a","match":false,"name":"Lehrbuch für Lernen und Lehren mit Technologien","score":36.62431,"type":"Service"},{"id":"urn:uuid:a6288042-b98e-434d-8b0d-0649e515ed32","match":false,"name":"L3T 2.0 in seven days","score":1.7725385,"type":"Action"}]},"q5":{"result":[{"id":"urn:uuid:ab167876-aa97-49a9-b73d-99c82ffbfb2b","match":false,"name":"edutags","score":82.91023,"type":"Service"},{"id":"urn:uuid:f4f8af31-ac5d-497c-9c96-ec958c465b09","match":false,"name":"DIPF - German Institute for International Educational Research","score":7.2217894,"type":"Organization"},{"id":"urn:uuid:0d395896-3847-4369-85b8-5d77f63446a8","match":false,"name":"University of Duisburg-Essen","score":4.5852633,"type":"Organization"}]},"q6":{"result":[{"id":"urn:uuid:fe2a38a2-ecb7-4363-bb3f-8998f0270913","match":false,"name":"Landesbildungsserver Baden-Württemberg","score":81.2084,"type":"Service"}]},"q7":{"result":[{"id":"urn:uuid:ac5d5269-6449-43c0-b43b-2ed372763a0e","match":false,"name":"Hamburg Open Online University","score":3.1665192,"type":"Action"}]},"q8":{"result":[{"id":"urn:uuid:5314276e-c2d1-4b9b-afbb-0cc23bd20c86","match":false,"name":"Synergie für Lehre und Lernen durch OER-Materialien","score":10.422469,"type":"Action"}]},"q9":{"result":[]}}

comprised in an "ok" (200) Play Result. Looks very much like what should be intended to me.

@literarymachine @fsteeg Any detail that I've missed?

**Comment by philboeselager** [comment]
Forgot to mention: the receiving (local) OpenRefine instance still hangs - displaying "Working...

**Comment by literarymachine** [comment]
> Looks very much like what should be intended to me.

I would say so, too. @fsteeg is the lobid reconciliation working with the current OpenRefine release?

**Comment by fsteeg** [comment]
I just tried it with OpenRefine 2.7, following the instructions at https://github.com/hbz/lobid-organisations/issues/55#issuecomment-129771979 (linked from http://lobid.org/organisations/api/en#openrefine) and it worked fine for me.

**Comment by philboeselager** [comment]
Dooh. [`type` has to be an array](https://github.com/hbz/oerworldmap/commit/9101d87aefaeb856c5ce9d34748a86bc1044e9ad). We had expected this to be "either-or"...

**Comment by literarymachine** [comment]
Fixed in #1331
