### ISSUE TITLE
Field for language looks "broken" in template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1171]
![image](https://cloud.githubusercontent.com/assets/18674205/24743483/af918e38-1aae-11e7-9df1-b2be1e890074.png)

**Comment by literarymachine** [comment]
Cannot reproduce:

![screenshot from 2017-04-06 10-45-22](https://cloud.githubusercontent.com/assets/149825/24745487/2fd0e70e-1ab6-11e7-8b1c-72f9a44d477a.png)

**Comment by karindr** [comment]
Seems to have been only temporary.
