### ISSUE TITLE
Strange start date subheading of entry

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1175]
have a look at this entry:
https://oerworldmap.org/resource/urn:uuid:e5579da0-ff00-4db2-ab70-90640ab92ddc?version=bbe73f1a9c9a53fc96b6075a6ec5d4bab71cdc7b
In the subheading there is 1. Jan 1970 as date but this date is not shown in the template (there is 2013) and in the following table (2013). How could we get rid of 1970?

**Comment by karindr** [comment]
And again:
![image](https://cloud.githubusercontent.com/assets/18674205/24857675/6ede177e-1de9-11e7-9fd6-4db599fcd5a8.png)

**Comment by karindr** [comment]
There seem to be a more general problem, here too:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Action#urn:uuid:4dbabfb8-4a3f-11e5-9319-001999ac7927

**Comment by literarymachine** [comment]
@j0hj0h maybe some issue with the moment helper not accessing the right field and thus defaulting?

**Comment by literarymachine** [comment]
@j0hj0h looks like given only a year as `startTime`, `{{moment startTime "D. MMM YYYY"}}` does not do what it should.
