### ISSUE TITLE
Map shows only water and can not be zoomed

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1176]
![image](https://cloud.githubusercontent.com/assets/18674205/24855063/aeaa9d86-1de0-11e7-8010-d87cc16fbea7.png)
Reloading solves the problem.

**Comment by trugwaldsaenger** [comment]
Works fine for me: https://oerworldmap.org/resource/?q=del+maule#urn:uuid:0e5bd7a7-17f9-4824-a4f0-8bdd6e8e61e2 !

**Comment by literarymachine** [comment]
This is indeed an occasionally occurring problem that should be fixed with the new GeoJSON layer version that is currently on beta, shouldn't it @j0hj0h?

**Comment by j0hj0h** [comment]
Chances are high that this is fixed.
