### ISSUE TITLE
Start Calendar View events from actual month

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1178]
Feedback from OEC: Right now the calendar view starts with the events which will take place most in the future. At the moment this is November 2017. It would be great if the map would directly jump to the actual month, so that you can see these events first, which will happen in the near future.

**Comment by karindr** [comment]
As wee can see on oerinfo
http://open-educational-resources.de/veranstaltungen/kalender/
we now have enough dates to do so. At the end of the list or above the list there should be a button for the option: show past events.

**Comment by trugwaldsaenger** [comment]
I guess this should not be too much work. We should try to implement this soon.

**Comment by karindr** [comment]
And the dates in the months should start with the first of the month not with the last date!

**Comment by literarymachine** [comment]
> And the dates in the months should start with the first of the month not with the last date!

@dobladov and @formimkontext told you so ;)

**Comment by formimkontext** [comment]
i think the most logical order of dates in a list is the following:

upcoming (from now to future (days, months and years))

today

june 6.
june 7.
june 8.
…

july 1.
july 2.
july 3.
july 4.
…

past (from now to the furthest behind (days, months and years))

today

june 5.
june 4.
june 3.
june 2.
june 1.

may 31.
may 30.
may 29.
…

**Comment by karindr** [comment]
If i can change between past and upcoming I like @formimkontext orders very much. If we have to choose one I would prefer the first.

**Comment by karindr** [comment]
This would really improve our event page!

**Comment by karindr** [comment]
There is a little shift of the calendar so the fields are cut of, see:
![image](https://user-images.githubusercontent.com/18674205/45737680-c6663e00-bbee-11e8-9f2f-bee285333e70.png)

**Comment by literarymachine** [comment]
Fixed and deployed to production: https://oerworldmap.org/resource/?filter.about.@type=Event

**Comment by karindr** [comment]
The new calendar view is much better than the old one starting with the event which is the farthest in the future. But I think it could meet the expectations of the visitors even better if we simply change the order of the events as @formimkontext suggested above for the future. Since an event calendar is used mainly for the future this should be our focus. If a visitor wants to see past events he can scroll back and gets this information as well.

**Comment by literarymachine** [comment]
> Since an event calendar is used mainly for the future this should be our focus.

Exactly. I would argue that the most important things come first in a list. If the most important is the future, why move it to the bottom?

**Comment by literarymachine** [comment]
Understood! @dobladov this might be solved easiest by sorting API-side, I'll check.

**Comment by karindr** [comment]
The months have the right order now. That's nice. The dates in the months should follow the same order from nearer to farther future:
1. Okt
5. Okt
20 Okt.

**Comment by literarymachine** [comment]
> The dates in the months should follow the same order from nearer to farther future:

Yes. As soon as that is done, this issue will be closed.

**Comment by literarymachine** [comment]
Fixed by https://github.com/hbz/oerworldmap-ui/pull/393 and https://github.com/hbz/oerworldmap/pull/1656 and deployed to production:

![image](https://user-images.githubusercontent.com/149825/46341622-ee1ac480-c638-11e8-9cf4-eabbb567d3dc.png)
