### ISSUE TITLE
Describe service

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#118]
As an OER provider, I want to describe my services so that OER users can easily find them.

**Comment by literarymachine** [comment]
Acceptance criteria (data elements):

- [ ] [Name](http://schema.org/name)
- [ ] [Description](http://schema.org/description)
- [ ] [Provider](http://schema.org/provider)
- [ ] [Access via](http://schema.org/availableChannel)
- [ ] [Audience](http://schema.org/serviceAudience) (Subjects of resources provided)
- [ ] [Audience](http://schema.org/serviceAudience) (Languages of resources provided)
- [ ] [Audience](http://schema.org/serviceAudience) (Grade levels of resources provided)

**Comment by acka47** [comment]
As discussed between several team members, we are thinking about broadening this one to cover services o the web and tools.

I suggest adding the possibility to add potential use cases of such a tool/service. We could use the[`schema:potentialAction`](http://schema.org/potentialAction) property for this.

**Comment by trugwaldsaenger** [comment]
This will be relevant to stories as well #117

**Comment by acka47** [comment]
`schema:serviceAudience` is superseded by `schema:audience`. Adding this to the [google doc](https://docs.google.com/spreadsheets/d/1MUA2jg15AlQTwN-M8h52OHGT8Xo5Zf1jHut4zuMQsQI/edit#gid=149704738).

**Comment by trugwaldsaenger** [comment]
As just discussed the license has to be included as well. So this story is linked to #237.

**Comment by j0hj0h** [comment]
Drafts for the modal to add and edit services ...

![151104-oer-world-map-modal-6-1](https://cloud.githubusercontent.com/assets/3071485/10938612/e64659dc-82fb-11e5-8158-f8690561b381.jpg)
![151104-oer-world-map-modal-6-2](https://cloud.githubusercontent.com/assets/3071485/10938613/e6615dc2-82fb-11e5-8954-f585988e4f03.jpg)
![151104-oer-world-map-modal-6-3](https://cloud.githubusercontent.com/assets/3071485/10938614/e6816d38-82fb-11e5-87be-09ad01046171.jpg)

**Comment by acka47** [comment]
to do for me from physical meeting: provide order of fields for web forms. 

Please let me know where I I should provide this (and assign this issue to me at some point if I don't remember delivering the order).

**Comment by acka47** [comment]
Another to do regarding service template: Adjust wording for "service channel". I think "Service URL" or just "URL" is a good choice.
