### ISSUE TITLE
Add level of accessibility to services

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1184]
As a teacher or learner I want to filter services (and potentially also other types of entries) by degree of accessibility. This could also become part of #237. /cc @inclusive-design

**Comment by literarymachine** [comment]
See https://wiki.fluidproject.org/display/fluid/Basic+Guidelines+for+Achieving+Accessibility

**Comment by acka47** [comment]
Accessibility is already part of the current "Openness Indicator" draft, see the "Platform design" dimension in https://docs.google.com/spreadsheets/d/1qjDUi9GvibnveOqj5Oo6ijx9m6FvukIxkGA1-ckXUJg/edit#gid=1400185386

**Comment by literarymachine** [comment]
> Accessibility is already part of the current "Openness Indicator" draft
