### ISSUE TITLE
Stop comma from being the first character in a line

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1186]
In this example it happens that the comma is the first character in a line of the subheading, see:
https://oerworldmap.org/resource/urn:uuid:55af3f50-fb2c-41aa-86d4-ce5e704dff9d
![image](https://cloud.githubusercontent.com/assets/18674205/25376155/8a7f7a3e-29a3-11e7-908b-5d7d9cd3ba7b.png)

**Comment by karindr** [comment]
A similar case in the Headline: The exponent is separated from the word before, see:
![image](https://cloud.githubusercontent.com/assets/18674205/25426823/b9ae562c-2a70-11e7-814b-98c1a116f5be.png)

**Comment by literarymachine** [comment]
Fixed in new UI, closing.
