### ISSUE TITLE
Greek display name is displayed although the chosen language of the browser is English

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1189]
Look at this example:
https://oerworldmap.org/resource/urn:uuid:73a9c92d-9236-4c43-a4ef-f5b61cefd50d
There is a Greek name and display name and an English name and the displayname is shown even though it has got the wrong language (my chosen language is English), see:
![image](https://cloud.githubusercontent.com/assets/18674205/25378999/df1af822-29ab-11e7-98d5-74a1166f5036.png)
In my opinion the display name should only be displayed when it fits to the chosen language.

**Comment by karindr** [comment]
@literarymachine or @acka47, we talked about this in the meeting,  see above there is the example!

**Comment by acka47** [comment]
> In my opinion the display name should only be displayed when it fits to the chosen language.

Hmm, I would rather expect this behaviour. I now added an English display name and it looks good.

**Comment by karindr** [comment]
Ok. This is a good solution, so I close this issue.
