### ISSUE TITLE
Choosing map view according to search result

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1190]
I know that we changed this to avoid that the map changes every time you enter something. But especially for the events (as @trugwaldsaenger mentioned) and when filtering for countries it is strange to see no results on the map. See for example filters on for events and Australia this map is shown:
![image](https://cloud.githubusercontent.com/assets/18674205/25381266/5611ce86-29b3-11e7-9586-9e1167c7fdae.png)
Any ideas for a compromise for this?

**Comment by karindr** [comment]
At least when you choose an entry from the list this entry should be visible. Sometimes the result is behind the open colums for example for china:
![image](https://cloud.githubusercontent.com/assets/18674205/25613284/f722384a-2f2d-11e7-8df2-df365ee9d6a9.png)
But there is an interesting change when you reload the page:
![image](https://cloud.githubusercontent.com/assets/18674205/25613358/3438429c-2f2e-11e7-90c4-4a09bc892464.png)

**Comment by j0hj0h** [comment]
Decision: We will introduce recentering on each click on a single resource.

**Comment by literarymachine** [comment]
> Decision: We will introduce recentering on each click on a single resource.

Re-centering not necessary any longer due to new single item view. Closing.
