### ISSUE TITLE
Strange line on map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1191]
When I move the mouse over the land (not over the water) a strange line appears, see:
![image](https://cloud.githubusercontent.com/assets/18674205/25381743/360a3748-29b5-11e7-8016-23addb978739.png)
https://oerworldmap.org/resource/?q=open+textbook&filter.about.%40type=Event

**Comment by karindr** [comment]
After zooming in and out the line disappeared.

**Comment by literarymachine** [comment]
@j0hj0h this seems to be some issue with the country border, do you agree?

**Comment by karindr** [comment]
Another line:
![image](https://cloud.githubusercontent.com/assets/18674205/26542541/9cdbc7c4-445a-11e7-8838-6b56074773f6.png)

**Comment by literarymachine** [comment]
Fixed by switch to mapbox, closing.
