### ISSUE TITLE
Browser seems to become very slow when doing a lot of searches on the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1198]
Working on the corrections for a print version of the German map I did a lot of searches on the map and followed a lot of links back and forth. After some hour my browser become slower and slower. At the end I had to wait until it scrolled down the page and two times it showed a white page. The next morning it started fast but it became slower again after some time although not as slow as the day before. I worked on the bit.ly website to create links at the same time. Don’t know if this interfered.

**Comment by literarymachine** [comment]
@j0hj0h we should probably do some profiling to verify this.

**Comment by literarymachine** [comment]
Fixed in new UI, closing.
