### ISSUE TITLE
Leave comments on data hub entries

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#12]
As a user of the OER World Map I want to leave a comment on a OER data hub entry.

**Comment by acka47** [comment]
Would I have to be looged in as a user to leave a comment?

**Comment by acka47** [comment]
Regarding technical implementation we should think about using [open annotation](http://www.w3.org/annotation/) and/or hypothes.is

**Comment by trugwaldsaenger** [comment]
I guess we should require registration for this. This would also be relevant for stories #117, so that users can make comments on stories. But we still have to think this out. If we allow comments on stories it might be necessary to make some automatic alert to the autor of the story, so that she/he can answer the comment...

**Comment by acka47** [comment]
We might just try [annotator.js](http://annotatorjs.org/) for comment function.

**Comment by literarymachine** [comment]
> We might just try annotator.js for comment function.

I am not so sure about this. As far as I understand it, annotator allows to leave comments / annotations on individual text sections, i.e. not a data hub entry as a whole. I would rather expect us to have a classic comment box underneath each entry.

**Comment by acka47** [comment]
> I am not so sure about this. As far as I understand it, annotator allows to leave comments / annotations on individual text sections, i.e. not a data hub entry as a whole. I would rather expect us to have a classic comment box underneath each entry.

I agree that we should enable people to comment a whole entry. But I imagine that you can somehow do this with annotator.js. However, I think that the possibility to annotate e.g parts of a story might make sense as a feature. What do you think, @trugwaldsaenger ?

**Comment by literarymachine** [comment]
> But I imagine that you can somehow do this with annotator.js

The question here is *what* we want to do, not *how*.

**Comment by trugwaldsaenger** [comment]
To me the priority is that we are able to comment on data hub entries. Also it should be possible to comment on comments, so that there can be discussion. Commenting on parts of a story would make sense as well. I guess this will be true for other data types as wel. E.g. it could be helpful to make a comment exactly the field, which you want to comment on. But for the beginning I would be happy if we could comment on whole entries.

**Comment by literarymachine** [comment]
> [A]s online audiences have grown, the pain of moderating conversations on the web has grown, too. And in many cases, the most vibrant coversations about a particular article or topic are happening on sites like Facebook and Twitter. So many media companies are giving up on comments, at least for now.

http://www.wired.com/2015/10/brief-history-of-the-demise-of-the-comments-timeline/

**Comment by trugwaldsaenger** [comment]
Interesting point. I nevertheless would argue in favor of comments. Could you think that Wikipedia would work without discussion pages? Hard to believe for me. Doing precise comments, ideally directly at the position of the page (including its data) would be very helpful for quality assurance as well. Without comments like this the process of communicating issues takes more ressources.

**Comment by philboeselager** [comment]
As we are not sure whether the comment feature will be used much, I favour an agile approach at first: serve a very basic but extensible comment function.

**Comment by literarymachine** [comment]
On beta, you need to be logged in to post comments. See e.g. https://beta.oerworldmap.org/resource/urn:uuid:bb497857-9485-4aae-8e6d-10056adc973c

**Comment by karindr** [comment]
Nice! 
But see, if somebody (like me on beta) has no information in his profile this is shown: "on 2016-08-10T11:46:04.794+02:00". Maybe there should be a placeholder for anonymous users? Or should people need to have a simple Profile to be allowed to comment?

**Comment by karindr** [comment]
At the moment on beta there is the possibility to comment on each type of entry. In my opinion a comment field on persons profiles is not a good idea. Especially when it is displayed before you started to create your profile. People might be discouraged to create their profile. As mentioned above the comments function is good for stories, services and projects, but in my opinion not for profiles of persons and organisations.

**Comment by literarymachine** [comment]
Being able to comment on Persons was a bug, will deploy a fix soon. As for
Organizations, it is up for @trugwaldsaenger, @acka47 and you to decide.
Am 11.08.2016 09:29 schrieb "Karin Driesen" <notifications@github.com>:

**Comment by literarymachine** [comment]
Comments on `Person` pages are now disabled. Also, comments may now only be made by people who have at least their name in their profile; comments by people who deleted there name after commenting are not deleted, but hidden. On beta.

**Comment by karindr** [comment]
![image](https://cloud.githubusercontent.com/assets/18674205/17662342/1b2e6b5c-62e5-11e6-946b-99606633550e.png)
There are spaces missing before and after "profile" in the sentence for users without name in the profile see above.
The rest works fine.

**Comment by acka47** [comment]
I think comments are great but I see that this will mean a lot of work improving comment view and functions when people really start using it. We'll need to solve problems already solved by others, e.g. voting for and reporting on comments. As hypothes.is and open annotation don't seem to be an option for the world map, we might think about embedding a discourse discussion which would give us a lot of functionality (likes, votes, stats etc.). See https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 for details. What do you think?

**Comment by trugwaldsaenger** [comment]
I still think that hypothes.is might be a solution for the world map. As far as I can remember, we said that it might be a good thing to differentiate and use hypothes.is for the editing team and other people interested in making very precise comments and use another commenting function for more general comments by users. 

As far as dicourse is concerned I think we argued, that it would be problematic, if users have to register on another platform as well in order to comment on the OER World Map.

**Comment by acka47** [comment]
> As far as dicourse is concerned I think we argued, that it would be problematic, if users have to register on another platform as well in order to comment on the OER World Map. 

This "other platform" would be associated with the world map and run by us on hbz servers. I guess we could even make it one registration and login process for both services.

**Comment by literarymachine** [comment]
> I think comments are great but I see that this will mean a lot of work improving comment view and functions when people really start using it.

If you look at what we are doing when using comments here on GitHub, I would argue that a simple flat list of comments can bring you a long way.

**Comment by acka47** [comment]
After speaking to @literarymachine offline, I think going forward with the simple flat comments approach is the best option for now. +1 from me.

**Comment by literarymachine** [comment]
> There are spaces missing before and after "profile" in the sentence for users without name in the profile see above.

Fixed. Also, Markdown is now supported in comments: https://beta.oerworldmap.org/resource/urn:uuid:bb497857-9485-4aae-8e6d-10056adc973c
