### ISSUE TITLE
Use Grunt?

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#120]
@literarymachine ... I brought up the question if we need Grunt (a task runner for typical deployment tasks) again. Here the issue to collect PROs, CONs and alternatives:

PROs:
- Concats JS files, which let's us split JS code by modules/widgets
- Compresses JS files
- Let's us handpick the needed parts of Bootstrap

CONs
- Runs on node.js, which is not in our technology stack

**Comment by acka47** [comment]
Can we close this one?

**Comment by j0hj0h** [comment]
Yes, I made a new issue that covers the topic:  #787
