### ISSUE TITLE
Add share button to country pages

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1200]
As visitor and as editor I want to be able to share a country page like I can share the other pages.

**Comment by karindr** [comment]
This will be solved when the new country view from beta is estabished on production (#1087).

**Comment by dobladov** [comment]
Share is accessible from the country view. Closing

![image](https://user-images.githubusercontent.com/1938043/43724341-015701a6-999a-11e8-9c09-4b941422eef4.png)
