### ISSUE TITLE
Startpage doesn't stop loading on Windows Phone

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1204]
(Yes, I know that I represent a minority with this phone.) But the world map doesn't stop loading showing the "Welcome"-Screen. I'm using the Eduroam WLAN here.

**Comment by literarymachine** [comment]
@karindr could you check if the problem is still there with the new UI?

**Comment by karindr** [comment]
The new start page works fine but after login in the endless spinner comes.

**Comment by dobladov** [comment]
We decided to not support internet explorer on this issue, clossing.
