### ISSUE TITLE
Establish possibility to link to the new type "publication"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1205]
At the moment there is no possibility to link to the new entry type. Maybe it would be the easiest way for the moment to add a field to the publications template:
"Add this publication to:"
In the field you can choose organisation, service, event and project. In the profiles of these types there will be a heading "Publication" with the link to the publication entry.
I suggest to put this at the end of the list in all cases.

For the personal profile there has to be a field in the persons template.

**Comment by literarymachine** [comment]
> Maybe it would be the easiest way for the moment to add a field to the publications template:
"Add this publication to:"

The question here is as what to add the publication; see https://github.com/hbz/oerworldmap/issues/1032#issuecomment-287107823 for an initial list by @acka47. But maybe that is over-engineering and a simple generic link to a document is enough for now.

**Comment by karindr** [comment]
I think there are to ways to do this:

1. Simple approach as described above: In the publication template you choose where the publication should be shown a link. The link than will be shown at the end of the list of for example a project with the heading "Publication". Exception it must be done from the personal template to add publications to the personal profile.

2. Differentiated approach: In the publication template there are 4 new fields (following @acka47 s list) where you choose the title with which the link will be shown.

- Add publication to organization
Publish as policy / publication (as drop down menu)

- Add publication to event
Publish as report / recording / publication

- Add publication to project
Publish as project proposal / project report / publication

- Add publication to service
Publish as tutorial / documentation / publication

- In template for personal profile:
Publish as own publication / recommended publication

**Comment by karindr** [comment]
Now there is the case that I want to add the "Stuttgarter Erklärung" (https://oerworldmap.org/resource/urn:uuid:629d1ef7-79a0-445e-81c4-9b30ef9f102f) to the Bildungsbündnis Open Content (https://oerworldmap.org/resource/urn:uuid:09c1c26f-263d-4cd1-86a3-db0e6a7c4dab) either simply as "Publication" or better as "Policy".

**Comment by literarymachine** [comment]
> either simply as "Publication" or better as "Policy".

On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:4df69bb5-4bed-4113-8843-fdd486a616aa. You can link from `Organization`, `Service`, `Project`, `Event`, `Person` templates to `Publication` or specify the publisher in the `Publication` template. I stuck with a generic `publisher` / `publication` relation for now; regarding other roles, I would like to discuss the approach suggested in https://github.com/hbz/oerworldmap/issues/941#issuecomment-267125691 with @acka47.

**Comment by karindr** [comment]
I am okay with the part that a publication is shown as publication in other profiles. But I see some problems with the other part showing the connected entry as “publisher”. Normally publisher is used for Verlag, Verleger und Herausgeber and this is not applicable in most cases of our “publications”. I suggest to write “published by” (which has a more open meaning) or skip this information totally.

Part of the problem is that the datatype “publication” is built to be used for very different publications. For “Own publication” on a person’s profile “author” would be the right term.

Minor change: In the field “action” is listed but is has to be “project”.

**Comment by acka47** [comment]
+1 for changing "Publishers" to "Published by".

**Comment by literarymachine** [comment]
> Minor change: In the field “action” is listed but is has to be “project”.

I created a new issue for this because this is a general problem: #1252

**Comment by trugwaldsaenger** [comment]
Good that we can link publications with other entries now! But we should not forget to make it more specific, especially by making a publication the outcome of a project or a recording of an event. Do we have an issue for this?

**Comment by literarymachine** [comment]
> Do we have an issue for this?

There has been a scattered discussion, e.g. at https://github.com/hbz/oerworldmap/issues/1032#issuecomment-287107823 and up there at https://github.com/hbz/oerworldmap/issues/1205#issuecomment-300706671.
