### ISSUE TITLE
Add email addresses to country champion lists

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1209]
There is a list of all country champions that can be created with the map:
https://oerworldmap.org/resource/?q=about.countryChampionFor:*
Please change this list so it includes the public email addresses of the country champions.

Is it possible for us to generate a list of the registration email addresses of the country champions, too? This would be very useful for the newsletter.

**Comment by literarymachine** [comment]
> Please change this list so it includes the public email addresses of the country champions.

This is currently a list like any other result list, too. We have to either (a) add public email addresses to the list view of all results or (b) implement an exception for the query. The latter I definitely do not prefer.

> Is it possible for us to generate a list of the registration email addresses of the country champions, too?

Currently, no, and would mean a bit of effort to implement this.

**Comment by karindr** [comment]
I think it should be nor problem to add the email to all lists. If somebody does not need them, he can delete them.

In the long term it would be useful to have a list of the registration emails for sending a newsletter. Otherwise there has to be a list done by cut and paste, country champions may get lost.

**Comment by literarymachine** [comment]
> I think it should be nor problem to add the email to all lists. If somebody does not need them, he can delete them.

I don't understand this. Are you talking about CSV or the HTML lists?

> In the long term it would be useful to have a list of the registration emails for sending a newsletter. Otherwise there has to be a list done by cut and paste, country champions may get lost.

Keep in mind that nobody agreed to get any mail to their registration account. It is currently meant for login only. Why not use their public email addresses and check back with them if they did not provide it?

**Comment by karindr** [comment]
In the CVS list you can easily delete a column. In HTML you can do this with a little more effort, too. So I think it would be ok for all to add the email.

It is right, that the registration address isn't approved for sending emails. But not all country champion have public emails and it would be important to reach all country champions. I agree that we should not send mails to "normal" users to their registration address. But if somebody was willing to be a country champion I think he would not sue us for mailing to his registrations address. For the future I will have a look at the new country champions and encourage them to add an public email address.

**Comment by literarymachine** [comment]
> In HTML you can do this with a little more effort, too. So I think it would be ok for all to add the email.

Ok. Just to be sure: our normal result list that is shown will then always include email addresses besides the names. Or should it be only added to CSV exports?

> For the future I will have a look at the new country champions and encourage them to add an public email address.

Why not contact these five right away and save some developer time?

https://oerworldmap.org/resource/?q=about.countryChampionFor:*%20AND%20_missing_:about.email

**Comment by karindr** [comment]
OK, I was talking about the export options cvs, json and so on. It makes no sens to show this on the website.

OK, thanks for the list of CC without email. Five are easy to handle, I will do this.
