### ISSUE TITLE
Refactor registration form

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1212]
Die Pflichtinformationen mit einem Sternchen zu versehen, selbst wenn alles Pflichtangaben sind. (Wobei das Kästchen für email, su. keine Pflicht ist.)

- ein Kästchen zum Anklicken einzufügen: 

„[ ] By registering, I agree to the terms of the privacy policy (link). I specifically agree to publish the information I provide, except for my password, which will be stored securely. Your activities within oerworldmap will also be stored and processed for the purpose of improving the service as well as to prove your consent to specific activities.*"

- ein weiteres Kästchen zum Anklicken einzufügen: 

"[ ] I also agree to the Terms of the service (link). Especially, I will ensure, that no rights of others are violated by me publishing information through oerworldmap. This includes the privacy and copyrights of others.*"

- Das Kästchen zum Publizieren der E-Mailadresse sollte im Defauls deaktiviert sein, da die DSGVO demnächst „privacy-by-default“ vorschreibt. Der Text könnte konsistenterweise so gefasst werden:

„[ ] I agree to having my email-address published as part of my profile“

Wichtig! Alle Kästchen müssen per Default auf „off“ sein, also nicht angekreuzt. Bezüglich der einzelnen Formulierungen können wir gerne versuchen noch eine einfachere Sprache zu finden. Bin da für Anregungen offen.

**Comment by literarymachine** [comment]
Also, a checkbox for newsletter registration will replace the current orange button which will be moved to the footer of all static pages (maybe along with a link to register, too).

**Comment by literarymachine** [comment]
> By registering, I agree to the terms of the privacy policy (link). 
> I also agree to the Terms of the service (link).

The privacy policy is part of the terms of service, so why does the user have to agree to both? Where should the links point, to the same document?

**Comment by acka47** [comment]
Hopefully, we can get rid of the line for agreeing to the privacy policy. AFAIK, we are still waiting for the lawyer to comment on this.

However, I just registered and checked "I want to subscribe to the OER World Map Newsletter". I directly got the mailman confirmation request and waited several minutes for the world map request until I noticed that it landed in the spam folder. This is not optimal. Probably, it would be best if the confirmation text read differently when one subscribes to the newsletter. Instead of:

> Successfully registered user xyz@zyx.de. We just sent you an email with verfication link. Check your inbox.

something like

>  Successfully registered user xyz@zyx.de. We just sent you two emails with verfication links for the registration and the newsletter. Check your inbox.

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
+1

**Comment by literarymachine** [comment]
> Hopefully, we can get rid of the line for agreeing to the privacy policy. AFAIK, we are still waiting for the lawyer to comment on this.

Should we wait for a response, @trugwaldsaenger? I think other than this, we are ready to go with the new terms and conditions.

**Comment by literarymachine** [comment]
> Should we wait for a response, @trugwaldsaenger?

Feedback via email: keep both check boxes.
