### ISSUE TITLE
Rewrite registration confirmation mail

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1213]
Bei der E-Mail würde ich empfehlen, das komplette Terms-Dokument beizufügen und den Text wie folgt zu fassen:

"Welcome to the OER World Map!

To complete registration, please verify your email address, by clicking on this link:

https://oerworldmap.org/user/verify?token=XXX

By clicking on this link you also reiterate that you that you have read and accept the Terms and Conditions, including the Privacy Policy attached below. [OER Terms and Conditions].

You have especially consented to publish all the information you provided except - of course - your password [and your emailadress, if not stated otherwise] (könnte man automatisch unterschiedlich generieren). Your activities within oerworldmap will also be stored and processed for the purpose of improving the service as well as to prove your consent to specific activities.

You have also promised to ensure, that no rights of others are violated by you publishing information through oerworldmap. This includes the privacy and copyrights of others.

Enjoy mapping the world of OER!

Yours sincerly,
The OER World Map Team

To get in touch with the administrators of OER Wold Map directly, please contact: info@oerworldmap.org.

Anbieterkennzeichnung i. S. d. §5 Telemediengesetz (TMG) und Verantwortlich für den Inhalt nach §55 Abs. 2 Rundfunkstaatsvertrag (RStV):
Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen (hbz), Jülicher Str. 6, 50674 Köln Deutschland, Tel.: +49 221 400 75-0 Fax.: +49 221 4 00 75-180
E-Mail: info-hbz@hbz-nrw.de Internet: http://www.hbz-nrw.de ISIL: DE-605, Umsatzsteuer-Identifikations-Nummer: DE 123486775
Das Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen ist eine Einrichtung des öffentlichen Rechts. Es wird gesetzlich vertreten durch Dr. Silke Schomburg (Leiterin). Das hbz untersteht der Dienst- und Fachaufsicht des Ministeriums für Innovation, Wissenschaft und Forschung des Landes Nordrhein-Westfalen, Völklinger Straße 49, 40221 Düsseldorf. Inhaltliche Verantwortung gem. § 55 Abs. 2 RStV: Dr. Silke Schomburg (Leiterin).
 

Und ausserdem: in plaintext/html or as PDF-Attachment bitte den „Full Text of Terms“ beifügen)

**Comment by literarymachine** [comment]
> Und ausserdem: in plaintext/html or as PDF-Attachment bitte den „Full Text of Terms“ beifügen)

@trugwaldsaenger In den Terms of Service heißt es bezüglich der Web Analytics: "...anytime you are accessing OER World Map from this browser." Das ergibt aber keinen Sinn, wenn der Text per Email verschickt wird. Was meinst du?

**Comment by acka47** [comment]
+1
