### ISSUE TITLE
Add newsletter registration form to footer of all static pages 

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1216]

**Comment by formimkontext** [comment]
Draft for the integration of the newsletter registration form in static page layout. Draft also shows how the FAQ page could work and look like in the future, using a accordion menu to browse through different questions. 

![20170530-faq](https://cloud.githubusercontent.com/assets/15141949/26587691/55a321e6-4553-11e7-8d6e-f02481a04bd8.png)

**Comment by karindr** [comment]
I like the design of this footer but it is very prominent in my opinion. If we are advertising this much for our newsletter we have to have a good plan what and how often we will sent mails this list. I open an issue for this: #1240.

**Comment by karindr** [comment]
The accordion menu for the FAQ looks great. It will work much better, because people will only see what they need and not a "Bleiwüste"!

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/5db332406775868e57674191d8483a35035c9dce, closing.
