### ISSUE TITLE
License and citation information for original and republished stories

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1222]
The situation for stories is a bit confused regarding licensing, citation information and even creator information. J. Schallerböck's proposal for publishing stories unfortunately doesn't address the difference between original and re-publication. So we will have to find a solution.

**Current status**

Original posts:
- There is no structured license indication / no possibility to choose an open license
- People aren't ask to agree publication under an open license and to assure they have the rights for publication for content and embedded images/videos.

Republished posts:
- There is no indication of the original source in the structured data (e.g. by linking to it with http://schema.org/isBasedOnUrl or http://schema.org/exampleOfWork)
- In the structured data, a person is recorded as `schema:creator` who actually isn't the creator but only added the story to the World Map.
- The original creator is only named in the story's body (in italics) with link to the original resource and license (see #912 )

**Proposal for improvement**
- _For republications_, add link to original version as `schema:basedOnUrl` or `schema:exampleOfWork` + citation field (http://schema.org/citation) with creator, title, license
- *For original publications*, add license field (http://schema.org/license) with dropdown and automatically create citation proposal (Creator, title, date license, URL)

Implementing the proposal would mean enabling people to choose a publication type (original or re-publication) when starting the publishing process. This probably isn't directly needed. For the start, we could just add the needed fields (isBasedOnUrl/exampleOfWork, license citation) and skip the automatic creation of a citation.

Regarding the legal text, it maybe could read like this (adjusting the text by J. Schallerböck):

> I agree to publish the information above with the following license notice and assure, that I have all rights necessary to publish the information and to attach this license:

**Comment by literarymachine** [comment]
> For original publications, add license field (http://schema.org/license) with dropdown

As discussed offline with @trugwaldsaenger, we will make the usage of CC-BY mandatory for stories, no drop down needed.

**Comment by acka47** [comment]
+1
