### ISSUE TITLE
Evaluate possibilities for a future OER World Map mobile app

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#1223]
Analyse the possibilities for creating a mobile app:
- What could be gained? (There was some enthusiasm for the idea of push notifications but these can also be implemented through a browser)
- How would the experience be different (if at all)?
- Is it worth the extra effort when what is gained might be minimal? 
- People might not update an app but mobile version will update automatically

One possibility would be to encouraged people to add a browser shortcut to their mobile device - this could function a lot like a native app.  (A separate ticket on "Slick Bookmarking"/Improving Mobile View has been raised for this.)

**Comment by literarymachine** [comment]
http://labs.ft.com/2012/08/basic-offline-html5-web-app/

**Comment by literarymachine** [comment]
Out of scope, use responsive version.
