### ISSUE TITLE
Improve style for hovered and "active" countries

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#1227]
Implement new drafts for style of country view and a similar clear solution for hovering.

**Comment by formimkontext** [comment]
Could be something similar to the country view.

![20170214-oerwm-countrychampion-1](https://cloud.githubusercontent.com/assets/15141949/26241013/756a2868-3c83-11e7-9b1f-aa2ee28e14c9.png)

**Comment by dobladov** [comment]
Fixed in the new UI, closing.
