### ISSUE TITLE
Logos are too big in mobile/small window view

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1229]
See e.g. https://oerworldmap.org/resource/urn:uuid:446fb8e9-281a-48bb-811a-4b5797c47291 on half of your screen.

Screenshot:
![bildschirmfoto vom 2017-05-19 12 53 39](https://cloud.githubusercontent.com/assets/160292/26244948/3c93b00e-3c92-11e7-9665-7737f2a69345.png)

**Comment by acka47** [comment]
Another example is https://oerworldmap.org/resource/urn:uuid:7ce0b73d-8162-4c32-b691-6915e848b911

**Comment by formimkontext** [comment]
Discussed the problem with @j0hj0h. He will fix it by redefining the breakpoints and image size.

**Comment by dobladov** [comment]
Fixed in the new UI. 

![image](https://user-images.githubusercontent.com/1938043/43405721-c34c4062-941a-11e8-8d6b-a8e376923973.png)
