### ISSUE TITLE
Verification e-mail not sent

### ISSUE THREAD

**Issue by klukens** [hbz/oerworldmap#1234]
Hello -

I'd like to register my event on the map, t3.snc.edu. I tried creating an account for the map using my krissy.lukens@snc.edu e-mail address, but have not received a verification email for my account. Help?

**Comment by karindr** [comment]
@literarymachine can you have a look? I searched in the list of registered users and could not find the email there.

**Comment by literarymachine** [comment]
@klukens unfortunately I cannot reproduce this issue. I tested the signup procedure and got the verification mail ok. There is a pending account to be verified for your email, and the email has also been sent. Did it perhaps end up in your spam?

**Comment by klukens** [comment]
Doh!! Dang spam. Yep - it was there. Thanks.
