### ISSUE TITLE
Location for projects should be optionally

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1237]
I just added the 101 Stories Project to the map:
https://oerworldmap.org/resource/urn:uuid:4c9803fd-c149-42a3-8639-04450bcb080e

I nearly failed to save it, since the platform requires adding a location or an operator for the project.

I could not give any of it, since it is run by six persons, which have not registered yet, at the same time I could not add a location, since these six peaple are living on six different continents.

I finally added GoGn as operator (because all operators are affiliated to GoGn), but this is not true and has to be changed.

**Comment by karindr** [comment]
In general it sometimes causes problems if you have to fill in fields that don't fit exactly. Another example is the OERcamp Ost with no date yet. This problem also occurs if you want to make a change to an old entry and this entry misses some of the required information so you can decide whether to leave the entry as it is or to add some data that is not completely correct. 

**Pragmatic solution: Make it a two step process**
When you save the template there is the answer "Please add a location and a end date!" (for example) and a second button with something like "save it anyway". This way users are pointed to fields we want to be filled in and on the other side we don't prevent things to be put to the map that don't fit in exactly.

**Comment by karindr** [comment]
See #1261, the two step Process would be helpful here, too.

**Comment by literarymachine** [comment]
> When you save the template there is the answer "Please add a location and a end date!" (for example) and a second button with something like "save it anyway".

From a workflow perspective, this is indeed a pragmatic approach. But keep in mind @acka47 that we then have to somehow model "recommended" fields in our schema and also implement validation for these because AFAIK there is no support for this. As you can imagine, this won't be trivial.

**Comment by literarymachine** [comment]
The schema should definitely be relaxed.

**Comment by literarymachine** [comment]
> The schema should definitely be relaxed.

On beta, see http://oerworldmap.localhost/resource/?add=Action
