### ISSUE TITLE
When I have set different filters I want to disable single filters by clicking on them

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1255]

**Comment by literarymachine** [comment]
Please clarify what you mean. Currently, clicking an enabled filter disables it. In which way should this be changed?

**Comment by karindr** [comment]
It should work like you describe it but it does not: 

- When I click on event and choose a subject and then click on service the chosen subject is lost.
- When I click on services, result list with 366 services. Than choose country filter Germany 94 entries. Than I want to turn off the filter services and click on it, the map starts showing the spinner and not stopping it for at least 3 minutes (I did not wait longer). Same for organisation and tag.

**Comment by literarymachine** [comment]
> When I click on event and choose a subject and then click on service the chosen subject is lost.

But this is how it should be. Click on event chooses the `Event` type:

![screenshot from 2017-06-27 11-05-18](https://user-images.githubusercontent.com/149825/27579696-aa2bb4a4-5b28-11e7-9170-8214681c2827.png)

The select a subject and apply filter:

![screenshot from 2017-06-27 11-05-40](https://user-images.githubusercontent.com/149825/27579711-b569d7ce-5b28-11e7-908a-17c661d4b53a.png)

Now both filters are active:

![screenshot from 2017-06-27 11-05-56](https://user-images.githubusercontent.com/149825/27579716-ba51bc98-5b28-11e7-88c6-50e1230ce9f0.png)

Click on the subject filter again to deselect the filter, now only the type filter is set again:

![screenshot from 2017-06-27 11-05-18](https://user-images.githubusercontent.com/149825/27579753-dd9ea986-5b28-11e7-9aeb-42b5e34b6fc4.png)

> When I click on services, result list with 366 services. Than choose country filter Germany 94 entries. Than I want to turn off the filter services and click on it, the map starts showing the spinner and not stopping it for at least 3 minutes (I did not wait longer). Same for organisation and tag.

I confirm this bug!

**Comment by literarymachine** [comment]
> When I click on event and choose a subject and then click on service the chosen subject is lost.

Now I understand; indeed, sub filters are currently unset when changing the type filter.

**Comment by karindr** [comment]
It would be very helpful to have this enhancement.

**Comment by literarymachine** [comment]
> It would be very helpful to have this enhancement.

How does this relate to https://github.com/hbz/oerworldmap/issues/1506#issuecomment-389481674?

**Comment by literarymachine** [comment]
@karindr would this be solved if we implement what @formimkontext describes in https://github.com/hbz/oerworldmap/issues/1155#issuecomment-328560905? Of course all filters would be represented like this, not only tags...

**Comment by karindr** [comment]
Yes, maybe with little headline with the name of the filter:
Tag:
advenced x    oer x
Country:
France x    UK x

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?filter.about.%40type=Service&filter.about.keywords=oer-award%202016&filter.about.award=https%3A%2F%2Fopen-educational-resources.de%2Fwp-content%2Fuploads%2Foerde16_logo_award.png&filter.about.availableChannel.availableLanguage=en&filter.about.availableChannel.availableLanguage=de&size=20:

![image](https://user-images.githubusercontent.com/149825/41966722-27835b86-7a00-11e8-8eec-b547325c3409.png)

> Yes, maybe with little headline with the name of the filter:

This would take a lot of space. We gave the filters a mouse over tool tip with the name of the filter.

**Comment by karindr** [comment]
+1
