### ISSUE TITLE
Establish graph and index for user interactions

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1257]
As discussed with @philboeselager, both a separate graph and a separate index shall be used for user actions such as #1128 to better separate those interactions from our usual entries.

**Comment by literarymachine** [comment]
The base type for all entries in the new graph / index should probably be [`InteractAction`](http://schema.org/InteractAction).

**Comment by philboeselager** [comment]
> The base type for all entries in the new graph / index should probably be InteractAction.

The schema.org type hierarchy is:

- Thing > Action > InteractAction > CommunicateAction > CommentAction
- Thing > Action > AssessAction > ReactAction > LikeAction

So, `InteractAction` does not suit the `LikeAction`. The base type must be `Action` then, right?

**Comment by literarymachine** [comment]
> So, InteractAction does not suit the LikeAction. The base type must be Action then, right?

Right! We should keep in mind that we are using `Action` (labelled `Project`) in our main database, too.

**Comment by philboeselager** [comment]
While running tests for this issue, the old play config seems to come up again. So I'm working on https://github.com/hbz/oerworldmap/issues/1296 first.

**Comment by acka47** [comment]
Regarding data models / vocabs for social interactions see also [Activity Streams 2.0](https://www.w3.org/TR/activitystreams-core/) and the [Activity Streams Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/).

**Comment by philboeselager** [comment]
Thanks for the link, @acka47 . Activity Streams only cover `Like`s (combinable with schema.org's `LikeAction`s), but not `comment`s or `LighthouseAction`s. So, we would need to be inconsistent when using Activity Streams, right? I would prefer referring to schema.org only then.

**Comment by acka47** [comment]
As we use schema.org anyway and if it covers a lot of what we need, we should go forward with it.

**Comment by literarymachine** [comment]
We have been doing fine without an extra graph and index for quite some time now, closing.
