### ISSUE TITLE
Export of list of persons connected to subprojects of "OER Förderrichtlinie" easily usable for users

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1262]
This issue is a kind of a second step to issue #1077.

From people from the oerinfo projects there is the idea of being able to generate a list of all people connected to oerinfo projects like the list above but including the description and the tags. And there has to be an easier way to get the data into excel. At the moment (see #1077) you have to use copy and paste, save as txt in notepad then open in excel, make several decisions and then format the list by hand. 

We need to establish an easier way to get to this list. First step would be to have a cvs download as from other points of the map.

**Comment by literarymachine** [comment]
Outdated, closing.
