### ISSUE TITLE
Strange characters in ecxel lists when opening cvs exports from the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1263]
When I take the cvs export from for example 
https://oerworldmap.org/resource/?q=&filter.about.%40type=Action&filter.about.keywords=oerinfo
and open it in excell I get a lot of strange characters like this:
"MatÂ³ - Offene Materialien fÃ¼r Mathematik-LehrkrÃ¤fte & Multiplikator_innen: Zwei-Ebenen- Qualifizierung fÃ¼r Entwicklung und Nutzung, de" 

Because excel simply opens the cvs file without any questions the usere has no possibility to change these characters before opening. Our goal should be to have a cvs that can be opened and shows clean data you can directly work with.

I also have feedback from somebody who tried to work with this cvs list and stopped after 15 minutes trying araound.

**Comment by literarymachine** [comment]
> Because excel simply opens the cvs file without any questions the usere has no possibility to change these characters before opening.

Well, this seems to be a matter of Excel then. We are exporting our data as UTF-8, and if I chose that when importing to Open Office, all seems good:

![screenshot from 2017-06-29 13-28-48](https://user-images.githubusercontent.com/149825/27685558-0823ef16-5ccf-11e7-92b7-780daa149a54.png)

There seems to be an option for this in Excel, too: https://superuser.com/a/302878

**Comment by literarymachine** [comment]
I can, of course, also change the encoding for CSV. But I have no idea what the default encoding is, that Excel expects. @karindr can you tell me?

**Comment by literarymachine** [comment]
"As of this writing, there exists a single usable CSV format that Microsoft Excel can both read and write safely across platforms. Tab delimited UTF-16LE with leading Byte Order Mark. [...] If you operate an application with a CSV exporter please use this as your default export format. It will save us all many headaches in the long run." https://donatstudios.com/CSV-An-Encoding-Nightmare

**Comment by philboeselager** [comment]
@literarymachine Unfortunately, they do no tell, whether UTF-16LE is a properly working decoding for OpenOffice / LibreOffice and other (CSV) applications, too. I strongly vote for and recomemnd working with commonly accepted standard formats - and UTF-8 is the world's most common decoding standard.

**Comment by philboeselager** [comment]
@karindr There should be a workaround for converting UTF-8 to other decodings. Please contact me, of that problem still exists by the time of having collected all necessary data.

**Comment by karindr** [comment]
Philipp an I talked about this. For the Atlas it is no problem, so we don't change anything in the moment. If an excell user askes we can tell him a way to solve the problem.

**Comment by literarymachine** [comment]
Won't fix, closing.
