### ISSUE TITLE
Abbreviation should be also shown in the result lists

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1268]
Often the abbreviation is better know than the real name of a project, organisation and so on. For this reason it should be also shown in the relusts list in brackets as usual.

**Comment by karindr** [comment]
This would be really helpful to find projects in long lists for example the Förderrichtlinien-list.

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/pull/1284#issuecomment-361522579
