### ISSUE TITLE
Remove HTML output from API

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1269]
Rendering the UI will be the job of an entirely new component, so any traces of HTML rendering should be removed from this repository.

**Comment by trugwaldsaenger** [comment]
@literarymachine: This seems to be the last open issue within the milestone "separation of concern". Can we close the milestone?

**Comment by literarymachine** [comment]
Resolved in 3749793c5918b0853d66c51c7292ea6fd8488b6a.
