### ISSUE TITLE
Big gaps under first paragraph next to images/fotos

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1270]
Why is ther such a big gap under the first paragraph? I don't remember such big gaps when using fotos/images. Has something changed? Or is there a trick to avoid these gaps?
![image](https://user-images.githubusercontent.com/18674205/27857404-d8f13e04-6171-11e7-9c14-389f7f3550c3.png)

**Comment by karindr** [comment]
@formimkontext: I this your "Baustelle"?

**Comment by literarymachine** [comment]
> Why is ther such a big gap under the first paragraph? I don't remember such big gaps when using fotos/images. Has something changed?

This probably has to do with with the image source being added since #1215, right @j0hj0h?
