### ISSUE TITLE
Delete line between "Comment" and first comment

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1271]
Please delete the line between "Comment" and first comment because it indicates that the comment section is allready closed. It seperates the headline from the content.
![image](https://user-images.githubusercontent.com/18674205/27857606-9dd2844e-6172-11e7-9a54-61e488467c2d.png)

**Comment by karindr** [comment]
@formimkontext, I think this is a design issue, isn't it?

**Comment by literarymachine** [comment]
> @formimkontext, I think this is a design issue, isn't it?

Well, the line being there might be a design issue. But if it is clear that it shouldn't be there, it is a matter of CSS styling for @j0hj0h.

**Comment by formimkontext** [comment]
The line seperating the single comments should have the same light colour like the lines seperating single list entries. I will talk with @j0hj0h about that.

**Comment by karindr** [comment]
The line above the first lighthouse comment and under the heading "Lighthouse Comments" is also too strong/dark. Please change it here also.

**Comment by dobladov** [comment]
We use a line to separate headings like _Comments_ and  _Tags_ in the new UI, should we make any changes @karindr?

![image](https://user-images.githubusercontent.com/1938043/43535697-fa2dd220-95ba-11e8-96db-4718b96270c9.png)

**Comment by dobladov** [comment]
> It is OK like this.

Closing the issue.
