### ISSUE TITLE
What happens if we delete a personal profile?

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1274]
Sometimes people from organisations use the personal profiles to enter the data about their organisation. we try to contact them but if they don't answer we transfer the information to an organisation page. After that I want the personal profile to disappear. Can I simply delete the profile or does this affect the registration/login of the user? And would he be able to create a new profile if he wishes to without new registration?

**Comment by literarymachine** [comment]
Since #893, deleting a profile also deletes the account. So you have to register again when your profile was deleted.

**Comment by karindr** [comment]
I see. Could't we establish a (secret) name that makes these profileses be hidden? For example change the name to "++this profile will not be shown++" and afterward it is no longer shown. I think we have profiles from people who registered early with numbers instead of names that are not shown. Otherwise we have to  stuck to these false profiles.

I don't like the idea of deleting the profile in these cases, because thee people only made a mistake. It is not like deleting a spam profile.

**Comment by acka47** [comment]
I am ok with using a specific name that makes the profile hidden.
