### ISSUE TITLE
Decide on CSS preprocessor for the new UI

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1275]
Should we use LESS, SASS, or something completely different? Up to you, @dobladov and @j0hj0h!

**Comment by dobladov** [comment]
I would say that the easiest thing we can do, it's to keep **Less**, **Sass** has more functionality but we probably don't need that anyway.

**Comment by j0hj0h** [comment]
We should talk about that next week. Previous question is, if we'll use a framework again and what preprocessor it is based on. I tend to not using a framework. And I'd be fine with both LESS and SASS ... but I'd like to talk about it with you in person @dobladov. Is that okay or do you want to decide this before?

**Comment by dobladov** [comment]
We should discuss this the next week, but I agree with you, I rather not use any framework and use [Flexbox](https://caniuse.com/#search=flexbox) for the layout, also bootstrap's components does not seem to fit much with what we are trying to archive, maybe if we decide to go with a framework we can use something smaller like [Skeleton](http://getskeleton.com/) just for the grid and forms.

**Comment by j0hj0h** [comment]
decision made: cssnext/postcss
