### ISSUE TITLE
We need "mentioned in" function for publications

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1276]
At the moment we can link for example from a project to a publication. Then the publication is listed on the projects profile as publication (as I wished) but on the other hand on the publications profile the project is listes under "Published by". In my example the publications are reports and interviews written by Informationsstelle OER about the 2.2er projects. They should be shown at the profiles of the projects but the projects are not the publishers! This is only Infostelle. See:
https://oerworldmap.org/resource/urn:uuid:18d86490-9f88-4ad3-aca7-568ff3731fca

So we need to establish a function "Entries mentioned" and "Mentioned in" as for stories. The "Mentioned in" section in the profiles can include both stories and publications, because they can be distinguished by their icon.

**Comment by karindr** [comment]
Again a case where I have to add the topic of a publication (an interview) as publisher because there is no "Entries mentioned"/"Mentioned in" field.
https://oerworldmap.org/resource/urn:uuid:8a7c5aa5-3b92-4ea3-acff-2b64a492ef68

**Comment by karindr** [comment]
This is still relevant.

**Comment by literarymachine** [comment]
Fixed in a0c50c3039babed9055cf6fa7dcb143a5760267e
