### ISSUE TITLE
Information to licences for stories are inconsistent (or at least confusing)

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1282]
As user i want to publish a story on the world map (original, not republishing).  In the template there is the checkbox for ccby I have to  activate that i can save, but the text above the save button says "I agree to publish the information above under the conditions of CC0-License." It can't be ccby and cc0 the same time.
![image](https://user-images.githubusercontent.com/18674205/28161689-b6b5f420-67c4-11e7-8161-71893ab4b5fe.png)

**Comment by literarymachine** [comment]
I think this is indeed a bug; the CC-0 note at the bottom should only be displayed for the other entry types, not for stories.

**Comment by trugwaldsaenger** [comment]
> I think this is indeed a bug; the CC-0 note at the bottom should only be displayed for the other entry types, not for stories.
Yes!
