### ISSUE TITLE
Prevent users from saving more than one time

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1300]
A user mailed: "nun habe ich, weil das Fenster sich beim Speichern nicht schloss, offenbar eine Publikation dreimal angelegt". I deleted the two of the entries. 

What can we do to prevent this? (As another user told us the World Map is often pretty bussy loading when the connection is not to good.)

**Comment by literarymachine** [comment]
> What can we do to prevent this?

@j0hj0h we should probably block the UI when the publish button has been pressed.

**Comment by karindr** [comment]
This happens quite a lot.

**Comment by literarymachine** [comment]
Ping @j0hj0h

**Comment by literarymachine** [comment]
Especially since https://github.com/hbz/oerworldmap/issues/1333#issuecomment-331121555 this is of high priority!

**Comment by karindr** [comment]
this did not happen for quite a long time. I think it is solved. Closing.
