### ISSUE TITLE
Links in comments

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1303]
At the moment links in comments are inactive, see:
https://oerworldmap.org/resource/urn:uuid:7ce0b73d-8162-4c32-b691-6915e848b911
In my opinion this is ok like this. if somebody wants to follow the link he can copy the url. But a user expected the links to be active. 

Should we stay like this or should we change this?

**Comment by acka47** [comment]
I think URLs should automatically turned into links as is done with GitHub markdown. The example comments really don't look good.

**Comment by karindr** [comment]
Links are aktive. Closing
