### ISSUE TITLE
Numbers get to close together on the startscreen

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1307]
Have a look at this, in the german translation the numbers get to colse so they look like a much bigger numer 390376231 (besides, cool great number ;-). See:

![image](https://user-images.githubusercontent.com/18674205/28618844-332efde4-7206-11e7-829a-4a52f5629dcc.png)

**Comment by formimkontext** [comment]
This Problem could and should be solved with the new / future splashscreen. see @ #1086
