### ISSUE TITLE
Cannot publish story without adding licence/citation; Text appears to be broken

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#1313]
I am trying to publish a story using content from http://www.uni-med.net/oer-morocco-declaration/.  When I try to publish it I get an error message asking me to select citation or licence but I could not see way to do this.  Eventually I was able to publish by ticking the box but the sentence next to it read like it was unfinished.... 

![screen shot 2017-08-16 at 11 37 13](https://user-images.githubusercontent.com/10849418/29359477-bcc4eb9c-8276-11e7-9f63-f59d664aa999.png)
![screen shot 2017-08-16 at 11 34 58](https://user-images.githubusercontent.com/10849418/29359485-c052efe8-8276-11e7-8a5c-fa22a2a9709f.png)
![screen shot 2017-08-16 at 11 32 51](https://user-images.githubusercontent.com/10849418/29359488-c28c3a94-8276-11e7-85b2-bb4d56f09866.png)

**Comment by literarymachine** [comment]
> Eventually I was able to publish by ticking the box but the sentence next to it read like it was unfinished....

You are right @drrobertfarrow, this is a bug.
