### ISSUE TITLE
Refinements in tools template and other points concerning tools

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1316]
In Abkürzung, see:
![image](https://user-images.githubusercontent.com/18674205/29514196-fa0b68ec-8667-11e7-8362-387c4beacaaa.png)

See also "Wir verwendet" instead of "Wird verwendet"

**Comment by karindr** [comment]
The help texts are missing. When you hover the "?" The name of the property (or what ever) is shown instead.

**Comment by karindr** [comment]
In the template for services there is no name tor the tools field. I suggest to use:

"Tools used" (Verwendete Tools)

und als Hilfetext:

"Tools used to build and maintain this service" (Tools, die verwendet wurden, den Service aufzubauen und weiterzuführen)

**Comment by karindr** [comment]
Tools should have a licence field simmilar to services with the software licences respectively the information that he software is proprietary. Jens Lechtenbörger pointed to this.

**Comment by karindr** [comment]
It should ne "Tags" instead of "Keywords" as for the other document typs.

**Comment by karindr** [comment]
The icon should be something more tools like (maybe a wrench). The actual icon reminds me of a folder.

**Comment by formimkontext** [comment]
Maybe just use this icon for tools: http://fontawesome.io/icon/wrench/

**Comment by karindr** [comment]
Mostly solved, closing.
