### ISSUE TITLE
Possible bug affecting display of champion logo/photo 

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#1319]
I've just been adding a story in Scotland and (accidentally) clicked on UK as a whole.  The country champion image for OER Hub seems stretched/distorted.
![screen shot 2017-08-23 at 10 03 32](https://user-images.githubusercontent.com/10849418/29607646-cb395b18-87e9-11e7-9dce-5a9e78c211a5.png)
I refreshed it a couple of times but that did not seem to fix it.

**Comment by karindr** [comment]
Still cut off in the new country view.

**Comment by formimkontext** [comment]
we will display logos / img in the following way:

images of personal profiles will be scaled proportional and displayed without padding. they might be still cut off, depending on the format of the original image.

logos of organizations, services, etc. will be displayed with a padding and adjusted to the size of the image box.

**Comment by literarymachine** [comment]
Fixed in the new UI, closing.
