### ISSUE TITLE
It is possible to enter more than 4 digigts as year for project start, should be changed

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1321]
A user entered 20161111 as date and it was accepted. This should not be possible.

**Comment by literarymachine** [comment]
> A user entered 20161111 as date and it was accepted. This should not be possible.

We are accepting [ISO 8601](https://de.wikipedia.org/wiki/ISO_8601) for all date inputs, where this is valid. Besides this, project starts should not only be limited to years, but also to months (e.g. `2017-01`) and exact dates (e.g. `2017-01-01`), no?

**Comment by karindr** [comment]
Most people will use "-" as separators. So I close this issue because according to ISO 8601 using no separators is not wrong.
