### ISSUE TITLE
Some points concerning map on oerinfo-website

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1323]
http://open-educational-resources.de/ is finally online. There are some points that should be changed:

- on the homepage the whole world is shown it should be only Germany as on the page when following the link
- the English version is shown, it should be the German version
- the picture of Jan as country champion is not shown

**Comment by karindr** [comment]
Sorry. Point two is correct on the website. I changed my browser to English before the weekend. So it is only point 1 and 3.

**Comment by literarymachine** [comment]
> on the homepage the whole world is shown it should be only Germany as on the page when following the link

I will hopefully deploy #1087 this week. After that, they should link to https://oerworldmap.org/country/de instead of https://oerworldmap.org/.

> the picture of Jan as country champion is not shown

Looks like @trugwaldsaenger deleted the image from his blog.

**Comment by karindr** [comment]
@trugwaldsaenger, your blog is not available. Should we use another image?

**Comment by acka47** [comment]
The blog is not available (looks like you lost the domain oersys.org, @trugwaldsaenger :worried:  ) but the image link actually went to http://open-educational-resources.de/wp-content/uploads/Jan-Neumann-Foto-unter-CC-BY-4.0.jpg. It seems like the link was changed in the process of updating the site. However, I now added the new link http://open-educational-resources.de/wp-content/uploads/Jan-Neumann-Foto-unter-CC-BY-4.0.jpg to Jan's profile.

**Comment by karindr** [comment]
@literarymachine, since #1087 has been closed. Con OERinfo now link to the german country view?

**Comment by literarymachine** [comment]
> Con OERinfo now link to the german country view?

As far as I can see, they are already linking there: https://open-educational-resources.de/karte/

**Comment by karindr** [comment]
Yes, but on their homepage ist the world, see in the bottom:
https://open-educational-resources.de/
So maybe they only have to change e linke or something like that? Do you know who to ask?

**Comment by literarymachine** [comment]
> Yes, but on their homepage ist the world, see in the bottom:

This is a static image, probably a screenshot they took some time ago. @trugwaldsaenger probably knows best who to contact, nothing we can do from developer side here.

https://open-educational-resources.de/wp-content/themes/oer2017/img/map.PNG

**Comment by karindr** [comment]
OK, I will ask Luka. So these points are solved :-)
