### ISSUE TITLE
Filter buttons for primary and secondary sector should be kept together ...

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1324]
... and the first should be the primary sector. At the moment it is like this:
![image](https://user-images.githubusercontent.com/18674205/30313230-ed1ea3a6-979c-11e7-8c94-340b12ad8681.png)

**Comment by trugwaldsaenger** [comment]
Agreed - both fields should be stand together, first the primary sector and then the secondary sector. Also it does not look nice that on both bottoms the words are cut off. Maybe we could use "1. Bildungssektor" and "2. Bildungssektor"?

**Comment by karindr** [comment]
Solved with new UI.
