### ISSUE TITLE
Orange dot is not shown after entering the location

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1333]
When I enter the location for the entries from the list from issue #1087 the orange dot is not shown after i saved the entry. This is irritating because I cant see if it has worked. When I go back to the home view and do a search for the entry the ornage dot is shown.

**Comment by literarymachine** [comment]
We have had this several times. This is due to the asynchronous indexing that we introduced due to long saving times.

**Comment by karindr** [comment]
At the moment the dot  appears immediately! Nice!

**Comment by literarymachine** [comment]
> At the moment the dot appears immediately! Nice!

Yes, but I disabled asynchronous indexing to do so. This means that in certain cases, saving can take longer again now, but in general indexing speed has greatly increased. Please let me know if you encounter cases where this is unacceptable!

**Comment by karindr** [comment]
OK.
