### ISSUE TITLE
Aggregated Consortia View

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#134]
As a member of an OER consortia (Open Education Consortia, Commonwealth of learning) I want to be able to display all institutions, which are members of the consortia.

**Comment by trugwaldsaenger** [comment]
This is actually kind of a variation of the country view (#26). But instead of looking for information, which is connected to a country I`m looking for information, which is connected to a consortia, which can be made of international members. This should be relevant for the statistics module as well. Example: 
- show me how many new projects have been started by consortia x in the last year.

**Comment by acka47** [comment]
Done. Closing.
