### ISSUE TITLE
Define Subcategories for Services

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1340]
It is pretty clear, that services should be divided in subcategories. The big question is, what are the subcategories? 

An initial list was  created for the [OER-Atlas 2016](https://oerworldmap.files.wordpress.com/2016/03/oer-atlas-2016-komplett.pdf): 
- Mooc-Platforms
- Textbookplatforms
- Repositories
- Referatories
- Wikis
- Others

This is better than no subcategories, but for sure it is far from perfect:

- One could doubt that **Textbooksplatforms** are a subcategory of themselves. It could also be a repository, which include OER of the special format "textbook". But this would require us to add yet another field (at least a tag) for formats in order to be able to identify repositories, which include textbooks. For **Mooc-Platforms**, this would be very similar.
- It is not easy to define, what an **OER repository** is. At the moment I think it should be understood in a narrow sense, as quality repositories, as you can find in Higher Education. These repositories, have well structered collections, use metadata, provide interfaces like OAI PMH and make it easy for the user to find the included contents, nomally providing a search interface.
- All other websites, which include some contents could be named "**other content sources**". 
- **Referatories** are services, which allow to search for OER, which are stored on other sides. I identified at least three types of referatories, which fit to this discription: search engines, social bookmarking services and manually created link lists.
- **Authoring tools**: This category has not been included in the Atlas, but in the UNESCO OERde report. As we have pointed out in xxx, the name is misleading, since we are speaking about services, not about tools. So we have to find a better name for this. Nevertheless, the category is quite important, since a good editor, which supports reuse of existing materials, applying open licensing and metadata adoption is critical for the success of OER. This was also one of the results from the Hewlett OER Infrastructure Meeting in February 2017.
- It has been frequently criticized that I added "**wikis**" as an own subtype. Wikis could be "other content sources" or maybe even "repositories", if using good metadata. If you use them for creating a link list, it would become a "referatory". Since you can create contents with them,  the are also editors/authoring tools. Additionally it seems to me :they support collaborative content creation very well, so that alltogether I guess they are somehow special.
- **blogs**: I think that it would be fantastic, if we could create a list of all existing blogs on OER, so this could be another subcategory.
- **Information & Reflection:** Blogs could be just part of a wider group, which provides information on OER, like OERinfo or podcasts on OER.
- **OER Tutorials:** This could be a special subcategory as well. Everything which is produced by the OERinfo Train the trainer projects fits into this category. 
- **Learning platforms:** Here the focus is not on delivery of content, but on providing a direct learning experience. So you will have to register, be tracked and analysed and often a learning path will be provided. I guess this will be a very important category of services in the future.
- Missing is something like **community platforms**, which allow to develop user communities. This seems to be very important to me as well, but have no idea, how to approach this practically.
- **other**: there will always be stuff, which does not fit into the mentioned categories, e.g. legal consultance on OER.

Another big question is, how to handle services, which fall into **multiple subcategories**. Best example for this are wikis (see above). But @thomashkov  pointed out that this is true for tutory as well. Actually I expect that most services will include elements from several subcategories. So how do we handle this?

**Comment by karindr** [comment]
Answer from Klaus Meschede‏ @kmesch1, Antwort an @oerworldmap_de
Community Platforms, z.B. https://www.facebook.com/groups/OERde/  :-)

**Comment by trugwaldsaenger** [comment]
I have started summarizing all second level types in one document: https://docs.google.com/document/d/1vH4odAccnQhKdg-ra4_GHEt4hdBADLC7eZNTHpst92k/edit?usp=sharing

**Comment by literarymachine** [comment]
> I have started summarizing all second level types in one document:

@acka47 I ported this so SKOS here: https://github.com/hbz/oerworldmap-ui/blob/1545-SecondLevelNavigation/src/json/services.json

**Comment by acka47** [comment]
I am not so happy with the organization subtyping. I guess it would make sense to remove some types and instead add another dimension in the description (at least the private/public distinction).

**Comment by literarymachine** [comment]
> I am not so happy with the organization subtyping. I guess it would make sense to remove some types and instead add another dimension in the description (at least the private/public distinction).

Again, maybe we should look at what others have done instead of reinventing the wheel. See e.g. the "EUN Organisation Type Values" in the [Vocabulary Bank for Education](http://europeanschoolnet-vbe.lexaurus.net/vbe/browse).

**Comment by trugwaldsaenger** [comment]
> Again, maybe we should look at what others have done instead of reinventing the wheel. See e.g. the "EUN Organisation Type Values" in the Vocabulary Bank for Education (which by the way is multilingual).

I generally agree, @literarymachine. Nevertheless in this special case I do not see, that we can use the EUN Organisatioin Type Values. From my perspective it appears to be
a) too much centered in the school sector
b) in some cases too unprecise (e.g. "industry", "vendor", "youth organisation")

@acka47: Do you see need to do some deeper analysis on this question?

**Comment by trugwaldsaenger** [comment]
> I am not so happy with the organization subtyping. I guess it would make sense to remove some types and instead add another dimension in the description (at least the private/public distinction).

@acka47: Do we need to discuss this issue?

**Comment by literarymachine** [comment]
We have had second level types for Services productive for a while now. Closing.
