### ISSUE TITLE
Filters still in English

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1344]
I'm pretty shure that there is a translation of this (in crowdin all three areas 100% translated):

![image](https://user-images.githubusercontent.com/18674205/30909626-22f047aa-a382-11e7-8be5-452e3ac54bcd.png)

**Comment by literarymachine** [comment]
@acka47 can you confirm or reproduce this? Looks good from over here:

![screenshot from 2017-09-27 13-22-04](https://user-images.githubusercontent.com/149825/30910898-e135899c-a386-11e7-9f07-1e95c3eebf4f.png)

**Comment by acka47** [comment]
Oups, didn't actually take a look. I can not reproduce it. Looking at the nav bar in @karindr's screen shot ("ABout", "Contribute") she obviously had the English UI requested by her browser. Closing.

**Comment by literarymachine** [comment]
> Looking at the nav bar in @karindr's screen shot ("About", "Contribute") she obviously had the English UI requested by her browser.

But there is also the little German flag next to the address bar, probably a language switcher plugin. So I am not completely sure if this is really resolved. @acka47, maybe you can check offline with @karindr?

**Comment by karindr** [comment]
Yes, it is the language switcher plugin and it was on German. I made a little test now: If you change the language, chrome only changes only the active tab but not the tabs in the background. For these you have to reload the pages. So everything is fine.
