### ISSUE TITLE
Entering characters in the country filter stopps you from being able to select more than one country

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1345]
When I want to select 3 countries in the country filter I can do this by moving in the list with the scrollbar. But in the moment I enter some charaters to the field above the country list (for example "sw") the country I chose before (for example "Germany") gets lost as chosen country! So when using the characters you are not able to chose more than one country.

**Comment by acka47** [comment]
Confirmed. This doesn't work as expected.

**Comment by literarymachine** [comment]
Not fixed in the new UI, @dobladov can you take a look?

**Comment by literarymachine** [comment]
Deployed to production.
