### ISSUE TITLE
Should countries in filter be sorted by number? (Umlaute are in the wrong place in alphabetical order)

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1346]
Look at the list of countries for the country filter: Österreich and Ägypten are at the end of the list. The same in the list of countries in the entry templates, here are some more coutries with "Ä" and a country with the nordish "A" with a circle on it.

**Comment by acka47** [comment]
Confirmed. We should use another way of sorting.

**Comment by karindr** [comment]
Now it is sorted by number of related entries. I don't know if this is useful. I prefere the alphabetical order.

**Comment by trugwaldsaenger** [comment]
> Now it is sorted by number of related entries. I don't know if this is useful. I prefere the alphabetical order.

I agree, alphabetical order would be preferable. Nevertheless, I also agree with the P3 priority for the moment. So if numbers of searches increase we can increase the priority.
--
