### ISSUE TITLE
There is two times a tag "mooc" in the list

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1348]
When you search for mooc the item mooc is listed twice. Could such duplicates be automatically prevented?

**Comment by acka47** [comment]
The reason for the repetition is that [in one entry](https://oerworldmap.org/resource/urn:uuid:7214c82a-798c-4141-9ddd-7c3f8554885f) the tag "MOOC" is used with trailing whitespace. I suggest to automatically trim leading and trailing whitespace. We should at least do this for tags but I see now reason to also do this for other fields.
