### ISSUE TITLE
Transform lists of words to seperated tags 

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1349]
Sometimes users enter lots of tags seperated by commas (for example search for "verkehr"). Is there a easy faster way to change these lists to seperate tags than to change it manually in the templates?

**Comment by acka47** [comment]
It might be good, to generally let people enter several tags with comma as separator. The "add tag" approach is a bit cumbersome anyway. Then separate tags in the background and trim leading/trailing whitespaces (#1348).

**Comment by literarymachine** [comment]
> It might be good, to generally let people enter several tags with comma as separator. The "add tag" approach is a bit cumbersome anyway.

True, but it allows the usage of [`datalist`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) for auto completion. If we want to change this and keep auto completion for tags, we will need to implement another UI widget.

**Comment by karindr** [comment]
Auto completion is pretty useful and should be kept. But I agree that the way we enter tags at the moment is a bit cumbersome.

**Comment by karindr** [comment]
Changing list of words in one tag field to single words in different tag fields has to be done quite often. In the long therm we should consider changing the widget and let them enter tags with commas

**Comment by literarymachine** [comment]
> Changing list of words in one tag field to single words in different tag fields has to be done quite often. In the long therm we should consider changing the widget and let them enter tags with commas

On production, ok like this?

**Comment by karindr** [comment]
I like the new widget. It seems to be quite intuitiv to handle! So I close this issue. If users begin to enter lists of word as one tag again we can reopen it.
