### ISSUE TITLE
Enhancement of and maybe a bug in the post to facebook functionality

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1354]
- if we post long urls from search results they are strangely cut. This is the resulting url: https://oerworldmap.org/resource/?q&filter.about.%40type=Service&filter.about.location.address.addressCountry=CH, but this was the original url: https://oerworldmap.org/resource/?q=&filter.about.%40type=Action&filter.about.%40type=Service&filter.about.location.address.addressCountry=DE&filter.about.location.address.addressCountry=AT&filter.about.location.address.addressCountry=CH . Any idea what happen here? This is relevant when people use the "share on facebook" function on the oer world map.

- it would be nice to have our logo shown in the preview on facebook. Does anybody know how this can be done? For an example scroll down in our timeline on fb to the post with "OpenCon March Community Call". They manage to let their logo be displayed. https://www.facebook.com/oerworldmap/

- if we add a link to a url of a search result from the world map always the same preview is displayed. Other sites manage to get different previews to be displayed. For example see the post "How to organise the procurement of OER?" in the oerinfo timeline https://www.facebook.com/OERinfo/

**Comment by literarymachine** [comment]
> if we post lang urls from search results they are strangely cut. 

Indeed, there seems to be a URL length limit. This brings up #1147 again. @acka47 is there any news on https://github.com/hbz/lobid/issues/278?

**Comment by literarymachine** [comment]
> it would be nice to have our logo shown in the preview on facebook.
> if we add a link to a url of a search result from the world map always the same preview is displayed.

@j0hj0h you probably know much more about Facebook integration than I do.

**Comment by acka47** [comment]
Nope, unfortunately currently neither concrete plans nor resources to set u a URL shortener.

**Comment by literarymachine** [comment]
> if we post lang urls from search results they are strangely cut.

Fixed on production.

**Comment by karindr** [comment]
+1
