### ISSUE TITLE
Country view: clicking on a list entry deletes filter selection

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#1360]
Clicking on a list entry after activating the type filter (e.g. organization) in the country view clears the type filter. This is unexpected behaviour, the type filter should not be cleared.

**Comment by karindr** [comment]
If I understand the description right this works now as expected. So should we close this issue?

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/pull/1285
