### ISSUE TITLE
Enable possibility to select two entry types as filters at a time in tablet view

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1364]
When I use the tablet view of the oerworldmap I can select two entry types at the same time. Sometimes this is nice but I cant do this in the desctop view, because when I click on the second typ the first type is deleted. Should we change this?

**Comment by trugwaldsaenger** [comment]
Makes sense to me. As just discussed the decision to choose only one data type at once was taken on purpose. Nevertheless I guess we should check this decision and eventually implement it with the next release. What do you think @j0hj0h @formimkontext ?

**Comment by formimkontext** [comment]
I’m not sure, if we need to change the behaviour of this filter. @karindr, what would be the benefit for you, if we make it an ›and‹ instead of an ›or‹ button?

**Comment by karindr** [comment]
That is not the point. What is irritating is that the filter works in different ways depending on how big my browser window is.
In some cases it would be nice to get al list of for example organisations and projects for a country.

**Comment by formimkontext** [comment]
So this is a bug. We agreed on the fact, that the main type filter is a ›or‹ button. It should work this way on every device. If you want to change the general behaviour of the main type filter, we should change the design of it, too.

**Comment by karindr** [comment]
"or" is ok to me.

**Comment by karindr** [comment]
seems to be solved.
