### ISSUE TITLE
Tune reconciliation results (October 2017)

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#1367]
Get reconciliation hits for:

- `Bc campus` (see https://oerworldmap.org/resource/?q=about.name.%40value%3ABc+campus&filter.about.%40type=Organization )
- `Bundeszentrale für poltische Bildung` (typo intended) (see https://oerworldmap.org/resource/?q=about.name.%40value%3ABundeszentrale+f%C3%BCr+poltische+Bildung&filter.about.%40type=Organization )

**Comment by philboeselager** [comment]
Having done some investigation, it seems that the only solution for eliciting (reconciliation) search hits like the ones mentioned above is to change Elasticsearch "must" option to "should" [here](https://github.com/hbz/oerworldmap/blob/master/app/services/repository/ElasticsearchRepository.java#L426).

While this works fine for the desired reconciliation, it destroys the desired restrictions tested by other BaseRepository search behaviour tests, like:

- testAbbreviatedSearch
- testBoostByLinks
- testBoostByLinksNested
- testCountrySynonyms
- testExactPersonHits
- testNoGroundlessHits
- testSearchHyphenWords
- testSearchMissing
- testSearchRankingNameHitsFirst

My conclusion is to not change the default search behaviour but choose "must" or "should" by parametrization, so that "must" is chosen by default and "should" is chosen in case of reconciliation only.

This leads to a bunch of reconciliation offers, which have to be handled in the act of reconciling.

Any comments, @literarymachine @karindr ?

**Comment by philboeselager** [comment]
OK, then I'm going to do it like that.

**Comment by literarymachine** [comment]
> This leads to a bunch of reconciliation offers, which have to be handled in the act of reconciling.

Sorry, I can't really tell if this is practical. Does it lead to many false-positives for the non edge-cases?

**Comment by philboeselager** [comment]
> Does it lead to many false-positives for the non edge-cases?

I don't think so. We will evaluate that using real world reconciliation. If we find that this is the case, we can revert this `should` easily.

The (imo.) only alternative to this "should" approach is giving the data one or several alternative name(s), "BC Campus" in this case.

**Comment by literarymachine** [comment]
> Does it lead to many false-positives for the non edge-cases?

>I don't think so. We will evaluate that using real world reconciliation. If we find that this is the case, we can revert this should easily.

@philboeselager turns out, we do have too many false-positives:

![image](https://user-images.githubusercontent.com/149825/37469642-04e396f4-2866-11e8-93d6-98e608f80ac3.png)
![image](https://user-images.githubusercontent.com/149825/37469683-1ec53ae6-2866-11e8-8d29-1cbfef493d75.png)

The list actually goes on and on.

**Comment by literarymachine** [comment]
Another example for the false positives:

![image](https://user-images.githubusercontent.com/149825/39302994-dfb62170-4954-11e8-9093-ee3d9baec4d5.png)

I think we should revert d19c7c4be109effb11639f69ff660a2c07802e08 and look into fuzzy queries regarding typos.

**Comment by literarymachine** [comment]
Solved by https://github.com/hbz/oerworldmap/commit/1eb6ca815fbb7dc616e1a9fdfddac7067812561d and #1584.
