### ISSUE TITLE
Increase visibility of research

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#137]
"As a researcher I want to be able to share my research in a way that makes it more visible"

**Comment by trugwaldsaenger** [comment]
This is another result of the workshop at OEGlobal 15 in Banff. I think it could be develop into the integration of an OER bibliographie. For phase II of the project, a simple way to increase visibility would be by using stories.

**Comment by karindr** [comment]
With the new type "publication" we solved this issue, see for example Robs profile and his list of publications. https://oerworldmap.org/resource/?q=rob#urn:uuid:b6725738-8495-11e5-a7a1-54ee7558c81f
II suggest to close this issue.

**Comment by literarymachine** [comment]
> I suggest to close this issue.

Done.
