### ISSUE TITLE
Tooltip for service.primary/secondarySector missing

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1375]
We have to add two strings to service.primary/secondarySector in the descriptions.properties and then Crowdin will also take care of the translations.

**Comment by karindr** [comment]
For services:
"The educational sector the service is built for in the first place."
"Educational sectors the service is also useful for."

For organisations:
"The educational sector the organisation is working for in the first place."
"Educational sectors the organisation is also working for."

For persons:
"The educational sector you are working for in the first place."
"Educational sectors you are also working for."

For projects:
"The educational sector the project is working for in the first place."
"Educational sectors the project is also working for."

For events:
"The educational sector the event is about in the first place."
"Educational sectors the service is also relevant for."

For tools:
"The educational sector the tool is used for in the first place."
"Educational sectors the tool is also useful for."

**Comment by literarymachine** [comment]
@acka47 can you add them and open a PR?

**Comment by acka47** [comment]
Added the tooltips with #1436. While I was add it I also added the other tooltips for the "Tool" template as there haven't been any at all yet.
