### ISSUE TITLE
Landing page: circling globe

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#138]
As I took a look at the landing page it came to my mind that the globe presented offers a Europe-centered view. Of course there is nothing "wrong" with that - one has to decide for a central point using a static map.
Nevertheless, in order to demonstrate that our philosophy is not Europe-centered, but a worldwide one, and we want to get in contact with all countries, it would be great to have some kind of a (slowly) circling globe.

**Comment by acka47** [comment]
+1 We also use a euro-centric projection where the size relations between north and south aren't kept. A spinning globe is probably the best way to avoid this. Otherwise, we could choose one of the [equal-area projection](http://en.wikipedia.org/wiki/Category:Equal-area_projections). My favourite would be the Mollweide projection, se e.g. http://upload.wikimedia.org/wikipedia/commons/8/84/World_borders_mollweide.png.

On world map projections, see also [this xkcd](https://xkcd.com/977/).

**Comment by trugwaldsaenger** [comment]
Just to make sure that I understand you right: Are you proposing to implement a globe instead of the map or are you referring to the globe, which is included in the logo?

**Comment by philboeselager** [comment]
The former: a neutral globe instead of a Euro (or whatever else) - centric map.

**Comment by trugwaldsaenger** [comment]
OK, I think a moving 3-D globe would look spectacular and it would have the right message! Great idea! But we probably would need the possibility to switch between a globe and a map, since a globe does not give you the opportunity to see everthing at a glance!

**Comment by philboeselager** [comment]
Of course, and we would need it as a fallback technology as well. The globe is a Very-Nice-To-Have with a great message, but still an add-on.

**Comment by literarymachine** [comment]
We are planning to switch to [OpenLayers 3](http://openlayers.org/) for the next release (we actually tried for v0.2, but had trouble with a bug in our map data). There is a [plugin](http://openlayers.org/ol3-cesium/examples/main.html) that should make a circling globe possible with reasonable effort. Hit the "Enable/disable" button to see the globe in action, though you have to manually rotate it in this example.

**Comment by acka47** [comment]
The map was changed on staging during the last days. Regarding my comment above (https://github.com/hbz/oerworldmap/issues/138#issuecomment-103005304) the new map is even less an equal-area projection. An easy way to check this is by comparing Africa and Greenland: "in reality Africa's area is 14 times greater and Greenland's is comparable to Algeria's alone." (source: https://en.wikipedia.org/wiki/Mercator_projection)

**Comment by literarymachine** [comment]
Which projection would you prefer? We switched to OpenLayers3, which indeed has Spherical Mercator (EPSG:3857) as it's default projection.

**Comment by acka47** [comment]
I mentioned Mollweide projection above. See here: http://openlayers.org/en/v3.1.1/examples/sphere-mollweide.html. That's already going into the direction of a globe...

**Comment by acka47** [comment]
Closing as this idea is off the table for now.
