### ISSUE TITLE
 Typed in "edu" but did not become "Education Labs"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1387]
When choosing the organisator for an event I typed in "edu" but did not become "Education Labs" as Suggestion, see:
![image](https://user-images.githubusercontent.com/18674205/32777661-5d2c5c94-c937-11e7-9148-991f5bc9d27b.png)
When I type "Qual" there is "Education Labs" as 5. entry, see:
![image](https://user-images.githubusercontent.com/18674205/32777739-9fe2e4ae-c937-11e7-9a7c-e3d8898777b1.png)

**Comment by literarymachine** [comment]
If you type in "Education labs" you should get the entry you are looking for:

![screenshot from 2017-11-14 12-37-03](https://user-images.githubusercontent.com/149825/32777972-92d9e89c-c938-11e7-812f-39567182bed1.png)

**Comment by karindr** [comment]
Yes, but why are other entries with Education in it in the list? No user will understand this behaviour.

**Comment by literarymachine** [comment]
> Yes, but why are other entries with Education in it in the list?

The request is the same as [this one](https://oerworldmap.org/resource/?filter.about.@type=Organization&filter.about.@type=Person&filter.about.@type=Action&size=10&q=edu*) one the world map, order is by relevance. We could [limit the search to the `name` field](https://oerworldmap.org/resource/?filter.about.@type=Organization&filter.about.@type=Person&filter.about.@type=Action&size=10&q=about.name.@value:edu*), but still there is no guarantee that what you are looking for is among the first 10 hits. We could also [increase the amount of results](https://oerworldmap.org/resource/?filter.about.@type=Organization&filter.about.@type=Person&filter.about.@type=Action&size=100&q=about.name.@value:edu*), but even then you would have to either scroll a bit or enter more than just `edu`...

**Comment by karindr** [comment]
That is interesting! Because the number of suggestions in the list is changing while typing I assumed that always all search results are shown which is not true. So I would have started to enter the organisation a second time if I would not have been so sure that it allready exists! To avoid this we could add the possibility for the user to click at the end of the list and see more results. That would be helpful!

**Comment by literarymachine** [comment]
> So I would have started to enter the organisation a second time if I would not have been so sure that it allready exists!

Right, but we catch this with #848.

> To avoid this we could add the possibility for the user to click at the end of the list and see more results. That would be helpful!

Create #1613 for this.

Closing.
