### ISSUE TITLE
Don’t accept wrong URL 

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#1389]
While testing the forms and provoking some validation errors, i found out, that the template does accept URL like http://www.formimkontext  Even this might be a rather rare appearing error, it should not be possible.

**Comment by literarymachine** [comment]
> Even this might be a rather rare appearing error, it should not be possible.

This is not an error, URLs strictly speaking need neither TLD nor sub domain. We are currently using the JSON schema `uri` format and I would like to keep it that way. As with email addresses, validation is simple at first glance, but then quickly gets more complicated (e.g. with character encodings).

**Comment by literarymachine** [comment]
Inactive, closing.
