### ISSUE TITLE
Cannot save Event with dates in `YYYY-MM-DD TT:MM` format

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1397]
In the JSON schema, we should restrict dates to the Elasticsearch `dateOptionalTime` format.

**Comment by dobladov** [comment]
First version, **not** checking for invalid months/days/hours/minutes or timezones.

`/^(\d{4})(-(\d{2})(-(\d{2})([T ](\d{2}):(\d{2})((?::(\d{2}((?:\.\d+)?))?((Z|[+-]\d{2}:?\d{2})$)?)?)?)?)?)?/`

```
// Valid
2018
2017-12
2018-11-25
2018-11-25T12:30
2018-11-25T12:30:00
2018-11-25T12:30:00Z
2018-11-25T12:30:00+0000
2018-11-25T12:30:00+00:00

//wrong
225558877777
2018/12/14
2018-11-25T12
2018-11-25T12:
2018-11-2512:30
2018-11-25T12:30:00:0000
```

**Comment by dobladov** [comment]
Final version for JS https://regex101.com/r/EmVr9d/1

```(^(\d{4})$|^(\d{4})-(0[1-9]|1[0-2])$|(^(18|19|20)[0-9]{2}-(0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01])|^(18|19|20)[0-9]{2}-(0[469]|11)-(0[1-9]|[12][0-9]|30)|^(18|19|20)[0-9]{2}-(02)-(0[1-9]|1[0-9]|2[0-8])|^(((18|19|20)(04|08|[2468][048]|[13579][26]))|2000)-(02)-29)(T([01]\d|2[0-3]):[0-5]\d(:[0-5]\d(Z|((\+[01][0-4])|\-[01][0-2])(:?[0-5]\d))?)?)?$)```

More redable PHP version https://regex101.com/r/nvyQQ7/3

```(
^(\d{4})$ |
^(\d{4})-(0[1-9]|1[0-2])$ |

(
^(18|19|20)[0-9]{2}-(0[13578]|1[02])-(0[1-9]|[12][0-9]|3[01]) |
^(18|19|20)[0-9]{2}-(0[469]|11)-(0[1-9]|[12][0-9]|30) |
^(18|19|20)[0-9]{2}-(02)-(0[1-9]|1[0-9]|2[0-8]) |
^(((18|19|20)(04|08|[2468][048]|[13579][26]))|2000)-(02)-29
)

(
T
([01]\d|2[0-3]):[0-5]\d(:[0-5]\d(Z|((\+[01][0-4])|\-[01][0-2])(:?[0-5]\d))?)?
)?

$)```
