### ISSUE TITLE
Seach Engine Optimisation: OER Librarian Network in Dropdown

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1398]
We just included the OER Librarian Network Germany to the map. If people now want to affiliate to this network, they have to use the "member of" field in their profile. The field offers proposals, as soon as you start searching. Quite irritating is, that "OER Librarians Network" is not even displayed on the list before you type in 5 or 6 characters. So if you look for "OER L" and get "The William and Flora Hewlett Foundation" as your first hit, you do not exspect that the entry is available.

**Comment by acka47** [comment]
By now, typing in "oer l" gives the OER Librarian Network Germany as first proposal. Closing.

**Comment by trugwaldsaenger** [comment]
@acka47 its true that now if you type in "OER L" you get what you are looking for. But one character less and the network is not displayed. Do you consider this sufficient?

I reopend the issue - I guess we should collect all examples of irritating behaviour of the search engine and discuss them all together.

**Comment by literarymachine** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/149825/46072806-8d484380-c183-11e8-9054-2f535f35b63f.png)

Did you maybe activate a type filter?

**Comment by literarymachine** [comment]
With activated `Organization` filter:#

![image](https://user-images.githubusercontent.com/149825/46072873-bbc61e80-c183-11e8-9d1d-604228d47011.png)

I suggest closing this issue.

**Comment by literarymachine** [comment]
> But one character less and the network is not displayed. Do you consider this sufficient?

I actually do - searching for `OER` on the OER World Map unsurprisingly delivers a lot of results. "OER" is used in titles and descriptions all over the place.

**Comment by trugwaldsaenger** [comment]
I get the same results as @literarymachine when using the main search. But the issue appears when using the "affilliation" field on your personal profile. There the behaviour seems to be different:
![grafik](https://user-images.githubusercontent.com/6639965/46073411-1e6bea00-c185-11e8-967f-b63d1fbc5938.png)

**Comment by trugwaldsaenger** [comment]
Just to clarify my intention: We might come to the result, that we have to accept behaviour like this. But I would like to collect a number of examples of irritating behaviour, so that we can analyse them in context.

**Comment by literarymachine** [comment]
Ok, I misread the issue title. Still, I would argue that basically anybody would simply continue typing and then find what they want; and "OER lib" gives the right result right away. Anyways, let's move the discussion to #1535 where @karindr is experiencing something similar.

**Comment by acka47** [comment]
> Do you consider this sufficient?

I do, because you wouldn't expect to get the result you want first when you type "oer" in a registry for OER things.

**Comment by philboeselager** [comment]
Does not seem to be an issue to me. Loosely speaking: if I type "www.", I don't expect the browser to suggest the desired website. It's the most natural behaviour to add at least one character here. Also suggesting to close this issue.
