### ISSUE TITLE
Finalize UI for stories

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#140]
Task for #117, @buschfeld and @j0hj0h will coordinate.

**Comment by buschfeld** [comment]
![oer_demo_map-teaser_70-30](https://cloud.githubusercontent.com/assets/10743356/7959828/88e9035c-09fc-11e5-8955-ce2078849fd1.png)
![oer_demo_map-detail_50-50_drag_cluster](https://cloud.githubusercontent.com/assets/10743356/7959842/a9d485f0-09fc-11e5-9d03-2818fad75e05.png)

**Comment by acka47** [comment]
@buschfeld Can you please explain the "mouseoverdown" text. I guess it isn't supposed to be actually included in the UI. How should I understand this?

**Comment by buschfeld** [comment]
This meant to indicate that the all textlinks change their color - a common effect differentiating between two kind of situations: mousecursor is placed over the actual text links without clicking - then (usually just a short flashing kind of impression) another color change when the links is actually clicked. 


Am 03.06.2015 um 15:30 schrieb Adrian Pohl:

**Comment by acka47** [comment]
@buschfeld Got it. THanks for the explanation.

**Comment by literarymachine** [comment]
Columns should not change width on load.

**Comment by buschfeld** [comment]
Some screen mockups for 
- Popup-Layers over the map including limited statistics
- various contents in the right column which might be linked between each other by keywords
-- Articles
-- Country Stats
-- Country Champion
-- Missing Country Champion
-- Project (including Image-Gallery [v03])

![oer_10_demo_map_articles](https://cloud.githubusercontent.com/assets/10743356/8206506/6dd6393c-14fa-11e5-9d76-b1bfb8293722.png)
![oer_11_demo_map_country](https://cloud.githubusercontent.com/assets/10743356/8206503/6dd2bdd4-14fa-11e5-9550-727f62f55297.png)
![oer_12_demo_map_countrychampion](https://cloud.githubusercontent.com/assets/10743356/8206504/6dd36716-14fa-11e5-8187-efa72af99113.png)
![oer_13_demo_map_countrychampionmissing](https://cloud.githubusercontent.com/assets/10743356/8206505/6dd5ee00-14fa-11e5-86c4-29252b117ff0.png)
![oer_14_demo_map_project gallery](https://cloud.githubusercontent.com/assets/10743356/8206507/6dd71ece-14fa-11e5-9104-390d4b7a2964.png)

**Comment by buschfeld** [comment]
ToDos @j0hj0h 
- Adapt layout proposals for right column for stories
-- includes reduce size of img area and H1 / H2 Headlines
- Change Navi- and Slogan Font to "Clear Sans" or "Open Sans"
- Change Logo-Design according to current version
- Exchange PIN-color to Header-BG-Blue = Hex 244267 (or similar to)
- Add 1px white border to Pins
- Create and idd favico based on logo
- slightly reduce and adapt font-size of pre-entry in textsearch
- include footer with CC-BY-Logo

**Comment by trugwaldsaenger** [comment]
Include a link to our GIT system in the header beneath the other links to facebook etc.

**Comment by j0hj0h** [comment]
@buschfeld: we tried the all-caps titles, but due to the huge number of acronyms the readability is much better with normal case. So we'll go with that.

**Comment by literarymachine** [comment]
@j0hj0h Could you take a look if all of this is implemented and tag the task with "Review" if so? Thanks!
