### ISSUE TITLE
Should we implement discourse?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1402]
After I got a little bit into discourse I think it might be worth thinking if we could and should implement it for the world map.

Here are some rough ideas, how this might look like:

- own hosted instance
- integrated into the oer world map website
- login provided with OER World Map Login
- plugin, which allows bidirectional linking to world map entries

I wonder, if we could use it for handling our comments as well (you click on comment and start a discourse thread). The good thing about it would be that in this case discourse would handle all the notification stuff for us... 

@acka47 Do you like the idea?

**Comment by acka47** [comment]
Re. using discourse for world map comments see also https://github.com/hbz/oerworldmap/issues/12#issuecomment-239777038 and following. (Using discourse for commenting would mean that people have to navigate to the forum before commenting.)

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/issues/12#issuecomment-239777038 for previous thoughts on this.

**Comment by trugwaldsaenger** [comment]
> Using discourse for commenting would mean that people have to navigate to the forum before commenting

This certainly would not be a good solution. So I guess it would need modification for this use case...

**Comment by trugwaldsaenger** [comment]
Discussed this issue last week with @literarymachine. We aggreed, that discourse is a good tool and might be an opportunity for the world map, but it does not make sense to include it only to improve our comment function. Especially for comments which discuss single metadata fields, hypothesis probably will be the better tool.

**Comment by acka47** [comment]
Closing this for now.
