### ISSUE TITLE
Copy edit static pages

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#141]
Task for #117.

**Comment by literarymachine** [comment]
@trugwaldsaenger Are the static pages ([Contribute](https://beta.oerworldmap.org/contribute), [FAQ](https://beta.oerworldmap.org/FAQ), [About](https://beta.oerworldmap.org/about) and [Imprint](https://beta.oerworldmap.org/imprint)) OK for now?

**Comment by trugwaldsaenger** [comment]
Yes they are. But we should try to refine the layout soon!

**Comment by literarymachine** [comment]
Closing this issue as this is about the content. To be honest, I don't see too many troubles with current layout but will check with @j0hj0h where we're at with it.
