### ISSUE TITLE
Shown entry does not change although I am clicking on other pins

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1411]
https://oerworldmap.org/resource/urn:uuid:749aaf9e-e5b1-44ee-b93d-3f2f0809cf2d#urn:uuid:562e7627-b327-4638-858d-8b244cad5891

In this part of the map shown on the left side I can click on the other pins for persons and so on but nothing happens. I stay with Dr. Bodo Röbel.

![image](https://user-images.githubusercontent.com/18674205/34669167-c8b48c34-f470-11e7-871f-93b04278141f.png)

**Comment by literarymachine** [comment]
Ouch, looks like a bug I introduced with https://github.com/hbz/oerworldmap/commit/cff91c55eddacca75cbdc5d27c86e39f4fda4564!
