### ISSUE TITLE
Strange table in template for location

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1414]
![image](https://user-images.githubusercontent.com/18674205/34715554-57cf5734-f52d-11e7-96db-24a74655030e.png)
![image](https://user-images.githubusercontent.com/18674205/34715588-6ac18c72-f52d-11e7-86ad-96bb63aca165.png)
This is especially strange as @trugwaldsaenger in firefox still gets the correct view.

**Comment by literarymachine** [comment]
Confirmed, apparently introduced in 5c295f8380cb086b30049a7371a5be19bc08b516.

**Comment by literarymachine** [comment]
Fixed in 9da1a2179a8284c5c717ba44cd97f42fc8d7711b
