### ISSUE TITLE
There are some problems with caracters in displaying the English list of countries

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1418]
![image](https://user-images.githubusercontent.com/18674205/34818342-cc98fd34-f6ba-11e7-8f0a-f179273dc112.png)
At the End of the list, see above and 

- Sao Tome
- Saint Barth...
- Curacao
- Reunion

The problems are in the English list shown in the Template for choosing the country champion and for the location. Simmilar problems in the List of languages:

- Bokm...
- MÄ?ori
- Volp...

**Comment by literarymachine** [comment]
Fixed on production.
