### ISSUE TITLE
Relocate button for filtering educational sectors

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1419]
The actual positioning of the buttons does not make sense. Both buttons should appear next to each other, and the primary sector should be shown first.

![educational-sector-filter](https://user-images.githubusercontent.com/6639965/34820392-b489ba02-f6c0-11e7-8a09-0ff6e546e2ca.PNG)

This issue is loosly related to #1413

**Comment by literarymachine** [comment]
Fixed on production:

![image](https://user-images.githubusercontent.com/149825/40353304-7f337f7a-5db1-11e8-92b9-7759214acb39.png)

Closing.
