### ISSUE TITLE
The map puts Germany slightly to the left

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1426]
This behavior changed the last days, see:
![image](https://user-images.githubusercontent.com/18674205/35216156-f0f30ed6-ff66-11e7-8922-22ef9c8c682f.png)

**Comment by literarymachine** [comment]
@karindr Sorry I don't get it. What is wrong? AFAIK nothing has been deployed that could have changed the behavior of the map.

**Comment by literarymachine** [comment]
Fixed in #1423.
