### ISSUE TITLE
Different names in different views, use everywhere name and abbreviation

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1433]
In this list there is the name of the project "Lehrerfortbildung durch Nutzung und Produktion von OER-Materialien"
![image](https://user-images.githubusercontent.com/18674205/35562397-86a91734-05b3-11e8-846a-ab0d8878ee44.png)
on the project page it is "LOERn (LOERn)"
![image](https://user-images.githubusercontent.com/18674205/35562453-b9b9cf06-05b3-11e8-919b-0d626bc3d10b.png)
This page is wrong but why?

**Comment by karindr** [comment]
Look here there are different names too (on the left and highlighted in the template):
![image](https://user-images.githubusercontent.com/18674205/35564240-cbf39458-05b9-11e8-840b-3e3e387c1ada.png)

**Comment by karindr** [comment]
I understood: It is the screen name thet is displayed in the column. If you ask me it is not very helpful to use the screen name there (you only find out the real name, when you go into the template!) and shouldn't the screen name be in the lists?

My suggestion: Why don't we forget about the screen name?

**Comment by trugwaldsaenger** [comment]
It is for sure right that the use of the full-name, the screen-name (and maybe also the abbreviation) is inconsistent and should be improved. Getting rid of the screen name might be a solution, but we included it on purpose, since sometimes the full-name is extremely long...

**Comment by formimkontext** [comment]
i agree, that the name in the result list and in the resource view should correspond. the problem about longer names is not the presentation in the result list but in the small resource view. part of the problem will be solved with the fullscreen resource view. 

my idea about the display name was to introduce more userfriendly names. ›OERinForm‹ is more self-explanatory or probably better known than ›Ein Verbundprojekt der Medieneinrichtungen an Hochschulen‹. As a matter of fact the ›OERinForm‹ facebook profile is called ›OERinForm‹ which is quiet easy to understand for everybody, i guess. 

maybe we can use the abbreviation as headline and the name as a subline and forget about the screen name:

abbreviation/headline: OERinForm
full name/subline: Ein Verbundprojekt der Medieneinrichtungen an Hochschulen

name/headline: hbz
full name/subline: Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen

**Comment by karindr** [comment]
That is a really good idea! The names should be consistently in this way  in every list: abbreviation (full name): in the result list and in the list you choose from in the input templates. So the users don't get confused from differnt views.

**Comment by acka47** [comment]
I think this resolved by now, isn't it @karindr ? Then please close the issue.

**Comment by karindr** [comment]
No, it is about adding the abbreviation to the name in any place the name is used.
