### ISSUE TITLE
Persons affiliated with an entity should not lighthouse it

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1437]
As the results are skewed when people start lighthousing their own offers, we should make clear that we don't want – or even technically prevent – such behaviour.

As discusses on slack, here are some measures to take:

- Add a question like "What do the lighthouses mean?" to the FAQ and make clear who ist supposed to give a lighthouse and who not.
- Put a "?" or "i" with a link to the FAQ besides the lighthouse so that people can check it out. (Alternatively, we may put the link into the window that pops up when clicking the lighthouse).
- At best, disable lighthousing of an entity from people that are affiliated with it.

**Comment by acka47** [comment]
@trugwaldsaenger writes in a – now closed – duplicate issue:

> a) The instruction on the popup form should be changed from "Please tell us what makes this entry a lighthouse" into "Please tell us what makes this entry a lighthouse. Please set lighhouses only in case you are not affiliated with the entry in any way". In German it should say "Bitte beschreiben Sie, was diesen Eintrag zu einem "Leuchtturm" macht. Bitte setzten Sie Leuchtürme nicht für eigene Initiativen." 
>
> b) An FAQ "What do I have to keep in mind when I set a lighthouse" should be added to our FAQ section. The Answer should be linked with the Help-Link on the Form. 
![lighhouse](https://user-images.githubusercontent.com/6639965/35734123-4b217a7a-0820-11e8-8fa9-9266feacf431.PNG)

**Comment by karindr** [comment]
I added the question and answer to the FAQ and created a pull request. I will translate this and the other sentences when they show up in crowdin.

**Comment by trugwaldsaenger** [comment]
Many thanks!

**Comment by literarymachine** [comment]
Fixed in hbz/oerworldmap-ui#236
