### ISSUE TITLE
Refine Lighhouse Process

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1438]
In order to make shure that lighthouses are not abused for marketing purposes we should clearly express that users should not set a lighthouse for entries they are affiliated with. 

In order to do so
a) The instruction on the popup form should be changed from "Please tell us what makes this entry a lighthouse" into "Please tell us what makes this entry a lighthouse. Please set lighhouses only in case you are not affiliated with the entry in any way". In German it should say "Bitte beschreiben Sie, was diesen Eintrag zu einem "Leuchtturm" macht. Bitte setzten Sie Leuchtürme nicht für eigene Initiativen." 

b) An FAQ "What do I have to keep in mind when I set a lighthouse" should be added to our FAQ section. The Answer should be linked with the Help-Link on the Form. 
![lighhouse](https://user-images.githubusercontent.com/6639965/35734123-4b217a7a-0820-11e8-8fa9-9266feacf431.PNG)

**Comment by literarymachine** [comment]
Duplicate of #1437?

**Comment by trugwaldsaenger** [comment]
@acka47 was faster than me! closing!
