### ISSUE TITLE
Filter projects & person by OER activity fields

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#144]
As a member of the OER community I want to filter the world map data (especially projects and experts) by special OER activity fields. 

Acceptance criteria:
- includes a special set of categories, which describe fields of activies within the oer movement

**Comment by trugwaldsaenger** [comment]
An initial version of cathegories which describe special fields of activity within the OER area can be found here: http://etherpad.lobid.org/p/opportunities

**Comment by trugwaldsaenger** [comment]
See also #13

**Comment by buschfeld** [comment]
Please see enclosed screen layout study showing
- proposals of filter UI applied to the map view
- proposals of filter UI applied to the result list
- statistic data and cross-links icons in tooltip layers on map
- variations of how to avoid pin clusters by adding numbers in large-scaled map views

I need to add that design draft includes the visualization of alternatives, added for internal discussions among the developing team. These alternatives include
- position and color of tooltip areas
- typography and style of cluster-pins
- position and style of icons (taken from the public source fontawesome library)
- color scheme of checkbox and close icon-areas
- last, not least – the two already known color systems: 
  a) orange = hovered/currently presented + b) dark blue = pure/not selected display

Note: This layout draft also applies to following issues:
#163, #160, #140, #40, #41, #42, #43, #34, #31

![oer_landingpage_basics_master_10 06 2015](https://cloud.githubusercontent.com/assets/10743356/8102412/32d361d6-1020-11e5-8a79-0f91d50a47ed.png)

**Comment by trugwaldsaenger** [comment]
I still believe that including the "fields of activity" would be very helpful for searching. It could be also used for browsing by showing related entries.
example: When looking at a project, which aims at content production, we could display "similar projects" which are also aiming at content production.

**Comment by literarymachine** [comment]
Yes, this makes sense. We would need those fields as a (SKOS) classification then. Or does this already exist and I missed it?

**Comment by acka47** [comment]
>  We would need those fields as a (SKOS) classification then. Or does this already exist and I missed it?

This doesn't exist yet. If this is needed and http://etherpad.lobid.org/p/opportunities is mature, I will make a ticket ad https://github.com/hbz/vocabs-edu and satrt working on it asap.

**Comment by trugwaldsaenger** [comment]
I will provide a final version of the classification ASAP!

**Comment by acka47** [comment]
To do:
> I will make a ticket ad https://github.com/hbz/vocabs-edu and start working on it asap.

**Comment by trugwaldsaenger** [comment]
One of the lessons learned from the OER Atlas was that our categories (http://etherpad.lobid.org/p/opportunities) are pretty good, but that simply choosing one or several of them did not work fine. I guess we need a more sophisticated mechanism here. One solution would be to add values (e.g. from 1-3 or 1-5) for every category. This would provide us with a possibility to make pretty good profiles of the projects. The input also could be visualized as a radar chart (https://en.wikipedia.org/wiki/Radar_chart). I guess this should enable us to identify similar projects very easy.

**Comment by trugwaldsaenger** [comment]
Here comes an example of an radar chart which I based on the fields of activity categories:
![fields-of-activities-radar-chart](https://cloud.githubusercontent.com/assets/6639965/18548143/a07c98b8-7b47-11e6-9889-f36bcac09d64.jpg)

**Comment by literarymachine** [comment]
> Here comes an example of an radar chart which I based on the fields of activity categories:

While I understand the categories, I don't yet understand where the values for the numerical scale will come from.

**Comment by trugwaldsaenger** [comment]
This has to be entered manually via according templates. For each category it should be possible to select a value, eg. 0-9 or 0-3.

**Comment by literarymachine** [comment]
> This has to be entered manually via according templates.

I see! This is definitely a new requirement and will make things more elaborate as we cannot simply reuse the same template elements we already have. Also, this will require some data modeling, pinging @acka47.

**Comment by literarymachine** [comment]
Sorry, I think I mixed this up with #686. I guess we will not need numeric values there, right?

**Comment by acka47** [comment]
> Sorry, I think I mixed this up with #686. I guess we will not need numeric values there, right?

Yes. No numerical values for #686 but for this story (#144).

**Comment by acka47** [comment]
Next step: Add a field in the schema to type `Person` so that it can be implemented in the world map.
