### ISSUE TITLE
Fine-tuning search index: PDXopen

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1441]
Searching for "PDX" brings no results. Searching for "PDXopen" finds the entry I`m looking for: https://oerworldmap.org/resource/urn:uuid:fc11eb2e-ffdf-450c-9d21-b87db02f4c24

**Comment by philboeselager** [comment]
Comprised in https://github.com/hbz/oerworldmap/commit/42868fbd76ae4910d095aa1c5b70ab902c69af38.

**Comment by literarymachine** [comment]
Deployed to beta, see https://beta.oerworldmap.org/resource/?q=pdx

**Comment by literarymachine** [comment]
Deployed to production, closing.
