### ISSUE TITLE
Linebreak false, comma in next line

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1442]
The comma after Das Institut für Entwicklung und Erforschung des Mathematikunterrichts belongs to this term and should not be at the beginning of the next line. See:
![image](https://user-images.githubusercontent.com/18674205/35971608-f36523be-0cce-11e8-9495-7e2251666f73.png)

**Comment by literarymachine** [comment]
@karindr what exactly is the problem here?
