### ISSUE TITLE
Mouse-over labels for "+Organisation" etc.

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1443]
In the drop down menu dropping down from the orange +-button there are no mouse-over labels. It would be nice to have them: "Add organisation" etc. Please keep in mind that the whole phrase should be translatable not only the words, otherwise we will end up with "Hinzufügen Organisation".

**Comment by dobladov** [comment]
Fixed in the new UI with the new header. 

![image](https://user-images.githubusercontent.com/1938043/43709662-b2cbaf86-996d-11e8-8ef4-ef2e01637fcb.png)
