### ISSUE TITLE
Change order of statistics on statistic page

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1445]
Look:
![image](https://user-images.githubusercontent.com/18674205/36247835-bec0cd40-1235-11e8-987e-21a5085e9d93.png)
As second statistic there is "Entries by secondary education sector". This statistic should be the statistic following the statistic "Entries by primary education sector" which is the last statistic at the moment. I suggest putting "Entries by secondary education sector" at the end of the list.

**Comment by trugwaldsaenger** [comment]
Completly aggreed - it makes no sense at all to show the statistics for the secondary education sector before the primary education sector. I would also expect that this is a small thing, which could be changed within a couple of minutes. @literarymachine @j0hj0h if possible you might consider this during the refactoring.

**Comment by literarymachine** [comment]
Fixed on production, see hbz/oerworldmap-ui#230 and https://oerworldmap.org/aggregation/
