### ISSUE TITLE
Give possibility to link from a project to a service

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1448]
Working on the documentation of the OERinfo projects I miss the possibility to create a link from a project to a resulting service, for example:
from project "OER World Map" to service "OER World Map"
from project "JOINTLY" to not yet existing service "OER Content Buffet"
and so on.

I think this would be helpful, because some visitors will look for resources and should be able to find the services lending to them without making the extra step to look up which organisation is behind a project and there to look which of the maybe several services of this organisation may belong to the project visited before. DIPF for example has already four services and OERinfo as service not yet there.

**Comment by karindr** [comment]
Newest example:

_project:_ Affordable Learning Georgia (ALG)
https://oerworldmap.org/resource/urn:uuid:16f63ec7-e978-4aef-837b-6997761c23b6
should be linked to
_service:_ GALILEO Open Learning Materials
https://oerworldmap.org/resource/urn:uuid:b2754f03-5a46-4be9-a04c-d969484ea54f

**Comment by acka47** [comment]
Everything is there in the schema and the `.properties` files (`Action.result` & `Servie.resultOf`) but in the end of 2015 we decided to not show it in the web form, though, see #524.

As I understand, you want a field in the Project web form that says "Resulting service" with tool tip "A service created during the project". However, for implementation we also need to know: 
1. Should there also be a "Result of" field in the "Service" web form?
2. Should the result of line be displayed in the service description?

**Comment by karindr** [comment]
> As I understand, you want a field in the Project web form that says "Resulting service" with tool tip "A service created during the project". 

Yes.

> Should there also be a "Result of" field in the "Service" web form?
> Should the result of line be displayed in the service description?

Yes, both times.
