### ISSUE TITLE
Lighthouses and Likes appearing in country view statistics

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1449]
See:
![image](https://user-images.githubusercontent.com/18674205/36472177-44c83f94-16f1-11e8-8475-1c20c15653ef.png)

**Comment by literarymachine** [comment]
The actual bug here is that `LikeAction` and `LighthouseAction` should currently not be showing up there at all.

**Comment by karindr** [comment]
OK. Lighthouse may be interesting here in the future, but for the moment they don't need to be shown here. Please feel free to rename this issue or close it and open a new one.

**Comment by karindr** [comment]
By the way they appear also in the label shown when the cursor is placed in Germany.

And there are strange numbers in this country view: 24 likes although there are only 20 likes shown for the whole world.

**Comment by literarymachine** [comment]
Fixed on production.
