### ISSUE TITLE
Mapping Mira data to schema.org

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#145]
As we want to integrate data from [Mira](http://mira.org.br/) into the OER worldmap, the data has to be mapped to schema.org.

The data can be obtained as GeoJSON at http://mira.org.br/?geojson=1. (I am awaiting a response whether we can get a slimmer JSON without the GeoJSON stuff which would be easier to process.)

**Comment by literarymachine** [comment]
From a processing point of view, it does not really matter if the properties are extracted from the GeoJSON or from something "slimmer".

**Comment by acka47** [comment]
I took a deeper look at the data and started the mapping. In my opinion we would be better off in adding the resources manually. The reasons for this are:

1. The data set is small (63 entries).
2. The data has to be manually adjusted anyway in several ares (typing, subject areas, start/end of an initative etc.)
3. The data hasn't been updated in a while and mainly is from April 2014. (two edits on 12/02/2015, three edits on 10/09/2014). I checked half the site_url links (in total there are 6, Ichecked 31) and four where dead while two referenced projects that are offline now or haven't been continued (see below). As we have no start/end Data information on this it probably would have to be added. 

dead links:
http://cesta2.cinted.ufrgs.br/xmlui
http://portaleducativo.edu.ve/
http://escoladigital.org.br/
http://www.hdt.gob.mx/hdt/

dead initiatives:
- no edits since 2013: http://ceibaljam.org/
- closed down: http://www.encicloabierta.org/

**Comment by tamielbr** [comment]
@acka47 I agree, it might be best to do it by hand, it's not a lot of data (we'd rather not work on the prototype anymore - update data - and just incorporate data into the new global map). 
ps - escoladigital.org.br is live

**Comment by acka47** [comment]
@tamielbr Thanks for the response. Good to know your GitHub handle so that next time I can address you directly here.

> ps - escoladigital.org.br is live

It probably was down temporarily, then...

**Comment by acka47** [comment]
As the data won't be transformed and added automatically and, thus, no mapping is needed I am closing this issue.
