### ISSUE TITLE
"Project lead in" line in personal profiles is displayed empty

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1450]
Look at Jan N.s profile, he is project lead in some projects but they are not shown. This is relevant for other personal profiles too. See:
![image](https://user-images.githubusercontent.com/18674205/36530775-47d51772-17bc-11e8-96d0-aa921955309c.png)

**Comment by literarymachine** [comment]
Luckily, this is a display bug and not one in the data. An empty row for `Project lead in` is shown in case a Person created a `LikeAction` or a `LighthouseAction` and at the same time is not `Project lead in` a Project.

**Comment by literarymachine** [comment]
Fixed on production, see e.g. https://oerworldmap.org/resource/urn%3Auuid%3A839897e6-178f-11e5-871b-3c970e4a9cbf
