### ISSUE TITLE
Enable filtering services for subjects more exactly (also on the second and third level)

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1451]
At the moment I only can select to filter from the first level of th subjects. But if I am a teacher, student or parent searching for services that offer OER for "Arts and humanities" is not specific enough. We should make it possible to search for the subjects from the second and even the third level of the subjects lists! It is so disappointing to see that the information is on the OER World Map, but I cant filter for it but have to ckick trough a list of for example 46 services to find out if the service covers for example German.

**Comment by literarymachine** [comment]
Duplicate of #744 and #1129, @karindr why did you close the latter? Implemented in the new UI, the indention style is still a bit unclear but the levels are there:
![image](https://user-images.githubusercontent.com/149825/36533937-60ef9a1c-17c5-11e8-9f92-4c244e5f68eb.png)

**Comment by karindr** [comment]
Wasn't aware of #744, so I close this.
