### ISSUE TITLE
Make it possible to change the displayed language of descriptions manually

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1453]
Last week we discussed using automated translating for the description texts of the different entry types. We talked about the possibility that the different language text may develop differently because someone will only change the text in one language but not in all languages. This points to a fundamental problem of having different language versions in our data. There is _never_ a guarantee that the corresponding texts are direct translations, they may be different from the beginning on. Often Projects have a main language where they offer detailed information and maybe one or two languages in which they offer brief information. 

To react to this I think we should give the visitors of the OER World Map the possibility to see that there are also texts in other languages and to change to them manually. (Visitors who are not logged in, can’t access the different texts via the template as we can. But it is also useful to editors because they have the possibility to see all different language texts they entered on the map.)

**Comment by trugwaldsaenger** [comment]
@karindr How could look this like concretely? I guess concentrating on the description might be a good start. Maybe we could add flags of all languages a description is available at above the description field?

**Comment by karindr** [comment]
Yes, the description is most important. There could be little flags or text like: See the description in Spanish, Portuguese, above or maybe better below the description.

**Comment by trugwaldsaenger** [comment]
Nice!

**Comment by programmieraffe** [comment]
👍👍👍

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/pull/455
