### ISSUE TITLE
Decide about which links should be part of which templates in general

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1458]
@trugwaldsaenger suggested that he, @acka47 and me should discuss this at some time in the near future.

**Comment by karindr** [comment]
Question: Have we descided that you can't connect an organisation to a service from the organisations template? At the moment when you start adding a new service you have to sopp and add the providing organisation first to be able to save the service. Or you address it to a country, enter the organisation, go back to the service, link it to the provider and delete the country.

**Comment by trugwaldsaenger** [comment]
Correct - I think this will be part of a comprehensive refinement of our input template!

**Comment by literarymachine** [comment]
Possible UI-solution:
- Show required fields by default
- Show populated fields by default
- Show Drop-down with *all* fields available, clicking a field adds it to the form
- Optionally cluster fields in the drop-down by topic (@trugwaldsaenger, @acka47, @karindr)

**Comment by formimkontext** [comment]
see #482 and those documents: 
https://docs.google.com/document/d/1e_SezYhhGMdPe4h8q9_xCI1CgmNvVecKAiqX7f6_TrY/edit
https://docs.google.com/spreadsheets/d/1XycxHG1hCn21NTzfGt8U1BymwIbz-Rbt0eH3WPPmJ4Q/

**Comment by literarymachine** [comment]
> Possible UI-solution:
>
> - Show required fields by default

This has been implemented. Closing.
