### ISSUE TITLE
Service Statistics View

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#1459]
Based on https://github.com/hbz/oerworldmap/commit/15512558af1b607a2d90d5831a39f2e170ed4920, rendering some kibana graphics is the next step to integrate statistics data (concerning materials and usage) into a Service resource entry.

@literarymachine Could you either please inform me about the next steps to be done or take over this issue?

**Comment by philboeselager** [comment]
Some initial dummy data:

    {
      "repository": {
        "name": "local",
        "domain": "www.dummysource.org",
        "oerworldmapid": "urn:uuid:3a81982f-fb6a-447d-a2ae-1ec03772dfbe",
        "uuid": "https://oerworldmap.org/resource/urn:uuid:3a81982f-fb6a-447d-a2ae-1ec03772dfbe"
      },
      "materials": {
        "licenses": [
          {
            "name": null,
            "type": null,
            "count": 694,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file-xml": 29,
                  "file": 51,
                  "file-image": 510,
                  "file-pdf": 31,
                  "file-word": 4,
                  "file-zip": 14,
                  "file-txt": 20,
                  "file-video": 10,
                  "file-script": 1
                }
              }
            ]
          },
          {
            "name": "CC_BY",
            "type": null,
            "count": 151,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file": 2,
                  "file-image": 147,
                  "file-pdf": 2
                }
              }
            ]
          },
          {
            "name": "CC_BY_SA",
            "type": null,
            "count": 5,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file-image": 5
                }
              }
            ]
          },
          {
            "name": "CC_BY_NC",
            "type": null,
            "count": 1,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file": 1
                }
              }
            ]
          },
          {
            "name": "CC_0",
            "type": null,
            "count": 8,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file-image": 8
                }
              }
            ]
          },
          {
            "name": "CUSTOM",
            "type": null,
            "count": 1,
            "facettes": [
              {
                "name": "cclom:format",
                "count": {
                  "file-image": 1
                }
              }
            ]
          }
        ]
      },
      "user": {
        "count": 0
      }
    }

**Comment by literarymachine** [comment]
> rendering some kibana graphics is the next step to integrate statistics data

The way Kibana works is that it uses Elasticsearch to create aggregations which are then visualized. Since in this case, we already have aggregated data in the first place, I don't think we can do this using Kibana.

**Comment by literarymachine** [comment]
Closing in favor of #1461
