### ISSUE TITLE
Look up registration address of nounstudents@yahoo.com

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1460]
I am changing old personal profiles which has been misused as organisations profiles. For this I renamend them to N. N. and contacted the email addresses. 
My question is about this personal profile:
https://oerworldmap.org/resource/?q=N.#urn:uuid:fa08dd13-8f1f-40d9-be79-0ff560639a3b
The Mail to "nounstudents@yahoo.com" came back as not existing. If the registration address is different i could write to it. If it is the same I can delete the profile.

**Comment by literarymachine** [comment]
You can search for `N. N.` in the groups administration to find the registration addresses of those accounts. Closing.
