### ISSUE TITLE
Wrong (and not translated) and not speaking labels in statistics in "Global statistics"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1462]
- In the first statisctic there is:
Action in stead of Project.
Article -> Story
WebPage -> Publication
Product -> Tool
These labels should be translatable!

- In the following statisctics there are sometimes URLs whath is not ideal but works in a way. 

- But sometimers (funders) there are the ID-numbers what is not really useful to anybody.

- Sometimes there are abbreviations, that is not ideal but works in a way. 

It would be the best to repeat the text below the statistic in the labels and translate it there as well.

**Comment by trugwaldsaenger** [comment]
This issue relates to the actual production system. As far as I can see, it has been solved on beta by now.

**Comment by literarymachine** [comment]
> This issue relates to the actual production system. As far as I can see, it has been solved on beta by now.

Yep! Once launched, we'll take some time and go through the issues and close what has been fixed during relaunch.

**Comment by acka47** [comment]
This is fixed on production. Closing.
