### ISSUE TITLE
Include OE Award badge on landing page

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1465]
http://www.oeconsortium.org/wp-content/uploads/2013/08/OE-Awards-Badge-2018-1.png

I would propose to include an additional section between the "Navigate the world of OER" and the "What is...." sections and show there the badge in a rather large format. I do not think additional text is needed, but for shure we could add a sentence or two. 

@drrobertfarrow: Do you have any additional advice for this?

**Comment by formimkontext** [comment]
i would add some information to the badge. maybe including a link to oeconsortium.org. 

![20180420-desktop1280px-award](https://user-images.githubusercontent.com/15141949/39044519-a7ad0abe-4490-11e8-8ba6-97a284b22fed.png)

**Comment by trugwaldsaenger** [comment]
Link to the Award side is certainly a good idea. Proposal looks OK to me, but we could drop the text, make the logo significantly bigger and put the link behind the logo. What do you think? If time is a problem, I´m happy to proceed like it is now.

**Comment by trugwaldsaenger** [comment]
Could we increase the size of the badge, skip the headline and simply keep the text?

**Comment by trugwaldsaenger** [comment]
Just an idea - if it does not work I trust in your judgement - but my feeling is, that the badge should be bigger ;-)
