### ISSUE TITLE
Add tools and publications as fully adequate data types to search & filter section

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1466]
In my opinion, both data types have been accepted pretty well and are used quite often. I see no reason any longer to handle them in a restricted way and would propose to add them to the filter section similar to all other data types. @acka47: Any opinion on this?

**Comment by formimkontext** [comment]
Draft for the filter section within the three column layout: Eight main type filter in the first row, dropdown for location and  tag filter in the second row below.  I am not sure about the icons we currently use for tools and publications so i made another suggestion. 

![20180416-aggregation-filter](https://user-images.githubusercontent.com/15141949/38817084-e82b336e-4197-11e8-87d3-849cc6175e5a.png)

**Comment by trugwaldsaenger** [comment]
Looks good to me! The new tools icon is definitivly better. For the publication I`m not sure, but we could discuss this during our next team meeting!

**Comment by karindr** [comment]
Really nice. I like the textsheet icon for publications better than the book icon we use at the moment.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/resource/

**Comment by karindr** [comment]
+1

**Comment by literarymachine** [comment]
Deployed to production, closing.
