### ISSUE TITLE
Add kibana statistics on country view

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1467]
We should define a basic statistics dashboard, which shows country related statistics:
- number of entries per data type 
- number of entries per sub-national entity
- number of entries per educational sector
- number of used licenses
- number of used topics

The dashboard should be included/linked to the country view: If you are on the country view for Germany, statistics related to Germany should be shown. If you are on the country view for the US, statistics related to the US should be shown and so on.

As far as the layout is concerned, I think we could consider to start with a simple link to a kibana dashboard. Eventually in a later stage of development, we can think of providing a more sophisticated solution.

**Comment by literarymachine** [comment]
Deployed to production, see e.g. https://oerworldmap.org/country/se and click on the statistics:

![image](https://user-images.githubusercontent.com/149825/50295526-81190d00-0478-11e9-955e-d1fa048d87d1.png)

The country dashboard will pop up:

![image](https://user-images.githubusercontent.com/149825/50295584-ac036100-0478-11e9-9e22-f6bab94e8bbc.png)

As mentioned in https://github.com/hbz/oerworldmap/issues/1711#issuecomment-449044738, we will have to look into the styling, but I thought it was worth having it here already.
