### ISSUE TITLE
Create World Congress Badge

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1470]
If possible, we should create a nice looking badge for the collected good practice examples: 
1. form: circle
2. frame: 
![grafik]:(https://pbs.twimg.com/profile_images/852141273809133568/5Rv5q1XX_400x400.jpg)
3. Within the circle following writing: 
https://user-images.githubusercontent.com/6639965/38546204-5287853c-3cac-11e8-9871-51870317b695.png
4. If possible: Add the wording: "Good Practice Example" or "Good Practice"

**Comment by formimkontext** [comment]
Here are two versions of the badge. Please delete the badge you dont want to use by editing  this comment. 

![oer-congress-gpe-badge-2](https://user-images.githubusercontent.com/15141949/38617591-b24a2966-3d97-11e8-9a82-490a6b263c7c.jpg)
![oer-congress-gpe-badge-3](https://user-images.githubusercontent.com/15141949/38617592-b26d07d8-3d97-11e8-8f12-265668549221.jpg)

**Comment by trugwaldsaenger** [comment]
Second badge was choosen to be used. Closing
