### ISSUE TITLE
Problems with localisation

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1473]
I think thi is not only relevant for OER World Map as service, I have seen it yesterday on at least an other example, but did not write it down.

The service is located in Berlin although the provider is hbz in Cologne
https://oerworldmap.org/resource/urn:uuid:29056e88-727b-407e-b00a-16df279ac506
![image](https://user-images.githubusercontent.com/18674205/38548678-9d90496e-3cb2-11e8-8694-1842ef1900a3.png)

**Comment by literarymachine** [comment]
Fixed on production.
