### ISSUE TITLE
Allow lighthouses for Events

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1475]

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:def7377c-b3a0-4bf9-ad9d-2bc03c55c8ca

**Comment by trugwaldsaenger** [comment]
+1 lighthouses for events are now available

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/commit/046b0fb3c10c66412ac7b6fdc0f7c5445e86256f
