### ISSUE TITLE
For the Primary Educational Sector you should be able to choose only one item  

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1477]
At the moment you can choose more than one item. @trugwaldsaenger has confirmed that the concept of the educational sectors is meant like this.

**Comment by karindr** [comment]
Since we have the new template this happens quite often, because it is more inviting now. I change it if I find more than one primary sectors chosen, but it should be changed in the template soon.

**Comment by trugwaldsaenger** [comment]
Still open on production. Probably not much work - I guess we should solve this in the near future.
