### ISSUE TITLE
Flexible column width

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#148]
Detail view: make it possible to change column width per drag, so that users can control how width is the map-column and how width is the text-column

**Comment by literarymachine** [comment]
Assigning this to @buschfeld to check if this makes sense in the intended UX.

**Comment by buschfeld** [comment]
It definitely make sense in the mid-screen resolutions like good old 640x480 or 800x600 px. Basically I would propose to do it in one of the following ways:
- defining a hot spot area of approx. 40px around the vertical axis where both columns meet and then change the cursor icon (icon with two horizontal pointing arrowheads or according to API standards). In this mode the user is enabled to resize the right column by drag & drop.
- introducing a kind of line grip similar too those common in all API Windows. Sticking to the layout proposed before the best place would be the left corner of the footer in the right column.

P.S.: This kind of resizing feature might be a bit complicated to implement, definitely we will need Javascript support for this. Johannes, what do you think?

P.P.S.: It seems like the GitHub image upload is not working for me. If so, I will sent an illustrating proposal via mail.

**Comment by buschfeld** [comment]
![oer_demo_map-detail_50-50_drag_cluster](https://cloud.githubusercontent.com/assets/10743356/7938095/185023c2-0944-11e5-8359-4fc36cdf5e7a.png)

**Comment by philboeselager** [comment]
@trugwaldsaenger Is this issue / request still valid?

**Comment by literarymachine** [comment]
> @trugwaldsaenger Is this issue / request still valid?

Nope, closing.
