### ISSUE TITLE
We are a map: Tools should have a location too

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1481]
At the moment searching for tools looks like this:
![image](https://user-images.githubusercontent.com/18674205/38977117-a7195b12-43b3-11e8-9215-ac23ad8031cd.png)
We collect the information who is using a tool. We could display this information for showing points on the map. This would be quite interesting because you can see which tools are only used locally and which are used globaly.

**Comment by literarymachine** [comment]
> We collect the information who is using a tool. We could display this information for showing points on the map. This would be quite interesting because you can see which tools are only used locally and which are used globaly.

We record which `Service` uses which `Tool`. Since most `Service` run on the web, we (usually) don't give them a location directly, but use that of their `provider`. So we would have to implement the location in the chain `Tool` => `isUsedBy` => `Service` => `provider` =>  `Organization/Person`.

**Comment by karindr** [comment]
This woulbd be ok from my point of view.

**Comment by trugwaldsaenger** [comment]
Agreed that tools should get locations as well. I like the idea of locating it at the location of it`s use. It´s an interesting new way of looking at the map. Nevertheless staying with the location of its provider (if there is one) seems more obvious to me.

**Comment by karindr** [comment]
If we want to locate the tools by using the location of their provider we will be forced to add the providers to te map to get locations. By doing this we will have to add a lot of organisations like Microsoft, Adobe and so on who are not really related to OER or openess. 

Because of this using the locations of the organisations/projects using the tools would be a lightweight option we should consider.

**Comment by literarymachine** [comment]
> We record which Service uses which Tool. Since most Service run on the web, we (usually) don't give them a location directly, but use that of their provider. So we would have to implement the location in the chain Tool => isUsedBy => Service => provider => Organization/Person => location => Place.

On beta, see https://beta.oerworldmap.org/resource/?filter.about.%40type=Product
