### ISSUE TITLE
Sharing and export buttons don't work

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1482]
I want to shore the country view of UK on twitter but nothing happens when I ckick on sharing exept adding #sharing to the URL.

**Comment by literarymachine** [comment]
Yikes, confirmed. @dobladov please take a look.

**Comment by dobladov** [comment]
Small error, we were missing a prop, fixed now.

**Comment by karindr** [comment]
On production? I made a reload, but nothing has changed.

**Comment by dobladov** [comment]
> On production? I made a reload, but nothing has changed.
Sorry, It's fixed but not deployed yet.

**Comment by karindr** [comment]
No problem, was just wondering :-)

**Comment by karindr** [comment]
+1 :-)

**Comment by karindr** [comment]
I don't find how to delete an entry, is this connected?

**Comment by literarymachine** [comment]
> I don't find how to delete an entry, is this connected?

Nope, but we indeed silently changed this. Sorry! The delete button can now be found at the bottom of the `edit` form:

![image](https://user-images.githubusercontent.com/149825/38984490-1754b71a-43c7-11e8-8ded-6f72e11c5f18.png)

When restructuring the code, we made a `Share & Export` component and deletion seemed not be in the right spot there. Can you live with this?

**Comment by literarymachine** [comment]
Fixed on production.

**Comment by karindr** [comment]
Yes, no problem.

**Comment by karindr** [comment]
+1
