### ISSUE TITLE
The colouring of the regions in the country view is strange

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1484]
For example India: There is a dot in the middle for a person who only chose India as location. It is ok that the region the dot is placed in is not green. Otherwise in the south there is a person with a "real" location, but the region is not green. And in the north there is a person in a region and this region is green.
https://oerworldmap.org/country/IN

For example UK: This seems quite strange, I did not look up everything, but some. There is OER Wales which is located in the Middle of Wales which is not green. Looking at the entry I would assume that OER Wales inherits the location of its operator which is located in Cardiff. In Cardiff there is no green either.
There seems to be lots of locations in the UK that have no adress, but maybe koordinates (maybe from an import?). All in all a lot of nicly placed dot but very few green regions.
https://oerworldmap.org/country/gb

**Comment by literarymachine** [comment]
> For example India: There is a dot in the middle for a person who only chose India as location. It is ok that the region the dot is placed in is not green. Otherwise in the south there is a person with a "real" location, but the region is not green. And in the north there is a person in a region and this region is green.

The reason for this is that the user "in the middle" provided a [country code and also coordinates](https://oerworldmap.org/resource/urn:uuid:18db3ade-dfaa-42f1-be8f-d450a7643059.json), but did not specify a region. The latter is needed for the coloring of the regions, the coordinates are used for the dots.

> There seems to be lots of locations in the UK that have no adress, but maybe koordinates (maybe from an import?). All in all a lot of nicly placed dot but very few green regions.

As far as I remember, we did not automatically import any UK data, but I might well be wrong. In general, it is indeed the same issue as with India above. There often are entries with coordinates (dots), but not regions (needed for the coloring).

I agree that we need to put some thought into how to get rid of this mismatch.

**Comment by trugwaldsaenger** [comment]
seems to be related to #1495

**Comment by literarymachine** [comment]
> seems to be related to #1495

Only loosely. The main issue here is that we have quite some [legacy data](https://oerworldmap.org/resource/?q=_exists_:about.location.geo%20AND%20_missing_:about.location.address.addressRegion) where coordinates are set (resulting in dots on the map) but regions are not (resulting in not being counted for the coloring of the regions).

**Comment by literarymachine** [comment]
> I agree that we need to put some thought into how to get rid of this mismatch.

Fixed this on the data level, all entries that had a pin but no region now have one. 

> For example India

See https://beta.oerworldmap.org/country/in, the remaining two dots without a region had a wrong region code already. We'll have to take a look and fix this manually

> For example UK

See #1555

**Comment by literarymachine** [comment]
Data fixed on production.
