### ISSUE TITLE
German descriptions are not displayed if English descriptions are availabe

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1485]
... Browser is set to German, see:
https://oerworldmap.org/resource/urn%3Auuid%3Affb043ce-365f-46f6-be98-79014da5e5c5
![image](https://user-images.githubusercontent.com/18674205/38987623-b739c906-43d0-11e8-94a2-eb676d3a9fff.png)

**Comment by literarymachine** [comment]
As discussed with @trugwaldsaenger, languages other than English are currently disabled until @acka47 and I fix hbz/oerworldmap-ui#210. Thus, only if no English is available a fallback to another language happens.

**Comment by literarymachine** [comment]
Fixed on production, see e.g. https://oerworldmap.org/resource/urn%3Auuid%3Affb043ce-365f-46f6-be98-79014da5e5c5
