### ISSUE TITLE
Strange "changes" showed in logs of entries

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1489]
Have a look at this:
https://oerworldmap.org/log/urn:uuid:311ad28b-83b2-406b-a53f-a34be89d29e2?compare=e68a6b1e50d7a7abd87e48d0102fc8ccd15b67b7&to=d8aa10dd5acf4c4d53fd318a35848bf23d2d4709
To me some of the changes (e.g. Partners and Tags) look like changes in the order not real changes. This seems to make no sense like this.

**Comment by literarymachine** [comment]
Fixed in hbz/oerworldmap-ui#276, see e.g. https://oerworldmap.org/log/urn:uuid:311ad28b-83b2-406b-a53f-a34be89d29e2?compare=e68a6b1e50d7a7abd87e48d0102fc8ccd15b67b7&to=d8aa10dd5acf4c4d53fd318a35848bf23d2d4709
