### ISSUE TITLE
There should be a search field in every view of the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1491]
When you are in the item view it is quite annoying that you have to close this view (what is quite slow) to be able to enter a search term.

**Comment by acka47** [comment]
I am not sure. Especially for stories it makes sense to have the focus on the entry. Maybe it would suffice implementing what I wrote in https://github.com/hbz/oerworldmap-ui/issues/192#issuecomment-378247098?

> When a detail view for an individual resource is open I should be able to go back to the map by clicking besides the profile on the map. Currently, I have to click on the x to get back.

**Comment by karindr** [comment]
> When a detail view for an individual resource is open I should be able to go back to the map by clicking besides the profile on the map. Currently, I have to click on the x to get back.

Yes, this would be good!

I think our graphic collegues would not like it ;-), but I think it is a not so bad idea: I suggest to put the search field in the hearder so automatically it is displaed in every view. If it is placed on the right it is still near the filter section.

**Comment by formimkontext** [comment]
> I suggest to put the search field in the hearder so automatically it is displaed in every view. If it is placed on the right it is still near the filter section.

with the header menu we talked about at the last teammeeting and we agreed to implement, the user will have access to the search field from every site of the world map. see draft below. maybe we can differ between "search" (search field) and "find" (categories) and add "search" as a single point to the header menu.

![201801-desktop-1280px-header_menu_1_find_3](https://user-images.githubusercontent.com/15141949/39700379-450b7da8-51fd-11e8-89f1-d1bc459393d8.png)

**Comment by trugwaldsaenger** [comment]
@formimkontext: I just had a look at the navigation, which is currently on beta. There I noticed, that the search field, which is included in the screenshot above, is not included yet. Do you know if this will come later, or did you change the design?

**Comment by formimkontext** [comment]
> Do you know if this will come later, or did you change the design?

We will implement the search field later.
