### ISSUE TITLE
Inconsistent behaviour of country views with regard to search terms 

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1493]

**Comment by literarymachine** [comment]
Can you explain? It works for me, clearing the filters but keeping the search term as requested in #891.

**Comment by literarymachine** [comment]
![image](https://user-images.githubusercontent.com/149825/39236426-2ee1434c-4879-11e8-8d93-49eed39f8dfa.png)

![image](https://user-images.githubusercontent.com/149825/39236459-3e63cd3a-4879-11e8-9e54-84efe45ae54b.png)

**Comment by karindr** [comment]
You are right. I got mixed up ;-). I'll change this issue to this:

When I have a search term in the search field and change to a country view, the country view is shown with all its entries not considering the search term (which is still shown), but when I change the list to be sorted in an other way the search term is beeing used and the number of results is being reduced.

**Comment by literarymachine** [comment]
Ah, I see! That is indeed not the way it is supposed to be.
