### ISSUE TITLE
Change "A description for this entry is missing. Help us by adding some information!" in personal profiles

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1496]
Since I can only change the bio in my own personal profile I think this text should not be shown to all visitors but only to the owner of the profile. If it is only shown to the owner the second sentence should read: "Please add information about youself". The text for the rest of the visitors could be the first sentence.
![image](https://user-images.githubusercontent.com/18674205/39291537-a8868f62-4933-11e8-94ed-87c1330410c4.png)
https://oerworldmap.org/resource/urn%3Auuid%3Ad1211163-da92-4ede-bc21-06d3e5f084cb

**Comment by literarymachine** [comment]
> Since I can only change the bio in my own personal profile I think this text should not be shown to all visitors but only to the owner of the profile.

You only see this because you are an admin. Other people only see this:

![image](https://user-images.githubusercontent.com/149825/40352959-8c65c384-5db0-11e8-860f-08b1ce2d1ee0.png)

I don't think we need a different wording for every little detail and suggest to close this issue.

**Comment by karindr** [comment]
Since this is only the administrators view it doesn't have to be changed.
