### ISSUE TITLE
Sorting by date created is not working precisely

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1498]
I am not shure if this is really a problem, but I want to share my finding. I the list of new entries sorted by date created there is the entry of Kai Wörner placed above the entry of DiBiS which was created by him. Clearly he could not have created this entry before he was registered.
![image](https://user-images.githubusercontent.com/18674205/39297364-974d18aa-4943-11e8-86e3-8cf97b2a4e4c.png)
https://oerworldmap.org/resource/?size=20&sort=dateCreated%3Adesc&features=true

**Comment by literarymachine** [comment]
I actually also stumbled across this behavior just this morning! Will investigate if there is a general issue with regards to sorting by `dateCreated`.

**Comment by literarymachine** [comment]
I can confirm this is a bug introduced in https://github.com/hbz/oerworldmap-ui/pull/276

**Comment by karindr** [comment]
It makes it quite difficult to work with the list, because it changes sometimes (e.g. since I opened this issue).

**Comment by literarymachine** [comment]
> It makes it quite difficult to work with the list, because it changes sometimes (e.g. since I opened this issue).

Yes. This is why I labelled it a bug and re-assigned it to the developers.

**Comment by literarymachine** [comment]
Fixed on production: https://oerworldmap.org/feed/

**Comment by karindr** [comment]
Looked at some entries, seems to be right now. +1 Thanks!
