### ISSUE TITLE
Get statistics on OER institutions

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#15]
As a policy maker I want to know how many institutions are engaged in OER in a specific country or continent. Additionally I want to
- compare these numbers with the numbers of previous years.
- restrict the results to certain countries, topics, forms of education and/or grade levels.

**Comment by acka47** [comment]
This obviously is an "epic" that has to be broken down in several more detailed user stories.

**Comment by philboeselager** [comment]
could be solved by #258.
