### ISSUE TITLE
Should we introduce likes for all entry types except persons?

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1504]
Moved here from https://github.com/hbz/oerworldmap-ui/issues/284:

Reading a story on the OER World Map I asked myself why I am not able to like it.

I suggest to make all entry types except persons likeable. As far as I can see people do not very often use the like button until now. Maybe the psychological barrier is lower to like a story than an organisation because you can simply read a story. About an organisation you have to know a lot of things to form an opionion about, this may seem more complex. And when pople start likeing simple things like tools, publications and storys they may also start liking projects and services, so we get more interactions on the map.

**Comment by trugwaldsaenger** [comment]
+1

**Comment by literarymachine** [comment]
Fixed in 78c1a801199b4b016b319a12d7d793a6650822a1.
