### ISSUE TITLE
Add missing region information based on geo coordinate

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1508]
Currently, there are ~550 **entries that have geo coordinates but no region information**: https://oerworldmap.org/resource/?q=NOT%20_exists_:about.location.address.addressRegion%20AND%20_exists_:about.location.geo

Furthermore, there are ~70 **entries missing region and coordinate information but having country and street address**: https://oerworldmap.org/resource/?q=NOT%20_exists_:about.location.address.addressRegion%20AND%20NOT%20_exists_:about.location.geo%20AND%20_exists_:about.location.address.streetAddress%20AND%20_exists_:about.location.address.addressLocality 

As region information has become more important due to the heat map for a country view, we should think about how to now include the region information.

**Comment by literarymachine** [comment]
> Currently, there are ~550 entries that have geo coordinates but no region information: 

There is (on beta) only a handful left over that for some reason could not automatically be mapped to a region:

https://beta.oerworldmap.org/resource/?q=NOT%20_exists_:about.location.address.addressRegion%20AND%20_exists_:about.location.geo

Once this is deployed to production, those will need to be fixed manually.

**Comment by literarymachine** [comment]
Data fixed on production.
