### ISSUE TITLE
Import OER policy registry

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1510]
- currently a wiki: https://wiki.creativecommons.org/wiki/OER_Policy_Registry ([template](https://wiki.creativecommons.org/wiki/Template:OER_Policy))
- Goal: Launch of policy map at OER Policy Meeting in Warsaw in Sept. 2018
- Potential additional fields: "resulting program"
- [ ] ~~Felix and Philipp do first conversion & import to Beta, then await Feedback~~
- [ ] @karindr will manually add a sample of the registry to Beta
- [ ] @literarymachine will ping Cable for updates
- [ ] @acka47 will take a look at the current list of fields at https://wiki.creativecommons.org/wiki/Template:OER_Policy

EDIT after discussion with @trugwaldsaenger

**Comment by literarymachine** [comment]
I checked the current fields and mapped them as follows:

```
OER Policy Title = name
OER Policy URL = url
Description = description
Author = creator
OER Policy Date = datePublished
OER Policy Status = 
Language code = inLanguage
OER Policy Jurisdiction =
Country = location
OER Policy Institution = publisher
Tag = keyword
License short name = license
```

So only `OER Policy Status` and `OER Policy Jurisdiction` are left. Also, `location` currently allows to enter more details than just a country, which we might want to change.

**Comment by literarymachine** [comment]
Based on the above additional fields, I manually [imported](https://beta.oerworldmap.org/resource/?filter.about.additionalType.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fpublications.json%23policy) the first three entries of the [registry](https://wiki.creativecommons.org/wiki/OER_Policy_Registry). Browsing by country works fine with our current filter:

![image](https://user-images.githubusercontent.com/149825/43462369-34e29be8-94d6-11e8-8e3c-ae36c7ba6b1b.png)

To browse by status and jurisdiction type, we'll have to add the corresponding fields and filters.

**Comment by literarymachine** [comment]
What I realized while doing this is that adding the things manually is probably the best way, because it implies some quality control, e.g. for outdated links. This is the case e.g. for [Argentina: Gleducar - Propiedad Intelectual](https://wiki.creativecommons.org/wiki/Argentina:_Gleducar_-_Propiedad_Intelectual).

**Comment by trugwaldsaenger** [comment]
> What I realized while doing this is that adding the things manually is probably the best way, because it implies some quality control, e.g. for outdated links.

I agree. According to my experience it will be very helpful to develop comprehensive understanding to import things manually.

**Comment by literarymachine** [comment]
Initial import is done, closing.
