### ISSUE TITLE
Searching for "neu" in Persons not getting Neumann as result

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1511]
https://oerworldmap.org/resource/?q=neu&filter.about.%40type=Person&size=20

**Comment by trugwaldsaenger** [comment]
> Tokenizing the strings so that matches like "neu" for Neumann and "ostr" for Ostrowski will lead to very many falsy hits.

I do not really understand this sentence. Anyway - we discussed today that adding autocompletion to the search box will be a good solution to this problem. Closing.
