### ISSUE TITLE
Tools shoud have a kind of licence field

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1513]
A user suggested we should have some information about the tools wether they are free, open source or fee based. I think that would be useful an consistent with the idea of openess on the OER World Map.

**Comment by acka47** [comment]
The thing is that tools use other licenses than Creative Commons. So we will first have to create a controlled list of possible values for licenses for tools. I suggest a simple binary solution, distinguishing between [Open Source definition](https://opensource.org/osd) compliant licenses (see https://opensource.org/licenses)  and closed source.

**Comment by acka47** [comment]
Ok. @literarymachine, does it make sense to just use the JSON schema for the two options instead of creating a SKOS file? I am not sure how internationalization would work with this approach, though...

**Comment by acka47** [comment]
I updated the schema, see the commit above. What should I do to add the field, the label and a description to the form as well as labels for the controlled values?

**Comment by literarymachine** [comment]
> What should I do to add the field, the label and a description to the form as well as labels for the controlled values?

To add the field to the form you need not do anything; forms are now based on the JSON Schema. Add `Product.rights` to [labels.json](https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/labels.json) and [descriptions.json](https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/descriptions.json). For the controlled values, you can for now simply add they keys `floss` and `proprietary` with their corresponding labels to [ui.json](https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/ui.json).

**Comment by acka47** [comment]
Reopening. We also need to merge and deploy https://github.com/hbz/oerworldmap/pull/1525 to close this.
