### ISSUE TITLE
Sharing a list from the World Map to facebook only shows the number of the entries

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1515]
When you want to share a list from the map on facebook it does not look very nice:
![image](https://user-images.githubusercontent.com/18674205/38854470-da497dbc-4220-11e8-8aae-61146c5e2275.png)

**Comment by literarymachine** [comment]
On production. Besides the pure number, the title is now more human readable and an image is always added to the shared link.

**Comment by karindr** [comment]
+1
