### ISSUE TITLE
Some design issues for the new item view

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1517]
Took some points from the long isssue to be able to close it:
https://github.com/hbz/oerworldmap-ui/issues/194

>the abbreviation is an exception which i think, doesn’t need to be shown in the list but in the headline (abbreviation – full name).

Yes, please hide the abbreviation in this list. It is not necessary here and this makes several problems disappear!

>i agree. can we do this like in this draft: https://user-images.githubusercontent.com/15141949/36307423-65eff280-131c-11e8-9e3f-fc2344d9040e.png

This would be good.

**Comment by karindr** [comment]
headings and text should be different. since allmost every entry within the lists beneath the tag-section is a link to another world map entry, its color would be blue.

Form me there is not enough difference. Have a look at a screen like this:
![image](https://user-images.githubusercontent.com/18674205/38928085-032e1fca-4308-11e8-94d1-35d171442ed3.png)

**Comment by karindr** [comment]
We aggreed on this points.

**Comment by formimkontext** [comment]
all done.

**Comment by karindr** [comment]
Sorry, I can't find these changes neither on production nor on beta.

**Comment by formimkontext** [comment]
i know, sorry!
