### ISSUE TITLE
Add OE relevance hint to input templates

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1519]
#Problem: We observe more entries which do not show a clear relation to OER or Open Education.

Solution: When adding a new dataset a hint should be shown:

"The OER World Map collects data related to Open Educational Resources (OER) and Open Education as outlined in the Cape Town Declaration (http://www.capetowndeclaration.org/) and the 2012 OER Paris Declaration (http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/CI/CI/pdf/Events/English_Paris_OER_Declaration.pdf). Please make sure that only related data is included. If not obvious, please outline the reference to OER in the description field briefly."

**Comment by trugwaldsaenger** [comment]
I guess we have to do this sometime (but not necessarily immediatly). I therefore set the prio to 1. @drrobertfarrow, @karindr: Any improvements concerning the text?

The text above is rather long, so we have to find a good place for this. On solution could be to display it directly over the map which appears after opening a new input template. @formimkontext: Any better ideas?

**Comment by karindr** [comment]
Here is a slightly shorter and straighter version (links have to be includes like above):
"The OER World Map collects data related to Open Educational Resources (OER) and Open Education as described in the Cape Town Declaration and the 2012 OER Paris Declaration. Please ad only related data. If not obvious, please outline the reference to OER in the description field."
A good place would be above the new Add-Fields, see on beta:
![image](https://user-images.githubusercontent.com/18674205/40651137-430a616a-6335-11e8-9489-481eb01cb073.png)
