### ISSUE TITLE
Format author data

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#152]
Detail view „OER World Map“-story: when clicking on link to author (Felix Ostrowski), a raw data-set without formatting is displayed. (http://oerworldmap-dev.graphthinking.com/resource/urn:uuid:b1e4cad1-d3f7-4f19-bb37-7a9b12b18811)

**Comment by literarymachine** [comment]
The author page should include the `name`, optional `url` and a list of contributions.
