### ISSUE TITLE
People with personal profiles without name can comment without name. Change this

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1520]
Maybe there are not much people like this and maybe they don't make comment but this possibility is against our strategie that we want comments to be referenced to their authors. This is kind of a bug but it is very unlikely to happen so I will take the label enhancement.

**Comment by literarymachine** [comment]
> Maybe there are not much people like this and maybe they don't make comment but this possibility is against our strategie that we want comments to be referenced to their authors.

For quite a long time now, `name` has been a required property that has to be given during registration and also cannot be removed when editing the profile. Thus, I think we are dealing with a non-issue here.

**Comment by karindr** [comment]
I have such an account, but won't do this. Closing.
