### ISSUE TITLE
Some problems with browser language

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1523]
There are some small inconsistencies with the language in the browser.

- [x] On the landing page (https://oerworldmap.org) the nav bar is always in English no matter what language the browser asks for.
- ~[ ] On https://oerworldmap.org/resource/ the nav bar is correctly in German when the browser asks for DE but it is in English when asking for PT-BR.~
- [x] The HTML title is ok with the German version but for PT the title is shown in English on all static pages except for https://oerworldmap.org/resource/.

**Comment by literarymachine** [comment]
> On the landing page (https://oerworldmap.org) the nav bar is always in English no matter what language the browser asks for.

Yes. Because the landing page is currently only available in English. The navigation will be localized once the content ist.

> On https://oerworldmap.org/resource/ the nav bar is correctly in German when the browser asks for DE but it is in English when asking for PT-BR.

Yes, because our files are named `.pt` and not `pt-br`. Asking for `PT` correspondingly delivers the Portuguese content. Crowdin also delivers `.pt`, not `.pt-br`, right? So this is IMHO not a bug, although we might want to implement falling back if the country specific i18n is not available.

> The HTML title is ok with the German version but for PT-BR the title is shown in English on all static pages.

See above.

**Comment by literarymachine** [comment]
> And in PT-BR the title on https://oerworldmap.org/resource/ shows the number of all entries (in English) and in German "Einträge anzeigen" (without number).

Again, we currently don't support `pt-br`. If individual strings are wrong like e.g. the German "Einträge anzeigen", they can be fixed in crowdin.

**Comment by karindr** [comment]
On the Contribute page there is no difference wether I use pt or pt.br but this difference is on https://oerworldmap.org/resource/.

**Comment by acka47** [comment]
> Again, we currently don't support `pt-br`. 

I updated the issue with using PT only as some of the problems pertain. As this actually is PT-BR what we offer, we will have to fix this. Am I right, that the i18n files have just to be named accordingly by CrowdIn (i.e. using "pt-br" instead of "pt")?

**Comment by acka47** [comment]
It actually is quite strange that pt-br is partly supported by the site. Can it be that this has to do something with the different naming conventions (dot versus underscore), @literarymachine ?

**Comment by literarymachine** [comment]
> Am I right, that the i18n files have just to be named accordingly by CrowdIn (i.e. using "pt-br" instead of "pt")?

I believe so, but then we will support only `pt-br` and not `pt` which would be a pity.

**Comment by literarymachine** [comment]
Just to understand this right. Can we agree that using `pt` works properly both on the map and on the static pages?

![image](https://user-images.githubusercontent.com/149825/39805579-82c99604-5377-11e8-9401-9a50451a96cd.png)

![image](https://user-images.githubusercontent.com/149825/39805591-8ce864da-5377-11e8-9e93-ddd2ba0c7922.png)

> It actually is quite strange that pt-br is partly supported by the site. Can it be that this has to do something with the different naming conventions (dot versus underscore), @literarymachine ?

No, it looks like the map and the static pages currently deal differently with country specific locales.

**Comment by acka47** [comment]
Closing this as everything is fine when requesting, de, pt or en.
