### ISSUE TITLE
Add Open Education Awards to Map

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1527]
https://docs.google.com/spreadsheets/d/1Pq2avxfcfUwgOTWcI0sbAiCOHIoNsJECDEzLBqTDMxw/edit#gid=1097758367
Main thing will be a editorial task:

- add all winners to the map
- add link to badge
- ask winner to register and complete profile
- celebrate

**Comment by karindr** [comment]
In this case the link to the badge comes without "name". So if you go to the award button in the filter section and open the list there there are some names shown but also some links.

**Comment by literarymachine** [comment]
> Jure did send us the links to the badges. Should we stay with these, or does it make sense to add the badges to our git, so that we can be sure the url will stay stable.

I would argue OEC should keep the URLs stable.

> I think we discussed adding a little more information to the badges. 

Yes, but for now we still only have the badge represented by a `url` and associated with a `label`.

> In this case the link to the badge comes without "name". So if you go to the award button in the filter section and open the list there there are some names shown but also some links.

I am unsure what you mean. The links that are shown are from somebody who used the field wrong, see https://github.com/hbz/oerworldmap/issues/1347#issuecomment-355942909. By now, `award` can only be entered by admins. I think we should fix this in the data, or add a label if we want to keep the entries.

**Comment by trugwaldsaenger** [comment]
Do I understand it correctly, that the label has to be added to the URL? In the comment I find following example:

> https\://open-educational-resources.de/wp-content/uploads/oerde16_logo_award.png

 = "OERde 16 Award".

I tried following URL, but it is not working...

> http://www.oeconsortium.org/wp-content/uploads/awards/badge-2017.png = "Open Education Award 2017".

I get an error message "should match format "uri" "

**Comment by literarymachine** [comment]
> Do I understand it correctly, that the label has to be added to the URL?

No. The process to add a new award is:

- [ ] Obtain image URL
- [ ] Add label to https://github.com/hbz/oerworldmap-ui/edit/master/docs/_data/locale/ui.json
- [ ] Assign award URLs to entries

I added the label in 9c9cb3f6590621579d6aa4ae0b06ccae4ae4b8b6, but I will have to deploy this and am currently travelling. Also, this will have to be translated via Crowdin for the other languages.

**Comment by trugwaldsaenger** [comment]
Many thanks for your quick reaction! No problem to deploy this later!

**Comment by literarymachine** [comment]
> All entries we could add are added. I contacted all persons via email and am going to contact people and organizations related to the other entries.

Assuming this is done, closing.
