### ISSUE TITLE
In the country view it would be nice to have hovering lables for the regions

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1528]
It would be nice to have such lables for regions as we have them for contries. It would also help us to find the regions to add the regional information to entries without this information.

**Comment by trugwaldsaenger** [comment]
I agree, that this would be helpful. I also agree that it is an enhancement and that its a Prio 3 issue.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/de:

![image](https://user-images.githubusercontent.com/149825/58023457-20b5f680-7b10-11e9-86ad-e6e8bd674956.png)
