### ISSUE TITLE
Stange behaviour of dots for entry 

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1529]
This enty has a country, region and an address but no dot on the map. Why?
https://oerworldmap.org/resource/urn:uuid:5b403cd0-e732-4ad7-acb2-30242c96742c?

**Comment by literarymachine** [comment]
> This enty has a country, region and an address but no dot on the map. Why?
https://oerworldmap.org/resource/urn:uuid:5b403cd0-e732-4ad7-acb2-30242c96742c

Because it does not have geo coordinates. The person who added it probably did not use the location lookup. In this case, no geo coordinates are added (because we don't know them).

**Comment by literarymachine** [comment]
> Same for this: https://oerworldmap.org/resource/urn%3Auuid%3Ad0010a46-2677-46d0-8225-5db57e4a575b#edit
> If I save it again there is a dot and if I make a reload it goes away! Very strange!
> It is even more strange: Reloding the dot appears and reloading again the dot sisappears.
> It is even more strange: Reloding the dot appears and reloading again the dot sisappears.

This one indeed (always) have a dot. The problem seems to be that sometimes it is placed off the view port and not being zoomed to.

**Comment by karindr** [comment]
> Because it does not have geo coordinates. The person who added it probably did not use the location lookup. In this case, no geo coordinates are added (because we don't know them).

I tried to fix this. It does not work because the regions for Denmark are wrong: Hovedstaden is missing, there is only Sjaælland but five times. If I choose this region I cant get the Address because it is the wrong region.

**Comment by literarymachine** [comment]
> Hovedstaden is missing, there is only Sjaælland but five times.

Added as bug #1530.

> If I choose this region I cant get the Address because it is the wrong region.

I'll be fixing the input template shortly as discussed at the team meeting (making the region not required to add the rest of the address).

**Comment by literarymachine** [comment]
@dobladov the behavior that the pin is not centered and zoomed to also occurs in the `Minimap` on the `PlaceWidget` every now and then. So I assume it is some timing issue.

**Comment by literarymachine** [comment]
> I'll be fixing the input template shortly as discussed at the team meeting (making the region not required to add the rest of the address).

Fixed on production, removed the region and added the location via the lookup for https://oerworldmap.org/resource/urn:uuid:5b403cd0-e732-4ad7-acb2-30242c96742c
