### ISSUE TITLE
Why is the Bundesland Brandenburg white allthough there is at least an organisation ...

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1532]
... with address and regional information:
https://oerworldmap.org/resource/urn:uuid:cc081290-c8d9-45dd-aa56-66d7e3fe6aed

**Comment by literarymachine** [comment]
This is most likely related to #1530. Unfortunately, getting regions right on a global scale is hard. @dobladov can you take a look at our regions layer what the code for Brandenburg is? Probably it is not matching what is given in the data.

**Comment by literarymachine** [comment]
> This is a bug on the regions layer, the current code_hasc for Brandenburg is DE. and I think it should be DE.BB like in the about.location.address.addressRegion of this resource.

Is this something we can fix directly in mapbox studion? /cc @formimkontext

**Comment by dobladov** [comment]
Mabox Studio does not allow to modify titlesets, only replace replace the current one, But I prefer if we upload a new one and we just change the tileset in mapbox Studio, this way we can rollback in case something is missing.

**Comment by literarymachine** [comment]
We should also evaluate moving to [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) instead of [HASC](https://en.wikipedia.org/wiki/Hierarchical_administrative_subdivision_codes). When we started, HASC was the only field that was (sort of) consistently used in our natural earth data. This would involve mapping and migrating from HASC to ISO 3166-2.

**Comment by literarymachine** [comment]
Could be useful: https://gist.github.com/migurski/4a5821699e1ed519a604

**Comment by literarymachine** [comment]
The most recent version of http://www.naturalearthdata.com/downloads/10m-cultural-vectors/ seems to have much better regions codes (also as HASC, so we would not need migrate now). Codes for #1530 are also fixed there!

**Comment by literarymachine** [comment]
Fixed on production, see https://oerworldmap.org/country/de:

![image](https://user-images.githubusercontent.com/149825/40475115-03b0e9d2-5f41-11e8-824e-c0b3dd4e0713.png)
