### ISSUE TITLE
"Service.availableChannel.serviceUrl" written in Service Template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1533]
In the template to enter services there is this kind of a name of the field instead of Website or URL. In the middle of the screenshot:
![image](https://user-images.githubusercontent.com/18674205/40046759-090f217e-582e-11e8-91eb-3a91446922eb.png)

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/9f62883ef1813d5a7b6d8fcc4383bdf6b6a7ec36 and deployed to production.
