### ISSUE TITLE
Some changes in the new UI make it harder to enter subjects

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1534]
Der Kürze halber mal auf deutsch.

Unsere Liste an Fächern ist nicht einfach zu verstehen, da sie versucht, die Fächer länderübergreifend abzubilden, aber sie ist das Beste, was wir haben, also wollen wir an ihr festhalten. Um bestimmte Schulfächer einordnen zu können, ist es oft notwendig, die Liste rauf und runter scrollen zu können und die Hierarchie zu sehen.

Im neuen UI wird die Liste als Ganze manchmal nicht angezeigt, erst, wenn man ein Leerzeichen eingibt. Das ist nicht intuitiv. Es wäre besser, wenn die Liste als default angezeigt würde (früher konnte man sie einfach herunterklappen).

In der Liste sind außerdem nicht alle Hierarchiestufen zu erkennen, das ist aber oft notwendig, um sich zu orientieren. Alle vier stufen sind notwendig.

Wenn ich beginne Buchstaben einzugeben ist das angezeigte Ergebnis teilweise sehr merkwürdig. Gebe ich beispielsweise "art" ein, weil ich das Fach Kunst suche, erscheint "Arts and humanities" (OK) und "horticulture" (???).

Teilweise ist das hier sicher nur ein Enhancement, um das es geht, teilweise erscheint mit das Verhalten aber auch fehlerhaft, deshalb auch Bug.

**Comment by literarymachine** [comment]
> Im neuen UI wird die Liste als Ganze manchmal nicht angezeigt, erst, wenn man ein Leerzeichen eingibt. Das ist nicht intuitiv. Es wäre besser, wenn die Liste als default angezeigt würde (früher konnte man sie einfach herunterklappen).

Die Liste wird angezeigt, sobald man das entsprechende Feld ansteuert. Es ist kein manuelles Herunterklappen mehr nötig, und eigentlich auch kein Eintippen von einem Leerzeichen:

![image](https://user-images.githubusercontent.com/149825/40051133-f8b9329a-5839-11e8-8dd1-22cf8358b0b8.png)

Bei funktioniert das zuverlässig. Wie ich aber sehe verschwindet die Liste, wenn man einen Suchbegriff eingegeben hat und diesen wieder löscht. Das sollte vermutlich besser nicht so sein.

> In der Liste sind außerdem nicht alle Hierarchiestufen zu erkennen, das ist aber oft notwendig, um sich zu orientieren. Alle vier stufen sind notwendig.

Wenn ich das richtig sehe, ist die vierte Stufe zwar in der Liste vorhanden, aber nicht eingerückt. Korrekt? Das sollte in der Tat nicht so sein!

> Wenn ich beginne Buchstaben einzugeben ist das angezeigte Ergebnis teilweise sehr merkwürdig. Gebe ich beispielsweise "art" ein, weil ich das Fach Kunst suche, erscheint "Arts and humanities" (OK) und "horticulture" (???).

Den "Horticulture"-Treffer kann ich gerade auch nicht ganz erklären.

**Comment by literarymachine** [comment]
> Den "Horticulture"-Treffer kann ich gerade auch nicht ganz erklären.

Ha! "Horticulture" ist auf deutsch "G**art**enbau".

**Comment by karindr** [comment]
> Wenn ich das richtig sehe, ist die vierte Stufe zwar in der Liste vorhanden, aber nicht eingerückt. Korrekt? Das sollte in der Tat nicht so sein!

Ja, die Einrückungen sind sehr wichtig um die Hierarchiestufe zu erkennen.

> Ha! "Horticulture" ist auf deutsch "Gartenbau".
Ja, klar ;-). Aber im Ernst, kann man das Suchen hier auf die jeweils angezeigte Sprache beschränken? 

> Bei mir funktioniert das zuverlässig. Wie ich aber sehe verschwindet die Liste, wenn man einen Suchbegriff eingegeben hat und diesen wieder löscht. Das sollte vermutlich besser nicht so sein.

Vielleicht war es das, aber ich hatte mehrfach den Fall, dass ich ein Leerzeichen eingeben musste, um die Liste wieder angezeigt zu bekommen. Wenn der o.g. Fall behoben ist, sehen wir ja, ob die Liste dann zuverlässig erscheint.

**Comment by literarymachine** [comment]
> Ja, die Einrückungen sind sehr wichtig, um die Hierarchiestufe zu erkennen.

@dobladov can you fix the levels of indention: #1538.

> kann man das Suchen hier auf die jeweils angezeigte Sprache beschränken?

Kann und sollte man: #1537.

> Vielleicht war es das, aber ich hatte mehrfach den Fall, dass ich ein Leerzeichen eingeben musste, um die Liste wieder angezeigt zu bekommen. Wenn der o.g. Fall behoben ist, sehen wir ja, ob die Liste dann zuverlässig erscheint.

Mache ich auch in #1537.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/pull/306
