### ISSUE TITLE
Display tags on stories

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#154]
Display tags on stories.

**Comment by literarymachine** [comment]
We should indeed include the tags. As I indicated in the Google Doc though, I believe these should not be free tags but categories from controlled vocabularies such as the ISCED.

**Comment by trugwaldsaenger** [comment]
I have defined another set of cathegories, which might be used to describe different activities (projects, services & experts) in the field of OER: http://etherpad.lobid.org/p/oertags

**Comment by trugwaldsaenger** [comment]
@literarymachine: At the moment it seems as if it is not possible to add tags to stories. Reopening this issue, so that we can add this functionality soon. I guess we can start with the normal tag field, as is provided with the other data types as well.

**Comment by acka47** [comment]
The `keywords` property is already in the current JSON schema, see https://github.com/hbz/oerworldmap/blob/2de099e62ebcd0c5d970e9a3e6dd0fbaa92ece6e/public/json/schema.json#L161-L166. We just need to add it to https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Article/edit.mustache then as well as to https://github.com/hbz/oerworldmap/blob/master/conf/labels.properties and to https://github.com/hbz/oerworldmap/blob/master/conf/descriptions.properties. Is this correct, @literarymachine? (I am not quite sure as I have been away for some time. but will be ready to implement it.)

**Comment by literarymachine** [comment]
> Is this correct, @literarymachine?

Yep.
