### ISSUE TITLE
Provide SKOS representation for Persons, Services, Publications, Organizations & Projects

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1541]
green marked fields should be transferred to SKOS

https://docs.google.com/document/d/1vH4odAccnQhKdg-ra4_GHEt4hdBADLC7eZNTHpst92k/edit#

**Comment by literarymachine** [comment]
@acka47 see https://github.com/hbz/oerworldmap-ui/blob/1545-SecondLevelNavigation/src/json/ for the SKOS versions.

**Comment by acka47** [comment]
+1
