### ISSUE TITLE
Include second level categories in input template

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1543]
...so that we can start generating content.

**Comment by literarymachine** [comment]
This is done on the schema level, from which the templates are generated by the UI.

**Comment by literarymachine** [comment]
On beta, see (and edit) e.g. these [examples](https://beta.oerworldmap.org/resource/?q=_exists_:about.additionalType.@id). Currently, the second level categories are displayed below the mini map. @formimkontext is that where they belong?

**Comment by acka47** [comment]
+1

**Comment by formimkontext** [comment]
> Currently, the second level categories are displayed below the mini map. @formimkontext is that where they belong?

One idea was, to replace the main type by the sub level category in the description aove the mini map in the header. The icon would still show the belonging to the main type.

**Comment by trugwaldsaenger** [comment]
The field is there - but there are no auto-suggestions. Also it seemingly does not accept my free-text input, so I faild to put in any second level categories. @literarymachine is it a bug or am I doing something wrong?

**Comment by acka47** [comment]
It works for me. Clicking into the field, the list of concepts to choose from shows up. By typing I can filter the list. Which resource do you have problems with?

**Comment by karindr** [comment]
Works for me too like Adrian said.

**Comment by karindr** [comment]
The problem was using firefox, it works for @trugwaldsaenger on chrome too.

**Comment by karindr** [comment]
It would be better to show more of the levels to choose from especially for organisations. Please make the window for the list longer.

**Comment by literarymachine** [comment]
> The problem was using firefox, it works for @trugwaldsaenger on chrome too.

@dobladov can you take a look?

**Comment by trugwaldsaenger** [comment]
@literarymachine @dobladov: I still have problems with this. Today it is neither working with Chrome nor with Firefox for me... I`m reopening the issue.

**Comment by literarymachine** [comment]
Can you post a screenshot? Because it is working fine here:

![image](https://user-images.githubusercontent.com/149825/40911594-82737044-67ef-11e8-9e28-cd747e7e270b.png)

**Comment by literarymachine** [comment]
Fine in Firefox, too:

![image](https://user-images.githubusercontent.com/149825/40911676-bf6447ee-67ef-11e8-8a0f-439495c6ea3f.png)

**Comment by trugwaldsaenger** [comment]
When clicking into the field, the field gets grey and a thick line appears under the field:

![grafik](https://user-images.githubusercontent.com/6639965/40911992-9e11a1e4-67f0-11e8-8a5d-aa118c618983.png)

When typing in a letter, no scrolldown menue appears.

**Comment by trugwaldsaenger** [comment]
I just checked this on my other laptop as well. The issue appears on both laptops when using Chrome as well as Firefox (60.0.1). Interesting, that it seems to appear with me only...

**Comment by trugwaldsaenger** [comment]
> Is this when editing, or when adding a new entry using https://oerworldmap.org/resource/?add=Service?

When editing!

**Comment by trugwaldsaenger** [comment]
It`s also happening when adding a new ressource...

**Comment by trugwaldsaenger** [comment]
Just created a new test-user, issue appears as well...

**Comment by literarymachine** [comment]
> Interesting, that it seems to appear with me only...

I just realized that you are using the German version, and I can recreate it when I switch to German, too:

![image](https://user-images.githubusercontent.com/149825/40913487-04b6c416-67f5-11e8-98aa-a620254a2814.png)

Can you switch to the English UI for now?

**Comment by literarymachine** [comment]
> I just realized that you are using the German version, and I can recreate it when I switch to German, too

This was broken by a fix for what @karindr reported in https://github.com/hbz/oerworldmap/issues/1534#issue-323153233:

> Wenn ich beginne Buchstaben einzugeben ist das angezeigte Ergebnis teilweise sehr merkwürdig. Gebe ich beispielsweise "art" ein, weil ich das Fach Kunst suche, erscheint "Arts and humanities" (OK) und "horticulture" (???).

"Horticulture" is "G**art**enbau" in German. The fix was to restrict the type ahead to filter only in the current language. Our new second level categories are not localized to German, though. So when your UI is set to German, no hits are ever found. I would argue that if we say we support German, we should support it everywhere and thus fix this issue by adding German (and Portuguese) labels to our second level categories. @acka47 what would you say?

**Comment by acka47** [comment]
> I would argue that if we say we support German, we should support it everywhere and thus fix this issue by adding German (and Portuguese) labels to our second level categories. @acka47, @karindr and @trugwaldsaenger what would you say?

+1

**Comment by trugwaldsaenger** [comment]
sounds reasonable to me - and should not be too much work... (I hope).

**Comment by karindr** [comment]
I translated what was new in Crowdin (for example "Service type"), but the terms für the categories itself (like "Repository". "Referatory") are not yet listed in Crowdin so I can't translate them.

@acka47 can you deploy the translations, please?
