### ISSUE TITLE
Include second level navigation to platform

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1545]

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/resource/:

![image](https://user-images.githubusercontent.com/149825/41966111-996e257a-79fe-11e8-9386-1f1ac96a5c2d.png)

Please also review the rest of the menu.

**Comment by trugwaldsaenger** [comment]
GO!

**Comment by literarymachine** [comment]
It would be good to have the descriptions for all entry types before launching this:

![image](https://user-images.githubusercontent.com/149825/41966442-6a17d630-79ff-11e8-9bf2-34638cff012a.png)

**Comment by literarymachine** [comment]
@literarymachine note to self: `Person` should not be included in the `Add` menu.

**Comment by literarymachine** [comment]
> “We invite you to share your OER story with the community and tell others about your OER activities!”
> “We invite you to share a link to your OER publication with the community!”
> “We invite you to share information on tools you use with the community!”

The "We invite you to" wording seems quite different from the rest, which is more of a definition, no?

>  we can think of using the subcategories here instead of definitions.

I think we should explain what we mean, not list even more terms.

**Comment by karindr** [comment]
> The "We invite you to" wording seems quite different from the rest, which is more of a definition, no?

As I wrote above: Yes, I know that the other 4 sentences are more like definitions, but I think it is not so difficult to decide with category to choose for the missing three so we could use more inviting sentences here.

**Comment by literarymachine** [comment]
> As I wrote above: Yes, I know that the other 4 sentences are more like definitions, but I think it is not so difficult to decide with category to choose for the missing three so we could use more inviting sentences here.

I don't understand this, but maybe @trugwaldsaenger does.

**Comment by literarymachine** [comment]
My quick take on the outstanding definitions, for @trugwaldsaenger to refine:

![image](https://user-images.githubusercontent.com/149825/41975973-1b565842-7a1c-11e8-99ac-916fbd1d2e4f.png)

**Comment by literarymachine** [comment]
![image](https://user-images.githubusercontent.com/149825/41976150-9e0e1ec8-7a1c-11e8-9de6-99f1d2213429.png)
