### ISSUE TITLE
Display of adresses in CJK-Scripts

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#155]
Detail view Organizations: For some organizations (University of Tsukuba, Lektorium LLC) the adress is displayed in Cyrillic/Japanese script. This is pretty cool (if done by our platform). Is it possible to show a „translation“? 
http://oerworldmap-dev.graphthinking.com/resource/urn:uuid:46f9dbb0-fe49-11e4-9612-989096a6beda

**Comment by literarymachine** [comment]
We will have to discuss this in more detail. The data you are referring to is that of the OEC members, the addresses stem from reverse lookups to the [nominatim API](http://wiki.openstreetmap.org/wiki/Nominatim), data is returned using the default language.

**Comment by philboeselager** [comment]
@trugwaldsaenger It looks like this is already implemented, see the location of the [China Education and Research Network](https://oerworldmap.org/resource/?q=China#urn:uuid:7068fa00-77eb-11e5-9f9f-c48e8ff4ea31). Can we close this issue?
