### ISSUE TITLE
For German, labels are the same as descriptions

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1551]
See e.g. https://oerworldmap.org/resource/urn%3Auuid%3Ae08975fe-acc0-4733-8496-2cfc034a120a

See also the labels file that does not has labels in it but descriptions: https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/labels_de.json 

What happened?

**Comment by acka47** [comment]
Something when re-setting up CrowdIn. This is the commit from 20 days ago (!) that messed it up https://github.com/hbz/oerworldmap-ui/commit/11e10671dc08c5ec31f2eac038942bb4de5c3efe#diff-18b0fa8bb7816dc63c44899012134d3c

I fixed the labels in #317. As @literarymachine is on holidays (and I think @philboeselager as well), is there anybody else who can deploy this?

**Comment by karindr** [comment]
@literarymachine can you deploy this please?

**Comment by literarymachine** [comment]
> @literarymachine can you deploy this please?

I merged and deployed https://github.com/hbz/oerworldmap-ui/pull/317 but to me it seems that the issue persist. @acka47 can you take a look. I am out of office this week for a conference and will postpone any further deployments until next week.

**Comment by literarymachine** [comment]
It looks to me like not all labels have been fixed, e.g.

https://github.com/hbz/oerworldmap-ui/pull/317/files#diff-18b0fa8bb7816dc63c44899012134d3cL39

Or is it correct like this, @acka47?

**Comment by acka47** [comment]
This whole CrowdIn migration to another repo sucked (not least because of I made several msitakes during the migration). Opened another PR at https://github.com/hbz/oerworldmap-ui/pull/323. It should be good after merging that one.

**Comment by literarymachine** [comment]
Fixed in hbz/oerworldmap-ui#323
