### ISSUE TITLE
Make description fields larger in input templates

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1553]
No description fits in the new tiny field. (Yes I know that I can enlarge it manually, but it is to small for 90 % of all descriptions entered, so please enlage it by default.)

**Comment by karindr** [comment]
Could the text in this field in the template be displayed with a bigger line spacing? This would be helpful too.

**Comment by literarymachine** [comment]
@dobladov implemented a whole new Markdown input, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:3a8dfbfa-1b1a-4af8-9419-2b7643dbed34!

**Comment by dobladov** [comment]
> No description fits in the new tiny field. (Yes I know that I can enlarge it manually, but it is to small for 90 % of all descriptions entered, so please enlage it by default.)

The size of the fields is now dynamic to the content on the initial load and they will enlarge themselves with new content.
![peek 2018-06-13 13-11](https://user-images.githubusercontent.com/1938043/41347922-62b206f8-6f0b-11e8-8fdb-a818e8662f8a.gif)

> Could the text in this field in the template be displayed with a bigger line spacing? This would be helpful too.

The line height is bigger now.
![screenshot from 2018-06-13 12-22-47](https://user-images.githubusercontent.com/1938043/41348152-246b6578-6f0c-11e8-9931-a4118609ead2.png)

The editor has a full screen view and preview of the content to make easier to edit big texts.
![full](https://user-images.githubusercontent.com/1938043/41348060-d4e20372-6f0b-11e8-9258-56540430f210.png)

**Comment by karindr** [comment]
Wow, looks promising!

**Comment by karindr** [comment]
It works very well. 

There is only one thing I don't know if you are able to change. When you enter return only once at the end of a line you want to stand alone it looks pretty nice in the previews (new line after the return). But in the saved version on the map there is no linebreak because marup requires two returns.

https://beta.oerworldmap.org/resource/urn:uuid:54f5229e-ad0e-4ca1-be42-a15feb306e7d#edit

To be clear, I don't want to change the behavior of displaying markup on the map. But I am asking myself if it is possible to achieve the preview to act the same. If you have no influence on this it is no problem, the new markdown input is great anyway.

**Comment by trugwaldsaenger** [comment]
@dobladov, many thanks, very cool :-)

**Comment by trugwaldsaenger** [comment]
I found just one tiny issue: If you create a list using bullet points, the preview in the fulltext mode will not show the bullets. In the final display it is OK.
