### ISSUE TITLE
It should be "Logo" instead of "Image" in the tools template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1556]

**Comment by acka47** [comment]
This has to be adjusted in the labels.json file in the oerworldmap-ui repo, see https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/labels.json#L172 Do you want to do this?

**Comment by karindr** [comment]
changed it in a branch and made a pull request.

**Comment by karindr** [comment]
done
