### ISSUE TITLE
Adding subjects from the third and forth level is not possible ...

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1558]
... because they are not shown in the list to choose from and can#T be accesed by entering the first characters. Try "chemistry".

**Comment by literarymachine** [comment]
![image](https://user-images.githubusercontent.com/149825/40909035-d407245c-67e8-11e8-8706-854cb8a7a711.png)

**Comment by literarymachine** [comment]
Works for me, both in German and English:

![image](https://user-images.githubusercontent.com/149825/40909084-ff9118b2-67e8-11e8-87d2-9a2e1c7c6f78.png)

**Comment by karindr** [comment]
![image](https://user-images.githubusercontent.com/18674205/40910198-ce1a78f2-67eb-11e8-9875-2945335f6b74.png)

**Comment by literarymachine** [comment]
Still not working e.g. here: https://oerworldmap.org/resource/urn:uuid:b1158d65-4392-4bc3-8448-6a27b2416755#edit

![image](https://user-images.githubusercontent.com/149825/40910856-861b5b1e-67ed-11e8-8ab0-805fb813daec.png)

**Comment by literarymachine** [comment]
Deployed to production: 
![image](https://user-images.githubusercontent.com/149825/40971092-c943f23c-68bc-11e8-8f95-52960894ad40.png)
