### ISSUE TITLE
Impossible to add educational sector to h5p tool

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1559]
Just tried to add an educational sector ("cross-sector") to H5P:

https://oerworldmap.org/resource/urn:uuid:7a4886c1-b219-4b8d-a242-b869dcbcb7e5?

It did not work and I received the error message "should NOT have additional properties"

**Comment by literarymachine** [comment]
Fixed and deployed to production, see https://oerworldmap.org/resource/urn:uuid:7a4886c1-b219-4b8d-a242-b869dcbcb7e5
