### ISSUE TITLE
Seemless zooming motion

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#156]
via @acka47: Clicking on a country from the worldmap or chossing an organization
while in country mode results in the opening of a new page with a
zooming motion onto the country/organization. Is it possible to somehow
have a more seemless navigation so that there is no recognizable loading
of a new page but the new page is loaded with a zooming motion?

**Comment by literarymachine** [comment]
FYI: We are currently not navigating using AJAX yet as this is a [non-functional requirement](http://en.wikipedia.org/wiki/Non-functional_requirement):

> Broadly, functional requirements define what a system is supposed to do and non-functional requirements define how a system is supposed to be.
>
> -- http://en.wikipedia.org/wiki/Non-functional_requirement

This is not to say that it is not important, but given the fact that our [Website is our API](http://www.jenitennison.com/2009/02/01/your-website-is-your-api-quick-wins-for-government-data.html), it seemed more important to properly support full page requests first:

    $ curl -H "Accept: application/json" http://oerworldmap-dev.graphthiing.com/resource/

Also, our progressively enhancing "Hijax" approach works best when we

> - Plan for Ajax from the start.
> - Implement Ajax at the end.
>
> -- http://domscripting.com/blog/display/41

**Comment by acka47** [comment]
The actual problem I had is solved. Before the three column layout, when loading a new page there where some distracting movements as – for a short moment – one part was loaded first over the whole display and then the other part was added changing the distribution on the display. This doesn't happen anymore. Closing.
