### ISSUE TITLE
Second Level Categories: Subtype "other" is missing

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1560]
Within the current second level categories the subtype "other" is missing. 

I assume that there is an underlying missunderstanding. The specification includes both "other content sources" and "other". "Other Content Sources" are websites, which include some OER, but cannot be characterized as repositories. "Other" could be anything, wich is not covered by the named categories.

I agree that the wording might be misleading. Instead of "other content source" we could use simply "content source" as well.

**Comment by karindr** [comment]
I would prefer "content source".

**Comment by acka47** [comment]
Do I get it correctly that you understand "content source" as "A source providing content for learning/teaching purposes"? Then this might make sense but I doubt that people will get it.

You could also understand it like this: All of those are publications, i.e. "content sources" so "other publications" equal "other content source"...

**Comment by karindr** [comment]
"other" is there now but "content source" is gone. That is not like it should be.

**Comment by literarymachine** [comment]
> "other" is there now but "content source" is gone. That is not like it should be.

@acka47 told you so ;)
