### ISSUE TITLE
Irritating Template Layout

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1563]
https://oerworldmap.org/resource/urn:uuid:3f11cdbd-a74a-4aa4-83b3-b4148bfdbe82

![grafik](https://user-images.githubusercontent.com/6639965/40967769-3a614d38-68b4-11e8-9bb6-86d5b7987756.png)

- Input fields seem to be missing for "grant"
- "funded by" appears twice, once with input field, once without
- "add funded by" appears twice

**Comment by literarymachine** [comment]
I agree this is irritating. Will fix this, but just FYI that this is correctly following our data model but not very clear in the UI:

> Input fields seem to be missing for "grant"

No, `Grant` is a complex field, it includes the `Budget` and `Funded by`.

> "funded by" appears twice, once with input field, once without

Yes, a `Project` is `funded by` a `Grant` which is `funded by` some `Organization`.

> "add funded by" appears twice

See above, you can theoretically add a second `Grant`, and a `Grant` can currently be funded by multiple `Organization`. I'll have to think a little bit about which fields to hide etc.

**Comment by karindr** [comment]
It would help to make "grant" a heading1 and "budget" and "funded by" a heading2.

**Comment by karindr** [comment]
This is the same with "place" as heading1 and "country", "region" and "address" a heading2 .
