### ISSUE TITLE
Link to markdown-syntax is missing in description and comment fields

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1565]
It seems as if this helpful link was lost during refactoring. I would strongly argue to include it again.

**Comment by literarymachine** [comment]
You are right, we missed to port this to the new UI. The image is available here: https://github.com/dcurtis/markdown-mark

**Comment by literarymachine** [comment]
It would probably make sense to solve this along with #1553.

**Comment by literarymachine** [comment]
The new Markdown input includes a help button:

![image](https://user-images.githubusercontent.com/149825/41348099-fc46797a-6f0b-11e8-9844-9fc46d663c5f.png)

But since it also exposes buttons for the most important Markdown features, help hopefully be needed that often any longer.

**Comment by karindr** [comment]
+1
