### ISSUE TITLE
Add award field to personal profile

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1566]
At the moment we can't give awards to people because there is no field for it.

Do we as administrators want to change the personal profiles of award winners and add the bade there?

**Comment by trugwaldsaenger** [comment]
> At the moment we can't give awards to people because there is no field for it.
Good you mention this - I was not aware of it! @literarymachine, could you add the field for persons as well?

> Do we as administrators want to change the personal profiles of award winners and add the bade there?
I see two groups: persons which are already on the map and those who don`t. The first group we can tell them that we plan to add the badge, when we ask them to register. For the second group we can add the badge and tell them that we did so by mail - I guess nobody will complain.
