### ISSUE TITLE
Enhance preview in twitter  

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1567]
I tweet an event overview every month, now it looks like below, the link to the view is below too. Why is the map in the picture empty? Is it possible to get rid of the words and numbers before entries?
https://oerworldmap.org/resource/?q=about.startDate%3A%5B2018-06-02%20TO%202018-06-30%5D&filter.about.%40type=Event
![image](https://user-images.githubusercontent.com/18674205/41022422-d13dd586-6969-11e8-85e4-fe86a0b61128.png)

**Comment by literarymachine** [comment]
Could you let us know what exactly was much better?

**Comment by karindr** [comment]
The map was not empty! The differnent greens of the countries were visible, there also have been dots on the map.

**Comment by literarymachine** [comment]
> The map was not empty! The differnent greens of the countries were visible, there also have been dots on the map.

Ok. @j0hj0h can you recall how this worked? As far as I remember, we didn't add any preview images explicitly. Did this just work with Openlayers maps?

**Comment by j0hj0h** [comment]
No idea how this worked. @karindr can you recall when it stopped working? And maybe when it started to work?

**Comment by j0hj0h** [comment]
@karindr do you remember if it was showing the UI components (e.g. header, filter section) as well? Maybe Twitter showed a screenshot generated on their server until we told them to to something else with the new meta data in the header ...

**Comment by karindr** [comment]
Hard to tell when something changed, because if it works like expected you don't pay attention. It worked with the old UI that is for sure. But I think it changed later than the official relaunch of the UI because I am pretty shure that I would have deleted this tweet, because the map is empty:
https://twitter.com/oerworldmap_de/status/986874254527475712
![image](https://user-images.githubusercontent.com/18674205/41088347-94b3826a-6a3f-11e8-876c-699de1890802.png)
So the change has to be later than this. And I am pretty shure that this tweet wasn't like this on the 2.05.:
https://twitter.com/oerworldmap_de/status/991613460961251328
I include screenshots because it looks like twitter is changing the shown version of the World Map also in older tweets. Because of this I think ther is no such thing as generated screenshot on their server.
![image](https://user-images.githubusercontent.com/18674205/41088289-6eaaf274-6a3f-11e8-8127-2f80d7990a11.png)

Maybe there was a change at twitter? I don't know. Sometimes it is not very clear if they show the text of a link or a picture of the website. But in the example above I refer to the regions of Germany so the have to have been visible.

I think there has always been only the map and not the lists beside the map, but i am not 100 % sure, only 80 %. I dont remember seeing the header and the filter-section, too.

**Comment by literarymachine** [comment]
I'll try to reconstruct the old twitter preview by running the old version of the map locally.

**Comment by literarymachine** [comment]
Ok, we rolled out the old UI to http://oerworldmap.graphthinking.com/resource/

Anything we tweet from there has no proper preview at all, e.g.

https://twitter.com/graphthinking/status/1004667563631104001
https://twitter.com/graphthinking/status/1004667179353165824

@karindr are you absolutely sure that the tweets you mention above actually included a preview back then? Or maybe just a URL? Because @dobladov, @j0hj0h and I all cannot explain how a map preview could have ended up in the twitter preview back then...

**Comment by literarymachine** [comment]
> I did not make screenshot, but I am pretty shure that I had a peview in this case:
> https://twitter.com/oerworldmap_de/status/986874254527475712
> This was allready with the new UI.

There cannot have been a preview with pins and colors and all of that at that point then!

> It is possible that we had mostly only URLs as text and no previews before. Only an URL is better than > an empty map! I could live with this too and add pictures if I need them.

Ok. We are actually by now very sure that such previews with the colors and points have not existed, neither in the old nor the new UI. We can roll back the empty map images and keep discussing what @j0hj0h summarized in https://github.com/hbz/oerworldmap/issues/962#issuecomment-387408067.

**Comment by dobladov** [comment]
>  Is it possible to get rid of the words and numbers before entries?

In the case of the one showing "about.startDate:[2018-05-02 TO 2018-05-31]", It's because in case of having a search we show the searched term on the title, I agree that we need to filter or not show this cases or return only the number of results found.

**Comment by karindr** [comment]
I am not sure with the dots but no green countries, really? But anyway better no peview than empty maps, I can live with this on twitter. As you said facebook reacts different.

**Comment by literarymachine** [comment]
> I am not sure with the dots but no green countries, really?

There cannot have been map previews with real data (dots and colors) in the old and in the new version. We simply do not expose the map in a format that makes this possible. We now link to an image in the mapbox static API, but it is not possible to easily put our data in there.

> As you said facebook reacts different.

Where have I said that?

**Comment by literarymachine** [comment]
> The map was not empty! The differnent greens of the countries were visible, there also have been dots on the map.

I think you are confusing this with screenshots you made and attached yourself. See e.g.

https://twitter.com/oerworldmap/status/989085791606525954

**Comment by literarymachine** [comment]
> I think there has always been only the map and not the lists beside the map, but i am not 100 % sure, only 80 %. I dont remember seeing the header and the filter-section, too.

Also compare

https://twitter.com/oerworldmap/status/989085791606525954
https://twitter.com/oerworldmap/status/986881379442085888
https://twitter.com/oerworldmap/status/971684974670876672

for this. There are probably more. If the list is shown or not depends on your view when you make a screenshot. Also, you can actually overwrite the default preview image by uploading a custom image. See e.g. https://twitter.com/graphthinking/status/1004694229216563200 vs. https://twitter.com/graphthinking/status/1004693715313709058

I think we should close this issue and move the discussion to #962 where @j0hj0h summarized what was discussed at the last team meeting.

**Comment by trugwaldsaenger** [comment]
> I think we should close this issue and move the discussion to #962 where @j0hj0h summarized what was discussed at the last team meeting.
