### ISSUE TITLE
Clear layout of search field

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#157]
via @acka47: The search field is pre-filled with "about.@type:Article" which is quite confusing and the button is labeled "submit" which leads to the impression that you could start a submission process for a new entry via the search field. Either change the text in the search field to "search" or rename the search button to "search".

**Comment by literarymachine** [comment]
`about.@type:Article` is a search filter (restricting to Articles only), these will be displayed outside of the search box:
![oer_demo_map-teaser_70-30](https://cloud.githubusercontent.com/assets/149825/7913261/9d9b75da-086e-11e5-9741-9bd6d308d15e.png)
(FYI, "submit" is the default label of an HTML form submit button. Will add custom label).
