### ISSUE TITLE
Search with different languages

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#158]
via @acka47 Search should work with different languages, e.g. a search for "Shinjuku" (http://oerworldmap-dev.graphthinking.com/resource/?q=Shinjuku) should give
http://oerworldmap-dev.graphthinking.com/resource/urn:uuid:4bdb5532-fe49-11e4-9612-989096a6beda
as a result.

**Comment by literarymachine** [comment]
If we had the data in different languages, the search would already work like that. Also see #155.

**Comment by philboeselager** [comment]
@trugwaldsaenger Is this issue done? See [this search result for Shinjuku]( https://oerworldmap.org/resource/?q=Shinjuku#urn:uuid:706b8db0-77eb-11e5-9f9f-c48e8ff4ea31).

**Comment by acka47** [comment]
Closing.
