### ISSUE TITLE
Display "More" every time the filter section is displayed

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1582]
There are some situations where it is not possible to expand the filtersection. This is bad for example in connection to the Open Education Awards. 

First and most important, when you enter the map you are not able to choose the awards because the filter button for awards is not shown and you are not able to make the filter button visible by clicking on "More", becaue "More" is missing. 

The second situation is  when you searched for something and got a list with no entries, "More" is also not shown.

A simple solution would be to display "More" every time the filter section is displayed.

**Comment by dobladov** [comment]
> First and most important, when you enter the map you are not able to choose the awards because the filter button for awards is not shown and you are not able to make the filter button visible by clicking on "More", becaue "More" is missing.

You can always show the list and subfilters like this without having to filter before.

![menu](https://user-images.githubusercontent.com/1938043/41711650-e3cd7c98-7548-11e8-907b-ba14fa4981c3.gif)

**Comment by karindr** [comment]
Yes, but are you sure every visitor will come to this conclusion? Is there any reason not to show "More" every time?

**Comment by literarymachine** [comment]
> Yes, but are you sure every visitor will come to this conclusion?

Are you sure they won't?

>  Is there any reason not to show "More" every time?

Looking at the UI, simply floating the "more" over the transparent background won't work. So we'd need a draft from @formimkontext if we want to change things.
