### ISSUE TITLE
Why are the images no longer shown in this story?

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1586]
https://oerworldmap.org/resource/urn%3Auuid%3Ac466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0#view

Is this a problem with http/https of the site we link to? What can we do to solve this?

**Comment by literarymachine** [comment]
> Is this a problem with http/https of the site we link to? What can we do to solve this?

Try opening the image directly: https://education.okfn.org/files/2016/09/oer1.jpg

It is a misconfiguration on their side, we cant do anything about that. Except upload the image somewhere else and use that copy in the Story then.

**Comment by dobladov** [comment]
They fixed the links to the images and now they work properly, closing the issue.

---

![image](https://user-images.githubusercontent.com/1938043/43409021-04eaeaca-9423-11e8-9ed6-13f256f604f7.png)
