### ISSUE TITLE
Existing tags are not suggested at the moment

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1587]
When I enter "oer" as tag the template asks me if I want to create "oer" but the tag already exists.
![image](https://user-images.githubusercontent.com/18674205/41898782-227da220-792b-11e8-978b-efb9de82f64a.png)

**Comment by literarymachine** [comment]
Confirmed. Seems to be an issue with the Elasticsearch update.

**Comment by literarymachine** [comment]
Fixed an deployed to production: 
![image](https://user-images.githubusercontent.com/149825/41899981-f1b72afa-792d-11e8-8203-0284f2aad719.png)
