### ISSUE TITLE
Center mini-map to country

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1589]
Didn't we find a way to center the mini-map to the country of an entry although there are no coordinates?
For example:
![image](https://user-images.githubusercontent.com/18674205/41959101-54b2a904-79ec-11e8-9d3c-fdbc472dd523.png)

**Comment by literarymachine** [comment]
@karindr please always provide a link along with the screenshot.

**Comment by karindr** [comment]
https://oerworldmap.org/resource/urn%3Auuid%3A639d8602-a4de-435d-b84f-65d696b5ce05

**Comment by karindr** [comment]
It does not work here:
https://oerworldmap.org/resource/urn%3Auuid%3A57e941e3-1926-46c2-8265-80bac9205a27
![image](https://user-images.githubusercontent.com/18674205/42018115-5f2e19ca-7ab1-11e8-82cd-ebfbdb5943c5.png)

**Comment by literarymachine** [comment]
@dobladov this is a similar, but different issue. The entry in https://github.com/hbz/oerworldmap/issues/1589#issuecomment-400932556 has a pin, so it should center on that (not on Australia).
