### ISSUE TITLE
The hovering country lable shows misleading information about the country champions

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1590]
It says the country champion is available also in cases it is not available, see for example Brazil:
![image](https://user-images.githubusercontent.com/18674205/41968895-0e1e4a38-7a06-11e8-9c11-172a0cce1170.png)
https://oerworldmap.org/resource/?map=0.00000,42.28481,1

**Comment by literarymachine** [comment]
Tel is the country champion for Brazil:

![image](https://user-images.githubusercontent.com/149825/41969990-8372822e-7a09-11e8-9066-a8919a81eb22.png)

https://oerworldmap.org/country/br

**Comment by dobladov** [comment]
With the current behaviour, we say _Country champion available_ if there is at least one country champion and nothing if there is none, should we change this? @karindr 

![image](https://user-images.githubusercontent.com/1938043/43536247-6a123aee-95bc-11e8-8ce7-dc0fbcff7ab7.png)

![image](https://user-images.githubusercontent.com/1938043/43536259-769d01cc-95bc-11e8-9e09-326460b99525.png)

**Comment by karindr** [comment]
I suggest:
"Country Champion" if there is at least one Country Champion
"No Country Champion yet" if there is no Country Champion
