### ISSUE TITLE
Borders of regions and countries are not the same, different colour is shining through

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1594]
For example:
![image](https://user-images.githubusercontent.com/18674205/42155594-1e848220-7de9-11e8-9809-995e7d4fc0ed.png)

**Comment by trugwaldsaenger** [comment]
Yes, I can reproduce this by zooming in a bit on the country view:
https://oerworldmap.org/country/de

Looks like a small bug to me. I guess @literarymachine or @j0hj0h should have a look at it after their holidays.

**Comment by dobladov** [comment]
This is because the layer for the region is more detailed than the layer for the global view of countries, uploading a more detailed layer is possible, but it will increase severely the processing required for rendering the map.

**Comment by programmieraffe** [comment]
Seems to be okay for me, small borders still not 100% clear - but does not matter for me
