### ISSUE TITLE
Sort Award`s in pull down menue

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1598]
@gandalfar noticed, that the pull down menue of the awards is unordered.

It would be great if we could chance this soon. I see two alternatives:

1) "alphabetical order": first the two OERde awards are shown, than the Open Education Awards follow, sorted according to their year, the most recent shown on top (inverse chronological order, referring to the number of the year included in the title). 

2) "inverse chronological order": All awards are shown in an inverse chronological way:
- Open Education Awards 2018
- OERde Award 2017
- Open Education Award 2017
- OERde Award 2016
- Open Education Award 2016
- ...
I guess that this would require exact dates of the awards, which we currently do not have  in our data-scheme. So if alternative 1 is easier to solve, I`m happy to proceed with this!

**Comment by trugwaldsaenger** [comment]
@acka47 can you help with this?

**Comment by acka47** [comment]
I am not the right person for this. I looked around https://github.com/hbz/oerworldmap-ui but could not find the place where to adjust the code, let alone how to adjust. As I also could not stick to the whole testing procedure etc. it is best to wait until @literarymachine and @dobladov are back from holidays.

**Comment by literarymachine** [comment]
> So if alternative 1 is easier to solve, I`m happy to proceed with this!

@dobladov can you add `sort` prop to `DropdownFilter`?
