### ISSUE TITLE
Visitor can't edit entries

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1599]
He wrotes: 
"I used a Mac 10.13.5 with Firefox 61.01.
I managed to login and change password using Chrome.
Still, I can't edit."
@literarymachine I send an email to you with the contact info.

**Comment by literarymachine** [comment]
> Still, I can't edit

What does that mean precisely? Is the edit button not showing? Is saving not working? All entries or only a particular one?

**Comment by literarymachine** [comment]
> @literarymachine I send an email to you with the contact info.

Please supply all necessary information here.

**Comment by karindr** [comment]
@trugwaldsaenger is going to ask the questions to the visitor.

**Comment by literarymachine** [comment]
@trugwaldsaenger any update on this? If not, please close this issue.

**Comment by dobladov** [comment]
Checked on safari and edition works, we fixed some bugs related to safari recently, closing.
