### ISSUE TITLE
Get a list of OER services

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#16]
As a learner or teacher I want generate a filtered list of OER discovery services.

**Comment by acka47** [comment]
Acceptance criteria in this case are primarily the kinds of filters one can employ:
- [ ] by subject
- [ ] by grade
- [ ] by country 
- [ ] by language

**Comment by literarymachine** [comment]
This is an epic that should be split into (at least) four user stories (one for each filter).

**Comment by literarymachine** [comment]
Epic has been split into #40, #41, #42 and #43.
