### ISSUE TITLE
highlight search term

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#160]
via @acka47: When I search for a term this term should be highlighted in the names/descriptions of resources in the result list, e.g. http://oerworldmap-dev.graphthinking.com/resource/?q=tools. (This would also make clear the relevance ranking used when searching with multiple terms, e.g. http://oerworldmap-dev.graphthinking.com/resource/?q=tools+platform.)

**Comment by buschfeld** [comment]
Included in the design proposal #140
![oer_demo_map-teaser_70-30](https://cloud.githubusercontent.com/assets/10743356/7960735/0afb679e-0a03-11e5-828f-049c59382918.png)

**Comment by buschfeld** [comment]
Please see enclosed screen layout study showing

proposals of filter UI applied to the map view
proposals of filter UI applied to the result list
statistic data and cross-links icons in tooltip layers on map
variations of how to avoid pin clusters by adding numbers in large-scaled map views
I need to add that design draft includes the visualization of alternatives, added for internal discussions among the developing team. These alternatives include

position and color of tooltip areas
typography and style of cluster-pins
position and style of icons (taken from the public source fontawesome library)
color scheme of checkbox and close icon-areas
last, not least – the two already known color systems: a) orange = hovered/currently presented + b) dark blue = pure/not selected display

Note: This layout draft also applies to following issues:
#163, #144, #140, #40, #41, #42, #43, #34, #31

![oer_landingpage_basics_master_10 06 2015](https://cloud.githubusercontent.com/assets/10743356/8102380/e7d6b37c-101f-11e5-811b-7e19a87b86f2.png)
