### ISSUE TITLE
Wrong administrative level for Regions layer

### ISSUE THREAD

**Issue by dobladov** [hbz/oerworldmap#1614]
Using [Natural Earth](https://www.naturalearthdata.com/), some countries are divided by the **sub** administrative region instead of the autonomic community, this happens for example with Spain.

A possible solution for this, is using [gadm](https://gadm.org) as our source for Regions.

![image](https://user-images.githubusercontent.com/1938043/43576222-1aef460e-9649-11e8-9990-64f65f5ab3c5.png)

![image](https://user-images.githubusercontent.com/1938043/43576243-2a65897c-9649-11e8-9513-d2280464cad5.png)

**Comment by literarymachine** [comment]
For now, the labels of the Spanish regions will be fixed by https://github.com/hbz/oerworldmap-ui/pull/368.

**Comment by dobladov** [comment]
Fixed in: https://github.com/hbz/oerworldmap-ui/pull/368
