### ISSUE TITLE
Review name and values of the field "coverage"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1619]
### A. name of the field
Right now, the field **"coverage"** is included in the policy template:
![grafik](https://user-images.githubusercontent.com/6639965/43636925-c12aabc4-9713-11e8-9844-db1d9168497d.png)

This field was named **"jurisdiction"** in the former OER Policy Registry
![grafik](https://user-images.githubusercontent.com/6639965/43637097-3bd8ec96-9714-11e8-95a8-9fe7cb30efc4.png)

Within their still unpublished "Guidelines on the Development of Open Educational Resources (OER) Policies" Dominic Orr and Ben Jansen use the term **"scale"**

Finally, within their Report "[Going Open Policy Recommendations on Open Education in Europe](https://oerworldmap.org/resource/urn%3Auuid%3A6b49470c-bdd3-4b75-aad7-415b05f31acc?)" the Joint Research Council (JRC) proposes the use of the term **"level**:

![grafik](https://user-images.githubusercontent.com/6639965/43637764-83e371da-9716-11e8-9d1c-465d33a30402.png)
 
I personally would argue that "level" is the term, which can be understood most easily since it it the most "speaking term". Also it relates to the established term "[multi-level governance](https://en.wikipedia.org/wiki/Multi-level_governance)", which seems to fit here well. 

### B. Values
Currently following values are included

- Global
- National
- State
- Institution - Primary
- Institution- Secondary
- Institution - Tertiary
- System

Instead I would propose following values:
- Multi-national
- National
- State
- Local
- Multi-Institutional
- Institution
- Department

**"Multi-national"** seems more comprehensive to me than "global" since it includes also policies, which refer not to all countries, but to several countries.

**Local** (German: "kommunale ebene") should be added, since we know examples of cities becomming active in the field of OER.

**Multi-Institutional"**: I`m not shure about this, but it seems reasonable to me that programs can be started by a consortium of institutions (e.g. the OEC). 

**"Institution"**: seems to sufficient, if we also add the [field "educational sector" to the policy template](https://github.com/hbz/oerworldmap/issues/1620):
![grafik](https://user-images.githubusercontent.com/6639965/43638524-87507f2c-9719-11e8-8237-a8405577c609.png)

In order to keep the same granularity, additionally tags have to be used to distinguish between "primary" and "secondary" school activity.

**Department**: I`m not sure about this either. But sometimes a policy refers only to a single service, common examples are policies for OER repositories. 

**System**: Though I like the term "system" very much, I`m not sure, what it means in this context.  Is there a definition for this?

**Comment by trugwaldsaenger** [comment]
**Summary:** 
I propose to name the field "level" and use following values:
-     Multi-national
-     National
-     State
-     Local
-     Multi-Institutional
-     Institution
-     Department

**Comment by karindr** [comment]
Connected to this concerning the multilingual approach: The terms "coverage", "status" and so on appeared in crowdin, but not the levels to decide from. (Can copy this in a new issue if you want.)

**Comment by trugwaldsaenger** [comment]
> For the initial import, I would keep the data as is.

Since we started refining the data already before the initial import we should consider to change this as well. I propose that we check the relevance while working with open refine...

**Comment by trugwaldsaenger** [comment]
Summary (updated):

The field "coverage" should be renamed into "level".

It should provide following values:

Multi-national
National
Multi-state
State
Multi-regional
Regional/Local
Multi-Institutional
Institutional
Multi-departmental
Departmental

Comment: Compared with the last version, which I discussed and verified with Fabio Nascimbeni, I added the values "multi-state", "mulit-regional" and "multi-departmental". It is clear that "multi-state" will be needed. Prominent example for this is the "Kultusminister Konferenz" in Germany. I also know that there are bilateral agreements regarding OER between some Canadian states.

**Comment by trugwaldsaenger** [comment]
@acka47: This is ready to proceed from my perpective. Could you please prepare the SKOS vocabulary, so that we can implement this on the site ASAP?

**Comment by trugwaldsaenger** [comment]
@acka47: Here comes the mapping:

Multi-national = Global
National = National
Multi-state = not included
State = State
Multi-regional = not included 
Regional/Local = not included
Multi-Institutional = not included
Institutional = Institution primary, Institution secondary, Institution tertiary

Currently 9 policies carry the value "system" we have to check these and see how to classify them with our new schema.
not included = system
Multi-departmental
Departmental

**Comment by trugwaldsaenger** [comment]
@acka47 Just a gentle reminder, that this issue is still waiting for you expertise... ;-)

**Comment by acka47** [comment]
I opened a PR for the SKOS scheme. how do we proceed? We should probably first adjust the frontend and then do the SPARQL updates, shouldn't we, @literarymachine ?

**Comment by literarymachine** [comment]
Sorry, just saw this now.

> I opened a PR for the SKOS scheme.

Do we really need a SKOS scheme here? We could just update the [`enum`](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L308) in the schema. 

> how do we proceed? We should probably first adjust the frontend and then do the SPARQL updates

The schema also needs to be adapted to point at the concept scheme, if we choose to use it.

**Comment by literarymachine** [comment]
@acka47 these are two necessary migrations if we stick with [updating the enum in the schema](https://github.com/hbz/oerworldmap/pull/1739/commits/95fa5d97ae39fe22c6e48bad519140e3a1a0a96b) instead of using a SKOS vocab:

- [ ] [Multi-national = Global](https://oerworldmap.org/sparql/update?delete=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%22Global%22&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%22Multi-national%22&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%22Global%22)
- [ ] [Institutional = Institution primary, Institution secondary, Institution tertiary](https://oerworldmap.org/sparql/update?delete=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%3Fcoverage&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%22Institutional%22&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%3Fcoverage+.+FILTER+regex%28%3Fcoverage%2C+%22Institution.*%22%29+)

> Currently 9 policies carry the value "system" we have to check these and see how to classify them with our new schema.

Once we update the allowed values, these nine policies should be checked soon. Keep in mind they cannot be saved when the value is `System` because this will violate the updated schema.

**Comment by acka47** [comment]
+1 for the SPARQL updates

**Comment by literarymachine** [comment]
Deployed to production

> Currently 9 policies carry the value "system" we have to check these and see how to classify them with > our new schema.

@trugwaldsaenger these should now be checked: https://oerworldmap.org/resource/?filter.about.spatialCoverage=System

**Comment by trugwaldsaenger** [comment]
Looks pretty good to me! Could you please also change the displayed name of the field into "level"?

**Comment by trugwaldsaenger** [comment]
> @trugwaldsaenger these should now be checked: https://oerworldmap.org/resource/?filter.about.spatialCoverage=System

@literarymachine: Done
