### ISSUE TITLE
Add value "inactive" to field "status"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1621]
The field "status" clearly refers to a kind of live-cycle, which is not complete without some kind of end...

**Comment by karindr** [comment]
Thinking of a kind of a life cycle I think something like "deactivated" or "no longer valid" would be clearer because a "proposed" policy is also kind of "inactive".

**Comment by trugwaldsaenger** [comment]
"deactivated" might fit - we should include some mother-tongue-speakers here...

**Comment by trugwaldsaenger** [comment]
I`m pretty sure we will need this soon and would propose that we add the value "deactivated", if possible before our first import of the data.
