### ISSUE TITLE
Include new field "influenced by"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1624]
There seems to be a trend to reuse policies between institutions.

**Example:** Institution A develops a policy for its OER repository and puts it under CC BY license. Institution B reuses the text with only minor modifications. 

To identify these cases, a field "influence by" should be added, which allows to link to a policy of another institution.

**Comment by literarymachine** [comment]
> To identify these cases, a field "influence by" should be added, which allows to link to a policy of another institution.

In schema.org, there is the property [`isBasedOn`](https://pending.schema.org/isBasedOn).
