### ISSUE TITLE
Include new field "triggered action"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1625]
One of the central advantages of using the OER World Map for the OER Policy Registry is, that it allows to link policies to the resulting activities. Ususally these will be programs or projects. In order to do so, a field "triggered action" should be included, which allows to link to one or several programmes or projects.

**Comment by trugwaldsaenger** [comment]
@acka47: Could you please have a look at this? The situation is that we need a solution for two different situations:
1. Policies should be connected to activities, like programs, projects and services
2. Policies should be related to other policies they are derived from or influenced by (#1624)
We still have not decided if we need two different fields for this, or if one field could be used for both use cases. I`m happy to start with one field and see how it works.

**Comment by trugwaldsaenger** [comment]
@acka47:Ping

**Comment by trugwaldsaenger** [comment]
We should implement the field for linking policies and programmes ASAP. Just recently I discussed this issue with Ben Janssen and he highlighted the importance of linking policies and the resulting activities. 

For me it would be OK to implement this first and think later if/how we could connect policies derived from each another. @acka47: Any proposals concerning which schema.org field we should start with?

**Comment by trugwaldsaenger** [comment]
This still seems to be one of the most important issues. I summarize:

1.     Policies should be connected to activities, like programs, projects and services
2.     Concerning the name of the field "related activity" might be even better than "triggered action"

@literarymachine: Do you need anything more from @acka47 to continue with this?

**Comment by literarymachine** [comment]
Since you asked @acka47 in https://github.com/hbz/oerworldmap/issues/1625#issuecomment-439303202 I was assuming that he would adjust the schema and open a pull request.

**Comment by literarymachine** [comment]
@acka47 see #1738

**Comment by acka47** [comment]
Sorry that I did not respond earlier. I could not find a fitting property in schema.org but `isBasedOn` is close enough for this purpose, I guess. 

I only have one question: Is it really necessary to also link services to a specific policy? Wouldn't projects  suffice? I will give my  for now but we should think about removing Services anyway.

**Comment by trugwaldsaenger** [comment]
> I only have one question: Is it really necessary to also link services to a specific policy? Wouldn't projects suffice? I will give my for now but we should think about removing Services anyway.

Yes it is! Policies can appear in very different forms. On the state label you are right that normally a policy will result in a programm. But especially on the institutional level there are examples of policies, which refer directly to a service, for example to a repository.

**Comment by literarymachine** [comment]
Deployed to production

> Concerning the name of the field "related activity" might be even better than "triggered action"

@trugwaldsaenger  the label of the field is now "based on", because a `Service` is not an action / activity and also because we use the same field to link policies as you suggested in https://github.com/hbz/oerworldmap/issues/1624#issuecomment-418710614.
