### ISSUE TITLE
Add filter options for result list

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#163]
via @acka47: Filtering options for the result list would be nice but we''ll add that anyway.

**Comment by buschfeld** [comment]
Please see enclosed screen layout study showing 
- proposals of filter UI applied to the map view
- proposals of filter UI applied to the result list
- statistic data and cross-links icons in tooltip layers on map
- variations of how to avoid pin clusters by adding numbers in large-scaled map views

I need to add that design draft includes the visualization of alternatives, added for internal discussions among the developing team. These alternatives include
- position and color of tooltip areas
- typography and style of cluster-pins
- position and style of icons (taken from the public source fontawesome library)
- color scheme of checkbox and close icon-areas
- last, not least – the two already known color systems: 
  a) orange = hovered/currently presented + b) dark blue = pure/not selected display

===========
Note: This layout draft also applies to following issues:
#160, #144, #140, #40-43, #34, #31

/Users/benbuschfeld/Desktop/OER_LandingPage_Basics_Master_10.06.2015.png

**Comment by buschfeld** [comment]
![oer_landingpage_basics_master_10 06 2015](https://cloud.githubusercontent.com/assets/10743356/8102297/46f4410e-101f-11e5-9165-a89416fb1ce0.png)

**Comment by buschfeld** [comment]
![oer_landingpage_basics_master_10 06 2015](https://cloud.githubusercontent.com/assets/10743356/8102356/bbc82a72-101f-11e5-8f1b-175e323586d8.png)

**Comment by philboeselager** [comment]
@buschfeld I like your proposed map filter in any detail! Looks great!
@literarymachine Do you agree to implement filtering using Elasticsearch facets?

**Comment by literarymachine** [comment]
> Do you agree to implement filtering using Elasticsearch facets?

"[Facets have been deprecated in favor of aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-facets-migrating-to-aggs.html)", which we actually already use e.g. for the heat map data (which is basically an aggregation by country code). So yes, I believe that is the way to go!

**Comment by literarymachine** [comment]
Added filters as drop-downs above the search box on https://beta.oerworldmap.org/resource/

I realized that we will have to discuss how the filters behave exactly. Currently, all filters are joined by an `AND`. The UI design is obviously preliminary.

/cc @acka47 @trugwaldsaenger

**Comment by acka47** [comment]
> Added filters as drop-downs above the search box on https://beta.oerworldmap.org/resource/

I suggest only showing the "availableLanguage" filter when the user has previously selected the "Service" filter as only services can be filtered via this field.

> I realized that we will have to discuss how the filters behave exactly. Currently, all filters are joined by an `AND`. The UI design is obviously preliminary.

Yes, we recently had the discussion about joining filters with AND or OR in NWBib. Both have advantages and weaknesses.

**Comment by literarymachine** [comment]
> I suggest only showing the "availableLanguage" filter when the user has previously selected the "Service" filter as only services can be filtered via this field.

You don't have to pick filters in any particular order. Thus, all filters are initially displayed. They disapper when no options are available due to the other filters that are set. I.e. you can select "availableLanguage" first, resulting in all resources that have an availableLanguage. Since this happen to be only Services, the type filter only contains the "Service" option after that.

**Comment by literarymachine** [comment]
> Yes, we recently had the discussion about joining filters with AND or OR in NWBib. Both have advantages and weaknesses.

We could also use a combination of these, e.g. applying an `OR` within a single filter (selecting `Person` and `Organization` in the `@type` filter would thus list all people and organizations) and combining the individual filters with an `AND` (selecting `Person` and `Organization` in the `@type` filter and `us` in the `addressLocation` filter would thus list all people and organizations from the US).
