### ISSUE TITLE
Single resource view does not load

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#1633]
I had this problem multiple times today. E.g. https://oerworldmap.org/resource/urn%3Auuid%3Ad6e33424-9234-46ba-9118-43db67e0f1ce will give me a blank page or will load for a long time after which I get this message:

![bildschirmfoto vom 2018-08-20 12 53 57](https://user-images.githubusercontent.com/160292/44336591-38c0f280-a478-11e8-87b1-e394faaa4e43.png)

It neither works in Chrome, Chromium nor Firefox. Site searches are working though.

**Comment by literarymachine** [comment]
Confirmed, @dobladov identified erroneous Markdown markup as the cause of this problem.

**Comment by literarymachine** [comment]
> E.g. https://oerworldmap.org/resource/urn%3Auuid%3Ad6e33424-9234-46ba-9118-43db67e0f1ce

See e.g. the `description` in the [JSON](https://oerworldmap.org/resource/urn%3Auuid%3Ad6e33424-9234-46ba-9118-43db67e0f1ce.json): `</br>`.

**Comment by literarymachine** [comment]
Unfortunately, https://github.com/hbz/oerworldmap-ui/pull/370 only fixed things when navigating on the client. When initially loading an entry with erroneous markup from the server, it still fails. Reopening.

**Comment by literarymachine** [comment]
Reopening because this caused https://github.com/hbz/oerworldmap/issues/1634.
