### ISSUE TITLE
Wrong description is shown

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1634]
There is a strange behavior: When following a link from an entry to another the description of the entry visited before is shown. When I reload the right description is shown.

When I make changes by editing the description the changes are not shown too, unless I reload the page.

See for example:
https://oerworldmap.org/resource/urn:uuid:52cc0850-12d5-4d53-ada7-4489e5cba5fc
![image](https://user-images.githubusercontent.com/18674205/44513937-094ff700-a6bf-11e8-8bd2-f57492b1099f.png)
![image](https://user-images.githubusercontent.com/18674205/44514049-5764fa80-a6bf-11e8-86a2-d0aff8200bf4.png)

**Comment by literarymachine** [comment]
@dobladov can this be related to https://github.com/hbz/oerworldmap-ui/pull/376?

**Comment by literarymachine** [comment]
Fixed by rolling back https://github.com/hbz/oerworldmap-ui/pull/376
