### ISSUE TITLE
Possibility to add persons as authors of publications who are not on the map

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1635]
We can only choose people with a profile on the map as authors. This is kind of problematic especially is there is a cc-by license (yes, I know it is only a link to the publication so we don't have to, but it is "schräg" not to be able to name the author).

For example in the case of the Lessons learned interviews we link to at OERinfo. They are cc-by and to be named is Jöran and the other Person who is not necessarily on the map. It is strange to name only one of the authors then. (And yes, we could ask the people to register, we have done this, but not all will do so.)

This may also occur in the case of policies, I think.

We discussed this before concerning the stories may be, but we did not come to a decision, as far as I remember. My suggestion would be to add a text field for unregistered authors.

**Comment by trugwaldsaenger** [comment]
Our wiki, Confluence allows to add links to not yet existing entries. Maybe we could implement something similar for authors. But how do we make sure, that the placeholder will be connected to the real person, as soon as it registers? We should try to discuss this issue during our next team meeting.

**Comment by drrobertfarrow** [comment]
This is absolutely essential since we cannot add persons without their permission.

Also, there is currently no possibility for multiple authorship of a publication - but most reports, etc. are typically authored by more than one person.

I have been pasting the correct author citation into the author field as it's not possible to give accurate information at the present time.

**Comment by drrobertfarrow** [comment]
Also, we may want to include publications about OER which are not themselves on an open licence.  We need more options for licensing (e.g. copyrighted; public domain; institutional pre-print, etc.) for the publication licence field.

**Comment by literarymachine** [comment]
> We need more options for licensing (e.g. copyrighted; public domain; institutional pre-print, etc.) for the publication licence field.

Copyright and public domain are include, if you scroll down a bit. I am unsure if "institutional pre-print" is actually a license.

**Comment by literarymachine** [comment]
> I have been pasting the correct author citation into the author field as it's not possible to enter accurate information at the present time.

This does not work and that information has been lost. The author field is to link to an author that is actually on the map.

**Comment by literarymachine** [comment]
Quick solution: we add a `citation` field similar to what we have for stories:

![image](https://user-images.githubusercontent.com/149825/45421035-117ecf00-b68c-11e8-8e19-58b5ff4e3fae.png)

There any additional citation information, including authors that are not on the map, could be entered. Would that suffice?
