### ISSUE TITLE
Add pending account verifications to admin UI

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1643]
As an administrator of the OER World map, I want to have an overview of pending account verifications, so that I can support newly registered users.

**Comment by dobladov** [comment]
I added the checkbox to the UI, we still need the data to check if the user is verified from the API, we can work on this branch https://github.com/hbz/oerworldmap-ui/tree/1643-VerifiedUsers

**Comment by literarymachine** [comment]
@programmieraffe @trugwaldsaenger I will show you how to do this on another channel.

**Comment by literarymachine** [comment]
Fixed in  #1742
