### ISSUE TITLE
Pop-ups at map border

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#165]
Pop-ups at the right border of the map are being cut of. (Example: Fiji, New Zealand). In these cases the pop-up should be left alligned.

**Comment by j0hj0h** [comment]
I made them overlapping the sidebar. Guess this is fine too. This won't work, if the sidebar isn't there (if we have a fullscreen view for exmaple) but this will probably not happen before switching to OpenLayers and that comes with it's own pop-ups.

**Comment by trugwaldsaenger** [comment]
![popups](https://cloud.githubusercontent.com/assets/6639965/8352853/9f25b8ca-1b38-11e5-97cc-ce6c7a76ccda.JPG)
This issues seemed to reappeared. If you open a popup close to the right border it will be cut off by the second column. Interestingly it stays there, if you switch with the mouse from the map to the second column.

**Comment by j0hj0h** [comment]
Yes, I know. The popovers are handcrafted again, so I have to care about all those behaviours. Quite some work, but I have it on my todo-list!

**Comment by trugwaldsaenger** [comment]
This sounds ugly. Since the focus of the map changes according to the country of the user, every popover can be positioned at the boarder, at least in theory. Do I understand this correclty?

**Comment by buschfeld** [comment]
Is it perhaps possible to show the popovers not centered "below" the mouse coordinates but kind of right-aligned. This might perhaps help if you can´t manage this problem by changing and adjusting the z-index via CSS?

**Comment by literarymachine** [comment]
As reported in https://github.com/hbz/oerworldmap/pull/399#issuecomment-146584464 the issue remains.
