### ISSUE TITLE
Reconciliation missing hit

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1653]
@karindr is using the reconciliation endpoint and has experienced the following problem:

![image](https://user-images.githubusercontent.com/149825/45941771-f8591500-bfdf-11e8-83d2-78b7f0c40d08.png)

I.e. "Kwame Nkrumah University of Science & Technology" is not found when reconciling Organizations although the spelling is exactly the same in the CSV as in our data:

![image](https://user-images.githubusercontent.com/149825/45941945-b086bd80-bfe0-11e8-9294-63ed2dfb75c4.png)

**Comment by karindr** [comment]
I changed the "&" on the map and in the refine table to an "and" then it worked fine. 

It is easy to avoid "&" but we have a lot of names with special characters because of different languages so it may be useful to have a look a this although the "Kwame" case is solved now.

**Comment by literarymachine** [comment]
> I changed the "&" on the map and in the refine table to an "and" then it worked fine.

Ok, excellent!

> It is easy to avoid "&" but we have a lot of names with special characters because of different languages so it may be useful to have a look a this although the "Kwame" case is solved now.

@philboeselager the special char is a good hint, but also the priority of this just dropped.

**Comment by literarymachine** [comment]
> Works out of the box, i. e. no code changes. Is it possible that we have a frontend issue here?

No, because reconciliation is not handled in the front end. Or are you referring to OpenRefine?

> Otherwise, I don't know how to reproduce this on the backend side and would maybe suggest to close this issue as "non-reproducible".

Did you try running OpenRefine and connecting to your local reconciliation service to debug the incoming request?

**Comment by literarymachine** [comment]
I think your test is not testing the correct [config](https://github.com/hbz/oerworldmap/commit/4efc561783fa92903e72e1200446f7055b97b26b#diff-8ebd6876aac5e63088acc8403a0b419eR171). It should probably read:

```
.setElasticsearchFieldBoosts(new ReconcileConfig().getBoostsForElasticsearch())
```

**Comment by philboeselager** [comment]
> I think your test is not testing the correct config. It should probably read: `setElasticsearchFieldBoosts(new ReconcileConfig().getBoostsForElasticsearch())`

Correct. Still, it works.

> No, because reconciliation is not handled in the front end. Or are you referring to OpenRefine?

Ahh... doh! Right.

> Did you try running OpenRefine and connecting to your local reconciliation service to debug the incoming request?

Not yet. I'm going to do this.

**Comment by philboeselager** [comment]
It has worked in my test due to the `test.conf` setting:

    es.search.fuzziness="TWO"

that differed from the `application.conf` setting

    es.search.fuzziness="AUTO"

The difference between the query term and the indexed (sub-) term was `\\&` vs. `&`, meaning a Levenshtein distance of 2. Fuzziness `AUTO` only allows **exact** matches for terms shorter than 3 characters (see the [ES reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness)).

I think that the two times escaping by using `QueryParser.escape()` twice is a mistake due to the history of the code, so I'm going to remove the second one probably. But still, one `\` will remain then. While escaping for sure makes sense and we've introduced it for a reason, the only way I see to deal this issue is to try to 

- replace `\&` by `&` after escaping or 
- replace ` \& ` by ` & ` (both surrounded by blanks) after escaping or
- using / implementing a more specific escape method which omits e. g. this case.

Any prefs or ideas, @literarymachine ?

**Comment by literarymachine** [comment]
> It has worked in my test due to the test.conf setting that differed from the application.conf setting

Ah! Good catch, we should probably change it to `AUTO` in `test.conf` since this is what we define in `application.example.conf`.

> I think that the two times escaping by using QueryParser.escape() twice is a mistake due to the history of the code, so I'm going to remove the second one probably. But still, one \ will remain then.

I don't see where we are introducing this double escaping; if we fix it to escape properly, shouldn't Elasticsearch take that into account when calculating the distance so that no further un-escaping is necessary?

**Comment by philboeselager** [comment]
> I don't see where we are introducing this double escaping

Right. My mistake.

> shouldn't Elasticsearch take that into account when calculating the distance so that no further un-escaping is necessary?

That would be nice - it **should**. We currently use the Lucene `QueryParser.excape()` method. I could not find any way to solve this - not even anyone else who had this issue before. I'm going to have another look.

**Comment by philboeselager** [comment]
@literarymachine As discussed above, `ReconcilerTest.testSearchSpecialCharAnd()` works, also given `es.search.fuzziness="AUTO"` that has been set meanwhile.

Also, reconciling the example above `Kwame Nkrumah University of Science & Technology` works on our production environment as it reconciles with `Kwame Nkrumah University of Science and Technology`. 

As there is no data case existent that causes a problem I vote for closing this issue and re-open given another example will occur.

**Comment by literarymachine** [comment]
> As there is no data case existent that causes a problem I vote for closing this issue and re-open given another example will occur.

:+1:
