### ISSUE TITLE
Difference between number of entries for country and number of entries in list

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1654]
When you select Germany as country in the filter section the number of 1008 entries is shown in brackets behind the name of the country in the list you select the country from. When you actually select Germany there are only 860 entries shown in the resulting list:
https://oerworldmap.org/resource/?filter.feature.properties.location.address.addressCountry=DE&size=20

**Comment by trugwaldsaenger** [comment]
Agreed - this is irritating behaviour. I remember, we had similar issues some time ago...
