### ISSUE TITLE
Add activity feed

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1660]
The activity feed should list the following type of activities in chronological order:

- New Users
- Other Additions
- Edits
- Comments
- Lighthouses
- Likes

Each entry should contain a preview / teaser of the entry and the person and date of action.

**Comment by formimkontext** [comment]
This is the format for an entry in the activity feed:

[how long ago / when]
[person] from [country] [added / edited / commented on / marked as a lighthouse: / liked / is attendig / is a member of] [resource]
[resource preview]
[comment]

Exception for new person joining the OER World Map:

[how long ago / when]
[person] from [country] joined the OER World Map
[profile preview]

**Comment by formimkontext** [comment]
We suggest to implement the activty feed as a modal. "Activity" replaces "Recent Additions", see drafts below.

[20180928-oerwm-activity-1](https://user-images.githubusercontent.com/15141949/46204096-43df2c00-c31c-11e8-8fc8-81a1c319bbeb.png)
[20180928-oerwm-activity-2](https://user-images.githubusercontent.com/15141949/46204097-43df2c00-c31c-11e8-98b7-e1b0880a0795.png)
[20180928-oerwm-activity-3](https://user-images.githubusercontent.com/15141949/46204098-4477c280-c31c-11e8-8fca-ce293606c500.png)
[20180928-oerwm-activity-4](https://user-images.githubusercontent.com/15141949/46204099-4477c280-c31c-11e8-8a52-2f82a4e094de.png)

**Comment by formimkontext** [comment]
Draft for a single feed card:

[20180928-oerwm-activityfeed](https://user-images.githubusercontent.com/15141949/46207214-dab0e600-c326-11e8-9987-02e3f2239521.png)

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/activity/

**Comment by acka47** [comment]
Looks very good. I am missing one thing. For edits of a page, I would like to go to the diff with one click. As currently the link to the edited resources is both behind the text and the box, one of them could be made the link to the diff or – even better – put the link to the diff behind "edited {entry}".

**Comment by trugwaldsaenger** [comment]
Looks great! I´m wondering how the relation to the "recently added" section will be. Currently both streams are available on beta. Do we need this, or should we combine them into one?

**Comment by literarymachine** [comment]
> I´m wondering how the relation to the "recently added" section will be. Currently both streams are available on beta. Do we need this, or should we combine them into one?

I would suggest keeping the `Recent Additions` under the `Find` menu and show `Activities` in the main menu as it is on beta right now.

**Comment by trugwaldsaenger** [comment]
I support the idea of linking to the diffs directly. But from my point of view this should not prevent us from putting the activity stream to production. @acka47: Do you agree?

**Comment by acka47** [comment]
+1
