### ISSUE TITLE
There is no easy way to enter a new address

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1661]
When I want to enter a new address for an organization because it has moved, I can see no way to get rid of the old location. I only can delete the old address and enter the new one in the lines below the text and drag the dot to the new position. 

It would be helpful to have a "Delete this address" button to start the creating of a new dot.

**Comment by literarymachine** [comment]
You can simply look up the new address:

![image](https://user-images.githubusercontent.com/149825/46195599-15098b80-c305-11e8-92e8-bcb343084e2a.png)

After selecting the new location, the pin is automatically set:

![image](https://user-images.githubusercontent.com/149825/46195716-59952700-c305-11e8-86bb-e2fe83065373.png)
