### ISSUE TITLE
The "source" field should not be mandatory for "stories"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1674]
A story can be written for the OER World Map and can be published only on our platform so we can't make the source field mandatory. Please change this back. @trugwaldsaenger agrees to this.

**Comment by literarymachine** [comment]
>  Please change this back.

There isn't really anything to "change back". As I said in https://github.com/hbz/oerworldmap/issues/1648#issuecomment-421952962, our schema is quite complex at this point:

> What this means is that you have to enter either a license, creator ("Author") and dateCreated or a citation and exampleOfWork ("Source").

This is hard to express properly in the UI. I still suggest to come up with a simpler schema.
