### ISSUE TITLE
Disallow crawling for non-production instance

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#1678]
By now, the beta instance is crawled by Google (and probably other serach engines), see: https://www.google.de/search?q=site:beta.oerworldmap.org . As this is not intended, crawling has to be disabled.

**Comment by acka47** [comment]
We may just reopen https://github.com/hbz/oerworldmap/issues/274 for this...

**Comment by acka47** [comment]
"Misbehaving robots.txt", sweet. :baby:

**Comment by literarymachine** [comment]
Configured for [beta](https://beta.oerworldmap.org/robots.txt) and [production](https://oerworldmap.org/robots.txt).
