### ISSUE TITLE
Automatically create documentation of data model 

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#168]
Currently, you can get an impression of the data model used in oer worldmap by looking at the [JSON schema file](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json). Users have aked for an overview of the entities described in the OER worldmap along with the used data elements and the values expected on each element. It would be nice if this doc could be automatically generated as a csv file from the JSON schema file. I will later add a link to an example file.

**Comment by literarymachine** [comment]
Having talked to @trugwaldsaenger about this before, I am still unsure if yet another table with data elements is the way to go. We could also simply link to the relevant http://schema.org entities and supply an example for each type. Our current schema is also not complete yet, we add elements as we go along. Maybe we could set up an etherpad that allows people to supply and discuss their data?

**Comment by acka47** [comment]
> We could also simply link to the relevant http://schema.org entities and supply an example for each type.

Could be a start. As I understood it, @trugwaldsaenger already wants an overview of the properties for resources not covered by the schema file yet, e.g. project. It may be quite confusing if we point people to `schema:Action` or `schema:Event` to describe a project (as no schema:project` exists). Also, if people just want to know what data to collect, the whole schema.org level might be too much information for them.

> Our current schema is also not complete yet, we add elements as we go along.

That's why I had the idea to create the doc from the schema to automatically keep them in sync. I would start work on the schema file for the missing resource types (event, project, service) then and the doc would be updated accordingly.

However, this was just an idea I had. I don't know whether this actually makes sense. Especially it might be hard to generate a doc that is easy to read regarding the up to three nested levels we have in the schema. Before discussing this for too long, I'd just write this down manually in a spreadsheet...

**Comment by literarymachine** [comment]
> However, this was just an idea I had. I don't know whether this actually makes sense. Especially it might be hard to generate a doc that is easy to read regarding the up to three nested levels we have in the schema. Before discussing this for too long, I'd just write this down manually in a spreadsheet...

That would be the way to go for now. Parsing the schema file is on @philboeselager and my list, but is not trivial and does not have a high priority because we don't need it for much more than automatic conversion of the schema to other formats. A manually maintained spreadsheet would also be a good basis to evolve the JSON schema!

**Comment by acka47** [comment]
FWIW, here is the example csv I announced above: https://github.com/acka47/oerworldmap/blob/issue168-csv-example/public/json/schema.csv

**Comment by acka47** [comment]
Here is the spreadsheet I talked about: https://docs.google.com/spreadsheets/d/1MUA2jg15AlQTwN-M8h52OHGT8Xo5Zf1jHut4zuMQsQI/edit#gid=1169308680 (Anyone can comment, who has got the link. Ping me if you want edit rights.)

**Comment by acka47** [comment]
We won't do this in the foreseeable future. Closing.
