### ISSUE TITLE
When navigating to the next section of a long list establish getting to the top 

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1687]
Now I can work in long lists (for example 130 policies) directly on the map because of the possibility to sort alphabetically. There is only a little inconvenience: when you go to the end of the first list (0-20) on a not so big screen and change to the next part of the list (20-40) the end of the second list is shown to you instead of the beginning as you would expect. So if a user is not paying attention to this he might miss the first parts of the lists. Please change the behavior to show always the top of the list after changing.

**Comment by acka47** [comment]
Currently, when clicking the "next" button the next 20 entries are shown with the position not changing (e.g. when you have been in the middle of the list when clicking "next" you would again be on the middle of the next list). It definitely makes sense to always got to the top of the hits after clicking "next".

**Comment by trugwaldsaenger** [comment]
+1
