### ISSUE TITLE
Pins for policies

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1693]
Currently all pins carry one colour. For the policies the "Coverage" should be visualized by using an individual colour for each pin. 

This will allow to see at one glance in which country/area we can find many institutional policies and in which countries we will find many national policies.

**Comment by trugwaldsaenger** [comment]
Before we can implement this issue, #1619 has to be closed first.

**Comment by literarymachine** [comment]
As discussed with @trugwaldsaenger, we will first implement pins for institution level policies. In those cases, the pin will be at the `location` of the `publisher` when the `coverage` is `institutional`.

**Comment by philboeselager** [comment]
Interesting. Is it for a practical / usability reason that policies should have a pin, @trugwaldsaenger ? Feels somewhat counter intuitive at first sight to me.

**Comment by trugwaldsaenger** [comment]
> Feels somewhat counter intuitive at first sight to me.
Thanks for this feedback, @philboeselager! I think policies are of a special "geopolitical" relevance and I can imagine, that it will be helpfull to see on the map, which areas "produce" many policies and which do not. This is especially true, if we can somehow distinguish between different levels of policies as are defined in #1619. This for example will help to identify areas, where a state/national policy triggers many institutional policies.

**Comment by trugwaldsaenger** [comment]
I assume that this has a rather high priority...

**Comment by literarymachine** [comment]
> As discussed with @trugwaldsaenger, we will first implement pins for institution level policies. In those cases, the pin will be at the `location` of the `publisher` when the `coverage` is `institutional`.

This will currently result in pins for the 25 of 157 policies on the map, which in my opinion rather distorts the data.

**Comment by literarymachine** [comment]
For the record: we will use the `location` of the `publisher` for all `Policy` entries.

**Comment by literarymachine** [comment]
> For the record: we will use the location of the publisher for all Policy entries.

On beta: https://beta.oerworldmap.org/resource/?filter.about.@type=Policy
