### ISSUE TITLE
Check for possible bug in newsletter registration

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1696]
I tried to register for the newsletter with the two email addresses I have and both failed. I got this message:
Cannot POST /user/newsletter
I am not 100% sure that I am not registered to the newsletter already, maybe this is the reason for the error. But if this really is the reason the error message should be changed to something like "You are already registered to the OER World Map newsletter."

**Comment by dobladov** [comment]
Confirmed, I have the same error with a mail that is not registered for the newsletter.

**Comment by acka47** [comment]
I just tried it out and it worked.

**Comment by literarymachine** [comment]
> I just tried it out and it worked.

Yeah, I just fixed it.
