### ISSUE TITLE
Links to API documentation in OER service description

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#17]
As a search engine owner/developer I want to get links to documentation of a service's API, dumps etc. in order to index the data into my search engine.

**Comment by acka47** [comment]
We need to create tasks for this one.

**Comment by acka47** [comment]
There's a type [`WebAPI`](http://pending.schema.org/WebAPI) and a property [`documentation`](http://pending.schema.org/documentation) in pending schema.org (see https://github.com/schemaorg/schemaorg/issues/1423 ). I suggest using them already and adding the link to API and its documentation to the `availableChannel` array. For example:

```json
{
   "@id":"urn:uuid:29056e88-727b-407e-b00a-16df279ac506",
   "name":[
      {
         "@value":"OER World Map",
         "@language":"en"
      }
   ],
   "availableChannel":[
      {
         "serviceUrl":"https://oerworldmap.org/",
         "availableLanguage":[
            "de",
            "en"
         ]
      },
      {
         "@type":"WebAPI",
         "url":"https://oerworldmap.org/resource/",
         "documentation":"https://oerworldmap.org/api"
      }
   ]
}
```

**Comment by acka47** [comment]
In the UI there should be an additional Heading "API" with fields "URL" and "Documentation".

**Comment by acka47** [comment]
@trugwaldsaenger writes yesterday:

> Ich wollte das gerade mal ausprobieren und zwar mit der API von NDLA:
> 
> https://oerworldmap.org/resource/urn:uuid:c4ace24a-7f00-11e5-a636-c48e8ff4ea31
> 
> Dabei sind mir zwei Dinge aufgefallen:
> 
> 1) Speichern des Links zur Dokumentation alleine ist nicht möglich. Es 
> kommt dann ein Fehlermeldung, die allerdings nicht erkenntlich auf die 
> API hinweist, sondern eine fehlende "service.service URL" oder so 
> ähnlich moniert.

We should fix this.

> 2) NDLA bietet ja direkt 4 API`s an. Brauchen wir die Möglichkeit, 
> mehrere API-Links abzulegen?

I don't think we should give the possibility to add multiple APIs. Otherwise we will also need mane and description for them which seems to be too much for me right now.

In addition to Jan's notes I realized that the current setup doesn't enable users to query the world map for all services that have an API link as `q=about.availableChannel.serviceUrl` will also give you services that only have a URL. Thus, you can not automatically parse for API URLs. This seems not optimal. Should we reopen the issue?

**Comment by trugwaldsaenger** [comment]
Thanks for you comment. Do I get it right that there are not four apis, but only one with the link: https://api.ndla.no/ ?

Automatically parse for API URLs would be very helpful!

**Comment by literarymachine** [comment]
> Ich wollte das gerade mal ausprobieren und zwar mit der API von NDLA:
> https://oerworldmap.org/resource/urn:uuid:c4ace24a-7f00-11e5-a636-c48e8ff4ea31

@karindr discovered a bug with the current implementation that prevents saving `URL` when `availableLanguage` is set. Since the above example seems to be the only case of adding a link to an API documentation so far, is it OK if I revert the changes and give this another thought?

**Comment by trugwaldsaenger** [comment]
OK!
