### ISSUE TITLE
Provide list of tools

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#170]
User Story: 
As an OER project which aims at developing a service, I want to see which tools other sucessfull OER projects are using, so that I can learn from their experience and choose the right tool for my own project.

Acceptance Criteria:
Possibility to add tools to a service description

**Comment by acka47** [comment]
@trugwaldsaenger In the user story it reads "I want to see which tools other sucessfull OER projects are using", the acceptance criterium is adding tools to a _service_ description. I'd say either the story has to be adjusted or the criterion "possibility to add tools to a project description" to be added.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:7d5a3c50-a508-4515-b455-219d10e97f64

**Comment by karindr** [comment]
Little typing mistake: "Wir verwendet" statt " Wird verwendet"
