### ISSUE TITLE
Likes and lighthouses disfunctional

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1702]
I just tried to like an entry as well as to set a lighthouse. Both actions did not work. The "like" buttom did not get organge and I was unable to save my lighthouse-comment. I tried to do so using both Firefox and Chrome.

**Comment by literarymachine** [comment]
Yep, confirmed. This is due to https://github.com/hbz/oerworldmap/issues/1673 which I have just deployed. So suddenly, `description` and `url` are mandatory. When liking or lighthousing an entry, we are updating it. If it has no `desciption` or `url`, it fails.

**Comment by literarymachine** [comment]
@trugwaldsaenger please always provide as much context as possible. In this case: which entry did you try to like?

**Comment by trugwaldsaenger** [comment]
This is the entry I tried to like: https://oerworldmap.org/resource/urn%3Auuid%3Ae0198a84-666b-44cb-b321-176c1d5ca736?

**Comment by dobladov** [comment]
Related: https://github.com/hbz/oerworldmap/issues/1397

**Comment by literarymachine** [comment]
Fixed in #1703
