### ISSUE TITLE
Change password results in Bad Request

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1704]
Tried to change password (after password reset via E-Mail), results in Bad Request.

Test password  uW3Aro8j

**Comment by literarymachine** [comment]
Cannot reproduce; could it be that you mistyped your current password (i.e. the one you got via E-Mail)?

**Comment by dobladov** [comment]
I also tried to replicate the issue, the only way I get `Bad Request` is when I put the wrong old password.

**Comment by programmieraffe** [comment]
Sorry, indeed my mistake. Can't reproduce it now either.
