### ISSUE TITLE
Adjust order of types in statistic to other statistics

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1713]
In all other statistics, the first colour (green) starting at 12 o'clock stands for the biggest part going on to the smallest part (orange). Only the "Entries by type" statistic does not follow this order. It starts with publication which seems random because it is in no way our most important type. This statistic should follow the same top-down order as the other statistics.
![image](https://user-images.githubusercontent.com/18674205/49066303-f8180880-f220-11e8-906e-3d561450ea69.png)

**Comment by dobladov** [comment]
We reimplemented the statistics in Kibana and now we don't have control of the colour to fix this issue.
