### ISSUE TITLE
Sort lastest policies on the map by dateCreated

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1715]
Yesterday I made a new entry: 
https://oerworldmap.org/resource/urn%3Auuid%3Ab66664c9-8f5c-459a-9f13-1e9773c151c3? 

It is included in the recent additions feed:
 ( https://oerworldmap.org/feed/ ), 

but not in the "policy feed" though it is a policy and therefore should appear there as well: (https://oerworldmap.org/oerpolicies ). 

Reload of the page in Firefox does not help...

**Comment by literarymachine** [comment]
It is there, it just isn't the first one:

![image](https://user-images.githubusercontent.com/149825/49141395-c2455380-f2f6-11e8-8ea1-9005f7ba832f.png)
