### ISSUE TITLE
Support multilingual input for name and description fields

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#172]
These fields should support multilingual input: `name`, `alternateName`, `description`.

Acceptance criteria:
- [x] Ability to indicate language a field is filled out in
- [x] Ability to fill out the same field in multiple languages

**Comment by acka47** [comment]
Sorry, forgot the user story. Here are two stories behind this issue:

1. As a non-English speaker I want to add a person, organization, service or project in a language I can speak/write.

2. As a non-English speaker I want to see names and descriptions on the map, in results lists and in item descriptions in languages I understand – if possible.

**Comment by acka47** [comment]
Related to #158 .

**Comment by literarymachine** [comment]
The good news is, our schema already supports this and when pushing data via the API, this is not a problem. Are you sure though, that `name` (which we only use for people) should be multilingual? We use `legalName` for `Organization`, which is multilingual.

Also, I think we should separate the related user stories into "Add service (etc) via JSON / API" and "Add service (etc) via Web Form". The former already works, and if we don't split them, the stories are huge.

**Comment by literarymachine** [comment]
In our [schema](https://github.com/hbz/oerworldmap/blob/story/%23117/public/json/schema.json), look out for entries such as

     "legalName": {
          "description": "The organization's primary name, e.g. a legally recognized name",
          "$ref": "#/definitions/LocalizedString"
        }

**Comment by acka47** [comment]
> We use `legalName` for `Organization`, which is multilingual.

We haven't talked about the use of `legalName` yet. I have noticed that you use it but don't understand yet what is the advantage of using a separate property for organizations. Why not use `schema:name` everywhere? Wouldn't that simplify provision of a search API if someone wants to search all resources by name?

**Comment by acka47** [comment]
Closing as the web forms now support both acceptance criteria.
