### ISSUE TITLE
Language strategy intrasparent for new users

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1720]
This is a rather big topic, but I want to state my first user experience before I'm getting to deep into the project. :) It is connected with the feeling of having no real control over world map usage as a user. Preselected information (browserbased e.g.) should be transparent for users imho.

**1. Missing language switch**

Yesterday I searched a couple of minutes for a language switcher, did not found one in bottom of page, did not found one in main menu. Then I tried to edit my user settings (wordpress puts language option there), did not found a setting. (I then suspected it is defined by browser setting, but I have a developer background ;-))

Use cases for language switch:
- Showing english version to a interested person (on a client pc, where I can't change browser settings)
- Figuring out correct englisch menu titles for github issues

**2. Interface does not clearly state a goal which languages I should input / sets no default standard**
![image](https://user-images.githubusercontent.com/777278/49210366-4104c400-f3bd-11e8-8715-36abac46bb21.png)
The world map is shown to me in german, I now can select which language I use for input information. I have no indication what goal should be reached with worldmap (e.g. collect all information in local language + englisch, collect at least everything english, collect at least everything multiple core languages - or if it is totally ok i I only input information in my local language?)
Interface should clearly state that goal/goals.

**3. Missing visual feedback/gratification for translations**
I added my information in three different languages, invested more time than usual and saved everything (e.g. event). Afterwards I still only see the german version:
![image](https://user-images.githubusercontent.com/777278/49210636-e91a8d00-f3bd-11e8-9964-5c4f742478bf.png)
There is no feedback or indication whatsoever when/where the translation will appear.
Possible improvement: Language switch for content

**4. Possible irritation regarding multilanguage strategy (inconsistent)**
World map offers only some languages for interface, but you can input information in every language?

**Possible reference projects:**
https://hopon-newcomers.com/de/
- clear information in header which language was preselected by page
- I can easily send a different language version to a colleague via URL (e.g. if english description is more comprehensive)
- selected language = content language, no irritation

**Comment by dobladov** [comment]
Related: [Make it possible to change the displayed language of descriptions manually](https://github.com/hbz/oerworldmap/issues/1453)
Related: [Implement specifying language in the URL](https://github.com/hbz/oerworldmap/issues/1363)

**Comment by dobladov** [comment]
> 2. Interface does not clearly state a goal which languages I should input / sets no default standard

At the moment the user starts writing the interface will select english as the default language.

![defaults](https://user-images.githubusercontent.com/1938043/49212594-a8714280-f3c2-11e8-9cad-837da26ee622.gif)

**Comment by programmieraffe** [comment]
Thanks for the addition! Really interesting "glitch": I did no enter text in description field, instead i clicked first on "Select language" (- the automatic switching was'nt triggered). Maybe just preselect english? (or is there reason for this "live switching" approach?)

**Comment by dobladov** [comment]
> Maybe just preselect english? (or is there reason for this "live switching" approach?)

We keep it this way because for the data model we can not have a set language with an empty value (description, name...) So this way the make sure there is only a selected language if the value is filled.

**Comment by programmieraffe** [comment]
> We keep it this way because for the data model we can not have a set language with an empty value (description, name...) So this way we make sure there is only a selected language if the value is filled

Is there no "validation on submit" solution possible?

**Comment by literarymachine** [comment]
> Is there no "validation on submit" solution possible?

There is definitely a way to have English pre-selected visually!
