### ISSUE TITLE
Searching for "US:" is suggested but causes "An error has occured"

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1726]
I seárched with these filters
https://oerworldmap.org/resource/?q=US&filter.about.additionalType.%40id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fpublications.json%23policy&size=20&sort=about.name.%40value.sort%3AASC

**Comment by literarymachine** [comment]
@dobladov this is about searching for `US:` (with a colon at the end) which does not work. This is because the search is interpreted as an elasticsearch query string. @philboeselager could you look into this?

**Comment by philboeselager** [comment]
The troubling trailing `:` is escaped in https://github.com/hbz/oerworldmap/pull/1728/commits/dd11faad0af39e6ae6c274972b55aca038d9fa90. This means the error is catched. This does not mean, however, that a trailing double quote (or another such special character) is getting influence on the search result. Searching for `US:` will return the same result as searching for `US`.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/pull/1728
