### ISSUE TITLE
Make it possible to change profile to new email address

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#1730]
I know this would be complicated because the login-email is used for identification. 

But for example, me leaving hbz and being registered with my hbz-address can't change the address. This way I would not be able to get "I forgot my password" emails.  I can start with a new account, but that is not really nice because I lose the connection to all I did before.

**Comment by literarymachine** [comment]
Available at https://beta.oerworldmap.org/auth/realms/oerworldmap/account/

**Comment by trugwaldsaenger** [comment]
seems to work fine. I changed my mail address and was able to sign in with the new mail.

**Comment by literarymachine** [comment]
Fixed in  #1742
