### ISSUE TITLE
Export for OER policy registry returns empty CSV

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1733]
https://oerworldmap.org/oerpolicies
"Sehen Sie hier alle bisher auf der Karte verfügbaren Policys." 
links to ->
https://oerworldmap.org/resource/?filter.about.additionalType.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fpublications.json%23policy

CSV export is empty.

Thanks in advance!

**Comment by literarymachine** [comment]
Confirmed. Problem is that the Link that is exposed in the "Export"-Menu:

![image](https://user-images.githubusercontent.com/149825/51260625-fe1f9f80-19ae-11e9-9447-636f306dcbd6.png)

does not properly escape the filter parameters: https://oerworldmap.org/resource.csv?size=-1&disposition=&filter.about.additionalType.@id=https://oerworldmap.org/assets/json/publications.json#policy

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?size=-1&ext=csv&filter.about.@type=Policy
