### ISSUE TITLE
Search by author name: publication not found

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1735]
Search I: https://oerworldmap.org/resource/?q=cronin%20catherine&size=20
Search II: https://oerworldmap.org/resource/?q=cronin&size=20

Publication: https://oerworldmap.org/resource/urn%3Auuid%3Ae3d7ab3f-e991-45e2-801e-a31aa08241e8

**Comment by trugwaldsaenger** [comment]
Can it be, that publications are not indexed at the moment? In this case, policies would not be indexed as well....

**Comment by literarymachine** [comment]
> Can it be, that publications are not indexed at the moment? In this case, policies would not be indexed as well....

Do you have any example for this assumption? The publication @programmieraffe is referring to in https://github.com/hbz/oerworldmap/issues/1735#issue-404728740 can be found by [searching for the title](https://oerworldmap.org/resource/?q=Openness+and+praxis) which means it is indexed.

**Comment by trugwaldsaenger** [comment]
Yes, you are right, the article can be found when I directly search for its title. So obviously no problem with the idexing. I assume that @programmieraffe`s observation was that the article by Cathrine Cronin is not found, when looking for Cathrin Cronin... So maybe the Author-field is not included?
