### ISSUE TITLE
Display of tagged resources not working 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1743]
I open following entry
https://oerworldmap.org/resource/urn%3Auuid%3A095c9e05-3204-48f3-846c-d9103c1996a9?
When I click on the tag "challenge: language & cultural isues" on the profile I receive 0 hits

When using the main search and setting a filter to "challenge: language & cultural isues" I receive 4 hits:
https://oerworldmap.org/resource/?filter.about.keywords=challenge%3A%20language%20%26%20cultural%20issues&size=20&features=true

**Comment by literarymachine** [comment]
Confirmed, in the link the "Tags" section is not property URL escaped.

**Comment by trugwaldsaenger** [comment]
Nevertheless this does not seem to be a general issue. For other entries it works:
https://oerworldmap.org/resource/urn%3Auuid%3A83cdcbf8-159d-452c-b1cd-c7371f57ee77?
