### ISSUE TITLE
Bullet Points are not displayed correctly

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1744]
Example:
https://oerworldmap.org/resource/urn:uuid:e0f344db-6c77-4a31-9112-dc98c29a6195

Bullet points have been created using the bullet-point-function of the editor (not by markup). They are displayed correctly using the previewfunction, but after saving the lists are broken.

**Comment by literarymachine** [comment]
Confirmed, there seems to be a slight difference in the preview rendering and the render engine we use for the actual view. Until we figure out how to deal with this, the work around is to add an empty line before a bullet list. See https://oerworldmap.org/resource/urn:uuid:e0f344db-6c77-4a31-9112-dc98c29a6195 where I fixed the list.
