### ISSUE TITLE
Language switch does not work (Win/Chrome+firefox)

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1747]
Content of https://oerworldmap.org/oerpolicies?language=en is always displayed in German.

**Comment by dobladov** [comment]
Confirmed. There is something definitely wrong, on _Windows + Chrome_ the content is **always German** when I set English or German, but changes correctly for Portuguese.

_Windows + Firefox_ seems to work with the latest version.

**Comment by programmieraffe** [comment]
Works for me now in Firefox + Chrome on beta. :+1:
