### ISSUE TITLE
How should we deal with policy-specific fields usage in non-Policy entries?

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1756]
When clicking on "Status: Current?", should the result list contain only policies? Would be usefel for navigating Policy Registry case: http://recordit.co/Q090I2h4Bx

**Comment by literarymachine** [comment]
The `Status` field is going to be limited to Policies when #1628 is deployed anyways. The [entries that use this field and are not Policies](https://beta.oerworldmap.org/resource/?filter.about.status=Current&q=NOT%20about.@type:Policy) have to be fixed on the data level (using a migration, I will do this if you agree).

**Comment by literarymachine** [comment]
I just realized that the field `level` (aka `spatialCoverage`) is now also limited to Policies but has been used for Publications:

https://beta.oerworldmap.org/resource/?q=NOT%20about.@type:Policy%20AND%20_exists_:about.spatialCoverage

We either have to keep the field for Publications or also remove it in the corresponding entries.

**Comment by trugwaldsaenger** [comment]
Yes, I`m aware of this. If I´m not mistaken, this affects only very few publications. I would remove it there and use it only for policies!

**Comment by literarymachine** [comment]
Migrations:
- [ ] https://beta.oerworldmap.org/sparql/update?delete=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fstatus%3E+%3Fstatus&insert=&where=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fstatus%3E+%3Fstatus+.+MINUS+%7B+%3Fentry+a+%3Chttp%3A%2F%2Fschema.org%2FPolicy%3E+.+%7D
- [ ] https://beta.oerworldmap.org/sparql/update?delete=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%3FspatialCoverage&insert=&where=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2FspatialCoverage%3E+%3FspatialCoverage+.+MINUS+%7B+%3Fentry+a+%3Chttp%3A%2F%2Fschema.org%2FPolicy%3E+.+%7D

**Comment by literarymachine** [comment]
> Migrations

Migrated on production, closing.
