### ISSUE TITLE
Refactor result list

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1758]
See the list on the rights hand side of https://learnmap.hochschulforumdigitalisierung.de/ for inspiration. 

@programmieraffe please provide more acceptance criteria here:

- [x] should contain `name`
- [x] should contain `description` (truncated, with `more` link
- [x] should contain `location`

@dobladov this replaces the pop-ups we currently have.

**Comment by dobladov** [comment]
Current state after refactor.

![refactor](https://user-images.githubusercontent.com/1938043/55558518-8e3ace80-56ec-11e9-8670-2c2d3debec58.gif)

**Comment by programmieraffe** [comment]
Nice! Is this "customizable" for every type?
If yes:  @trugwaldsaenger could point to what would be acceptance criteria for policies, e.g. Level?
(I'm just a bystander regarding policies ;-))

**Comment by literarymachine** [comment]
> Is this "customizable" for every type?

No, currently not.

**Comment by programmieraffe** [comment]
Okay, but if the description is shown that's a big win for the policy registry and the event next week :-) :+1:

**Comment by literarymachine** [comment]
@dobladov looks really good! Could you maybe add some sort of horizontal ruler in between the entries, it is sometime a bit hard to see where one ends and the next begins.

@programmieraffe we have to keep in mind that this change only works well when descriptions are provided. See https://beta.oerworldmap.org/resource/?q=NOT%20_exists_:about.description
