### ISSUE TITLE
Idea: Special header for detailed view of policy (as part of policy registry)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1762]
Idea: Special header for type policy in detailed view? With link to OER policy registry summary? (Make it clear to users, that this is a special type for policy registry) https://oerworldmap.org/resource/urn%3Auuid%3A8b02602c-ee34-4396-89ee-4e259b9322a1

**Comment by literarymachine** [comment]
See e.g. https://oerworldmap.org/resource/urn:uuid:8b02602c-ee34-4396-89ee-4e259b9322a1

![image](https://user-images.githubusercontent.com/149825/55725604-5397a580-5a0e-11e9-97f7-d89d1ba0f474.png)
