### ISSUE TITLE
User registration path: Register > Confirm mail > First Login > Ask user to add profile information

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1763]
See https://hfdcert.de/ for a good solution of guiding the user regarding first login after registration (Call to action after first login)

(Maybe usability or identity milestone)

**Comment by literarymachine** [comment]
+1, I was thinking about postponing the creation of the actual profile to the first login after having created an account.

**Comment by programmieraffe** [comment]
:+1: hfdcert has also the flexible checkbox option "private profile yes/no" which is not listed in the public  directory (it can be changed from day to day if the user wants to do so - i don't know if this would be a problem for elastic search, but in terms of privacy & openness and low barriers to participate in adding infos we should really discuss this option / think it through :-))

**Comment by literarymachine** [comment]
User without a profile shall be asked to create one after every login but given an easy way to skip this step.

**Comment by programmieraffe** [comment]
Documentation of further discussions:
- Maybe communicate this as "Add yourself with a profile to the OER actors category on oerworldmap.org"
- Re-discuss if people who aren't user have placeholder profiles (e.g. researchers/authors of publications), so they can be linked

**Comment by literarymachine** [comment]
Deployed to https://beta.oerworldmap.org/.login, please test creating an account and then adding & editing your profile!

**Comment by literarymachine** [comment]
Fixed in  #1742
