### ISSUE TITLE
Set og:image / twitter share pic to (profile) picture of item

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1764]
Example: https://oerworldmap.org/resource/urn:uuid:306f58c2-1107-45d2-87be-773fe2029736

Example Social Media Preview Image: https://twitter.com/oerworldmap/status/1105212460271849472

**Comment by literarymachine** [comment]
@dobladov shouldn't `twitter:image` and `og:image` be the same?

![image](https://user-images.githubusercontent.com/149825/55628445-036fd780-57b1-11e9-8b9b-018e397423b3.png)

**Comment by dobladov** [comment]
I think we are not doing it right now because of the required sizes for the preview, I will take a look and see how they might look.

**Comment by literarymachine** [comment]
Du to the `robots.txt` on beta, we'll have to test this when it is on production.
