### ISSUE TITLE
Change search input placeholder to "Search in entries" when filter is set

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1766]
![image](https://user-images.githubusercontent.com/777278/55642707-8143db00-57d1-11e9-95a8-d4d097a3af7f.png)

"Search the (whole) map" is correct, but if user sets a filter (e.g. type "projects") it should be something like "Search in entries/results ...".

For CountryView it should be "Search in country entries", etc.

Is it easy to detect if a filter was set and change the placeholder?

Alternative quick pragmatic fix: Change placeholder to something general like "Search on map / in entries (if filter is selected"

**Comment by programmieraffe** [comment]
Just a short reminder: User can also select a category first, e.g. "Projects", not only countries :-)

My inititial idea was to move the search bar to the entries list and category icons to the top. I think it would become much more clearer to the user, that he only can search in the current shown results list ( a new entry in the search bar won't reset the filters)

First idea draft:
![image](https://user-images.githubusercontent.com/777278/55800690-99b73c80-5ad4-11e9-8a9a-ec468d37e792.png)

Second idea draft
![image](https://user-images.githubusercontent.com/777278/55800699-9de35a00-5ad4-11e9-8f6a-cc72dc93266f.png)

But right now I feel generally that the list needs much, much more space (especially with the new detailed list, which i really like!) - maybe there is a better quick/easy solution for the filter section, especially on smaller screens:
![image](https://user-images.githubusercontent.com/777278/55800797-d08d5280-5ad4-11e9-8c79-d3ce090340f2.png)

**Comment by dobladov** [comment]
Included now:
-  Search entries
-  Search entries in %{country}
-  Search %{filter} entries in %{country}
-  Search in %{filter} entries

![searchentries](https://user-images.githubusercontent.com/1938043/55815044-f6742080-5aef-11e9-8d9b-d4e285d020cb.gif)

**Comment by programmieraffe** [comment]
Nice work!

I discovered #1784, but I guess it has nothing to do with approving this one.

Are the shown strings "Search entries in X" translateable via oerworldmap-ui/crowdin? (I would like to set the first default string to "Search the OER World Map" and the policies to "Search in Policy Registry")

**Comment by dobladov** [comment]
These are the strings that will be present in crowdin **when we merge**.

-  "search.entries":  "Search entries",
-  "search.entries.country": "Search entries in %{country}",
-  "search.entries.country.filter": "Search %{filter} entries in %{country}",
-  "search.entries.filter": "Search in %{filter} entries"

For policies I can create a new use case, for now, they are "Search in %{filter} entries" (_Search in policy entries_) independently of the type of filter.
