### ISSUE TITLE
Quick fix: Remove map header from detail item view?

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1767]
Mapbox in header has no real additional value imho, title is not where users expect it (top left), users have to scroll to see additonal infos (on small screens)

![image](https://user-images.githubusercontent.com/777278/55643920-ac7bf980-57d4-11e9-9cd1-97a316b85b23.png)

**Comment by programmieraffe** [comment]
For policy registry:

Can we show somewhere "This policy is part of the OER policy registry" with link to https://oerworldmap.org/oerpolicies? 

Two user flows are possible:
a)
1. https://oerworldmap.org/oerpolicies -> click on single policy (we could show a back link, but maybe complicated to detect right now)

b)
1. https://oerworldmap.org/oerpolicies > click on
2.. category in kibana > map view with filter https://oerworldmap.org/resource/?filter.about.primarySector.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fsectors.json%23higherEd&filter.about.@type=Policy
3. click on single policy -> back link should just close or filter is lost (link to "This policy is part of the OER policy registry" must be optional)

**Comment by literarymachine** [comment]
Add Policy Icon before like icon:

![image](https://user-images.githubusercontent.com/149825/55709571-e7567b00-59e8-11e9-8aaa-95efbedaa896.png)

**Comment by dobladov** [comment]
See #1762
