### ISSUE TITLE
Add new field "type" and rename existing field

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1768]
The existing field "type" should be renamed into "scope"

The new field "type" should have following values:
- legislation
- policy document
- strategy document
- call for tender
- other

These new subtypes should be included into the second level navigation.

**Comment by literarymachine** [comment]
Migration:

https://oerworldmap.org/sparql/update?delete=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Fat+.&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fscope%3E+%3Fat+.&where=%3Fs+a+%3Chttp%3A%2F%2Fschema.org%2FPolicy%3E+.+%3Fs+%3Chttp%3A%2F%2Fschema.org%2FadditionalType%3E+%3Fat+.
