### ISSUE TITLE
Description-text beneath country field in policy?

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1772]
I used Policy.location (https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/descriptions.json), but it is not shown anywhere?

I see no other field in here?
https://github.com/hbz/oerworldmap-ui/blob/master/docs/_data/locale/labels.json

![image](https://user-images.githubusercontent.com/777278/55728630-b855fe80-5a14-11e9-9497-e9cccc759d94.png)

Or is this field retrieved via "PostalAddress.addressCountry"?

**Comment by literarymachine** [comment]
> I used Policy.location, but it is not shown anywhere?

There is actually one more level of indirection, the property was missing in the schema: 1109d37
