### ISSUE TITLE
Move search / result column to the left

### ISSUE THREAD

**Issue by dobladov** [hbz/oerworldmap#1773]
Move the main column of the site from the right to the left of the site to follow the pattern of sites like google/bing maps.

**Comment by programmieraffe** [comment]
i really like it!

little suggestion: map needs to have an other default center value, right now:
beta.oerworldmap.org -> list is shown, North/South America points are hidden by list 

new start point would be something like that? https://beta.oerworldmap.org/resource/?filter.about.@type=Action&size=20&map=-68.91786,42.28481,0

**Comment by programmieraffe** [comment]
Same with country views: The focus/zoom-in action is optimized for list on the right side

![image](https://user-images.githubusercontent.com/777278/55879289-8e304800-5b9e-11e9-916f-d6e8cec3b584.png)

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/pull/508
