### ISSUE TITLE
Rearrange "Show list" button

### ISSUE THREAD

**Issue by dobladov** [hbz/oerworldmap#1777]
Change the current Show List button for an arrow to show and hide the column

**Comment by programmieraffe** [comment]
Great solution!

On mobile the arrow is out of the screen area unfortunately:
![image](https://user-images.githubusercontent.com/777278/55878590-0990fa00-5b9d-11e9-9511-4d24d5ae3d1b.png)

(Reminder for later: We should discuss, what UI element user should first use - my current opinion is, that we have to show the list at the beginning, so users can check out the latest entries - but we'll discuss this another time :))

**Comment by dobladov** [comment]
> On mobile the arrow is out of the screen area unfortunately:

I completely forgot about this, I decided to put it up next to the search bar since in the middle it will obscure some of the information and in the bottom could be confused with the pagination.

![move](https://user-images.githubusercontent.com/1938043/55893387-706fdc80-5bb8-11e9-914d-726202c404d8.gif)
