### ISSUE TITLE
Rearrange closing country view Icon

### ISSUE THREAD

**Issue by dobladov** [hbz/oerworldmap#1778]
Use an `X` symbol as the close button inside the box displaying the country information.

**Comment by programmieraffe** [comment]
I hope you don't hate me ;-))

1. Country view hides language switch
![image](https://user-images.githubusercontent.com/777278/55879389-ccc60280-5b9e-11e9-87ec-a6e812c31ac2.png)

2. Problem with long names
![image](https://user-images.githubusercontent.com/777278/55879430-e6674a00-5b9e-11e9-87cc-5c222618107e.png)

**Comment by dobladov** [comment]
> I hope you don't hate me ;-))

Don't worry, there are valid issues, do not hesitate.

![countr](https://user-images.githubusercontent.com/1938043/55880971-149a5900-5ba2-11e9-8249-3920e15ff826.gif)

Fixed now on the same pull request
