### ISSUE TITLE
Add popovers for countries

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#178]

**Comment by buschfeld** [comment]
Remark: Additional info for Country Champion maybe delted or shown without numbers

![oer_11_demo_map_country](https://cloud.githubusercontent.com/assets/10743356/8210330/d143ec5a-1511-11e5-8338-e56deb3daf60.png)

**Comment by trugwaldsaenger** [comment]
As in #234 I would propose to include the rocket symbol, which is also in the screenshots. Apart from this the mouseover looks great!. If there is no time left to include the rocket, please go on to deploy directly!
