### ISSUE TITLE
Recent additions - hover is still shown

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1790]
![image](https://user-images.githubusercontent.com/777278/56048392-b909d000-5d47-11e9-9215-f8674baa9ed7.png)

We removed that hover info from the general list, we should remove it here as well
https://oerworldmap.org/feed/

**Comment by dobladov** [comment]
Should we use only on the resource view or we definitely don't use it?

![image](https://user-images.githubusercontent.com/1938043/57065558-18655b00-6cca-11e9-8a67-ed375128e96b.png)
