### ISSUE TITLE
Export feature with core set of (human-readable) data as XLS

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1793]
Multiple people asked for export of certain categories or data. We have the export feature, but in some cases there are no titles (like projects.csv export).

Most requested format ist XLS, csv should also be okay, but we have to include a little tutorial how to open it correctly with Microsoft Excel (I guess).

Suggestion by @trugwaldsaenger for minimal core set fields:

> Service
> - Name
> - Description
> - Provider
> - URL
> - Service Type
> - Available Since
> - Primary educational sector
> 
> Projects
> - Name
> - Operator
> - Project Type
> - Description
> - URL/Project Homepage
> - Start
> - End
> - Primary Educational Sector
> 
> Organisationen
> - Name
> - Country
> - Address
> - Organization Type
> - Website
> - Description
> - Tags
> - Primary educational sector

**Comment by literarymachine** [comment]
> Suggestion by @trugwaldsaenger for minimal core set fields:

@trugwaldsaenger what about our other types?

**Comment by literarymachine** [comment]
Also, we need to specify what to include e.g. for the `Provider` of a `Service`. Only the `id`? Only the (English?) `name`? Both?

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?size=-1&ext=csv&filter.about.@type=Action
