### ISSUE TITLE
Item details: Link to lighthouse category

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1794]
![image](https://user-images.githubusercontent.com/777278/56291008-b2eb6900-6124-11e9-82f6-1e8be26879cc.png)

Link to https://oerworldmap.org/resource/?filter.about.objectIn.@type=LighthouseAction&sort=lighthouse_count:DESC to let interest users know, what lighthouses are

**Comment by literarymachine** [comment]
https://github.com/hbz/oerworldmap-ui/pull/568 implements the alternative @trugwaldsaenger specified in https://github.com/hbz/oerworldmap/issues/1864#issuecomment-524844793, closing.
