### ISSUE TITLE
Events > future/old events filter not implemented for map view

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1797]
Filter for future events is set, but all events are shown on map:

![image](https://user-images.githubusercontent.com/777278/56888089-8237f780-6a73-11e9-99ff-45c41103a490.png)

https://oerworldmap.org/resource/?q=oercamp&filter.about.@type=Event&map=4.68108,52.30718,4

**Comment by dobladov** [comment]
Confirmed, at the moment we only filter the list.

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?filter.about.%40type=Event

**Comment by trugwaldsaenger** [comment]
+1

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/pull/1812
