### ISSUE TITLE
Ask for preferred language instead of country in registration form.

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1804]
There is a drop down list of languages *the ui currently supports* in the upper right corner of the registration:

![image](https://user-images.githubusercontent.com/149825/57767759-6a66a180-770a-11e9-9293-dfecc2b580ad.png)

**Comment by programmieraffe** [comment]
I like the UI solution! 

Just to clarify it for me: Is the language stored in userprofile/usersettings?

**Comment by literarymachine** [comment]
> Just to clarify it for me: Is the language stored in userprofile/usersettings?

Yes, it is stored as an attribute in Keykloak.

**Comment by literarymachine** [comment]
Fixed in  #1742
