### ISSUE TITLE
Country disappears while scrolling out (beta)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1809]
http://recordit.co/yAyCNs2uoe

**Comment by literarymachine** [comment]
Fixed on beta, there is a short delay when bringing back the country when zooming out. We won't get around that for now, because there is an issue with mapbox and @dobladov had to implement a workaround.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/pull/516
