### ISSUE TITLE
Click path is not useful: Country > State > ??? (beta)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1810]
http://recordit.co/4RJJ0YyPnI

User clicked federal state, gets the same info pop-over again, clicks again -> pins should be shown?

**Comment by literarymachine** [comment]
@programmieraffe this type of feedback is best added to the corresponding issue #1799.

**Comment by literarymachine** [comment]
@dobladov solution:
- hide pop up for selected region
- add country / region statistics to info box

**Comment by literarymachine** [comment]
On beta:

![image](https://user-images.githubusercontent.com/149825/58254303-be0c6700-7d6a-11e9-9312-40903bdd7fe5.png)

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/pull/516
