### ISSUE TITLE
Country view is not mobile-device-optimized

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1814]
![image](https://user-images.githubusercontent.com/777278/58408232-af28fb80-806d-11e9-8dcb-7e0d02253740.png)

**Comment by dobladov** [comment]
New controls for the mobile view are implemented now.

![Screen Shot 2019-07-31 at 11 51 43-fullpage](https://user-images.githubusercontent.com/1938043/62202445-9993c300-b389-11e9-9c05-da1c04dddeea.png)
