### ISSUE TITLE
Quick-Fix: Slide up button for menu on mobile screens

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1819]
![image](https://user-images.githubusercontent.com/777278/58881392-6bbc3600-86da-11e9-85fa-0ab30907c457.png)

Talked with @trugwaldsaenger about this today, can we fix this between sprints? @literarymachine 

Mobile users (16% in May) deserve a good scrollable list :)

**Comment by trugwaldsaenger** [comment]
+1, is working fine on my desktop, Ipad and mobile!
