### ISSUE TITLE
Add new "map home button" to reset everything?

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1828]
It's good that users can now re-enter the landing page if they're logged in.

Now we need a solution for letting users get back to the full map without filters. Maybe a button next to the title or a Map-Icon?

**Comment by dobladov** [comment]
Added an icon next to the title.
![image](https://user-images.githubusercontent.com/1938043/62202239-3b66e000-b389-11e9-88ff-3adae8adc866.png)
