### ISSUE TITLE
Open Idea: Guided tour which introduces the pin show/hide selector

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1829]
We've introduced some new elements, but users don't really know. Offer them a short guided tour:

https://react-joyride.com/

**Comment by dobladov** [comment]
I completely agree with adding a tour.

![image](https://user-images.githubusercontent.com/1938043/60006788-6581ff80-9671-11e9-8d29-84da3e053fee.png)
Discussing with @formimkontext  we agreed that the guide message even when is useful for new users it takes a lot of space for the rest for the users that know how to use the site, the solution proposed was to add a modal at the beginning explaining the user some small instructions on how to use the site, this will only be show until the user presses hide and then not be show again.

Also combined with showing on the tooltip the possibility to click on a country or a region while hovering it.

![image](https://user-images.githubusercontent.com/1938043/60007136-05d82400-9672-11e9-9344-cd7c7be955dc.png)

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/:

![image](https://user-images.githubusercontent.com/149825/61709238-0803d000-ad4f-11e9-9b5a-50dce72ca661.png)

@trugwaldsaenger @programmieraffe next step would be for you to provide the actual narrative of the tour.

**Comment by programmieraffe** [comment]
Quick narrative:

1. Welcome to the OER world map! The OER World Map is a project which aims to illuminate the global Open Educational Resources movement by facilitating interaction and collaboration. We do that by collecting and sharing open data about actors and activities related to OER.

2. [Add entry] As a user you can add and modify entries. Every edit is valuable for us, thanks for joining us on our journey! To add something, just select add. 

[Sidenote: It would be really great if we could get back the "+"-button in the sidebar for adding entries :-)]

3. There are different data types which can be added. Do you want to explore the entries before adding a new one? Let's explore the map!

4. [Pin switch] This is our pin switch. You can hide and show the entry pins.

5. [Pin switch hide] If the pins are hidden, you can easily select a specific country. Let's explore Brasil. Recently we welcomed many new members in brasil.

6. [Select data type persons] To check out who is active in Open education in brasil, switch the category filter to "persons"

7. [Select Tel Amiel] This is Tel, he's our country champion. This means he recommend the OER world map and he is our contact regarding activies in brasil.

8. [Leave entry, select projects] What about projects? Let's check them out.

(Sidenote: subtype filter is still missing, we could explain it here :(( ;-))

9. [Leave country, select category events] We also collect events as well as stories. Let's leave this country and check out all of the upcoming events. 

10. [Select subfilter educational events, highered] We also can filter events based on educational sector. 

11. That was our quick tour. Do you have questions or suggestions? Contact Jan Neumann via info@oerworldmap.org. Now it's time to explore or register yourself, good luck on your journey to open education!

**Comment by programmieraffe** [comment]
**Tour 2 (simple approach, just highlight page sections):**

1. [Image placeholder - image of an OER event, e.g. https://www.oercamp.de/17/ost/bildergalerie/] Welcome to the OER world map! The OER World Map is a project which aims to illuminate the global Open Educational Resources movement by facilitating interaction and collaboration. We do that by collecting and sharing open data about actors and activities related to OER.

2. [Highlight "Add" entry in menu top-right] As an OER world map user you can add and modify entries. Every edit is valuable for us, thanks for joining us on our journey! To add something, just login and select add.

3. But first, let's explore the entries already added to the OER World map. There are different data types, let's explore them. 

4. Just one quick information before we explore the data entries about OER activities: The pin switch. It's our most important navigation element. You can hide and show the pins on the map. 

5. If the pins are hidden, you can easily select a specific country and its regions. Let's explore Brasil and a specific region. Recently we welcomed many new members in brasil. Here is how it's done:
[ GIF WITH COUNTRY / REGION SELECTION] 

6. [Highlight filters] Okay, back to data types. 

7. [Highlight a single filter] Explain every data type? Use description text from "add" hover main menu? 
![image](https://user-images.githubusercontent.com/777278/63260156-7a999a00-c280-11e9-81d4-bdcc3b1cdf8f.png)

8. [Highlight activity feed] To check out what's going on currently,use the Activity Feed. 

9. That was our quick tour. Do you have questions or suggestions? Contact Jan Neumann via info@oerworldmap.org. Now it's time to explore or register yourself, good luck on your open education journey.

**Comment by literarymachine** [comment]
> Tour 2 (simple approach, just highlight page sections):

On https://beta.oerworldmap.org/resource/

As for the order of the steps, @dobladov and I believe it is a bit jumpy right now. Suggestion:

1. [Image placeholder - image of an OER event, e.g. https://www.oercamp.de/17/ost/bildergalerie/] Welcome to the OER world map! The OER World Map is a project which aims to illuminate the global Open Educational Resources movement by facilitating interaction and collaboration. We do that by collecting and sharing open data about actors and activities related to OER.
2. [Highlight primary filter section] First, let's explore the entries already added to the OER World map. There are several different data types, let's take a look at those.
3. [Highlight every single filter] Explain every data type, using description text from "add" hover main menu.
4. [Highlight Pin Switch] Here is our pin switch. It's our most important navigation element. You can hide and show the pins on the map with it.
5. If the pins are hidden, you can easily select a specific country and its regions. Let's explore Brasil and a specific region. Recently we welcomed many new members in brasil. Here is how it's done:
[ GIF WITH COUNTRY / REGION SELECTION]
6. [Highlight "Add" entry in menu top-right]  As an OER world map user you can add and modify entries. Every edit is valuable for us, thanks for joining us on our journey! To add something, just login and select add.
7. [Highlight activity feed] To check out what's was recently added or edited, use the Activity Feed.
8. That was our quick tour. Do you have questions or suggestions? Contact Jan Neumann via info@oerworldmap.org. Now it's time to explore or register yourself, good luck on your open education journey.

**Comment by programmieraffe** [comment]
I like it a lot. I have many small improvements, but just about the content (Can I change them later easily?)

Changes regarding coding:
- I think the URL jump to https://beta.oerworldmap.org/country/br/mr/ is cool, but it is distracted. Please remove this jump, User should focus on the GIF 
(alternative: remove gif and show the info window over sidebar, so that it is clear what is happening? And just jump to https://beta.oerworldmap.org/country/br/)
- new step after filters (15) and before activity feed: highlight an entry in the left result list - "Just click on a entry to get the all associated information"
- on first page the "CC BY 4.0" must be linked to the URL https://creativecommons.org/licenses/by/4.0/deed.de

But in terms of review I think it is "good enough" to release it.

**Comment by trugwaldsaenger** [comment]
Some minor refinements

1.
Headline: "OER World Map" in capital letters

1.
Text: "Open Education Movement" instead of "Open Educational Resources movement"

2. 
OER World **M**ap

5.
Add full stop at the end of the sentence

8.
Exchange sentence: "A story publicated on the OER World Map plattform related to Open Education."

9. 
Exchane sentence: "A formal regulation or strategy regarding the creation and use of OER."

15.
OER **W**orld **M**ap

15.
Exchange second sentence: "Every edit is valuable, thanks for joining our collective journey!."

15. 
...and select **"**add**"**.

17.
Exchange second sentence: "Contact us via info@oerworldmap.org."

17.
Exchange last sentence: "Now it`s time to explore the map and register yourself. Good luck on your personal journey into Open Education!
