### ISSUE TITLE
Rework About page

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#183]
- Display logos on partnering orgnaizations
- Write new introduction, also welcoming newbies
- Write a Howto

**Comment by buschfeld** [comment]
All content based on the text draft by Jan and Rob.
Two alternative versions how to position text and style the background
- A: plain white BG alligned left
- B: white column centered above semi-transparent layer

![oer_16_demo_about_mapbg](https://cloud.githubusercontent.com/assets/10743356/8210525/b79da65a-1512-11e5-9715-65c01d7337a2.png)



P.S.: Did not really managed to handle the assign feature in my browser - please check ...

**Comment by acka47** [comment]
Done for now. Closing
