### ISSUE TITLE
UI shows two fields named location

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1832]
![grafik](https://user-images.githubusercontent.com/6639965/60289847-b1ee6900-9917-11e9-868b-61d459a94784.png)

**Comment by trugwaldsaenger** [comment]
I propose to name the first field "geografic focus" and the second "Author location"

**Comment by literarymachine** [comment]
Expected behavior: we actually allow multiple `locations` for publications, and they cannot be differentiated because they are just multiple values of the same field.
