### ISSUE TITLE
Password reset yields error

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1835]
Inputing email when asking for a password reset results in error message:

![error](https://user-images.githubusercontent.com/3904166/60596204-c82d7680-9da8-11e9-8711-07dc3666b6fc.png)

Goes to: https://oerworldmap.org/user/password/reset

**Comment by literarymachine** [comment]
There seems to have been an issue with the mail server, registration and password reset are working again. Closing.

**Comment by tamielbr** [comment]
Tried a couple of times just now, same error.

**Comment by literarymachine** [comment]
Works fine for our side - email is case sensitive, perhaps you have thus misspelled your address? I just entered the one registered in our system and there was no problem sending the mail. Should be in your mailbox now.

**Comment by literarymachine** [comment]
> Should be in your mailbox now.

I think you may have registered with an email address that is now invalid since our mail server could not deliver the email. Note that the email address in your profile is *not* necessarily the one connected to your account to log in.
