### ISSUE TITLE
Favicon from kibana overwrites general favicon? (Safari/OSX)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1837]
Provided by CF

Visited kibana, now safari icon for world map is still kibana?

**Comment by dobladov** [comment]
To close this issue is required to manually replace the icons in `/kibana/src/ui/public/assets/favicons` with this icons [Icons.zip](https://github.com/hbz/oerworldmap/files/3416570/Icons.zip)

**Comment by literarymachine** [comment]
Done, closing.
