### ISSUE TITLE
Bad request while registration

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1839]
Another case today, user tried three times
(informed me via private message)

**Comment by literarymachine** [comment]
Nothing wrong with the World Map itself, this seems to have been an issue with the hbz mail server. Closing.

**Comment by programmieraffe** [comment]
Just a quick addition:
The user tried three times and we have no way of seeing these errors as admins/staff? Would it be possible - that even if email fails - to register the user so that he/she can verify the account later when the email server is back alive?

(Registration numbers are a success criteria regarding funding goals)

If it is not easy to implement, just close it & we'll adress it in the new login system.

**Comment by literarymachine** [comment]
> Would it be possible - that even if email fails - to register the user so that he/she can verify the account later when the email server is back alive?

The user is actually registered even if the email server is down, but we indeed have no way for see this in our admin UI: https://github.com/hbz/oerworldmap/issues/1643

**Comment by literarymachine** [comment]
Fixed in  #1742
