### ISSUE TITLE
UI glitch: Hide filters (only on Chrome/Win10)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1840]
https://oerworldmap.org/country/de/nw?filter.about.primarySector.%40id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fsectors.json%23higherEd&size=20

Could not reproduce on Firefox/Win10

![worldmapgif (1)](https://user-images.githubusercontent.com/777278/61441033-144dee80-a945-11e9-96d5-e471d25cc576.gif)

**Comment by dobladov** [comment]
Confirmed, it also occurs with Chrome/Linux
