### ISSUE TITLE
Live-Event-Hashtags: Show pin popup/info if event is currently running and has a hashtag

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1844]
Idea by @trugwaldsaenger for a "dynamic map" experience, based on "vibrating data heart"-concept.

Add simple frontend code to highlight events, which
a) are currently running and
b) have a value in hashtag field

Implementation: e.g. pulsating or another custom marker/color?

a) https://bl.ocks.org/danswick/2f72bc392b65e77f6a9c

Add a Live-Button to Popup and Entry Details, e.g.:

![image](https://user-images.githubusercontent.com/777278/61708069-2f0cd280-ad4c-11e9-94c9-db62b1a6378e.png)

(I'm very open to other suggestions)

Button takes you to: https://twitter.com/search?q=%23CONFERENCEHASHTAG&src=typd

Needed changes as well:
- Change UI description for hashtag field to "Twitter-Hashtag" (no need to change data field for that, its just an experiment)

Open idea:

Also show events which will start soon in another color, e.g. set time filter to one day before.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/resource/

> Add a Live-Button to Popup and Entry Details, e.g.:

No button has been added to the popup because popups cannot be clicked. In the entry details, there is a button in the upper right.

@dobladov did quite some refactoring of the map and discovered a performance issue in the API. It will have to be fixed before this can be deployed to production.

**Comment by programmieraffe** [comment]
Could we match the color and make it more prominent? Also - if this would also vibrate, i would like it a lot :) 

Suggestion:

![image](https://user-images.githubusercontent.com/777278/63249479-d278d680-c269-11e9-917e-90cb15e1be95.png)

**Comment by literarymachine** [comment]
@literarymachine the API currently omits running events when "include past events" is not activated.

**Comment by programmieraffe** [comment]
Current state:
![image](https://user-images.githubusercontent.com/777278/67283981-ff00d700-f4d4-11e9-849c-34ad56e7c69f.png)

**Comment by literarymachine** [comment]
On beta, including performance fixes. See https://beta.oerworldmap.org/resource/
