### ISSUE TITLE
Drop down lists in policy template are not available

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1846]
Drow down lists for all fields in the policy template are not working.
https://oerworldmap.org/resource/?add=Policy
Could be a general problem...

**Comment by programmieraffe** [comment]
"Uncaught TypeError: i.vocab is not a function
   at t.value (bundle.js:20)
   at m (bundle.js:20)
   at v (bundle.js:20)
   at y (bundle.js:20)"

Win10/Chrome

**Comment by literarymachine** [comment]
Broken during refactor, fixed on production:

**Comment by literarymachine** [comment]
Fixed inhttps://github.com/hbz/oerworldmap-ui/commit/13155d805cd88a1e61a30c56bc10077f10565d78
