### ISSUE TITLE
Add new field "Policy focus" to policy template

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1847]
Values:

1. Pedagogy
2. Recognition
3. Content
4. Quality
5. Infrastructure
6. Strategy
7. Awareness Rising
8. Capacity Building
9. Collaboration
10. Research
11. Legal Framework
12. Funding
13. Access
14. Policy Making

It would be cool to keep the order of the values!
Helptext: "Please indicate here which topics are addressed by the policy."

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c

**Comment by trugwaldsaenger** [comment]
+1, working as expected
