### ISSUE TITLE
Kibana lists on policy registry show ID instead of expected name

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1848]
https://oerworldmap.org/oerpolicies

![grafik](https://user-images.githubusercontent.com/6639965/61952547-6b426c00-afb4-11e9-81fa-c1d98bb22fb7.png)

**Comment by literarymachine** [comment]
@dobladov could you look into this? This is most likely to switching to language maps for the `names` (as opposed to the arrays with `@language` and `@value` we used before).
