### ISSUE TITLE
Exchange Value in the Field Status

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1849]
https://oerworldmap.org/resource/?add=Policy
The current value "deactivated" should be changed into "ended".

**Comment by literarymachine** [comment]
Todo: [migrate data](https://oerworldmap.org/sparql/update?delete=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fstatus%3E+%22Deactivated%22+&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fstatus%3E+%22Ended%22+&where=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Fstatus%3E+%22Deactivated%22+) when 1cb0e4a has been deployed.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c

**Comment by trugwaldsaenger** [comment]
+1, works as expected, https://beta.oerworldmap.org/resource/urn:uuid:559f9959-0395-4815-a0f1-a7165498b6ba
