### ISSUE TITLE
Include field Affiliation to Policy Template

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1851]
https://oerworldmap.org/resource/?add=Policy

1. The existing field "Affiliation" should be added to the policy template.
1. It should be possible for a person to affiliate herself to a policy

Helptext: "Add your name here, if you have special knowledge about this policy or are somehow affilliated to this policy."

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c

**Comment by trugwaldsaenger** [comment]
+1, working as espected, see https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c
