### ISSUE TITLE
Add field "mentioned in" to policies

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1853]
https://oerworldmap.org/resource/?add=Policy
Currently it is only possible to add a policy to a publication in the field "mentions". It should be possible to add the relation from both sides.

The helptext should say: "Inlcude here a link to a publication, which mentiones the policy."

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c

**Comment by trugwaldsaenger** [comment]
+1, working as expected, see https://beta.oerworldmap.org/resource/urn%3Auuid%3Afdf9f5cf-7af5-4a7c-aa10-2f9a2ae37da6?
