### ISSUE TITLE
Sort fields within the policy template

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1854]
The fields of the policy templated should be sorted as following:

1. Title
1. URL
1. Type
1. Description
1. Level
1. Scope 
1. Focus
1. Primary educational sector
1. Secondary educational sector
1. Published by
1. Date published
1. Date ended (see #1855 )
1. Status
1. Authored by
1. Additional authors
1. Contact (see #1850 )
1. Affiliated (see #1851 )
1. Language
1. License of policy document
1. Country
1. Region
1. Based on
1. Basis for
1. Mentioned in (see #1853 )
1. Awards
1. Tags

**Comment by trugwaldsaenger** [comment]
Not sure, if this can be done within the next sprint. If this is not possible, no problem!

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:02bc2455-3ef6-4b0f-97b0-01b36094345c#edit

**Comment by trugwaldsaenger** [comment]
+1, order of fields is as expected!
