### ISSUE TITLE
Provide a more friendly message after registration

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1860]

**Comment by programmieraffe** [comment]
![Bildschirmfoto 2019-08-22 um 11 40 11](https://user-images.githubusercontent.com/777278/63504426-d1e27900-c4d1-11e9-972f-d88b5c9d597f.png)

This is a warning, user expects a

"Thanks very much joining"

"Success"

Green tick icon, etc.

**Comment by programmieraffe** [comment]
Also - could we show the emailadress user entered, so that he/she can be sure to which email this went?

**Comment by friedelitis** [comment]
"One more thing: to verify that it belongs to you, we need you to **verify your email address by clicking a link we just sent to your inbox**. It will take you just a second and it will help us to keep spam and abuse to a minimum on the World Map. Thanks in advance for your help!"

**Comment by dobladov** [comment]
![image](https://user-images.githubusercontent.com/1938043/69875942-98828c00-12be-11ea-8512-a13e4d048d95.png)

I updated the English text and style.

> "One more thing: to verify that it belongs to you, we need you to verify your email address by clicking a link we just sent to your inbox. It will take you just a second and it will help us to keep spam and abuse to a minimum on the World Map. Thanks in advance for your help!"

We need this text in German and Portuguese (@tamielbr) before deployment since these translations are not in Crowdin.

**Comment by tamielbr** [comment]
PT_br: "Mais uma coisa: para verificar que pertence a você, precisamos que você verifique seu endereço de e-mail clicando em um link que enviamos para sua caixa de entrada. Vai lhe tomar apenas um segundo e vai nos ajudar a manter o spam e o abuso a um nível mínimo no Mapa Global REA. Obrigado desde já pela sua ajuda!"
