### ISSUE TITLE
Clarify display of lighthouses

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1864]
It is great to see, that the use of lighthouses and likes is increasing. In order to make the functionality more usable, I would propose two improvements:

1) Within the [list of lighthouses](https://oerworldmap.org/resource/?filter.about.objectIn.@type=LighthouseAction&sort=lighthouse_count:DESC) the number of received lighthouses should be shown in brackets behind the name. I think we already had this implemented in the past. Also at the beginning of the list it should say "ordered by the number of lighthouses" and not "ordered by the date created".

2) Within the profile the number of lighthouses is shown. This should be linked to the lighthouse comments, so that a user can find them easily.

Both improvements should be done for likes accordingly.

**Comment by trugwaldsaenger** [comment]
![screenshot-lighthouse](https://user-images.githubusercontent.com/6639965/63691472-94525880-c80f-11e9-82df-7f62920ee779.JPG)

**Comment by trugwaldsaenger** [comment]
![screenshot-lighthouse3](https://user-images.githubusercontent.com/6639965/63691492-a46a3800-c80f-11e9-857f-8d6b0f5459e1.JPG)

**Comment by literarymachine** [comment]
@dobladov we should try to show the number of lighthouses and likes after the abbreviation in brackets.

**Comment by trugwaldsaenger** [comment]
Showing the numbers in brackets would be one solution - I would also support the idea of @literarymachine to show number of likes and lighthouses with icons and in grey. Very likely this will look nicer than haven two sets of brackets, one for the abbreviation and the other for the likes/lighthouses.

**Comment by literarymachine** [comment]
On production, see e.g. https://oerworldmap.org/resource/?filter.about.objectIn.@type=LighthouseAction&sort=lighthouse_count:DESC and https://oerworldmap.org/resource/?filter.about.objectIn.@type=LikeAction&sort=like_count:DESC

Also see https://oerworldmap.org/resource/urn:uuid:0a7536ac-3b85-11e5-be26-54ee7558c81f#lighthouses

**Comment by literarymachine** [comment]
![Filters](https://user-images.githubusercontent.com/1938043/67278449-4aad8380-f4c9-11e9-90ce-d6480805b394.gif)
![Link](https://user-images.githubusercontent.com/1938043/67278536-73ce1400-f4c9-11e9-8ef5-830c79dcf116.gif)

**Comment by trugwaldsaenger** [comment]
I Love it :-) ! Closing
