### ISSUE TITLE
Homepage layout broken on Ipad 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1865]
Observed on iOS 12.1.4 similar on both Firefox and Safari browser
![Datei 26 08 19, 14 57 06](https://user-images.githubusercontent.com/6639965/63692713-95d15000-c812-11e9-9a42-5035172c01cd.jpeg)

**Comment by dobladov** [comment]
I was able to recreate the issue by setting a browser language that is not in the list of the supported ones.

![image](https://user-images.githubusercontent.com/1938043/63769474-325b2700-c8d3-11e9-800d-4408d6be5540.png)

I think we can assume the issue is not related to iOS.
