### ISSUE TITLE
Export seems to only export fields in EN

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1868]
Using the export function on the map, I get a CSV file that seems to contain:

![export](https://user-images.githubusercontent.com/3904166/64782678-324a6080-d53c-11e9-9006-aa8a94b0f9f3.png)

* Non-language specific concent (e.g. country)
* Language specific-content only in EN (e.g. `/additionalType/0/name/**en**`)
* Many empty fields on language-specific content that exists, which seems to indicate that ther ir no **en** content, but **pt** content not exported.

It would be useful to export all content available for the viewable list of entries. As a sugested feature, we could allow the selection of languages on export.

**Comment by tamielbr** [comment]
I see what you mean. Perhaps the export function could identify languages and these could be checkboxed? The use case: we're updating all 190 entries in Brazil. Exporting will allow us to at least get the names on a table and then work on them as a checklist of what is done. Since names are in PT_br, we get many empty, unless the names were also put in English (which many times is just a duplicate).

**Comment by tamielbr** [comment]
@literarymachine any chance you might be able to export all of Brazil in all languages for now, just for our current work updating entries? This will help us make sure we don't miss anything.

**Comment by literarymachine** [comment]
> @literarymachine any chance you might be able to export all of Brazil in all languages for now, just for our current work updating entries? This will help us make sure we don't miss anything.

Sorry for the late response - I am currently travelling, but I'll see what I can do ASAP!

**Comment by literarymachine** [comment]
I just sent you an email, but it was rejected by your inbox.

**Comment by trugwaldsaenger** [comment]
@tamielbr: Can we close this issue?

**Comment by tamielbr** [comment]
Yes, got the data.
