### ISSUE TITLE
Language selector is not in alphabetical order

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1870]
Adding a language to description, the drop down menu is not in alphabetical order which makes it hard to find some languages. 
Can't screen capture the dropdown (it doesn't remain when switching windows).

![language](https://user-images.githubusercontent.com/3904166/66128365-175f8f00-e5c4-11e9-8c09-84c34d439b22.png)

**Comment by trugwaldsaenger** [comment]
Good point @tamielbr! We will have a look at this. I checked and it seems to me that the quality of the alphabetical order seems to differ in different languages. For example it looks better in German than in English.

**Comment by trugwaldsaenger** [comment]
One more question @tamielbr : How urgent is this issue for your work? If you know the language you are looking for, you can find it by typing in the first characters.

**Comment by literarymachine** [comment]
@dobladov we might want to look into using a more sophisticated type ahead widget here.

**Comment by tamielbr** [comment]
> One more question @tamielbr : How urgent is this issue for your work? If you know the language you are looking for, you can find it by typing in the first characters.

Not urgent at all. We can (have been) working around it, but just pointing out what would be user expectation (alphabetical).

**Comment by literarymachine** [comment]
On production, see e.g. https://oerworldmap.org/resource/?add=Organization

**Comment by trugwaldsaenger** [comment]
Looks fine! Closing!
