### ISSUE TITLE
Error in adding policy with 1 value in focus-field

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1871]
Adding policies results in error message: "Internal Server Error" and nothing else. Seems to happen only with policies.

Adding "District Law 5,592/2015" just now threw errors. We also had errors with "Municipal Decree of the City of São Paulo (52,681/2011)" which ended up showing five times in the map.

**Comment by tamielbr** [comment]
One sure way to get an error is in FOCUS to select the ACCESS option. We get `Bad request` error page.

**Comment by trugwaldsaenger** [comment]
This seems to be an issue, which I thought we already solved. The problem appears, when within the field "focus" just one value is choosen. When choosing two values, its possible to save the entries.

@tamielbr: I will delete the new entries marked a "tobedeleted" ASAP!

**Comment by literarymachine** [comment]
Fixed on production, see e.g. https://oerworldmap.org/resource/urn:uuid:ebd436b2-729c-4bec-989a-119c424c2edf

**Comment by trugwaldsaenger** [comment]
I was able to add one value in the focus field for the OER policy in Reutlingen:
https://oerworldmap.org/resource/urn:uuid:0d95023f-a071-4113-a215-cddd818c3017

**Comment by trugwaldsaenger** [comment]
Closing. @tamielbr: If you still observe any issues with this, please let us know!

**Comment by trugwaldsaenger** [comment]
Sidenote: When searching for "District Law 5,592/2015" I receive an error message. Seems to be connected to the slash - when searching for "District Law 5,592 2015" everything works fine. @literarymachine shall we make a seperate issue for this?

**Comment by literarymachine** [comment]
> @literarymachine shall we make a seperate issue for this?

There already is: https://github.com/hbz/oerworldmap/issues/1872
