### ISSUE TITLE
Error when including "/" in search (Internal Server Error)

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1872]
Search for "cne/ces" entry (which exsits) (the resulting URL is `https://oerworldmap.org/resource/?q=cne%2Fces&size=20`) results in _Internal server error_

Changing the POI name to "cne-ces" and searching for this string (the resulting URL is `https://oerworldmap.org/resource/?q=cne-ces&size=20`) does not give error.

Removing `/` seems to solve the problem, no errors.

**Comment by acka47** [comment]
It also works with a phrase search, like ["cne/ces"](https://oerworldmap.org/resource/?q=%22cne%2Fces%22&size=20)

**Comment by trugwaldsaenger** [comment]
Looks to me as if the lack of a comprehensive documentation is rather the issue here. Do you agree @tamielbr ?

**Comment by tamielbr** [comment]
I'm not sure - should w enot allow "/" to be used as part of names? If so, yes - but perhaps it could be flagged on entry.

**Comment by trugwaldsaenger** [comment]
@acka47: Do you have a good answer for @tamielbr?

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/d65ce17c1dca366131dc4aafd90cc6e2c4629c1f, see https://oerworldmap.org/resource/?q=%22cne%2Fces%22
