### ISSUE TITLE
Can't edit organization type

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1874]
Trying to edit the organization type for URI `https://oerworldmap.org/resource/urn:uuid:c25253a7-b17b-4e58-9464-fd2e9ae4337b`, clicking on publish doesn't go anywhere. Button changes color to orange, when clicked, but seems not to be activated.

**Comment by acka47** [comment]
Thanks for the report, Tel (and all the others). I am able to reproduce this bug.

**Comment by trugwaldsaenger** [comment]
Yes, I cannot edit this entry as well. Might be something specific with this entry since I can edit other organisations.

**Comment by trugwaldsaenger** [comment]
I was able to change edit the insitutional type. I assume @tamielbr and @acka47 can do so as well and close the issue!

**Comment by tamielbr** [comment]
Seems like this one has a similar problem, still. Can't edit and publish - button changes color, but no effect. Tried with three different users and different machines:

https://oerworldmap.org/resource/urn:uuid:9a030999-4d38-44fa-879c-c7fa63925a77?

**Comment by literarymachine** [comment]
Confirmed, this is also a schema issue related to the introduction of the `Policy` type.
