### ISSUE TITLE
Date inserted for services shows YEAR-1

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1875]
When insering year (for example "2011"), and saving the actual date shows "2010", one less. See for example: https://oerworldmap.org/resource/urn:uuid:58473b0a-d36f-43b2-9ba0-b50e9137158e which should be 2013.

**Comment by acka47** [comment]
Thanks for the report. I could not even lookup the example resource you provided. Currently, there strangely exist two start dates in the data: `"startDate" : [ "2014", "2013" ]` @literarymachine, I tried to remove one date via SPARQL and API but didn't succeed (it might be my mistake).

**Comment by literarymachine** [comment]
> @literarymachine, I tried to remove one date via SPARQL and API but didn't succeed (it might be my mistake).

I cleaned up the date using SPARQL and also tried editing the date and all seems fine to me. @tamielbr do you have any additional examples? The only thing that I can think of is that this could somehow be related to your time zone.

**Comment by tamielbr** [comment]
I think all of them. See this example (https://oerworldmap.org/resource/urn:uuid:151ffc2f-60d2-4c86-9320-d1ad0a4f1cb0#view).

**View**
![esc_1](https://user-images.githubusercontent.com/3904166/67223783-453b3500-f406-11e9-9e60-5bf34b9b73ab.png)

**Edit**
![esc_2](https://user-images.githubusercontent.com/3904166/67223784-453b3500-f406-11e9-884c-a014ba377c82.png)

**Comment by literarymachine** [comment]
Interesting, I think it really is a problem with mistakenly handling this with a locale timezone (2013 is interpreted as midnight Jan 01 in GMT which is still 2012 in Brazil). All is fine from here:

![image](https://user-images.githubusercontent.com/149825/67278461-4ed9a100-f4c9-11e9-82b0-0effb356c0ad.png)

@dobladov could you look into why this is happening?

**Comment by literarymachine** [comment]
On production, see e.g. https://oerworldmap.org/resource/urn:uuid:151ffc2f-60d2-4c86-9320-d1ad0a4f1cb0

**Comment by literarymachine** [comment]
@tamielbr please give us a short +1 here if this works for you. Thanks!

**Comment by trugwaldsaenger** [comment]
Hard for me to test, but looks fine...

**Comment by literarymachine** [comment]
> Hard for me to test, but looks fine...

That is why it is assigned to @tamielbr ;-)
