### ISSUE TITLE
Cookie notice on Chrome/Windows: cross-site cookie

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1876]
"A cookie associated with a cross-site resource at http://hbz-nrw.de/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."

**Comment by trugwaldsaenger** [comment]
Cannot judge the priority of this issue. @programmieraffe & @literarymachine : Is this something we have to address during our october-sprint?

**Comment by programmieraffe** [comment]
![image](https://user-images.githubusercontent.com/777278/67194043-a78c3980-f3f6-11e9-9244-6a7d22f496a1.png)

**Comment by programmieraffe** [comment]
2DO: check if we can change the value in matomo

**Comment by programmieraffe** [comment]
Will be fixed in a future release of matomo, closing it now.
https://github.com/matomo-org/matomo/issues/14395
