### ISSUE TITLE
Allow organizations as regionalChampionFor

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1879]

**Comment by literarymachine** [comment]
On production, see e.g. https://oerworldmap.org/country/de/nw

**Comment by trugwaldsaenger** [comment]
Works fine for both projects and organization. Keep in mind that the structure of the key must follow "DE.RP". Closing

**Comment by trugwaldsaenger** [comment]
Sidenote: The front end has to be adapted: When clicking on a state the regional champion should be opened and the country champion closed.

**Comment by trugwaldsaenger** [comment]
![grafik](https://user-images.githubusercontent.com/6639965/67376780-fe277e00-f584-11e9-9210-56583a2c1662.png)
