### ISSUE TITLE
Prevent mixed-content warning

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#1880]
...by using protocol relative links for external images.

**Comment by programmieraffe** [comment]
Example:
![image](https://user-images.githubusercontent.com/777278/67194146-d4d8e780-f3f6-11e9-810d-71c4885afc3d.png)

**Comment by literarymachine** [comment]
To prevent what @tamielbr is experiencing in 
 https://github.com/hbz/oerworldmap/issues/647#issuecomment-545054968 we could validate the logo fields to allow `https` only.

**Comment by trugwaldsaenger** [comment]
@programmieraffe: Could you have a look at this?
