### ISSUE TITLE
Provide better welcome message for new users

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1886]
New registered users will now be redirected to the following screen where they can decide wheter they want a public profile on OER world map:
https://oerworldmap.org/user/profile?language=en#edit
![Bildschirmfoto 2019-10-24 um 10 58 26](https://user-images.githubusercontent.com/777278/67469942-3eeaca00-f64d-11e9-847a-61e0b2d98fff.png)

Problem: It is not clear that their profile is not yet published, we could solve this by a better welcome message

We'll talk with Christian about that because it is also relevant to community development.

**Comment by friedelitis** [comment]
"Add a few details about yourself, your work and your expertise in just a few steps. Hit "publish" and others will find you and your work on the World Map!"
