### ISSUE TITLE
Mobile: Language switch in login system not visible

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1887]
![image](https://user-images.githubusercontent.com/777278/67470956-ec121200-f64e-11e9-9866-766a8850cc2d.png)

Chrome-App/Android

**Comment by dobladov** [comment]
Fixed with: https://github.com/hbz/oerworldmap-keycloak-theme/commit/f26d9b9f0537ef6033d6b8e9b9e0251a2612b934

![image](https://user-images.githubusercontent.com/1938043/67685990-49cb9480-f996-11e9-848c-f8bcf65bfcac.png)

**Comment by literarymachine** [comment]
+1, closing
