### ISSUE TITLE
Detail view of entries: Move mini-map to the right / finetune header

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1889]
We removed the map for policies (https://github.com/hbz/oerworldmap/issues/1767), but somehow we forgot about the other detail views :)

Suggestions:

a) Move the mini-map from header to the location row:

![image](https://user-images.githubusercontent.com/777278/68120164-f82a8900-ff04-11e9-98e3-00b0d7a8e81f.png)

Also two aspects related to this:

b) Editing history should also be shown to non-logged-in-users? 
c) "Login to edit" is very useful, but it is way to distracting right now and has no icon?
![image](https://user-images.githubusercontent.com/777278/68120398-8d2d8200-ff05-11e9-9987-7951502275a0.png)

Quick suggestion for c)

![image](https://user-images.githubusercontent.com/777278/68120652-32485a80-ff06-11e9-91bb-f24f1c115a44.png)

**Comment by dobladov** [comment]
We need to think where to put the logo, at the moment I sketched this to put it over or under the location.

Please give some feedback or another possible solution and I will implement it.

![image](https://user-images.githubusercontent.com/1938043/68203170-836b5380-ffc5-11e9-96b7-3c6465331cfd.png)
![image](https://user-images.githubusercontent.com/1938043/68203187-8a926180-ffc5-11e9-9565-27b4659f5854.png)

Also @literarymachine  suggested to get rid of the default type image if the resource has no images.

![image](https://user-images.githubusercontent.com/1938043/68203199-8fefac00-ffc5-11e9-9d6a-ec9d2718c37f.png)

**Comment by programmieraffe** [comment]
Nice!

- Yes, +1 for removing the default image.
- I like the solution with the image above the location field.

Personally I feel like there is too much whitespace above the h1 title?

I don't like the link icon with no description, I think the old solution with the shortened link was better and more easy to find/to understand.

Two possibilities I see:
a) Link beneath the title and above the description
b) Link in the right sidebar as well with divider and tab title "Website"

![image](https://user-images.githubusercontent.com/777278/68205035-92ec9b80-ffc9-11e9-9181-5a83e11d2255.png)

**Comment by dobladov** [comment]
>I don't like the link icon with no description, I think the old solution with the shortened link was better and more easy to find/to understand.

The mentioned icon is for the social links (twitter, facebook, external) and is not the same as the one mentionen on this issue https://github.com/hbz/oerworldmap/issues/1890, 

At the moment is looking like this in the current PR https://github.com/hbz/oerworldmap-ui/compare/1889-DetailsForEntries?expand=1
![image](https://user-images.githubusercontent.com/1938043/68213570-2038eb80-ffdc-11e9-9f21-87ccd8a5b2e0.png)

**Comment by programmieraffe** [comment]
Ah okay, sorry :)

I like!
Small last wish: Could we align icons and the sub title?
![image](https://user-images.githubusercontent.com/777278/68216965-187c4580-ffe2-11e9-9d74-d22bf371722a.png)
