### ISSUE TITLE
Suggestion: Easier way to return to the map (header logo)

### ISSUE THREAD

**Issue by programmieraffe** [hbz/oerworldmap#1898]
Problem: User navigates to oerworldmap.org/resources/, wants to reset the map (tries it via top left brand link in header, but lands in landing page. Navigation elements (globe icon for map) is not visually separated/easy to understand in a split time of seconds)

Inspiration - t3n solves this quite well:

https://t3n.de/

User navigates to https://t3n.de/pioneers/das-netzwerk/

Clicking left top brand lets user return to startpage of pioneers network

![image](https://user-images.githubusercontent.com/777278/68466540-e69ef500-0214-11ea-992f-98482944cc4c.png)

Startpage (t3n) is accessible via another link which clearly states "t3n".de

**Comment by dobladov** [comment]
![image](https://user-images.githubusercontent.com/1938043/69617308-4f210b00-1038-11ea-89ba-dcb4f460a211.png)

Is this issue solved by these changes?

**Comment by gandalfar** [comment]
I've checked and this is fixed by new version.
