### ISSUE TITLE
Find OER Funders

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#191]
Story:
As an OER project I would like to find someone who funds my project, so that I can start my project (or keep it running).
Alternative Story:
As an policy analyst I would like to see how the OER development is financed.

**Comment by trugwaldsaenger** [comment]
There seem to be at least two possibilies to provide the necessary data for this story: 
- tag organizations as "funders"
- include "funding" as a subtype of "service"

**Comment by acka47** [comment]
I just stumbled over the [Open Funder Registry](http://www.crossref.org/fundingdata/registry.html) by CrossRef. It's CC0 licensed and data comes in different formats, including JSON. There are already a lot of research funders in there, also [Hewlett Foundation](http://data.crossref.org/fundingdata/funder/10.13039/100004439). For more information see http://www.crossref.org/fundingdata/index.html.

We should at least at links to the resources there when we collect funders ourselves.

**Comment by literarymachine** [comment]
Fixed by `organization` sub-type [`funding body`](https://oerworldmap.org/resource/?filter.about.additionalType.@id=https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Forganizations.json%23fundingBody).
