### ISSUE TITLE
University of the South Pacific hard to find

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1910]
There is an entry for the University of the South Pacific:
https://oerworldmap.org/resource/urn:uuid:3de31e3b-85b3-4cd8-839c-592345d1bffd

When searching for this entry I receive the (related) OER Repository of the University of the South Pacific as first hit:
https://oerworldmap.org/resource/urn%3Auuid%3Ad9957074-309d-4033-a846-c154fb1d0f90

The profil of the University of the South Pacific does not appear in the list, respectively appears very late. Even when restricting my search to Organisations, the entry appears on page 4 of the search result list:
https://oerworldmap.org/resource/?q=%22University+of+the+south+pacific%22&filter.about.%40type=%22Organization%22

Issue might be connected to the fact, that the entry does not have a description.

**Comment by literarymachine** [comment]
> Issue might be connected to the fact, that the entry does not have a description.

Why not add a description?

**Comment by trugwaldsaenger** [comment]
Searching for "Merlot" I receive a result-list, where three entries, which carry "Merlot" in the name appear on position 9-11: https://oerworldmap.org/resource/?q=%22Merlot%22
All three entries include "Merlot" also in the description.
