### ISSUE TITLE
After server reboot oerworldmap didn't start up automatically

### ISSUE THREAD

**Issue by dr0i** [hbz/oerworldmap#1912]
There was an incident at 2020-05-06: the vm-server crashed and went to reboot. Unfortunately the oerworldmap instance didn't came up automatically.

Tasks:
- [x]  add startup init process
- [x]  add `monit`
- [x]  analyze logs.

**Comment by acka47** [comment]
Have you noticed the email by W.T. from 2020-06-05? I quote:

> Der Absturz der Maschine hat nicht direkt mit OER zu tun.
> 
> Bei Gelegenheit würde ich gerne eine neue formale VM für OER anlegen und 
> das System (die Platte) der neuen VM zuweisen. Vielleicht ist dieses 
> lästige Problem dann behoben.

Maybe we should rather do this first? Or does one not have anything to do with the other?

**Comment by dr0i** [comment]
Both actions are indicated. Even a new machine will not guarantee a non-crashing system.
As we don't have a redundant, high-available proxy like in lobid for oerworldmap, I would at least  add minimal "self-healing" processes like for skohub (e.g. https://github.com/hbz/skohub-pubsub/pull/34).

**Comment by dr0i** [comment]
The service is already available for `systemctl`, but it's not `enabled` (i.e. configured to automatically start after reboot:)
```
www:~ # systemctl status oerworldmap.service
● oerworldmap.service - OER World Map API
   Loaded: loaded (/etc/systemd/system/oerworldmap.service; disabled; vendor preset: disabled)
```

The `enabled` ones are also seen in `/etc/systemd/system/multi-user.target.wants/` where a link for `oerworlmap-ui` exists (and which did came up automatically) . It's missing for `oerworldmap`.
So we enable it like this:
```
www:~ # systemctl enable oerworldmap.service 
Created symlink from /etc/systemd/system/multi-user.target.wants/oerworldmap.service to /etc/systemd/system/oerworldmap.service
```
And check it:
```
www:~ #  systemctl status oerworldmap.service
● oerworldmap.service - OER World Map API
   Loaded: loaded (/etc/systemd/system/oerworldmap.service; enabled;
```
`apache` is already enabled so we leave at this.

**Comment by dr0i** [comment]
Also added monitoring with `monit`.
Closing.
