### ISSUE TITLE
Opening a link to a profile as a logged in user opens editing mode directly

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1915]
1. I´m loggin in (using firefox)
2. I´m opening a link to a profile, e.g.: https://oerworldmap.org/resource/urn:uuid:b2c85d7b-9fa7-4cf8-8edd-d9b522b3795e
3. The editing mode is opened automatically, the view mode is displayed under the editing mode publishing is not possible

![grafik](https://user-images.githubusercontent.com/6639965/84251008-0aa91880-ab0d-11ea-843f-4c7f1e8e8e6f.png)

**Comment by literarymachine** [comment]
Deployed to beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:663b7ddb-1fd8-44f8-96b1-db8110084104#edit:

![image](https://user-images.githubusercontent.com/149825/90376972-97290780-e077-11ea-95a7-7543e654d7df.png)

**Comment by gandalfar** [comment]
I can confirm that clicking on https://beta.oerworldmap.org/resource/urn:uuid:663b7ddb-1fd8-44f8-96b1-db8110084104 doesn't open edit mode anymore.

**Comment by trugwaldsaenger** [comment]
Confirmed, opening a link to a profile as a logged in user on beta does not open the editing mode any longer, nor does it show the broken UI any longer!
