### ISSUE TITLE
Reactive Search filter displays only part of the policies, which carry information in the focus field

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1917]
![grafik](https://user-images.githubusercontent.com/6639965/84256178-dd139d80-ab13-11ea-8498-dde39d7dc9f9.png)

According to the numbers displayed behind the values there should be only 29 policies carrying a focus-value. After looking at many random samples it seems as if all are carrying a focus-value.

**Comment by literarymachine** [comment]
Looking directly at the search index, it looks like only 13 documents have focus values set: https://oerworldmap.org/elastic/_search?q=_exists_:about.focus.keyword&_source_includes=about.focus&size=100

Do you have an actual example of a problematic item?

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/commit/eb0107cb133842e3614bc1048ee327a591cb353b

![image](https://user-images.githubusercontent.com/149825/84783209-477f7e80-afe9-11ea-93d6-dade9c1375fc.png)

**Comment by trugwaldsaenger** [comment]
confirmed, working and looking good!
