### ISSUE TITLE
Clicking on find/country champions delivers no hits

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1918]
![grafik](https://user-images.githubusercontent.com/6639965/84257811-3977bc80-ab16-11ea-8099-93c72033031c.png)

**Comment by literarymachine** [comment]
@gandalfar last time I checked it worked, but this could well have been broken with https://github.com/hbz/oerworldmap-ui/pull/623/files where the `DataSearch` widget of ReactiveSearch was reconfigured. In general, the query works: https://oerworldmap.org/elastic/_search?q=_exists_:about.countryChampionFor

**Comment by literarymachine** [comment]
Deployed to beta, see https://beta.oerworldmap.org/resource/?q=%22_exists_:about.countryChampionFor%22:

![image](https://user-images.githubusercontent.com/149825/90376278-7dd38b80-e076-11ea-8b92-076e3147793a.png)

**Comment by trugwaldsaenger** [comment]
+1 List of country champions appears again!
