### ISSUE TITLE
Location field for policies missing

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1920]
Issue #1916 describes that inherited locations are not working properly, which is also true for policies. 

Depending on the approach, it would also be possible to cut of the inheriting-process and request that also for policies, the adress should be included directly manually. This is currently not possible, since the fields necessary for this are not available:

![grafik](https://user-images.githubusercontent.com/6639965/84663569-a972b200-af1d-11ea-8a70-3e87da9bb08c.png)

**Comment by literarymachine** [comment]
> Depending on the approach, it would also be possible to cut of the inheriting-process and request that also for policies, the adress should be included directly manually. This is currently not possible, since the fields necessary for this are not available:

Please note that when we imported the initial data from the CC policy registry, we decided to always use the location of the publisher. I cannot recall exactly what the country and region fields contain. Maybe you should dig through some old issues before making a decision here?

**Comment by trugwaldsaenger** [comment]
I did not mean to take a decision here. If inheriting geolocation from the publisher works, this is fine for me. Alternatively it would be also OK, if we could add the location manually, but in this case the necessary fields have to be added to the template.

**Comment by literarymachine** [comment]
Fixed in eb0107cb133842e3614bc1048ee327a591cb353b

**Comment by trugwaldsaenger** [comment]
Confirmed, after @literarymachine and @dr0i fixed #1919 this workaround is currently not needed. But we might decide to get rid of inherited geo-location and come back to this question again.
