### ISSUE TITLE
Field to set country champion might be missing

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1921]
Not sure if it was lost during the switch to reactive search or if I have tomatos on my eyes...

**Comment by trugwaldsaenger** [comment]
Solution still waits to be implemented

**Comment by literarymachine** [comment]
This has been fixed in https://github.com/hbz/oerworldmap-ui/pull/626 for a while, @dr0i please deploy if you have a minute!

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:663b7ddb-1fd8-44f8-96b1-db8110084104#edit:
![image](https://user-images.githubusercontent.com/149825/90410515-bb520c00-e0aa-11ea-99ef-b3c401cb2b5d.png)

**Comment by trugwaldsaenger** [comment]
+1 reappeared and working!
