### ISSUE TITLE
Logo is inserted, valid URL, but doesn't show

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1922]
POI:
* https://oerworldmap.org/resource/urn:uuid:706b0214-77eb-11e5-9f9f-c48e8ff4ea31
Link to logo, inserted is valid:
* http://grupomontevideo.org/escala/images/Logos/UNC.jpg

Results
* POI shows but no logo.

Thought we had this problem in the past, but searched and couldn't find the issue.

**Comment by acka47** [comment]
Hi Tel, I assume, the problem is that the image link is not https. If it was the logo would be shown.

**Comment by literarymachine** [comment]
> Hi Tel, I assume, the problem is that the image link is not https. If it was the logo would be shown.

Exactly! We strip the protocol part and turn the link into protocol-relative to prevent mixed-content warnings. https://grupomontevideo.org/escala/images/Logos/UNC.jpg cannot be reached though.
