### ISSUE TITLE
assignment of editing rights currently not supported by frontend

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1923]
In the past I was able to assigne editing rights (especially the opportunity to delete entries) to new editors. This functionality seemingly was lost during one of the last updates. Mayb just the corresponding button disappeared.

**Comment by literarymachine** [comment]
Assigning roles (`admin` being the necessary one here) is now done in Keycloak.

**Comment by literarymachine** [comment]
@trugwaldsaenger @gandalfar We can take a look at this together on Wednesday's call!
