### ISSUE TITLE
list of existing tags is not shown when entering a new tag

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1924]
When adding a tag to an entry, normally a list of existing keywords should be displayed. Currently this functionality is not working. In the attached screenshot I´m trying to add the tag "policy advisor" to an profile. Since this tag already exists, it should be possible to choose it from a list. Nevertheless the system offers to create a new tag called "policy advisor". 

![grafik](https://user-images.githubusercontent.com/6639965/89192650-14974700-d5a5-11ea-9c52-1f7e6e525e3e.png)

**Comment by trugwaldsaenger** [comment]
Just noticed, that the tag policy advisor cannot be found using the search interface as well:
![grafik](https://user-images.githubusercontent.com/6639965/89196040-f253f800-d5a9-11ea-9567-c7eda72a61df.png)
Nevertheless it definetly exists in the database:
https://oerworldmap.org/resource/?filter.about.keywords=[%22policy%20advisor%22]

**Comment by literarymachine** [comment]
> Just noticed, that the tag policy advisor cannot be found using the search interface as well:

Confirmed, the tag filter is currently limited to the top 100 tags.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:663b7ddb-1fd8-44f8-96b1-db8110084104#edit:

![image](https://user-images.githubusercontent.com/149825/90377128-d22b3b00-e077-11ea-83aa-8965758d2382.png)
