### ISSUE TITLE
Map legend shows no/wrong values

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1926]
![grafik](https://user-images.githubusercontent.com/6639965/89194184-52956a80-d5a7-11ea-95bf-71d2f0362dfa.png)

"Entries per country" currently says "from 0 till 0". It should say "from 0 till x", where as x stands for the highest number of entries a contry has.

**Comment by literarymachine** [comment]
Deployed to beta, see https://beta.oerworldmap.org/resource/?view=map:

![image](https://user-images.githubusercontent.com/149825/90376192-567cbe80-e076-11ea-8ed0-a4126c06d123.png)

**Comment by trugwaldsaenger** [comment]
+1
