### ISSUE TITLE
Document keycloak setup

### ISSUE THREAD

**Issue by gandalfar** [hbz/oerworldmap#1927]
README has the following steps:

```
Configure default actions
Configure admin credentials in application.conf
Copy create profile script to registration flow
Copy create profile script to first-broker-login flow
Set up Mappers for profile_id and groups
```

I can't figure out what exact steps are to do those actions. Can you provide a few more steps on how to do it or maybe a screenshot for each major step. (It's also possible that my keycloak is configured incorrectly and that's why I don't see the options to do this).

**Comment by gandalfar** [comment]
Another small detail, in README there's instruction to:

> Add X-Forwarded-For and X-Forwarded-Proto headers to proxy vhost.conf

I'm not sure how/where it should have that.

**Comment by gandalfar** [comment]
I also noticed that it seems that certain secrets needs to be synced (I guess OIDC) so that `/user/profile` works.

**Comment by literarymachine** [comment]
> Add X-Forwarded-For and X-Forwarded-Proto headers to proxy vhost.conf

`X-Forwarded-Proto` has been added to [`conf/vhost.conf`](https://github.com/hbz/oerworldmap/blob/master/conf/vhost.conf#L38), `X-Forwarded-For` is automatically added by Apache when [acting as a reverse proxy](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers). Will simply remove this step from the README to prevent confusion.
