### ISSUE TITLE
Export from country data is broken

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1929]
Go to: https://oerworldmap.org/country/br/%3Ffilter.about.%40type=%22Service%22.

Try to export to any format (CSV, GeoJson)

Get error: `For request 'GET /country/br/?filter.about.%40type=%22Service%22&ext=csv&size=-1' `

If instead you then click on map (view Brazil), you can export with no problems.

**Comment by literarymachine** [comment]
> Go to: https://oerworldmap.org/country/br/%3Ffilter.about.%40type=%22Service%22

Is this link exposed anywhere? There is a trailing slash after `br` that is / should not be part of the route. Removing it fixes it:

https://oerworldmap.org/country/br?filter.about.@type=%22Service%22
https://oerworldmap.org/country/br?filter.about.@type=%22Service%22?ext=csv&size=-1

**Comment by tamielbr** [comment]
Sorry, I had this previously linked and didn't notice it was perhaps changed. I start from (https://oerworldmap.org/country/br/). The one above if a filter added to service. Should this base link not be used anymore?

**Comment by literarymachine** [comment]
I think the canonical base for a country has always been https://oerworldmap.org/country/br, but I could be wrong. In any way, it is and perhaps the other one incidentally worked in the past but definitely does not any more!
