### ISSUE TITLE
Tags selector should not show duplicate tags

### ISSUE THREAD

**Issue by gandalfar** [hbz/oerworldmap#1934]
When assigning tag at: https://beta.oerworldmap.org/resource/urn:uuid:663b7ddb-1fd8-44f8-96b1-db8110084104#edit

![Screenshot 2020-08-18 at 10 32 04](https://user-images.githubusercontent.com/13806/90489893-36183700-e13e-11ea-86b4-5f3f5e55a233.png)

There are two "open data" entries.

**Comment by literarymachine** [comment]
> There are two "open data" entries.

Pretty sure they are spellt differently under the hood.

**Comment by gandalfar** [comment]
What's the process debug/inspect such case? (is it common that this happens?) and how to resolve it?

**Comment by literarymachine** [comment]
> What's the process to debug/inspect such case? (is it common that this happens?) and how to resolve it?

Similar to https://github.com/hbz/oerworldmap/issues/1928#issuecomment-675341161, you can [list the corresponding tags like this](https://oerworldmap.org/sparql/query?q=SELECT+%3Ftag+WHERE+%7B%0D%0A++%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%3Ftag+.%0D%0A++FILTER+%28lcase%28str%28%3Ftag%29%29+%3D+%22open+data%22%29+.%0D%0A%7D):

```
SELECT ?tag WHERE {
  ?entry <http://schema.org/keywords> ?tag .
  FILTER (lcase(str(?tag)) = "open data") .
}
```

and you can fix them to all be lower case by applying a patch based on [this query](https://oerworldmap.org/sparql/update?delete=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22Open+Data%22+.&insert=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22open+data%22+.&where=%3Fentry+%3Chttp%3A%2F%2Fschema.org%2Fkeywords%3E+%22Open+Data%22+.):

```
DELETE {
  ?entry <http://schema.org/keywords> "Open Data" .
}
INSERT {
  ?entry <http://schema.org/keywords> "open data" .
}
WHERE {
  ?entry <http://schema.org/keywords> "Open Data" .
}
```

**Comment by literarymachine** [comment]
I just realized that the problem here is also a trailing white space:

```
SELECT DISTINCT ?tag WHERE {
  ?entry <http://schema.org/keywords> ?tag .
  FILTER regex(?tag, "^open data.*", "i") .
}


{
  "head": {
    "vars": [ "tag" ]
  } ,
  "results": {
    "bindings": [
      {
        "tag": { "type": "literal" , "value": "open data" }
      } ,
      {
        "tag": { "type": "literal" , "value": "Open Data " }
      } ,
      {
        "tag": { "type": "literal" , "value": "open data " }
      }
    ]
  }
}
```

and I fixed it like this:

```
DELETE {
  ?entry <http://schema.org/keywords> "Open Data "
}
INSERT {
  ?entry <http://schema.org/keywords> "open data" .
}
WHERE {
  ?entry <http://schema.org/keywords> "Open Data " .
}
```

and:

```
DELETE {
  ?entry <http://schema.org/keywords> "open data "
}
INSERT {
  ?entry <http://schema.org/keywords> "open data" .
}
WHERE {
  ?entry <http://schema.org/keywords> "open data " .
}
```

![image](https://user-images.githubusercontent.com/149825/91190395-d26cab80-e6f3-11ea-81dd-52f72cdb2f72.png)
