### ISSUE TITLE
Comment function deactivated

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1947]
As a logged in user I would like to add a comment to an entry, e.g. to

https://oerworldmap.org/resource/urn:uuid:49e75b35-caed-4fd4-8f01-11c38f29f68a

Though I´m logged in, the systems asks me to join in order to comment:

![grafik](https://user-images.githubusercontent.com/6639965/91460370-05e03f00-e888-11ea-8cd4-2c184174d03e.png)

After clicking on "Join us to comment" an error message appears

**Comment by literarymachine** [comment]
@gandalfar could you test https://github.com/hbz/oerworldmap-ui/pull/636 in your local dev setup?

**Comment by gandalfar** [comment]
What I can see working:
- Form is displayed for logged-in users, with call to action for anonymous users

What I'm not sure if it's related (or a bug in my dev setup):
- If I leave a comment, my name is not attached to the comment so the comment doesn't end up getting displayed.

**Comment by trugwaldsaenger** [comment]
@gandalfar, I understand that the issue does not occur on your development machine. Just to avoid confusion, please let me know in case you cannot reproduce the issue on production.

**Comment by gandalfar** [comment]
@trugwaldsaenger after a chat with @literarymachine we figured it out that the problem is with my Keycloak config on my dev machine. So not a problem for this PR.

**Comment by dr0i** [comment]
@trugwaldsaenger I've deployed it to production. Can you please check again if this is now working?

**Comment by trugwaldsaenger** [comment]
@dr0i Yes, working smoothly - many thanks!
