### ISSUE TITLE
Delete record that shows in the results page but cannot be retrieved

### ISSUE THREAD

**Issue by st-martin** [hbz/oerworldmap#1961]
Please, delete record that can be found in the results page (e.g. <https://oerworldmap.org/resource/?filter.about.keywords=%5B%22tobedeleted%22%5D>), but its URL resolves into a server error (<https://oerworldmap.org/resource/urn:uuid:6890a7aa-a383-4813-88d0-acefdfe7a21a>).

**Comment by gandalfar** [comment]
Merging this issue with https://github.com/hbz/oerworldmap/issues/1972 (please continue discussion there)
