### ISSUE TITLE
Reduce font size of OE Policy Hub

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1962]
We received quite often the feedback, that the font size is to big. Could we try, how it looks with a smaller font, e.g. 14?

**Comment by formimkontext** [comment]
font size could be a bit smaller. but only reduce the font size would lead to more longer lines. so better reduce the max width of the content container to 896 px. also change headline font sizes and spacing like padding, too. @gandalfar i will send you a message.

**Comment by gandalfar** [comment]
Closing after email review by @formimkontext of updated version.
