### ISSUE TITLE
Change Size of service name and slogan

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1963]
![grafik](https://user-images.githubusercontent.com/6639965/93072675-021f2b80-f682-11ea-891c-5124a6cab290.png)

The hub team discussed if it might look better, if the font size of "OE Policy Hub" and "Shaping the future of education together" could be exchanged, so that OE Policy Hub becomes bigger and "Shaping the future of education..." becomes smaller.

@formimkontext: Could you provide a draft, which shows, how this would look like?

**Comment by formimkontext** [comment]
here is a draft of the header section with a slightly different layout. i changed the font-sizes of head- and subline / service- name and slogan. this is – in my opinion – the second best solution. the first one would be the current one. to me it makes more sense to emphasize the offer (what you do) than the provider (who is doing it).

![20200929-OEPH-Desktop-01](https://user-images.githubusercontent.com/15141949/94564114-e1e99200-0267-11eb-8726-215755bb07ca.png)

**Comment by formimkontext** [comment]
also i put the logo with all words written out in the navigation bar. i prefer using the one that is used right now (OE Policy Hub). becaus we can show it a lttle bit bigger and set the other links in the same font size. 
if you don't want to use multiple versions of the logo, then i would not use the version with spelled out words. the other two versions (which are used in the current header and as favicon) are almost identical - except that ›policy hub‹ is spelled out once. so it is basicaly the same logo.

**Comment by trugwaldsaenger** [comment]
many thanks @formimkontext! I will share it with the team and see what they think! My initial response would be, that I liked the original version better - apart from the bold links, which definetly could be an alternative!

**Comment by gandalfar** [comment]
@trugwaldsaenger based on discussion, my understanding is that we won't change the homepage hero header?

**Comment by trugwaldsaenger** [comment]
@gandalfar Yes, this is correct - we keep it like it is! Closing
