### ISSUE TITLE
Increase visability of links

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1964]
![grafik](https://user-images.githubusercontent.com/6639965/93073952-f7fe2c80-f683-11ea-9dad-a2be197a0062.png)

Currently links are a bit difficult to spot. @formimkontext, do you see a possibility to increase the visibility of links?

**Comment by formimkontext** [comment]
i suggest to make links within the text bold and get rid of the underline.

**Comment by trugwaldsaenger** [comment]
Happy to give it a try!

**Comment by gandalfar** [comment]
Fixed by https://github.com/gandalfar/oepolicy-next/commit/829bfcb5725bfd8cd70413da2c80529d02197d4c

Here's a preview:
<img width="1158" alt="Screenshot 2020-10-01 at 10 58 35" src="https://user-images.githubusercontent.com/13806/94789344-175fbe00-03d5-11eb-8800-0b51e4eece2e.png">

**Comment by formimkontext** [comment]
works for me
