### ISSUE TITLE
Delete "Authority Tool" form Tools & Resources cards

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1965]
![grafik](https://user-images.githubusercontent.com/6639965/93075494-2d0b7e80-f686-11ea-9ec0-92fd9bf4dab4.png)

The headline "Authority Tool" should be deleted. 

Instead please include "Tools and Resources"

**Comment by gandalfar** [comment]
Just remove the header meta

**Comment by gandalfar** [comment]
Implemented

**Comment by trugwaldsaenger** [comment]
+1
