### ISSUE TITLE
Add link to registry to site-header

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1966]
![grafik](https://user-images.githubusercontent.com/6639965/93076911-59c09580-f688-11ea-9900-22f32c516635.png)

Instead of "collection & statistics" and "tools & resources" the header should inclued links to

1. "Registry" (https://oerworldmap.org/resource/?filter.about.%40type=%22Policy%22)
2. "Statistics" (https://oepolicyhub.netlify.app/explore)
3. "Resources" (https://oepolicyhub.netlify.app/tools)

**Comment by gandalfar** [comment]
Statistics, Resources, Registry

**Comment by trugwaldsaenger** [comment]
+1

**Comment by gandalfar** [comment]
Implemented

**Comment by trugwaldsaenger** [comment]
+1
