### ISSUE TITLE
Add Santiagos  Profile to "About us site"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1968]
To the About us site: https://oepolicyhub.netlify.app/about
Santiagos profile should be added:
http://education.okfn.org/oegw-team/

**Comment by st-martin** [comment]
Please, add this updated text instead and the attached picture:
"Santiago Martín is an MA in Library and Information Science and BA in Media Production. He currently works at UCL Library Services, is the Community Lead at the Open Knowledge Open Education Working Group and a member of the European Network of Open Education Librarians. Santiago is interested in information ethics and openness, offers support to early career researchers and educators into opening up their research and pedagogical resources and is a Free and Open Source Software advocate."
![200703-portrait-720](https://user-images.githubusercontent.com/11011338/93090177-46b3c280-f694-11ea-85ed-9d307546f58d.jpg)

**Comment by gandalfar** [comment]
Implemented

**Comment by trugwaldsaenger** [comment]
+1, looks good to me!
