### ISSUE TITLE
Create Sub-page "Contribute"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1970]
- [ ] @trugwaldsaenger to provide final mockup
- [ ] @gandalfar to implement mockup

**Comment by trugwaldsaenger** [comment]
@gandalfar, here comes a first draft for the contribution site: https://docs.google.com/document/d/11PdkcA0aYwHSkFxL5sFdA3TDtsdRrcnRRwa9vQraf2c/edit#heading=h.mjth9brvsnxu

**Comment by gandalfar** [comment]
Implemented: https://oepolicyhub.netlify.app/contribute

**Comment by trugwaldsaenger** [comment]
Very good, many thanks @gandalfar !

We still have to adjust the link from the home page. 

Currently it looks like this:
![grafik](https://user-images.githubusercontent.com/6639965/93328955-bfde2180-f81c-11ea-95c5-5041478c5aba.png)

Instead of the two buttons, there should be only one, whch is named "contribute" and is linked to the new site!

**Comment by gandalfar** [comment]
Please check now

**Comment by trugwaldsaenger** [comment]
Perfect!
