### ISSUE TITLE
Include Attribution to CC on OE Policy Hub

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#1979]
The OE Policy Registry was originally started by CC and handed over to the OER World Map.

Attribution to this important contribution has to be added to the OE Policy Hub site.

In order to do so, the text on the about site: https://www.oepolicyhub.org/about should be changed into: 

"The heart of the hub is the Open Education Policy Registry, an evolving database which collects and classifies Open Education Policy documents from all educational sectors and levels of governance around the world. The collection of policy documents was originally started and maintained till 2018 by Creative Commons under the name "OER Policy Registry". We sincerly thank CC for contributing this important data set to the OER World Map."

To increase visibility of this attribution, an asterisk should be added to the "what it´s all about" section on the homepage, which links to the about site:

"The heart of the hub is the Open Education Policy Registry*, an evolving database which collects and classifies Open Education Policy documents from all educational sectors and levels of governance around the world."

**Comment by gandalfar** [comment]
Fixed in https://github.com/gandalfar/oepolicy-next/commit/f8da65c928b81b6a39a5c3bfeecfdcee66178ab1
