### ISSUE TITLE
Statistics do not show filtered data

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#1997]
When selecting data to populate a list, I would expect that clicking on statistics would give me data as filtered. Instead it seems to show all data. This filters 4 categories with 57 entries:

https://oerworldmap.org/resource/?filter.about.additionalType.%40id=%5B%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23learningPlatform%22%2C%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23repository%22%2C%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23referatory%22%2C%22https%3A%2F%2Foerworldmap.org%2Fassets%2Fjson%2Fservices.json%23contentSource%22%5D&filter.feature.properties.location.address.addressCountry=%5B%22BR%22%5D

But statistics include 6 categories, two of which were not included in the filter (Authoring tool, Community platform) which then leads me to think the remaining data is for the full Brazil data set.

**Comment by acka47** [comment]
I think everything works as expected. The thing is that some entries have two `additionalType` entries (shown as "Service type" in the edit form), e.g. [EDUCARE](https://oerworldmap.org/resource/urn:uuid:2c01b075-683f-42c5-879a-89bd71515f96) is both typed as "Authoring tool" and "Repository". The other one is [MEC RED Platform](https://oerworldmap.org/resource/urn:uuid:1a58d45a-0afa-4aa7-b19b-236b1f48f46f) which has three `additionalTypes`: "Repository", "Community platform", "Referatory". If this resolves your question, please close the issue.

**Comment by tamielbr** [comment]
It does, my mistake. Didn't think of this possibility.
