### ISSUE TITLE
Certificate on https://oerworldmap.org has expired and https://oerworldmap.org/resource/ is 502

### ISSUE THREAD

**Issue by micgro42** [hbz/oerworldmap#2000]
The certificate on [https://oerworldmap.org](https://oerworldmap.org) has expired today.

Additionally, even after accepting the expired certificate, [https://oerworldmap.org/resource/](https://oerworldmap.org/resource/) fails with a 502 error.

**Comment by acka47** [comment]
Thanks for reporting this. @dr0i can you please take care of this?

**Comment by acka47** [comment]
We are back up again, see https://oerworldmap.org/resource/. Thanks for taking care of this, @dr0i. Please excuse the inconvenience, @micgro42 . Closing.
