### ISSUE TITLE
Put Folhas story to staging server

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#204]
https://drive.google.com/open?id=0B9czXDEWAyg1fk1pV0tKSkJyTjhzMElXZUVpbzdFbFJ3aDZZQkRrV1ItQVdrWEY3NUladzQ&authuser=0

include picture delivered in folder

**Comment by literarymachine** [comment]
No author at all for this one?

**Comment by literarymachine** [comment]
No date of release?

**Comment by literarymachine** [comment]
For `Service`, there is actually a [`serviceType`](http://schema.org/serviceType) property, no need to use `additionalType`.

**Comment by literarymachine** [comment]
The language of a `Service` could (should?) be captured as

    "availableChannel": [
         {
            "availableLanguage": ["por"]
         }
    ]

**Comment by literarymachine** [comment]
Instead of `logo`, [`image`](http://schema.org/image) should be used.

**Comment by literarymachine** [comment]
Sorry, my bad. Didn't see the `logo` property.

**Comment by acka47** [comment]
> For `Service`, there is actually a [`serviceType`](http://schema.org/serviceType) property, no need to use `additionalType`.

Good. Will do this in the future.

> The language of a `Service` could (should?) be captured as

>    "availableChannel": [
         {
            "availableLanguage": ["por"]
         }
    ]

I am not that happy with [`inLanguage`](http://schema.org/inLanguage) either as it isn't expected to be used on a service. But adding another level of indirection with `availableChannel` doesn't give any benefits I think. It might make sense if we expect to add services with different channels (Website, API, ?) in the future. For now, I would use `inLanguage`.

**Comment by literarymachine** [comment]
I would argue that if we use schema.org, we should try to use it as intended. Especially if we want to enable discovery of Services. If we do so, we should also add the URL to the channel:

    "availableChannel": [
         {
            "availableLanguage": ["por"],
            "serviceUrl": "http://www.educadores.diaadia.pr.gov.br/modules/conteudo/conteudo.php?conteudo=6"
         }
    ]
