### ISSUE TITLE
Put Copilot Story to staging server

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#205]
https://drive.google.com/open?id=0B9czXDEWAyg1fm11ckgyTTRHbkZKSncycmhKclEwYnR6Q0k3cDlrcXV2UmEwZ3ZnSk9idHM&authuser=0

include picture in folder if possible (I failed to make a good jpeg out of the included pdf...)

**Comment by literarymachine** [comment]
Cannot include PDF as image. A thumbnail would be enough, could you perhaps just grab a screenshot?

**Comment by trugwaldsaenger** [comment]
The pin on the map is still missing. Did send the adress of Nancy to @acka47 and @literarymachine by mail.
