### ISSUE TITLE
Put Roytech story to staging

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#206]
https://drive.google.com/open?id=0B9czXDEWAyg1flZubXV3azNTVFBrZjE5WmFNU3Z6TmdDOUk3Umpud2JHaktpMHF1U3FBd2M&authuser=0

include picture in folder

**Comment by literarymachine** [comment]
Our data model currently requires an `email` of the author (which we can, if wanted, store encrypted). Would it be possible to provide that?
