### ISSUE TITLE
Register a user account

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#21]
As person from the OER community willing to contribute I want to easily register a OER World Map/data hub user account so that I can comment as well as add and edit existing entries.

**Comment by literarymachine** [comment]
Designs by @formimkontext:
![20160405-oer-register-01](https://cloud.githubusercontent.com/assets/149825/14308966/bb93eba8-fbd9-11e5-9722-9c8e6423be0a.jpg)
![20160405-oer-register-02](https://cloud.githubusercontent.com/assets/149825/14308971/bb9742d0-fbd9-11e5-9caf-7dbf85093a6e.jpg)
![20160405-oer-register-03](https://cloud.githubusercontent.com/assets/149825/14308968/bb9556c8-fbd9-11e5-8591-03c022504f52.jpg)
![20160405-oer-register-04](https://cloud.githubusercontent.com/assets/149825/14308967/bb9407f0-fbd9-11e5-986d-accc5c01266b.jpg)
![20160405-oer-register-05](https://cloud.githubusercontent.com/assets/149825/14308970/bb9735d8-fbd9-11e5-8a8e-517e6ef631a5.jpg)
![20160405-oer-register-06](https://cloud.githubusercontent.com/assets/149825/14308969/bb9715f8-fbd9-11e5-8325-44503fc27139.jpg)
![20160405-oer-register-07](https://cloud.githubusercontent.com/assets/149825/14308972/bbac4a68-fbd9-11e5-9950-95299682f8c2.jpg)
![20160405-oer-register-08](https://cloud.githubusercontent.com/assets/149825/14308973/bbae982c-fbd9-11e5-8081-3fb063ca3597.jpg)
![20160405-oer-register-09](https://cloud.githubusercontent.com/assets/149825/14308974/bbafb98c-fbd9-11e5-8b3e-08c103128270.jpg)

**Comment by karindr** [comment]
When my account seemed not to work some time ago, I tried to work with my gmx address. The account I created that time still works and I was able to create an personal page for me.

**Comment by acka47** [comment]
Closing. Although registered users can not add/edit entries, the functionality to register is there. (We will have to discuss opening up editing/adding for all, though.)
