### ISSUE TITLE
Map not shown in Chromium

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#217]
At the moment, the map isn't shown in Chromium browser but only a list of country labels and number of people registered from there. Screenshot:

![20150622_oerworldmapscreenshot](https://cloud.githubusercontent.com/assets/160292/8283613/90c823ae-18f8-11e5-9eac-d2b7680ac487.png)

I tested this on two different devices (running Ubuntu 14.04 and Linux Mint 17.1 (which based on Ubuntu 14.04)).

**Comment by literarymachine** [comment]
Not good. But at least that's the good thing about progressive enhancement: if the Javascript fails, you're not stuck with nothing. Could you maybe check the Javascript console (Shift+Ctrl+j) for errors and post them here? I'll install Chromium ASAP, too.

**Comment by acka47** [comment]
The errors from the console:

> https://cdn.rawgit.com/mathiasbynens/jquery-placeholder/master/jquery.placeholder.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:71
Uncaught TypeError: undefined is not a function

**Comment by j0hj0h** [comment]
Rawgit delivers a 404 for the library. @literarymachine, can you switch that to a local copy?

**Comment by literarymachine** [comment]
Just saw that it is not browser dependent, too. @j0hj0h, yes I will switch all libraries to local copies.

**Comment by j0hj0h** [comment]
Thanks ... by the way for v0.2 I already did that. Will come with the next merge, in about 15 minutes ...

**Comment by literarymachine** [comment]
Fixed by #218
