### ISSUE TITLE
Create a new OER data hub entry

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#22]
As a registered user of the OER World Map I want to create a new OER data hub entry describing a person, service, organisation or project.

**Comment by j0hj0h** [comment]
@acka47: In the user story #29 you're naming institutions. Guess they are the same as organisation? If so we should maybe stick to one wording. My suggestion would be institution.

**Comment by drrobertfarrow** [comment]
I think it's a good idea to just have one label!  I can see why 'institution' is appealing but I wonder whether 'organisation' can be a bit broader and apply to a wider range of potential users.

**Comment by j0hj0h** [comment]
Ok, in german "Institution" is the far more general term, I'd say. But if it's the other way round in english, we should take "organisation".

**Comment by acka47** [comment]
+1 for "organisation".

**Comment by literarymachine** [comment]
+1 for "organization" (note the "z", to align the [spelling](http://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#-ise.2C_-ize_.28-isation.2C_-ization.29) with [schema.org](http://schema.org/Organization)).

**Comment by trugwaldsaenger** [comment]
+1 for "organization". It seems to be the broader term to me. Especially I like that it can be distinguished into formal and informal organizations. So the term can be used to describe legal persons as well as "communities" & "initiatives", which often are more self organizing and less clear defined. I generally prefer the british spelling with an "s" but agree that we should orient on schema.org.

**Comment by acka47** [comment]
Closing this one, as we have implemented this epic for all entity types.
