### ISSUE TITLE
homepage: single pin does not change colour when mouseover

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#221]
The pin for "Secretaria da Educação do Paraná" in Brasil does not get orange, when doing a mouseover. All other pins do.

**Comment by literarymachine** [comment]
Did not find the exact cause yet, but I believe that both the [Story](https://beta.oerworldmap.org/resource/urn:uuid:878f36d6-15d5-11e5-bcc3-3700f09c76de) and the [Project](https://beta.oerworldmap.org/resource/urn:uuid:9fd1fd1c-15d7-11e5-b82b-332b7535164b) have the exact same location, resulting in two overlapping pins. Will investigate further with @j0hj0h.

**Comment by literarymachine** [comment]
It was as I expected, the pin for the Project was overlapping that for the Organization. I fixed this simply by removing the pin for the Project for now.
