### ISSUE TITLE
homepage: highlighting pins by story mouseover

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#222]
When doing a mouseover over a story the related pins get highlighted by becoming bigger. Our regular way to highlight an item is by changing its colour from blue to orange. I would prefer to have it this way here as well. If the colour is changing I guess the pins need not get bigger.

**Comment by trugwaldsaenger** [comment]
What do you think about it?

**Comment by buschfeld** [comment]
Yes, I agree. Although I also can imagine using both behaviours at the same time. But if it is only one of both I also would prefer the change of color. 

I aslo would prefer having the font-sizes of the headlines (of institutions etc. in the right column), but I guess this is still on the ToDo-List, at least I put it down under the Finalize UI entry #140 Jun 17

**Comment by trugwaldsaenger** [comment]
Doing both (change of colour and size) is allright for me as well. But it might be worth considering keeping the enlarged size a bit smaller than it is right now!

**Comment by trugwaldsaenger** [comment]
We could experiment in order to find the perfect size, but right now it looks fine for Version 0.2!
