### ISSUE TITLE
homepage: set link to privacy policy

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#225]
by using the "newsletter" action buttom, you can open the registration field. On this field there is a link to our privacy policy which seems to be dead and has to be updated.

**Comment by trugwaldsaenger** [comment]
Link goes to the right page now. Could the link direcly jump to the heading by using an anchor or similar?

**Comment by literarymachine** [comment]
It actually links to https://beta.oerworldmap.org/imprint#privacy already and jumps to that anchor fine in my browsers.
