### ISSUE TITLE
storyview: refine layout

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#226]
The layout of the storyview (after clicking on a story) has to be refined:
- the headline does not look nice and sits to close to the picture
- having the story pictogram close to the picture does not look so nice
- it should be possible to click on the picture and open a full size view
- the related data should be displayed clean 
- the "contribution" line is too close to the text
- add a line for subtitles when available (https://beta.oerworldmap.org/resource/urn:uuid:967fca4e-15cf-11e5-abe2-4785fa5f5d27)

**Comment by acka47** [comment]
Closing.
