### ISSUE TITLE
Provide email contacts of story authors

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#229]
We need the email addresses of the authors to complete #203, #204, #205 and #206.

**Comment by trugwaldsaenger** [comment]
#203 = Author: Lauryn Oates, e-mail: lauryn.oates@gmail.com
#204 = Author: Mary Hutner, e-mail: maryhutner@hotmail.com
#205 = Author: Nancy Graham, e-mail: N.Graham1@lse.ac.uk
#206 = Author: Alicia Swinamer, e-mail: aswinamer@col.org

**Comment by acka47** [comment]
I can add these but will wait until https://github.com/hbz/oerworldmap/pull/252 is merged.

**Comment by acka47** [comment]
@literarymachine I guess we can close this one with https://github.com/hbz/oerworldmap/commit/f7c466b83ced2e2f41be1f4b489fd4144ea1ee16 ?

**Comment by literarymachine** [comment]
I'll close tickets once everything is merged to master and deployed.
