### ISSUE TITLE
service description: Make audience/levels easier to understand

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#230]
Under audience the ISCED levels are displayed, which is great. Nevertheless the descriptions should be more "telling" ("sprechend"), so that everyone understands, whithout having to look up things first.

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/issues/231#issuecomment-118761282, this also applies to ISCED grade levels.

**Comment by trugwaldsaenger** [comment]
To me the problem seems to be more urgend for the grade level than for the topic descriptions, because the grade levels are hard to understand at all, if you do not have prior knowledge. Nevertheless, I think we should not spend to much time on an interims solution.

**Comment by literarymachine** [comment]
Why is this assigned to me, is there anything I should do right now?
