### ISSUE TITLE
Service description: Change Topic description

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#231]
The topics are presented using ISCED field numbers and in brackets the name of the topic:

ISCED: 001 (Basic programmes and qualifications)

I think it would look better the other way around:

Basic programmes and qualifications (ISCED: 001)

**Comment by literarymachine** [comment]
We should not forget that right now, the classifications are merely strings. As soon as we have a SKOS representation of the ISCED, we will link there and can then decide on a format for display. If @trugwaldsaenger thinks it is important, we could of course fix the strings for the time being (@acka47, perhaps you could also do this at https://github.com/hbz/oerworldmap/tree/release/v0.2/data/ingest).

**Comment by trugwaldsaenger** [comment]
It`s a nice to have - if its makes sense to solve this point later, this will be fine for me!
