### ISSUE TITLE
service description: Dublicated Topics

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#232]
https://beta.oerworldmap.org/resource/urn:uuid:fbbd8618-15d8-11e5-8850-2bd783bbdf05

Within the topic list some topics appear as ISCED and non-ISCED topics:

ISCED 0223 (philosophy and ethics) and Philosophy

or

ISCED 0314 (Sociology and cultural studies) and Philosophy

**Comment by literarymachine** [comment]
@acka47 can you correct the data at https://github.com/hbz/oerworldmap/blob/release/v0.2/data/ingest/878f36d6-15d5-11e5-bcc3-3700f09c76de.json and open a pull request when done?
