### ISSUE TITLE
country view: include business card layout for country champions

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#233]
The contact information of the country champions should be displayd in a business card layout.

**Comment by trugwaldsaenger** [comment]
We also have to find a solution for displaying information for the case of multiple country champions. One solution would be to show a scrollable gallery of business cards, similar to the Mac Gallery view.

**Comment by literarymachine** [comment]
Is this OK [as is](https://oerworldmap.org/country/de)?
