### ISSUE TITLE
Country view: show projects and services in country stats

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#234]
Projects and services are our most important data types and should be included in the country stats.

**Comment by literarymachine** [comment]
As discussed before, we need this in our data then. So far, only `Organization` and `Person` have a `location`. If we stick to the schema.org model, we can directly attach a `location` to an `Action` (Project), but not to a `Service`. A `Service` can have a `provider` though, which then has a `location`.

**Comment by trugwaldsaenger** [comment]
I asked @acka47 to provide the needed information.

**Comment by acka47** [comment]
I included the provider in the service descriptions, see https://github.com/hbz/oerworldmap/pull/252.

**Comment by literarymachine** [comment]
@trugwaldsaenger see e.g. https://beta.oerworldmap.org/country/ca and https://beta.oerworldmap.org/country/br

**Comment by trugwaldsaenger** [comment]
The overall look is good - I also like the looks in the mouseover very much! There is one minor issue: We had a rocket icon earlier for projects, which fits much better than the gears icon. If possible, I would prefer to include this icon. If this has to be done after the launch, this will be OK as well.
