### ISSUE TITLE
Refine FAQ page

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#239]
https://drive.google.com/open?id=16XdNOhFyEb0XOjAHK2AhEoLtJHCyGfae245ONqMG9w8

@acka47 @drrobertfarrow: This is quite an important task, since we included some more questions about Open Licensing, so it actually will be a first version of our collection policy. We should discuss the included questions carfully, so that we do not have to change our policy soon in the future!

**Comment by trugwaldsaenger** [comment]
We should finish this task by the end of the week.

**Comment by literarymachine** [comment]
See https://beta.oerworldmap.org/FAQ, layout tbd.

**Comment by trugwaldsaenger** [comment]
Great that you managed to get this in!
