### ISSUE TITLE
Read blog post

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#24]
As an OER community member I want to read the project blog.

**Comment by acka47** [comment]
As soon as @trugwaldsaenger passes the admin password for the oerworldmap.org domain I will set up a a reverse proxy with @dr0i so that we have http://blog.oerworldmap.org for https://oerworldmap.wordpress.com/ .  Then I will add the other existing posts...

**Comment by literarymachine** [comment]
To be honest, personally I believe we'd be better off with no blog than the current one (content- and especially layout-wise): https://blog.oerworldmap.org/
/cc @acka47 @trugwaldsaenger @drrobertfarrow

**Comment by acka47** [comment]
I guess, @drrobertfarrow changed the theme without notice. I switched back to the theme before. I think, we shouldn't use a theme that can't be viewed with java script blocked/switched of.

**Comment by drrobertfarrow** [comment]
Hi guys.  Apologies if I created some confusion.  I was experimenting with some themes and didn't reverse the changes - my bad.  I didn't imagine a WP theme would be so inaccessible.

I do think we will need the blog, though.  I am happy to write a post for Open Education week and try to get things looking more organised.  I was looking for a theme that could have better visual continuity with the landing page; and also one that would support widgets for Twitter, RSS and so on - though maybe the existing theme accommodates this.  The blog will be an important part of how we raise awareness and connect with the right people.  I think it would be good for Jan to write a post on what has been happening from an overall perspective, and perhaps also a post from one of the developers on the technical side of things.  I could write about the events that are coming up where the project can have a presence and explain how people can become involved or make contact.  Just suggestions - I'm happy to do things differently.

With the Hewlett Grantees Meeting, OER15, and OE Global in the next six weeks we should definitely be aware of how we are presenting the project.  The blog will be really important for this as it's our main way of communicating the narrative of the project. Twitter will also be really important and I'm happy to run the account if the details are passed on to me.  

In OERRH we have found that momentum is important for communicating with stakeholder.  It might be good to agree a blogging schedule for the next few months.  Posting on consecutive days next week would probably raise a lot of attention, and it would be good if we can convert that to signups (assuming we are ready).

I didn't mean to write so much but I thought I would share these considerations!

**Comment by literarymachine** [comment]
> I do think we will need the blog, though.

I do, too - looks like my plan to get the discussion started here worked out :)

>  I am happy to write a post for Open Education week and try to get things looking more organised.

Great!

> I was looking for a theme that could have better visual continuity with the landing page; and also one that would support widgets for Twitter, RSS and so on - though maybe the existing theme accommodates this. The blog will be an important part of how we raise awareness and connect with the right people.

RSS is provided, we use the feed to embed the most recent post on the landing page. I understand the concerns regarding visual continuity but would focus on the content first.

That being said, in https://github.com/hbz/oerworldmap/issues/38#issuecomment-77169683 @acka47 states that the current reverse proxy-setup is not ideal. Once on the blog, the URLs are relative to oerworldmap.wordpress.com.

If the blog is that central to our project, we maybe really should consider installing wordpress ourselves (which is easy to do, and @j0hj0h really knows his way around behind the scenes of wordpress). It still is an additional system to (technically) take care of, though.

> a post from one of the developers on the technical side of things

I was going to do a write-up of the technical side of things anyways, and will be happy to put that on the blog!

> It might be good to agree a blogging schedule for the next few months.

Sounds like a good plan. What schedule would you suggest? We should not be too ambitious, maybe we could tie this to our monthly team meetings and always blog what has happened and what is planned?

> Posting on consecutive days next week would probably raise a lot of attention, and it would be good if we can convert that to signups (assuming we are ready).

I'll try to have the post on the technical side of things ready by the end of the week (assuming that it is OK if it is the last one).

> I didn't mean to write so much but I thought I would share these considerations!

This is great! I really think that discussing also rather non-technical issues here is a good way to go.

**Comment by trugwaldsaenger** [comment]
OK - so we all consinder the blog important -  content will come - I`m planning to do two posts "What is the OER World Map" and "How to collaborate with the OER World Map" very soon!

**Comment by drrobertfarrow** [comment]
I have drafted a post at https://wordpress.com/post/82854330/47.  I would
like to publish it later today so if you could review and send some brief
feedback in the next 4 hours that would be great.  If I don't hear from
anyone I will publish later this afternoon!

On Mon, Mar 9, 2015 at 9:03 AM, Jan Neumann <notifications@github.com>
wrote:

> OK - so we all consinder the blog important - content will come - I`m
> planning to do two posts "What is the OER World Map" and "How to
> collaborate with the OER World Map" very soon!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hbz/oerworldmap/issues/24#issuecomment-77819513>.
>



-- 
Dr. Robert Farrow
@philosopher1978
http://philosopher1978.wordpress.com/

**Comment by drrobertfarrow** [comment]
If you can't access the post through the link just log in to the blog and look at the most recent draft post!

**Comment by literarymachine** [comment]
Could I also get access to the blog? My wordpress user name is `literarymachine`.

**Comment by acka47** [comment]
I've sent you an invitation.

**Comment by acka47** [comment]
From my perspective, the post is ready to be published. I made a few small edits and added a link to the  ["The Team" page](https://oerworldmap.wordpress.com/the-team/) I added.

We might also add links to the individuals when mentioned in the post...

**Comment by literarymachine** [comment]
@drrobertfarrow Thanks for the post! My only minor quibble would be that it currently links to oerworldmap.graphthinking.com, which is our internal staging server. The link should be updated as soon as we are up and running at oerworldmap.org (hopefully tomorrow).

**Comment by literarymachine** [comment]
I fixed the link in https://oerworldmap.wordpress.com/2015/03/09/making-connections-oer-world-map-in-2015-openeducationwk/ to point to https://oerworldmap.org. Closing.
