### ISSUE TITLE
Analyse Open Education Week Data

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#243]
Background: The Open Education Consortium organizes Open Educaton Week on a yearly basis. The data collected during OEW could be included in the OER World Map. 

There are Archives of the last OEW available:
http://www.openeducationweek.org/

Maybe it is also possible to get the data by their API. 

The idea would be to include OEW data into the World Map on a regular basis.

**Comment by acka47** [comment]
> Maybe it is also possible to get the data by their API. 

This is a wordpress site. I don't see any structured data in the html and I don't think the site has a way to programmaticely get metadata (although plugins – eg. https://wordpress.org/plugins/json-rest-api/stats/ – for this exist). 

> The idea would be to include OEW data into the World Map on a regular basis.

I wonder hiw the data should be included. Should we add single [resources](http://www.openeducationweek.org/resource/) as events? That might make sense. We should also think about offering OER Worldmap as a platform for upcoming OER weeks...

**Comment by trugwaldsaenger** [comment]
Just spoke with Igor and Jure. We came to the conclusion that integrating OE-Week from the past will not make much sense and that it will be better to look for future data. Therefore analysing the OE Week input templates will make a good start:

http://www.oeconsortium.org/events/open-education-week-2015/open-education-week-2015-submission-form/

When comparing our data collection approaches we learned that OE Week concentrates on single Ressources (like Videos or Courses) on Events and on Project Showcases. Ressources are not included in the scope of phase II and are of minor priority for us right now. But events and project might be very interesting for the OER World Map. Also behind every event there normally is a project or an institution, so it might be possible to add fields for this data into the OE-Week templates.

**Comment by gandalfar** [comment]
Regarding data structure / API - once we define what data we want to share, I'll define either JSON endpoint or another way for you to access it.

Same for any other projects (directory, events).

**Comment by trugwaldsaenger** [comment]
Hi @gandalfar! Thanks for dropping in and adding your comment!

**Comment by trugwaldsaenger** [comment]
After speaking with @acka47 one possible solution to include the data would be to add a field "project" in the general part of the OEW-template. This would allow us to collect institutions, persons, projects and events. All additional information collected by OEW, like videos, informational resources or online discussion ideas might be included as related links.

**Comment by gandalfar** [comment]
Please also include "upstream source" as permalink. You'll need it for source citation and so that you can remove/update your copy if upstream changes/is removed.

**Comment by acka47** [comment]
A spreadsheet with the Open Education Week data is at https://docs.google.com/spreadsheets/d/1_4xksxE5YHbI2Rqe6L-xUJW60xyp_R6GegDLfen8BCs/edit?pref=2&pli=1#gid=0

**Comment by acka47** [comment]
Cooperation of OEW and OEr World Map is planned for 2018. Preparation for OEW will start in September 2017.

**Comment by acka47** [comment]
There actually is an API, see https://api.openeducationweek.org/api/
