### ISSUE TITLE
Implement new Text to "contribute" page

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#244]
https://docs.google.com/document/d/12M1VWSwvOhY39CvgqaCygn2807oI7JWMfgdyMiZOiHw/edit

**Comment by trugwaldsaenger** [comment]
The content is there and looks fine. But the colourscheme I used to mark active (=green), partly active (= yello) and non-active/planned (=red) actions does not fit with the colourscheme of the page. If @buschfeld or @j0hj0h can offer a better solution, we should try to implement it. If we don`t find the time to do so, we probably should keep the colours away completely.

**Comment by buschfeld** [comment]
Basically all three navigation pages should have the same typographic settings via CSS-Style-Definitions. Therefore I would like to include three layout drafts for

- About page (as already developed during the physical team meeting)
![oer_17_demo_about_whitebg](https://cloud.githubusercontent.com/assets/10743356/8569486/6df0eb5e-2578-11e5-9098-ccb56465eeb3.png)

- FAQ page (open/close-function via arrowheads is just an option TBD)
![oer_19_demo_faq_whitebg](https://cloud.githubusercontent.com/assets/10743356/8569488/73355af0-2578-11e5-9513-d68566e71072.png)

- Contribute page (including display of three different status notes)
![oer_18_demo_contribute_whitebg](https://cloud.githubusercontent.com/assets/10743356/8569497/8f253fd2-2578-11e5-8bea-ff66139be0c3.png)
