### ISSUE TITLE
Tranfer Serlo Story to Json

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#245]
https://docs.google.com/document/d/1bc9O3RJUhWzXLI5kfY3222A8hWpnMlyWSJkPx51Iqr4/edit

**Comment by acka47** [comment]
A picture for the story would be nice. Do you have an idea or will you ask Simon for one?

**Comment by trugwaldsaenger** [comment]
A good picture is already available in the google drive folder: https://drive.google.com/open?id=0B9czXDEWAyg1TUY0bzdIeWpvWlU
