### ISSUE TITLE
Provide Map Gadged for OER World Map partners

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#254]
~~Story:
As the Open Educaton Consortium, which organizes Open Education Week on a yearly basis  I would like to include into my side a map generated by the OER World Map platform, which displays the contributions presented at Open Education Week.~~

**Comment by trugwaldsaenger** [comment]
One question would be here which information should be displayed on the map. I guess that
1) Institutions
2) Persons
3) Local events 
could be put on the map rather easily.

**Comment by drrobertfarrow** [comment]
Anyone would be able to take a screen shot of the map after they have applied relevant filters - but does this refer to being able to export a specific query using something native to the OER World Map system?

One related issue - and one that perhaps needs its own 'use case' scenario - is being able to provide an academic citation for information on the map at a particular point in time.  We may need to add something to the FAQ around 'how to cite'.

**Comment by gandalfar** [comment]
This story might be more useful in another context, e.g. Showing all initiatives for EU/Country specific site.

For OEW, we'll have to do our own, since we'll have to include the data that might not fit inside the OER Map project.

**Comment by trugwaldsaenger** [comment]
@drrobertfarrow: The idea is not to include a screenshot, but a gadget, which displays the included information according to a specific filter in real time. 

I really like the idea of making the map citebal! Could you provide a user story for this?

**Comment by trugwaldsaenger** [comment]
@gandalfar: Thanks for clarifying this - I understood Igor that this might be an interesting option for you as well. Generally you are completly right that this functionality will be very interesting for many partners. Especially for our country champions, this functionality hopefully will provide much value!

**Comment by gandalfar** [comment]
It would be, but more as part of http://www.oeconsortium.org/info-center/ or on other sub-pages of OEC site.

**Comment by trugwaldsaenger** [comment]
I reformulated the title of the story to make it more abstract. We can see later if we close this issue and open a more general one, or if we continue to work on this one.

**Comment by trugwaldsaenger** [comment]
Story: As a country champion I want to include a map of the OER activity in my country in my website/worldpress blog

**Comment by trugwaldsaenger** [comment]
I put this story into the ready column. I do not exspect that we are providing this functionality in August, but it would be great, if we could make a first analysis of this topic this month

**Comment by acka47** [comment]
To do: define tasks for this story.

**Comment by literarymachine** [comment]
See e.g. https://open-educational-resources.de/karte/
