### ISSUE TITLE
Add OEC member data

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#255]
OEC would be interested to have a look how their membership data would look like on the OER World Map.

**Comment by acka47** [comment]
Just browsed the data on beta that includes the imported OEC data. It shows that this generated some duplicates, at least these seven pairs that have to be merged (and probably more):
- https://beta.oerworldmap.org/resource/urn:uuid:f9331cb2-41b8-11e5-a99d-001999ac7927 & https://beta.oerworldmap.org/resource/urn:uuid:7067ff60-77eb-11e5-9f9f-c48e8ff4ea31
- https://beta.oerworldmap.org/resource/urn:uuid:706976c4-77eb-11e5-9f9f-c48e8ff4ea31 & https://beta.oerworldmap.org/resource/urn:uuid:3e6fe134-4268-11e5-b186-54ee7558c81f
- https://beta.oerworldmap.org/resource/urn:uuid:8961bece-4290-11e5-92e7-54ee7558c81f & https://beta.oerworldmap.org/resource/urn:uuid:706b4c4c-77eb-11e5-9f9f-c48e8ff4ea31
- https://beta.oerworldmap.org/resource/urn:uuid:2adb2bb2-3073-11e5-b60d-bfcc6080a842 & https://beta.oerworldmap.org/resource/urn:uuid:706904c8-77eb-11e5-9f9f-c48e8ff4ea31
- https://beta.oerworldmap.org/resource/urn:uuid:7069908c-77eb-11e5-9f9f-c48e8ff4ea31 & https://beta.oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0
- https://beta.oerworldmap.org/resource/urn:uuid:de67e70c-3b7b-11e5-8d59-54ee7558c81f & https://beta.oerworldmap.org/resource/urn:uuid:7069aa18-77eb-11e5-9f9f-c48e8ff4ea31
- https://beta.oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927 (service) & https://beta.oerworldmap.org/resource/urn:uuid:70696b2a-77eb-11e5-9f9f-c48e8ff4ea31 (org)

**Comment by gandalfar** [comment]
Sorry, that's my mistake/change. Can you check for duplicate key or I can give you own URL.




-jure



—

**Comment by acka47** [comment]
I can't see, why this would be your mistake, @gandalfar. @literarymachine got the data via your API and I checked for duplicates against some also to be imported organizations before we imported the OEC data. But I didn't check against already existing resources... We will have to decide whether we will do another import with an automatic duplicate check. It might be easier for now to do a manual merge, though, which I could do on Monday.

**Comment by literarymachine** [comment]
Exactly @gandalfar, I don't think you could have done anything about this. Maybe it would have been a good idea to add the OEC data earlier on so that it could have been referenced from stories. On the other hand, duplicates will be inevitable in the long run, so we need a strategy to deal with them anyways.

> We will have to decide whether we will do another import with an automatic duplicate check.

Sorry, no time for re-imports and automated duplicate checks. There is development to be done, too. We can do some data grooming later on, but there will not be any kind of automated duplicate check for the time being.

> It might be easier for now to do a manual merge, though, which I could do on Monday.

Please don't rush with this. We have to think carefully what implications a merge has. Let's talk Monday before you start.

**Comment by literarymachine** [comment]
By the way, the data is not only on beta but also on production: https://oerworldmap.org/

**Comment by acka47** [comment]
Another duplicate:
https://beta.oerworldmap.org/resource/urn:uuid:f9331cb2-41b8-11e5-a99d-001999ac7927 & c48e8ff4ea31

**Comment by acka47** [comment]
For OER Africa (which is also listed in the comment above listing the duplicates), we actually have three entries (one of them only on beta):
- https://oerworldmap.org/resource/urn:uuid:97d4cb64-15b2-11e5-80f8-001999ac7930
- https://oerworldmap.org/resource/urn:uuid:706976c4-77eb-11e5-9f9f-c48e8ff4ea31
- https://beta.oerworldmap.org/resource/urn:uuid:3e6fe134-4268-11e5-b186-54ee7558c81f

**Comment by acka47** [comment]
> Another duplicate (only on beta):
https://r/resource/urn:uuid:f9331cb2-41b8-11e5-a99d-001999ac7927 & https://beta.oerworldmap.org/resource/urn:uuid:7067ff60-77eb-11e5-9f9f-c48e8ff4ea31

I added additional information from beta in the version from OEC on production.
