### ISSUE TITLE
Include refined "About" page text

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#269]
https://docs.google.com/document/d/15odI9XvyNpzK-8lnQZRB0VomFGHDErXYCeNv5rn2SvQ/edit#heading=h.vohqpidbnwa

If possible for the launch - if not after!

**Comment by literarymachine** [comment]
@drrobertfarrow see https://beta.oerworldmap.org/about, remove the "Review label", add the "Deploy" label and assign this ticket back to me if all is well.

**Comment by literarymachine** [comment]
Ping @drrobertfarrow, should I merge and deploy this or not?

**Comment by drrobertfarrow** [comment]
Yes, I think you should merge them - I have just assigned the ticket back
to you.  Cheers!

On Thu, Jul 16, 2015 at 1:48 PM, Felix Ostrowski <notifications@github.com>
wrote:

> Ping @drrobertfarrow <https://github.com/drrobertfarrow>, should I merge
> and deploy this or not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hbz/oerworldmap/issues/269#issuecomment-121947332>.
>



-- 
Dr. Robert Farrow
@philosopher1978
http://philosopher1978.wordpress.com/
