### ISSUE TITLE
Browse Calendar

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#27]
As an OER practitioner I want to browse the calendar so that I can find upcoming OER events.

**Comment by formimkontext** [comment]
![20161123-oer-world-map-calendar-02](https://cloud.githubusercontent.com/assets/15141949/20601303/3f281c48-b258-11e6-9bf8-e9914f3ce439.jpg)
![20161124-oer-world-map-calendar-002](https://cloud.githubusercontent.com/assets/15141949/20601324/61706fa8-b258-11e6-9f58-ac67a54e84a6.png)

**Comment by formimkontext** [comment]
Current draft of the calendar-view, including the extended filter section and calendar sheets for every list entry, order selection dropdown and notify button (bell icon).

![20161215-oerworldmap-calendarview-01](https://cloud.githubusercontent.com/assets/15141949/21224788/1d87ca4e-c2ce-11e6-9590-c2234bed5ab9.png)
![20161215-oerworldmap-calendarview-02](https://cloud.githubusercontent.com/assets/15141949/21224836/5bb90328-c2ce-11e6-8864-ffbe7b863732.png)

**Comment by karindr** [comment]
Looks good and useful.

**Comment by j0hj0h** [comment]
@literarymachine: the `_id` field in the calendar aggregation as a `.about` suffix. Shell I cut this of for building the hrefs or can you fix that?

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Event

**Comment by karindr** [comment]
+1

I suggest that we don't show the month without event. Especially when searching for something special it may be disturbing to have these empty month displayed.

**Comment by literarymachine** [comment]
> I suggest that we don't show the month without event. Especially when searching for something special it may be disturbing to have these empty month displayed.

+1, ping @j0hj0h

**Comment by literarymachine** [comment]
> I suggest that we don't show the month without event. Especially when searching for something special it may be disturbing to have these empty month displayed.

On https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Event

**Comment by karindr** [comment]
+1
