### ISSUE TITLE
Re-term "Country Champion"

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#272]
As some team members were not that convinced by the term "country champion", let's collect some alternatives by the means of this ticket and see what evolves from it. Here are some initial suggestions:
country spokesman
country ambassador
country agent
country proxy
country messenger
country expert
country master
country advocate

**Comment by philboeselager** [comment]
While discussing an expert board today, it came to my mind, that the term of an "ambassador" is emotionally a good one. It's quite an abstract way of describing the function of a such person, but anyways, it's fitting much better than "champion". An "ambassador" is a quite privileged person, but comes along with a proper amount of responsibility. And he is communicating in both directions (from country to worldmap and vice versa). Still thinking about alternatives... anyone?

**Comment by acka47** [comment]
I really sympathze with the wish for reterming but it is probably too late now. We might be able to do this if we have a major overhaul of the platform in the future, also adjusting other concepts. Closing.
