### ISSUE TITLE
Explore upcoming OER events on a map

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#28]
As a (potential) OER practitioner I want to discover upcoming OER events in a specific region on a map.

**Comment by acka47** [comment]
Variation:
Schedule event
As a conference organizer I want to find out when to schedule the event so that it won't clash with other OER events.

**Comment by literarymachine** [comment]
Done, https://oerworldmap.org/resource/?filter.about.%40type=Event&size=20
