### ISSUE TITLE
Broken links in nav bar

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#289]
Clicking on links in the nav bar ("[Contribute](https://oerworldmap.org/contribute)", "[FAQ](https://oerworldmap.org/FAQ)", "[About](https://oerworldmap.org/about)" and "[Imprint](https://oerworldmap.org/imprint)")  I am getting a "Page not found"/404.

```
$ curl -i https://oerworldmap.org/FAQ
HTTP/1.1 404 Not Found
Date: Wed, 22 Jul 2015 12:22:25 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 14

```

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/pull/290
