### ISSUE TITLE
Import OER Repositories World Map data

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#295]
http://www.zeemaps.com/view?group=562530

**Comment by literarymachine** [comment]
https://docs.google.com/spreadsheets/d/1jb-uYKkLmAAfAS-ROeC6lJK-vQpB2HvtKw1rxh2RSJ8/edit?usp=sharing

**Comment by acka47** [comment]
Currently, I am step by step going through the spreadsheet deleting dead services and trying to make the data more homogenous so that it can be imported automatically. @literarymachine, please ping me when you have time to try a first import.

**Comment by acka47** [comment]
As decided offline, we will add the service data manually via the input form. @literarymachine please let me know when I can start with doing this.

**Comment by literarymachine** [comment]
On http://h2481931.stratoserver.net:9000/, along with OEC member organizations. @j0hj0h is currently finalizing the clustering of pins since we now have quite a lot of them.

**Comment by acka47** [comment]
Regarding the OEC member organizations I told you in Frankfurt that a `memberOf` link to OEC would be nice. I now added OEC to production, see https://oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f. Let me know when you rather want a separate issue for adding this relation.

**Comment by literarymachine** [comment]
> I now added OEC to production, see https://oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f. 

This reminds me of the fact that there once was the idea to add all OEC members with a story about OEC. It would be no problem to import only the organizations needed for the repository list for now, if @trugwaldsaenger is still pursuing this plan.

**Comment by acka47** [comment]
BTW, we have aseparate issue for OEC data: #255 . Will discuss things re. OEC data there.
