### ISSUE TITLE
Survey of newletter registrants

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#297]

**Comment by literarymachine** [comment]
TODO:
- decide on survey platform
- formulate three survey questions

/cc @trugwaldsaenger @acka47

**Comment by literarymachine** [comment]
I'd suggest going with [Google Forms](https://docs.google.com/forms/d/1Q328nxW-pZS-kcuZk9x9UYjlrl6qVESNiEVHa_teHhI/edit) as platforms such as [Survey Monkey](https://www.surveymonkey.com/pricing/) are costly when more than 100 responses are required.

**Comment by trugwaldsaenger** [comment]
I spoke with Susan yesterday. She reminded me, that the academic world is quite hard to reach in August and suggested to perform major community activities in the beginning of september.

**Comment by drrobertfarrow** [comment]
Is there a reason for only three questions?  Is the idea that people will commit to answering just three?

**Comment by acka47** [comment]
To do: Share on Twitter, Facebook etc.

**Comment by literarymachine** [comment]
Ping @drrobertfarrow, this might be something to do before the holidays?

**Comment by literarymachine** [comment]
Is this obsolete? Please close, if so @drrobertfarrow.

**Comment by literarymachine** [comment]
Done, see https://docs.google.com/forms/d/1Q328nxW-pZS-kcuZk9x9UYjlrl6qVESNiEVHa_teHhI/edit#responses
