### ISSUE TITLE
How can we filter services by type?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#303]
It would be great if we could provide at least three lists for the most important service types:
1. A list of OER repositories
2. A list of OER Textbooks Provider
3. A list of Mooc Platforms
In order to do so we can either include a field called "Service Type", or we can use simply tags in the beginning.

**Comment by literarymachine** [comment]
We are already using [`serviceType`](http://schema.org/serviceType), but maybe we should model the possible values as SKOS? What do you think, @acka47?

**Comment by acka47** [comment]
Yes, we already have the needed field but it isn't populated consistently yet...

**Comment by acka47** [comment]
We can do this in SKOS but the question is what the list of possible values for this field should look like.

> 1. A list of OER repositories
2. A list of OER Textbooks
3. A list of Mooc Platforms

I guess, 2. should read "A list of OER Textbooks collections" as we don't have individual textbooks in our system. Regarding the user story, the service types to start with would read:

- OER repository
- OER textbook collection
- MOOC platform

I am not sure whether this is a flexible start we can build upon. It might be better to have "Collection" as general concept with "Textbook Collection" and collections of other OER as sub concepts...

**Comment by acka47** [comment]
Closing, as work is done at https://github.com/hbz/vocabs-edu/issues/25 resp. https://github.com/hbz/vocabs-edu/pull/26.
