### ISSUE TITLE
Provide global statistics on homepage

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#304]
Similar to the country views global statistics should be provided on the homepage. This would 
1. Provide additional value to the user
2. Make clear that the OER World Map is not an OER story project, but a powerful database aiming at providing a complete global overview.
3. Get an idea of how the final design of the homepage will look like. 

I would suggest that we provide three different functionalities:
1. Search function including filters
2. Statistics module
3. Stories

**Comment by trugwaldsaenger** [comment]
This issue is related to #242

**Comment by trugwaldsaenger** [comment]
Maybe this could be combined with the filters. We could make filters out of the different content types, so that e.g. only projects are displayed if someone clicks on "projects".

**Comment by literarymachine** [comment]
See https://beta.oerworldmap.org/

**Comment by trugwaldsaenger** [comment]
I think we can close this issue
