### ISSUE TITLE
Show images for resources

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#309]
I tried to add images/logos to resources where available and most resoures actually have a link to an image in the JSOn. It would be nice to show this for each resource type.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:ce3e25f0-39ee-11e5-86e0-001999ac7927

Layout will have to be worked on, but this is handled by #140.

**Comment by acka47** [comment]
It doesn't work yet for png files, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:95ac0fbe-2fb6-11e5-9361-001999ac7927.

**Comment by acka47** [comment]
Also, at https://beta.oerworldmap.org/resource/urn:uuid:2adb2bb2-3073-11e5-b60d-bfcc6080a842 nomimage is shown, though the "image" link goes to http://www.oeconsortium.org/wp-content/uploads/2013/11/logo-3-web-300x169.jpg.

**Comment by acka47** [comment]
Another one, where it doesn't work: https://beta.oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0

**Comment by literarymachine** [comment]
This had nothing to do with the file format, but with the fact that according to our [schema](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L473) we are using the `logo` property for `Organization`. I adjusted the template accordingly, feel free to do the same with the schema.

**Comment by acka47** [comment]
Got it. Will adjust the schema. Just that I understand how it works: Why didn't I get an error then posting `image` on `Organization` to the API? Would have expected that...

**Comment by acka47** [comment]
+1 BTW

**Comment by literarymachine** [comment]
> Just that I understand how it works: Why didn't I get an error when posting image on Organization to the API?

You are right. Currently, the schema is partially still relaxed; known properties must conform to the specification, but unknown properties are simply accepted (at least for `Organization`). Will change this when #118 resp. #273 is done.

**Comment by literarymachine** [comment]
Deployed, see e.g. https://oerworldmap.org/resource/urn:uuid:1a8efa2e-3b7f-11e5-a24e-54ee7558c81f
@acka47: could you update the instance data for resources of type `Organization` to use the `image` instead of the `logo` property?

**Comment by literarymachine** [comment]
> could you update the instance data for resources of type Organization to use the image instead of the logo property?

Sorry, got mixed up there. We *are* using image, not logo. But it is missing here on production whereas it is present on beta: https://oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0 vs. https://beta.oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0

**Comment by acka47** [comment]
I had to update the data on production after implementing the license-array thing, see https://github.com/hbz/oerworldmap/issues/346#issuecomment-136315401. Did that, looks good now, see https://oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0.

**Comment by acka47** [comment]
Closing.
