### ISSUE TITLE
Adjust address format

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#310]
Currently, we have one format for showing addresses in the OER worldmap: street, locality, postal code, country. I don't know whether this makes sense in any country but at least for Germany and US it doesn't make much sense. It might come near ther US style, but, the region is missing...

I would favor a cuntry-specific formatting but don't know how hard it is to implement. We will have to discuss this here.

**Comment by literarymachine** [comment]
> Currently, we have one format for showing addresses in the OER worldmap: street, locality, postal code, country. I don't know whether this makes sense in any country but at least for Germany and US it doesn't make much sense. It might come near ther US style, but, the region is missing...

In general: why does this not make sense in Germany? `Jülicher Str. 6, 50674 Köln` makes sense to me. Also, we now have `addressRegion`. Can we close this issue?

**Comment by acka47** [comment]
> why does this not make sense in Germany? `Jülicher Str. 6, 50674 Köln` makes sense to me. 

Yes, it is good now. This issue is from 2015. From my comment, it must have been `Jülicher Str. 6, Köln, 50674; Germany` or so back then. Closing.
