### ISSUE TITLE
Show social media links

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#320]
I added links to social media accounts (Twitter, Facebook, YouTube etc.) of services, organizations and projects where available. It would be nice if they showed up in the HTML view, probably best as a row of logos with the underlying link to the account.

**Comment by literarymachine** [comment]
On dev, e.g. http://h2481931.stratoserver.net:9000/resource/urn:uuid:df04cbe2-39f2-11e5-8263-001999ac7927

**Comment by acka47** [comment]
Good to have them there. I suggest not to show the URL but only putting the icons with the respective link behind it in one row. For example, similar to how Rice University does it on their homepage: http://www.rice.edu/.
