### ISSUE TITLE
Problems with presentation of organizations that aren't mentioned in a story

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#321]
I noticed some problems with organizations that aren't mentioned in any story:

- The text is on the left and map is on the right (the other way round than other entries)
- No marker shows up on the map

Examples:

https://beta.oerworldmap.org/resource/urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927
https://beta.oerworldmap.org/resource/urn:uuid:944e2e88-41b1-11e5-b833-001999ac7927
https://beta.oerworldmap.org/resource/urn:uuid:6af6b838-2655-11e5-80ee-033038be6ec9
https://beta.oerworldmap.org/resource/urn:uuid:f067d150-15b1-11e5-92c6-001999ac7930
https://beta.oerworldmap.org/resource/urn:uuid:944e2e88-41b1-11e5-b833-001999ac7927

**Comment by acka47** [comment]
Projects seem to be ok, though. See https://beta.oerworldmap.org/resource/urn:uuid:df65b4ee-41bc-11e5-a4e3-001999ac7927.

**Comment by literarymachine** [comment]
Fixed by #325, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:f067d150-15b1-11e5-92c6-001999ac7930

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
Looks good to me!

**Comment by acka47** [comment]
Closing, as this is done for some time now.
