### ISSUE TITLE
Wrong Country Champion in Brazil

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#322]
IndioEduca (a service) became country champion for Brazil, when looking on the country view:
https://oerworldmap.org/country/br
Right would be Tel Amiel
@literarymachine This is an urgend issue to be solved by the beginning of next week, since there will be a presentation of the system in Brazil.

**Comment by literarymachine** [comment]
I had to migrate data last week in order to fix a bug with the sorting of entries by date. Apparently I broke something, the country champion for e.g. Germany is missing: https://oerworldmap.org/country/de. Will look into this ASAP.

**Comment by acka47** [comment]
I will do this one fix for Brazil manually. Ok?

**Comment by literarymachine** [comment]
No. I have to analyze what is wrong here. This is a general mistake.

**Comment by literarymachine** [comment]
As you can see [here](https://oerworldmap.org/resource/urn:uuid:ca037478-15b2-11e5-9331-001999ac7930), the information is there. The error is somewhere else.

**Comment by acka47** [comment]
Ok, got it. Thus, assigning this to you.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/br or https://beta.oerworldmap.org/country/de

**Comment by acka47** [comment]
+1 from me

**Comment by trugwaldsaenger** [comment]
Fine, Tel is back! Could you directly include a picture of him, if you put it on production? I will send it to you by mail!
