### ISSUE TITLE
Upload data on sub-national administrative divisions (Scotland)

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#327]
The Opening Educational Practices in Scotland project (http://oepscotland.org/) has agreed to provide a range of linked data on practices involving OER in Scotland.  

Content for the Map: 
- Scottish survey data 
- Data from OEPS Advisory Forum (October 2013) 
- Desktop research of current practice 
- Case studies and impact data from research with OEPS projects/initiatives/organisations 
- Ongoing input from OEPS team, contributors etc.

**Comment by philboeselager** [comment]
@drrobertfarrow 

- Do we intend to set up an automatic update? Or would we transfer data manually first?
- How can I get access to some sample data?

**Comment by trugwaldsaenger** [comment]
@drrobertfarrow: Could you please give us an update on this issue? Is the data available yet? Even some example data might be a good start!

**Comment by literarymachine** [comment]
Inactive for two years, closing.
