### ISSUE TITLE
Sluggish performance in Firefox

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#329]
Reported by @trugwaldsaenger in https://github.com/hbz/oerworldmap/issues/323#issuecomment-131725163. CPU usage shoots up on mouse-overs.

**Comment by literarymachine** [comment]
@j0hj0h I used Firebug to profile this:

Function                                        | Calls  | Percent | Own Time   | Time       | Avg       | Min     | Max       | File
------------------------------------------------|--------|---------|------------|------------|-----------|---------|-----------|-------------------------
ol.render.canvas.PolygonReplay.prototype.finish	| 13     | 17.74%  | 3352.424ms | 6786.791ms | 522.061ms | 2.458ms | 900.128ms | ol-debug.js (line 60306)
ol.geom.flat.simplify.snap                      | 660736 | 17.59%  | 3324.055ms | 3324.055ms | 0.005ms   | 0.004ms | 20.123ms  | ol-debug.js (line 20692)
ol.render.canvas.Replay.prototype.replay_       | 113    | 16.76%  | 3166.282ms | 4775.777ms | 42.264ms  | 0.459ms | 210.657ms | ol-debug.js (line 59197)

All in all these method calls account for 50% execution time, so maybe it is worth looking onward from here. I don't quite know where to look, though. Any ideas?

**Comment by j0hj0h** [comment]
Yes, I'm aware of this and have a solution in mind. I'll fix this after my vacations.

**Comment by literarymachine** [comment]
Unfortunately, performance at least in Firefox 40.0.3 (Ubuntu) is still slow. Using the Firefox Javascript Profiler, a call from [OpenLayers 3](http://openlayers.org/en/v3.7.0/build/ol-debug.js) to requestAnimationFrame (goog.async.AnimationDelay.prototype.doAction_, line 36174) is taking more than 180ms. @j0hj0h can you take a look? I don't get what could be wrong.
