### ISSUE TITLE
Search for OER events

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#34]
As (potential) OER practitioner I want to do a full text search for OER events.

**Comment by drrobertfarrow** [comment]
It's not clear to me at the moment where this information will come from.  There are lists (like https://groups.google.com/forum/#!forum/oer-advocacy-coalition) which share a lot of important dates and we might be able to pull data from places like these.  

I wonder whether we might think of this section as 'news and events' - this would be easier to pull in from existing sources and would include details of events as they are advertised.
