### ISSUE TITLE
Adjust duration presentation for running projects

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#343]
The current presentation of a project's duration is ok for finished projects like https://oerworldmap.org/resource/urn:uuid:e8cd9900-3b79-11e5-bd3d-54ee7558c81f. It doesn't work for running projects (without an end date), though. Example: https://oerworldmap.org/resource/urn:uuid:3773439c-3b76-11e5-aa68-54ee7558c81f

The easiest way would be to add a dash after the date whether there is an end date or not.

**Comment by acka47** [comment]
Just stumbled over this again. Can't this easily be fixed?

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:3773439c-3b76-11e5-aa68-54ee7558c81f

**Comment by acka47** [comment]
+1
