### ISSUE TITLE
JSON schema: allow "result" property for Action

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#344]
I want to link a service to the project/action it was a result of. Thus, we have to enable "result" on Action.

**Comment by literarymachine** [comment]
While our schema is still evolving, we could also simply allow any additional properties for the time being. Then look at actual usage later and reflect that in restrictions again.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/. Still confused whether I should comment this at the PR, or here.

**Comment by acka47** [comment]
> Still confused whether I should comment this at the PR, or here.

I think here is ok. For lobid, we also do it like this because often I do the functional review on beta and the coders review their code so that the PR is assigned to them. Accordingly, code comments are on the PR and functional comments on the ticket the PR originated from. As your comment addresses functional review, it best fits here.

**Comment by acka47** [comment]
+1 It works, see https://beta.oerworldmap.org/resource/urn:uuid:dda9c992-427f-11e5-92ed-54ee7558c81f

**Comment by literarymachine** [comment]
Deployed to https://oerworldmap.org/
