### ISSUE TITLE
JSON Schema: Set "type" to "array" for "license"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#346]
Currently I am working on adding http://www.africanstorybook.org/ to the map. As many other services they enable chosing between different licenses (CC-BY and CC-BY-NC, see http://www.africanstorybook.org/content/our-story). Thus, it makes sense to enable indicating several licenses for one service.

@literarymachine I can adjust the schema. I may also adjust the current data as I don't think there are already many services with license information. Of course it would be more safe to adjust this by a script...

**Comment by literarymachine** [comment]
Changing `license` to allow multiple values will make it necessary to update the elasticsearch mapping. Thus, all data will have to be ingested into a new index. While at this, I might as well script the changes to the existing data.

**Comment by acka47** [comment]
OK. I will request a pull soon.

**Comment by acka47** [comment]
Reminder for myself: Add the African Storybook project as soon as this is deployed.

**Comment by literarymachine** [comment]
On beta.

> Changing license to allow multiple values will make it necessary to update the elasticsearch mapping.

@acka47: I was mistaken here, changing the type to `array` does not require a new mapping because the values remain strings. Would you mind adjusting the current Service descriptions manually?

**Comment by acka47** [comment]
I adjusted and re-posted toe beta the following stories:
OER research hub, IndioEduca story, Opening Canons, Folhas (removing the license info), Serlo

Looks good. +1 Let me know when I should re-post them to production...

**Comment by literarymachine** [comment]
Deployed to production. /cc @acka47
