### ISSUE TITLE
Project count incorrect on country page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#348]
See e.g. https://oerworldmap.org/country/us or https://beta.oerworldmap.org/country/za where the project count is always on "0" though there are actually projects listed.

**Comment by literarymachine** [comment]
On beta, e.g. https://beta.oerworldmap.org/country/za

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
@acka47 @literarymachine Seems to be done - shall we close the issue?
