### ISSUE TITLE
JSON Schema: Add "description" to type "Article"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#349]
It would be great to have teasers for stories to be shown on the start page instead of the cut-off first sentence. We will start wirth adjusting the schema to allow a "description" property on type "Article".

**Comment by literarymachine** [comment]
On beta

**Comment by literarymachine** [comment]
@acka47 Is this OK?

**Comment by acka47** [comment]
+1 Works, see https://beta.oerworldmap.org/resource/urn:uuid:9784d85c-3f56-11e5-9a19-001999ac7927.
