### ISSUE TITLE
Export Results as CSV and / or JSON

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#35]
As a general user I want to export search results as CSV so that I can manipulate them in an apllication like Libre Office Calc or MS Excel.

**Comment by philboeselager** [comment]
@literarymachine Should we keep this story open until the export function is involved in the frontend?

**Comment by literarymachine** [comment]
@philboeselager Yes, I would say so.

**Comment by acka47** [comment]
I just noticed https://github.com/OpenDataServices/flatten-tool/ (via http://csvconf.com/#bwebb). It seems that it might be useful for our purposes.

**Comment by literarymachine** [comment]
Yes, I was in that session yesterday and it seems worth to investigate this further. It is pretty close to what @philboeselager has already implemented.
