### ISSUE TITLE
Show URL for projects

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#351]
URLs are given for most projects but not shown in the HTML, see e.g. https://oerworldmap.org/resource/urn:uuid:e8cd9900-3b79-11e5-bd3d-54ee7558c81f.

**Comment by trugwaldsaenger** [comment]
URL is also missing for organizations where it is even more important to be shown.

**Comment by trugwaldsaenger** [comment]
I would propose writing the link directly under the name/headline of the entry 
Example:("URL=http://hbz-nrw.de")
By doing so, we can distinguish between internal and external links. If a name is directly linked, it is an internal link going to another World Map entry. If it is written out, it is an external link.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:1a8efa2e-3b7f-11e5-a24e-54ee7558c81f

**Comment by acka47** [comment]
+1 from my side

**Comment by acka47** [comment]
@trugwaldsaenger is also ok with this. Assigning Felix and moving to "deploy".

**Comment by literarymachine** [comment]
Deployed, see e.g. https://oerworldmap.org/resource/urn:uuid:1a8efa2e-3b7f-11e5-a24e-54ee7558c81f
