### ISSUE TITLE
JSON Schema: Repleace "logo" by "image"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#356]
See https://github.com/hbz/oerworldmap/issues/309#issuecomment-136351263.

**Comment by acka47** [comment]
Merged, thus, closing.

**Comment by acka47** [comment]
I assumed this already was deployed, is it?

**Comment by literarymachine** [comment]
Yes. Sorry, this PR vs issue thinking is something I'm still not very happy with.
