### ISSUE TITLE
Provide list of licenses to be chosen in Service form

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#358]
At least, we will need all CC licenses including, CC0 and Public Domain Mark. Additionally, we will need "none" and something like "Other".

**Comment by acka47** [comment]
One question will be, what link we add to the data. E.g. CC-BY exists in different laguage versions, for example https://creativecommons.org/licenses/by/3.0/br/deed.en and https://creativecommons.org/licenses/by/3.0/de/. We may even think about creating another controlled vocabulary for this...

**Comment by acka47** [comment]
At #swib15 I learned about http://rdflicense.linkeddata.es/ – a dataset with URIs and RDF descriptions for ~ 150 licenses. We should also think about making use of this dataset.

**Comment by acka47** [comment]
I guess we don't need this list when we have the openness indicator (#237) in place, do we?

**Comment by acka47** [comment]
> I guess we don't need this list when we have the openness indicator (#237) in place, do we?

I just talked to @trugwaldsaenger. We decided to provide the list as the openness indicator won't be finished soon.

**Comment by acka47** [comment]
As discussed offline with @literarymachine, I will provide a SKOS-JSON-LD file for this and put it into https://github.com/hbz/oerworldmap/tree/master/public/json.

**Comment by acka47** [comment]
I made the SKOS file, see #590. As of now it would enable choosing between:

- Creative Commons Attribution
- Creative Commons Attribution Share-Alike
- Creative Commons Attribution Non-Commercial
- Creative Commons Attribution Non-Commercial Share-Alike
- Creative Commons Public Domain Dedication
- Other (Attribution)
- Other (Share-Alike)
- Other (Non-Commercial)
- Unspecified

@trugwaldsaenger is this ok for the start or do you envision something different?

**Comment by acka47** [comment]
I just discussed this offline ith @trugwaldsaenger. We decided to also add No-Derivatives licences:

- Creative Commons Attribution No-Derivs
- Creative Commons Attribution Non-Commercial No-Deriv
- Other (No-Derivs) 

Reassigning myself.

**Comment by acka47** [comment]
Moved this to ready and assigned @literarymachine as the this has now has to be implemented in the web form.

**Comment by literarymachine** [comment]
> Moved this to ready and assigned @literarymachine as the this has now has to be implemented in the web form.

Because we still have legacy data in `licence`, I will add a temporary field `licenceConcept` that will hold the links to the licences. Once the data is migrated, `licenceConcept` will be moved back to `licence`.

**Comment by literarymachine** [comment]
On beta, see e.g. the form of https://beta.oerworldmap.org/resource/urn:uuid:c23c958c-7f00-11e5-a636-c48e8ff4ea31 where I added links to the licenses but left the textual representations intact.

**Comment by acka47** [comment]
It works and I'd say the basic requirement of this issue is met, thus +1.

Some things are still missing, though, and I will make issues for them as soon as this is deployed:

1. To all services with textual licenses, I will add the SKOS versions.
2. After 1, we have to remove the other license field from the display.
3. The labels icons don't seem appropriate. We should add the [CC buttons](https://creativecommons.org/about/downloads/) for CC logos and another icon for the other licenses. (I could add them to the SKOS file with http://schema.org/image or so.)
4. The licenses should be shown in the description – at best using the same icons as we will add to the form.
5. We will also have to add another filter – by license – to the services search.

**Comment by acka47** [comment]
Working on #612 I realized that we should definitely add a `Copyright` option. We have a number of services in there that explicitely offer resources that have full copyright restrictions. Currently, I don't add any license information for these but thus is not satisfying. @literarymachine Shall we leave this ticket open for adding it or should I open a new issue?
