### ISSUE TITLE
Show all resources reverse-chonologically on start page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#363]
Currently, only the stories are shown on the start page. As we move the focus away from adding stories, we will adjust the start page to show all types of resources in reverse-chronolgical order.

**Comment by trugwaldsaenger** [comment]
+1 We should do this with high priority!

**Comment by literarymachine** [comment]
Not all done yet, but on https://beta.oerworldmap.org/ nevertheless. Prev/next links are currently somewhat lost underneath the result listing.

**Comment by acka47** [comment]
As far as I understand, the sorting is by "last modified", i.e. date of last POST. Am I right? I am not sure whether this is what we want. Listing modified resources on top may be an incentive to keep ones resources up-to-date but on the other hand, people may add spaces to their entries just to be listed on top. 

@trugwaldsaenger, what do you think?

If we want them sorted by date of publication (not modification) we probably will have to add `datePublished` to the JSON (see #311 ), don't we?

**Comment by literarymachine** [comment]
> As far as I understand, the sorting is by "last modified", i.e. date of last POST. Am I right?

Nope, the sorting is by date created: see https://beta.oerworldmap.org/resource/?sort=dateCreated:desc vs. https://beta.oerworldmap.org/resource/?sort=dateModified:desc

> If we want them sorted by date of publication (not modification) we probably will have to add datePublished to the JSON (see #311 ), don't we?

No. This would mean that only `Article`s could be sorted by publication date. Now that we have all types of resources in the result listig, this does not make sense. We have a `dateCreated` and `dateModified` property for each resource (these are actually properties of the `Record` the resource is embedded in in the background).

**Comment by acka47** [comment]
Great. Thanks for the explanation, @literarymachine . (I am afraid you already told me all of this on the phone but obviously I need some repetion once in a while.)

**Comment by literarymachine** [comment]
I've discussed some internal changes with @philboeselager and it looks like we're good to go. So @acka47 and @trugwaldsaenger does the listing / paging basically work how you expect? Then I would merge this to master and @j0hj0h can take over from there for some styling along with other UI fixes he is making.

**Comment by acka47** [comment]
> So @acka47 and @trugwaldsaenger does the listing / paging basically work how you expect? 

It does on the first page but not when I start navigating the list. Obviously, the sorting changes when changing pages. E.g., when I got to https://beta.oerworldmap.org/, click on the "next" button and then on the "prev" button I expect to come back to the same page as I started on but I won't.

**Comment by literarymachine** [comment]
Fixed on https://beta.oerworldmap.org/

You might still experience slighlty odd sorting behaviour. This is due to the fact that when ingesting multiple resources at the same time, they all have the same timestamp. Ordering within those resources is thus not possible and may vary due to elasticsearch ranking.

**Comment by acka47** [comment]
+1
