### ISSUE TITLE
Complement "non-formal education" and "informal education" to list of levels of education?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#366]
The scope of ISCED covers only formal education, but not non-formal and informal education. 

ISCED 2011 (http://www.uis.unesco.org/Education/Documents/isced-2011-en.pdf, page 11) defines non-formal education as following:

> Like formal education (but unlike informal, incidental or random learning), non-formal education
> is education that is institutionalised, intentional and planned by an education provider. The 
> defining characteristic of non-formal education is that it is an addition, alternative and/or 
> complement to formal education within the process of lifelong learning of individuals. It is 
> often provided in order to guarantee the right of access to education for all. It caters to people 
> of all ages but does not necessarily apply a continuous pathway structure; it may be short in 
> duration and/or low-intensity; and it is typically provided in the form of short courses, workshops 
> or seminars. Non-formal education mostly leads to qualifications that are not recognised as 
> formal or equivalent to formal qualifications by the relevant national or sub-national education 
> authorities or to no qualifications at all. Nevertheless, formal, recognised qualifications may be 
> obtained through exclusive participation in specific non-formal education programmes; this often 
> happens when the non-formal programme completes the competencies obtained in another 
> context.

Informal learning is defined on page 14 as: 

> Informal  learning does not fall within the scope of ISCED for measuring participation in 
> education, although recognised qualifications obtained through informal learning are considered 
> when determining educational attainment levels. Informal learning is defined as forms of learning 
> that are intentional or deliberate, but are not institutionalised. It is consequently less organized 
> and less structured than either formal or non-formal education. Informal learning may include 
> learning activities that occur in the family, workplace, local community and daily life, on a self-
> directed, family-directed or socially-directed basis. Like formal and non-formal education, 
> informal learning can be distinguished from incidental or random learning

It's quite complex and I'm not sure if I understood everything right, but it seems to me that many sorts of vocational training and further education as being described in Germany recently by the Whitepaper OER Weiterbildung/Erwachsenenbildung (see http://open-educational-resources.de/oer-whitepaper-weiterbildung/) is according to ISCED non-formal education. Another example would be the P2PU, which considers itself explicitly as "outside of institutional walls" (https://www.p2pu.org/en/about/), so I guess this makes it a platform, which supports informal learning according to ISCED. 

Though we have to check this with our definition of OER and our collection scope, I would strongly argue that we should collect these kinds of ressources as well. If all this is correct the question is, how we should include non-formal education and informal learning to our skosmos ISCED representation. I would argue that we should include a new top level starting with "formal education", "non-formal" education" and "informal education". It would be great to get some advice from an ISCED expert on this!

**Comment by acka47** [comment]
Discussing this some days ago, we found that informal/non-formal/formal is rather a classification  complementary to a classification by levels and thus should be added as a separate classification.

**Comment by drrobertfarrow** [comment]
The terms 'non-formal' and 'informal' are contentious.  I have just written a paper on what we ultimately came to refer to as 'non-formal' learning.  By this we meant people using open resources without guidance and without it leading to a qualification.  

The phrase 'informal' learning I understand to refer more to things like workplace learning.  But there is no real agreement on this - or at least this was the view of my team.  In OER Research Hub we considered informal learning to be another 'level' on the basis that resources from any level can be used informally by potentially anyone.  Our view is closer to the OECD definition (http://www.oecd.org/edu/skills-beyond-school/recognitionofnon-formalandinformallearning-home.htm) than the ISCED.

For me, the simplest solution would be to have two categories: formal (organised and structured, and has learning objectives) and non-formal (everything else).  The complication is where formal resources are re-appropriated and used non-formally.  As long as we are consistent I do not think there will be a problem - but we can expect the possibility that some people will criticise any schema we use so we should be prepared to write a justification.

**Comment by acka47** [comment]
> For me, the simplest solution would be to have two categories: formal (organised and structured, and has learning objectives) and non-formal (everything else). 

@trugwaldsaenger and I came to the same conclusion when discussing this in the past. Just to be sure: I do understand you correctly that you agree this should be a complementary classification and not part of the educational levels classification?

**Comment by drrobertfarrow** [comment]
I think so - because a resource may be intended for a particular (formal)
level of education but used in entirely different ways once
re-appropriated.  Most of the time non-formal use will be re-use of
materials written for a formal purpose (e.g. open textbooks).

As I say, this quickly gets complicated and there is a lot of disagreement
over the best way to categorise it.  Often resources are generated for a
formal purpose but used in other ways. It's hard to think of many things
that would meet the non-formal definition from the beginning - but they are
probably the most widely used resources (e.g. Wikipedia, YouTube).  A
further complication is in how resources from the commons are used
informally by those working in formal contexts (e.g. a teacher prepares for
a lesson by looking at Wikipedia, or pulling some pictures from Flickr).

In short, I don't think there is an easy answer.  I even wonder whether we
should use the language of formal/non-formal at all.  Maybe it would be
better to just provide the suggested educational level (where it is known)
and call everything else 'general' or 'commons'... ?


On Wed, Oct 14, 2015 at 10:45 AM, Adrian Pohl <notifications@github.com>
wrote:

> For me, the simplest solution would be to have two categories: formal
> (organised and structured, and has learning objectives) and non-formal
> (everything else).
>
> @trugwaldsaenger <https://github.com/trugwaldsaenger> and I came to the
> same conclusion when discussing this in the past. Just to be sure: I do
> understand you correctly that you agree this should be a complementary
> classification and not part of the educational levels classification?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hbz/oerworldmap/issues/366#issuecomment-147993004>.
>



-- 
Dr. Robert Farrow
@philosopher1978
http://philosopher1978.wordpress.com/

**Comment by literarymachine** [comment]
Inactive.
