### ISSUE TITLE
JSON Schema: Add memberOf/affiliation

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#367]
Currently, we can neither link an organization to another org it is member of nor link a person to an organization it is affiliated with. We should add this possibility and adjust schema.json accordingly.

There are two options:

1. Use [`schema:memberOf`](http://schema.org/memberOf) both for persons and organizations.
2. Use `memberOf` for organizations and the sub property [`schema:affiliation`](http://schema.org/affiliation) to link persons to an organization.

I guess 2. isn't really necessary as we can see what kind of relation it is by the type of the linked resources. Anyway, it might be easier for people who read/write/submit the JSON. What do you think, @literarymachine ?

**Comment by acka47** [comment]
In the case of the properties `image` and `logo` who chose to use the more generic (`image`) both for persons and organizations. If we follow this example, we should use `memberOf` here. As discussed before chatting, I am not very pleased with the schema.org wording, as I actually think "member of" is more specific than "affiliation" with regards to persons. This might be an argument for chosing the more appropriate term "affiliation" for persons.

**Comment by literarymachine** [comment]
>  I am not very pleased with the schema.org wording, as I actually think "member of" is more specific than "affiliation" with regards to persons

I definitely agree with you from a natural language point of view. Nevertheless, one could argue that we should use `memberOf`, not so much because of the more or less formal semantics defined in schema.org but so that the overall number of properties is reduced.

**Comment by acka47** [comment]
> one could argue that we should use `memberOf`, not so much because of the more or less formal semantics defined in schema.org but so that the overall number of properties is reduced.

+1 Will go ahead adding `memberOf` to `Person` and `Organization`. Shall I also add the inverse property `member` or should it only be added automatically?
