### ISSUE TITLE
JSON Schema: Add ContactPoint construct to Organization

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#368]
We will have to add a way of indicating a contact person for an organization. Currently, we use a workaround that may be confusing in the UI. See for example https://oerworldmap.org/resource/urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930 (snippet):

```javascript
{
  "@id" : "urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930",
  "@type" : "Organization",
  "name" : [ {
    "@value" : "OER Research Hub c/o Dr. Rob Farrow",
    "@language" : "en"
  } ],
  "countryChampionFor" : [ "GB" ],
  "email" : "rob.farrow@open.ac.uk"
}
```

It should rather look something like this:

```javascript
{
  "@id" : "urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930",
  "@type" : "Organization",
  "name" : [ {
    "@value" : "OER Research Hub",
    "@language" : "en"
  } ],
  "countryChampionFor" : [ "GB" ],
  "contactPoint": [ "urn:uuid:$some-uuid" ] .
```

...with a separate entry for the actual person:

```javascript
{
  "@id": "urn:uuid:$some-uuid",
  "name": "Rob Farrow",
  "honorificPrefix": "Dr.",
  "email" : "rob.farrow@open.ac.uk"
}
```
(I don't know whether we actually need the `honoricPrefix`, though.)

@literarymachine You will probably object, that schema.org rather suggests/expects/proposes to use a  resource of type `ContactPoint` linked with the property `contactPoint`. I actually see no problem with using a `Person` as such a `ContactPoint` for `Organization` (indeed, I wouldn't add the additional type `ContactPoint`). If you have no objections for this approach, I will go on adding it to the schema.

**Comment by literarymachine** [comment]
> I actually see no problem with using a Person as such a ContactPoint for Organization (indeed, I wouldn't add the additional type ContactPoint). If you have no objections for this approach, I will go on adding it to the schema.

Fine with me. Since this is a new property, re-indexing data should not be required.

**Comment by acka47** [comment]
looks good to me. I already updated https://oerworldmap.org/resource/urn:uuid:f067d150-15b1-11e5-92c6-001999ac7930 & https://oerworldmap.org/resource/urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930. Will add missing country champions next week.

BTW, as Centrum Cyfrowe has a long description sameAs etc. it is a good country champion entry to look into for layout adjustments: https://oerworldmap.org/resource/urn:uuid:f067d150-15b1-11e5-92c6-001999ac7930

**Comment by acka47** [comment]
I updated all other organizational champion entries I knew of that have a person associated with them. Closing.
