### ISSUE TITLE
Copy existing posts to wordpress blog

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#37]
Task derived from #24. Copy posts from https://wiki1.hbz-nrw.de/pages/viewrecentblogposts.action?key=WOERLD to https://oerworldmap.wordpress.com.

**Comment by acka47** [comment]
I copied the first two posts. I didn't add https://wiki1.hbz-nrw.de/x/KoD7Ag, though, at it is about the public wiki which we want to replace by the wordpress blog.

I also added a wordpress page with the proposal, see https://oerworldmap.wordpress.com/proposal/. I didn't upload the uimage files to wordpress though, the links still go to the hbz wiki page. Will do this later.

**Comment by acka47** [comment]
I did some more work on the [proposal](https://oerworldmap.wordpress.com/proposal/), adjusted the html anchors and uploaded the embedded/linked to images and pdf to wordpress. It already looks much better than the wiki page.... It should all be at wordpress now so that the public wiki space can be deleted.

I am happy to give others admin access to the blog. Just contact me.

Closing.

**Comment by trugwaldsaenger** [comment]
Looks great - much better than our confluence blog! Thanks very much acka47! One important detail: In the sub-headline it should be "The William and Flora Hewlett Foundation". I would be happy to get admin  access!

**Comment by acka47** [comment]
@trugwaldsaenger Sent you an invitation and capitalized the "The" in the sub-headline. I think that this spelling was ok witht the foundation.
