### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#371]
We should have old data being "normalized" for the release of v.03, since newly ingested data will automatically be normalized from then onwards and we need to be consistent in all our data. Therefore, we should define a data migration procedure that ensures that all data is according to the new "scheme" after a migration.

**Comment by philboeselager** [comment]
An approach of favour is to GET the old index and to POST it into a new one.

A) This could either be done by a script. @jschnasse gave notice to be careful of Elasticsearch inner sort order that might change during subsequent page requests. (Might not be a problem as long as the index is small, but the danger increases with the indexes size.) @dr0i has found a good solution for avoiding these problems by using scrolling.

B) Another approach could be to make use of the https://github.com/mallocator/Elasticsearch-Exporter that seems to deliver anything desirable (and much more).

**Comment by literarymachine** [comment]
> An approach of favour is to GET the old index and to POST it into a new one.

We should not GET and POST data directly from the ES index, but via our API. It is then automatically validated against the schema so that no invalid data can get into the new instance.

**Comment by literarymachine** [comment]
@philboeselager see #381

**Comment by acka47** [comment]
Done. Closing.
