### ISSUE TITLE
Improve SSL server security

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#372]
I just ran an analysis of the oerworldmap SSL server, see https://www.ssllabs.com/ssltest/analyze.html?d=oerworldmap.org. Obviously, this could be improved.

**Comment by philboeselager** [comment]
Having talked to Peter Reimer, it points out that the best way to go is to upgrade the server's operating system and the web server - all by the help of our IT department. From your point of view, @acka47 and @literarymachine , is there any disadvantage in doing so? We can discuss that in detail on the chat channel if you like.

**Comment by literarymachine** [comment]
I can't see any disadvantage in having an up to date server. So +1 from me.

**Comment by acka47** [comment]
+1 from me as well.

**Comment by philboeselager** [comment]
Upgrade is expected to be done on September 21st.
