### ISSUE TITLE
Set up reverese proxy for blog.oerworldmap.org

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#38]
To hide https://oerworldmap.wordpress.com/ and use http://blog.oerworldmap.org instead.

Task derived from #24

**Comment by acka47** [comment]
As soon as @trugwaldsaenger passes the admin password for the oerworldmap.org domain I will set up a a reverse proxy with @dr0i.

**Comment by literarymachine** [comment]
Visiting http://blog.oerworldmap.org/ currently yields an HTTP 500. /cc @dr0i

**Comment by acka47** [comment]
The reverse proxy now works for https://blog.oerworldmap.org. However, as soon as I navigate within the blog – e.g. by clicking the post or the map in the upper lef corner – I will end at a `wordpress.com` URL. I couldn't find a way to configure the site so that this doesn't happen.

I guess there are only two ways to solve this:
# Pay wordpress.com for the custom URL, see https://en.support.wordpress.com/domains/.
# Install our own wordpress instance on our own server.

**Comment by literarymachine** [comment]
3. Live with it.

**Comment by literarymachine** [comment]
Closing this, as there is nothing left to be done for the reverse proxy.
