### ISSUE TITLE
Show heat map of registered email addresses origins on landing page

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#39]
As an OER advocate I want to see a heat map displaying how many email addresses where registered for which country so that I can focus on attracting interest in underrepresented countries.

**Comment by literarymachine** [comment]
@j0hj0h and I came up with the idea that instead of using the map on the landing page to display country champions, we could use it to display the origins the countries of users that the registered their email addresses. On the one hand, this would most likely result in a more dynamic (i.e. evolving) map. On the other hand, and this is more important, we would have a first iteration of the heat map that is meant to be on the start page anyways.

**Comment by trugwaldsaenger** [comment]
Great idea!
