### ISSUE TITLE
Missing Link to fields of education

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#392]
The link to "fields of education" is missing ("Not found")
Priority: 1

**Comment by acka47** [comment]
On beta, it now works, see https://beta.oerworldmap.org/resource/https://w3id.org/class/esc/scheme. I suggest showing a list of all top concepts by default. (And we will have to think about getting some order into this.)

**Comment by literarymachine** [comment]
Are there any top concepts missing in the list? You can expand by clicking "Show more". This behavior comes from other resource listings such as [1], where displaying all links is a bit of an overkill.

[1]: https://beta.oerworldmap.org/resource/urn:uuid:cc0b18cc-3b5d-11e5-b315-54ee7558c81f

**Comment by acka47** [comment]
> Are there any top concepts missing in the list?

No.

> You can expand by clicking "Show more".

I bascially meant that the list should be expanded by default.

**Comment by acka47** [comment]
Done.
