### ISSUE TITLE
Unify "Fields of education" and "Topics"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#393]
As far as I can see it, both terms are synonym. @acka47: Could you please confirm this? If synonym, we should use only one term. I would argue for "topics" because it is shorter...
Prio 1

**Comment by acka47** [comment]
Yes, all these are synonomous: "topic", "field of education", "subject". As we will name the ESC "educational subjects classification", "subject" is also a term we should think about.

**Comment by acka47** [comment]
On beta, still both are used. I suggest consistently using "subject area".

**Comment by literarymachine** [comment]
Didn't know which term to use, so didn't fix it. Is it "topic", as @trugwaldsaenger suggests, or "subject area". I'd actually kick the "area" and go with "subject".

**Comment by acka47** [comment]
"Subject" would be also ok with me and I suggest using it in both occurrences for now so that we don't confuse user by using two different terms. After that we may still think about adjusting it.

I like "subject area" more because it is 
1. used with a generic meaning like "topic" or "subject" (German "Themengebiet"),
2. also used synonymous to "field of study" and "discipline" (German "Fahcrichtung") which is good in our context.

@drrobertfarrow, what do you think as a native speaker?

**Comment by drrobertfarrow** [comment]
An alternative description would be 'discipline' but 'subject area' I think
is fine.  I can see that we may want to distinguish two levels here.  One
would be the specific sub-field of the subject area - most likely this is
the data that we will be provided with.  But there may also be some use in
applying an overarching taxonomy as well.  For example, the list provided
by HESA at https://www.hesa.ac.uk/content/view/1776/649/ is a taxonomy that
incorporates the full list of subject areas described in
https://www.hesa.ac.uk/dox/datacoll/jacs3/JACS3_20120529.csv

I have a feeling we may have already discussed this and arrived at a
solution - if so, apologies!  But differentiating broad and specific
categories for this might be useful later on.

**Comment by trugwaldsaenger** [comment]
@drrobertfarrow Thanks for sharing the HESA taxonomy - I was not aware of this. It seems to be much more detailed than the ISCED cathegory we are using, since it contains more than 1500 subjects. Would you argue that we should include this in the nearer future? I guess that it would be hard for us from a ressource point of view, because it seems more easy to use the less granular ISCED classification

**Comment by trugwaldsaenger** [comment]
Let me see. I count five proposals:
1. Fields of education
2. Topic
3. Subject
4. Subject Area
5. Discipline
It seems as if we need a decision here. I would tend to use I will discuss this tomorrow with @acka47 and provide a final decision ASAP!

**Comment by acka47** [comment]
We decided on "subject" (last at the physical meeting). Moving to "ready".

**Comment by literarymachine** [comment]
#486 on https://beta.oerworldmap.org/

**Comment by acka47** [comment]
I can see the changes in commit https://github.com/hbz/oerworldmap/commit/77b89bfa832369ab1457c3c0b914e647724058c4 but it's currently not on beta. Anyway, +1 from seeing the commit.

**Comment by literarymachine** [comment]
> I can see the changes in commit 77b89bf but it's currently not on beta.

Sorry, didn't merge 77b89bf back to beta after deploying #491.
