### ISSUE TITLE
Reposition link to "search page"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#395]
New Homepage: The link to the search page is acutally hidden behind the word "more" at the bottom of the right column. We should place it somewhere more prominent. I see following solutions:
1) Place it as a button beneath "Contribute" in the top navigation
2) Place it as a search slot in the top navigation, e.g. left to "Join us in mapping..."
3) Include it at the end of the short text on the top of the right coloum "You can search our database here"
Prio: 1
I guess 3) will be the easiest and fastest solution

**Comment by acka47** [comment]
On beta, I currently don't see any search field on the start page. Clicking on "organizations" and then into the search field, the filter set and search field overlap.

It's not so bad in Firefox:

![overlap_firefox](https://cloud.githubusercontent.com/assets/160292/10377924/521ab8b6-6e06-11e5-9d07-8dae355ce6d7.png)
 
In Chromium it is quite an obvious flaw, though:

![overlap_chromium](https://cloud.githubusercontent.com/assets/160292/10377967/89b88c44-6e06-11e5-96b4-cf94532fbe1c.png)

(This doesn't really have much to do with the original issue. Feel free to make a separate issue out of this.)

**Comment by literarymachine** [comment]
As for the link on the start page, I discussed this with @j0hj0h a bit. We both believe that since basically *any* link from the start page takes the user to the search page, we don't need an explicit link.

Concerning the layout: this is still in the works, the search box and the list of filters will not be deployed like this. #394 will be fixed along with it.

**Comment by trugwaldsaenger** [comment]
I think we can close this issue at the moment, since we will introduce another navigation soon, which will include a clear navigation to the search function.
