### ISSUE TITLE
Include news section on landing page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#4]
As a member of the OER community or someone from the general public I want to comfortably see headline of and links to the latest news regarding the OER World Map.

**Comment by acka47** [comment]
Part of epic #11.

**Comment by literarymachine** [comment]
Do I assume correctly that the "news" referred to here are the blog posts from #24?

**Comment by drrobertfarrow** [comment]
I think that makes the most sense but it would be good to ensure that we have news to share!  I am going to propose a blogging schedule as a new ticket but overall I am happy to take care of making sure there is news there.  It might also be a good idea to create a Twitter account for the project which can also function as a news feed.
