### ISSUE TITLE
Filter OER services by grade level

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#40]
As a learner or teacher I want to filter OER discovery services by grade level.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/resource/

/cc @acka47 @trugwaldsaenger

**Comment by acka47** [comment]
Works fine but shouldn't it be possible to combine two filters with OR? Also, I would call the filter "grade level" (we even will use another property than "audience" in the JSON, see #412).

**Comment by literarymachine** [comment]
As mentioned in https://github.com/hbz/oerworldmap/issues/163#issuecomment-141785454, could we please discuss the intended behavior / combinations of filters in general?

**Comment by acka47** [comment]
> As mentioned in https://github.com/hbz/oerworldmap/issues/163#issuecomment-141785454, could we please discuss the intended behavior / combinations of filters in general?

See #447 for discussing the intended behaviour of filters. +1 for this one.
