### ISSUE TITLE
Enable browsing ESC on one page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#402]
As a user I want to browse the whole classification on one page seeing each notation in its relation to other notations.

This means, we should make something like a hierarchical "accordion" navigation available where I can fold out a broader notation to show the sub-notations and may subsequently collapse it. See e.g. http://lobid.org/nwbib/classification?t=Sachsystematik.

**Comment by trugwaldsaenger** [comment]
This is related to #413

**Comment by literarymachine** [comment]
On beta: https://beta.oerworldmap.org/resource/https://w3id.org/class/esc/scheme

**Comment by acka47** [comment]
Looks very nice. One thing I noticed using it: The `+` and `-` for unfolding/collapsing are a bit far off on a wide screen. For browsing the classification it may be be good tohave them nearer to the respective text.

**Comment by j0hj0h** [comment]
We'll probably limit the column width (of 2nd and 3rd column) to a maximum value in the future, so the lines wouldn't get to long anymore.
