### ISSUE TITLE
Query for services within a specific notation & its subnotations

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#404]
As a user I want to easily show a list of services associated with a specific field of education and its sub-fields so that I can easily filter it further by other dimensions (e.g. language).

Browsing ESC, I want to be able to easily initiate a search for every notation and its subnotations. Basically, I want to show the list of services for which the overall number is already indicated at each level (see #403).

**Comment by literarymachine** [comment]
See http://h2481931.stratoserver.net:9000/resource/?filter.about.about.@id=https%3A%2F%2Fw3id.org%2Fclass%2Fesc%2Fn05 vs https://oerworldmap.org/resource/?filter.about.about.@id=https%3A%2F%2Fw3id.org%2Fclass%2Fesc%2Fn05

**Comment by literarymachine** [comment]
As is, a `Service` is explicitly enriched with broader concepts in the database, see e.g. topics in http://h2481931.stratoserver.net:9000/resource/urn:uuid:6fc9d260-23bb-11e5-bba4-001999ac7927 vs those in https://oerworldmap.org/resource/urn:uuid:6fc9d260-23bb-11e5-bba4-001999ac7927

**Comment by literarymachine** [comment]
http://h2481931.stratoserver.net:9000/resource/https://w3id.org/class/esc/n05 vs https://oerworldmap.org/resource/https://w3id.org/class/esc/n05

**Comment by acka47** [comment]
Done.
