### ISSUE TITLE
Only show top-level notations for service classification on start page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#405]
To get a better overview over which materials the services recorded in the OER worldmap provide, we should only show the ten top-level fields in the "services by subject" overview on the start page. Clicking on a top level I will get the result list with all the services and the possibility to further filter by sub-fields.

This isse depends on #404 and #403.

**Comment by trugwaldsaenger** [comment]
+1 At the moment it is impossible to use the diagrams for navigation, due to the many shown segments.

**Comment by literarymachine** [comment]
On http://h2481931.stratoserver.net:9000/

**Comment by literarymachine** [comment]
Had to also implement #404 for this because close to non services where associated directly with a top-level concept.
