### ISSUE TITLE
Change functionality of "Recent additions - more"

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#409]
On the homepage, right now clicking on "more" opens the search page. I find this functionality confusing since a link to the search page should be named "search" or similar. 

It is also not clear to me according to which criteria the results are sorted, which appear after clicking on "more". Since it is standing under the headline of "Recent additions" I would argue that a button "more" should link to a list which shows more recent additions, e.g. all entries in the data hub in a chronological order.

**Comment by acka47** [comment]
Duplicate and done. Closing.
