### ISSUE TITLE
Filter OER services by subject

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#41]
As a learner or teacher I want to filter OER discovery services by subject.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/resource/

Formatting is not ideal and vocabulary hierarchy is not reflected in drop-down. I would argue that these are issues for the re-design of the filter section, though.

/cc @acka47 @trugwaldsaenger

**Comment by acka47** [comment]
> Formatting is not ideal and vocabulary hierarchy is not reflected in drop-down. I would argue that these are issues for the re-design of the filter section, though.

+1 But I think an OR combination of subjects would be useful. It makes sense to have an exclusive type filter but it should be possible to combine subjects...

**Comment by literarymachine** [comment]
As mentioned in https://github.com/hbz/oerworldmap/issues/40#issuecomment-155820289, I believe that the actual behavior and combination of filters is a separate issue.

**Comment by acka47** [comment]
Ok then: +1. The actual behaviour and combination will be defined in #447 .
