### ISSUE TITLE
Fix height of pie charts

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#411]
Right now the height of the pie charts changes, depending on the size of the monitor you are using. On smaller monitors the headings are shown in two lines, which presses the pie chart down. If possible, the pie charts should always be shown in one line.

**Comment by trugwaldsaenger** [comment]
![piecharts](https://cloud.githubusercontent.com/assets/6639965/10478420/98958e0a-725d-11e5-964c-4b650cfcf72d.JPG)

**Comment by acka47** [comment]
problem doesn't occur in the [new statistics view](https://oerworldmap.org/aggregation/). Closing.
