### ISSUE TITLE
Deletion of resources is not reflected in denormalization

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#419]
When deleting a resource, the link views to the deleted resources are still present.

**Comment by philboeselager** [comment]
Thinking about where to implement that:

- in the leaf repositories (i. e. FileRepository and ElasticsearchRepository). Advantage: relatively simple. Disadvantage: no direct dependency deletion across the leaf repos.
- in BaseRepository: a bit more complicated to implement, but cross-leaf-repo deletion would be possible.

Would we need cross-leaf-repo deletion (one day)?

**Comment by literarymachine** [comment]
> Would we need cross-leaf-repo deletion (one day)?

I think it would be good to implement this in BaseRepository because that is also the place where denormalization takes place.
