### ISSUE TITLE
Many Services not displayed on Map 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#423]
Right now there are 72 services included, but only 50 of them are displayed on the map. @acka47  assumes that there is a problem with the automatic generation of the geodata. 
Here are some examples:
1)
https://oerworldmap.org/resource/urn:uuid:c7046e14-7f00-11e5-a636-c48e8ff4ea31
https://oerworldmap.org/resource/urn:uuid:1e5625dd-6241-4cdf-86ff-c93d0c738ee7
2) 
https://oerworldmap.org/resource/urn:uuid:c1290716-7f00-11e5-a636-c48e8ff4ea31
https://oerworldmap.org/resource/urn:uuid:8a9995d6-450a-48b7-8650-47610339aaf4
3)
https://oerworldmap.org/resource/urn:uuid:c37f4340-7f00-11e5-a636-c48e8ff4ea31
https://oerworldmap.org/resource/urn:uuid:a2726d16-6019-47e7-b3da-adc3e67b2c0a
4)
https://oerworldmap.org/resource/urn:uuid:c71b92e2-7f00-11e5-a636-c48e8ff4ea31
https://oerworldmap.org/resource/urn:uuid:616446c2-510c-421b-bdc4-4fe6bf4f7448
5)
https://oerworldmap.org/resource/urn:uuid:c4455684-7f00-11e5-a636-c48e8ff4ea31
https://oerworldmap.org/resource/urn:uuid:af9868e0-8b59-4e56-a34d-3ee0f4f5b19f

**Comment by literarymachine** [comment]
We are using OpenStreetMap to look up geo locations. Some locations could not be found, see e.g.

http://nominatim.openstreetmap.org/search?q=Piet%20Heinstraat%2012%20Enschede%207511%20JE%20Netherlands

or

http://nominatim.openstreetmap.org/search?q=Vester%20Voldgade%20123%20Copenhagen%20DK-1552%20Denmark

I'm afraid we'll have to fix this manually.

**Comment by acka47** [comment]
> I'm afraid we'll have to fix this manually.

I will do this.

**Comment by acka47** [comment]
All examples listed in https://github.com/hbz/oerworldmap/issues/423#issue-114554022 are now shown on the map. it seems the biggest part of the services is shown, see https://oerworldmap.org/resource/?filter.about.@type=Service. Either the OSM lookup has been improved or someone else (@karindr ?) has added the geo coordinates manually.

Is there a way to get all services whose provider has no geo coordinates? Can I make a SPARQL query on the data?

I guess we can close the issue..

**Comment by literarymachine** [comment]
> Either the OSM lookup has been improved or someone else (@karindr ?) has added the geo coordinates manually.

There have been no more automatic imports and thus no OSM lookups.

> Is there a way to get all services whose provider has no geo coordinates?

This should list all Services that neither have a location themselves nor a provider that has a location:

https://oerworldmap.org/resource/?q=_missing_:about.provider.location.geo%20AND%20_missing_:about.location.geo&filter.about.@type=Service

> Can I make a SPARQL query on the data?

Currently no SPARQL-Endpoint is exposed.

**Comment by literarymachine** [comment]
> I guess we can close the issue..

@acka47 feel free to do so.

**Comment by acka47** [comment]
> This should list all Services that neither have a location themselves nor a provider that has a location:

> https://oerworldmap.org/resource/?q=_missing_:about.provider.location.geo%20AND%20_missing_:about.location.geo&filter.about.@type=Service

This is great to be able to ask for missing fields! I already added some geo coordinates or `provider` links. Closing.

P.S.: Also interesting for @karindr. E.g., here is a query that serves all organizations without geo data: https://oerworldmap.org/resource/?q=_missing_:about.location.geo&filter.about.@type=Organization
