### ISSUE TITLE
OEC appears in the countries of its members

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#424]
I would exspect that the OEC, like every other organization appears once on the map, namely at its location in concord, US. Nevertheless it seems to be located at all its members locations.
![ocw_location](https://cloud.githubusercontent.com/assets/6639965/10878092/af1cab0c-814b-11e5-90e9-647bdf53db53.JPG)
It also appears, when clicking on a country of its members in the search results of the country view. Interestigly, it seems not to be counted by the statistics module. E.g. in France, the statistics section counts 5 organizations, while in the search results, there are 6 organizations shown.
![numberoforganizations](https://cloud.githubusercontent.com/assets/6639965/10878204/66aa7722-814c-11e5-8ffe-edb58ff70ac3.JPG)

**Comment by literarymachine** [comment]
> I would exspect that the OEC, like every other organization appears once on the map, namely at its location in concord, US. Nevertheless it seems to be located at all its members locations.

Well, I thought that it is actually much more interesting to show the members on the map, as it is a consortium. I think we'll have to sit and think about what precisely we want to display on the map in which cases. This never has been defined.

**Comment by acka47** [comment]
> Well, I thought that it is actually much more interesting to show the members on the map, as it is a consortium. 

+1 Nonetheless, I think OEC wouldn't have to be shown in relation to each member. If it is feasible, I am in favour of only showing `member` relations on the map and not `memberOf`.

**Comment by literarymachine** [comment]
>  If it is feasible, I am in favour of only showing member relations on the map and not memberOf.

Currently we are displaying any linked resources on the map. It would be great if we could define a list of properties instead. `member` seams to be a good first candidate.

**Comment by acka47** [comment]
To do: Make a broader issue to provide a list of relations whose resources should be shown on the map.

**Comment by acka47** [comment]
@literarymachine I made the list for relations to be considered when putting markers on the map: https://github.com/hbz/oerworldmap/issues/441#issuecomment-155475628

You can go ahead and add them as exceptions to the (new) rule that we don't show markers to linked resources.

**Comment by acka47** [comment]
Closing, as this was solved with #476.
