### ISSUE TITLE
Pin Highlighting by mouseover of search results is lost

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#425]
Until recently, pins on the map were highlighted in orange, when doing a mouseover on the realted entry in a search result list. This usefull functionality seems to be lost, probably by the introduction of the pin clusters. 

It might also be interesting to include a reverse function, which highlights the search result entry, when doing a mouseover on a pin.

**Comment by literarymachine** [comment]
> This usefull functionality seems to be lost, probably by the introduction of the pin clusters.

Yes. Could you define what you would expect? I am unsure if highlighting clusters (a) makes sense and (b) is even possible.

**Comment by literarymachine** [comment]
@j0hj0h This is something we would like to have back soon, if possible.
