### ISSUE TITLE
Who is "?" ?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#426]
https://oerworldmap.org/resource/urn:uuid:f3d0e5c7-8db1-412c-89c9-366b69d3c122

**Comment by trugwaldsaenger** [comment]
http://www.world-lecture-project.org/imp/

**Comment by acka47** [comment]
? stands for the provider of http://www.world-lecture-project.org/imp/ which Elise couldn't find out who it is. As usual, there are two possible solutions for this:

1. Add another "World lecture project" entry with type `Organization` that is the provider of the service.
2. Delete the provider and add the address information and email to the service itself.

Which one do you prefer?

**Comment by trugwaldsaenger** [comment]
Do we have a rule for this decision?

**Comment by acka47** [comment]
> Do we have a rule for this decision?

No, otherwise I would have applied it.It may be time to make up such a rule. We currently have both cases in the data:

- org+ service: https://oerworldmap.org/resource/urn:uuid:c21f22ae-7f00-11e5-a636-c48e8ff4ea31
- service only: https://oerworldmap.org/resource/urn:uuid:822b87fc-2963-11e5-8198-001999ac7927

For the sake of simplicity, I prefer just one record for the service (i.e. option 2. from my comment above).

**Comment by acka47** [comment]
Here is another edge case: Just added KlasCement as an Organization, see https://oerworldmap.org/resource/urn:uuid:98ec1438-f8cf-46bf-97a0-ab639b385077 describing it as " a free platform where teachers help each other by sharing resources for students of all ages" which would we rather type as service. As KlasCement is also country champion for BE we have to type it as organization. Looking at the KlacSement web page, there is no thing as "KlasCement - the organization providing the service" but it is provided by Ministerie van Onderwijs en Vorming...

**Comment by acka47** [comment]
The simplest solution to the KlasCement problem would be allowing services as "institutional" country champions...

**Comment by acka47** [comment]
> The simplest solution to the KlasCement problem would be allowing services as "institutional" country champions...

Thinking about it, the solution I prefer would be not to add KlasCement as country champion because it isn't an organization. Instead we could directly add Jans de Boer as personal champion who is then affiliated with KlasCement.

**Comment by acka47** [comment]
Regarding the world lecture project, I added the name of the e.V. which is named as provider in the [impressum](http://www.world-lecture-project.org/impressum/). Closing.
