### ISSUE TITLE
Country champion information at wrong place for organizations

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#429]
For persons, the sentence "Country champion for x" is displayed right under the name, see e.g. [Jan's entry](https://oerworldmap.org/resource/urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf).

If an organization is country champion, something is wrong. The information "Country champion for x" is in the field "Contact person". Examples:

- https://oerworldmap.org/resource/urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930 (OER Research Hub)
- https://oerworldmap.org/resource/urn:uuid:97d4cb64-15b2-11e5-80f8-001999ac7930 (OER Africa).

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/urn:uuid:f95a8144-15b2-11e5-a066-001999ac7930 & https://beta.oerworldmap.org/resource/urn:uuid:97d4cb64-15b2-11e5-80f8-001999ac7930

**Comment by acka47** [comment]
+1
