### ISSUE TITLE
JSON schema: add Event entity 

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#435]
Task for #30. Will use http://schema.org/Event as type. At the phsyical meeting we decided on the following properties:

> - schemaorg Properties to be included: name, alternateName, image (logo), description, location, about/subject, about/activity fields, url, sameAs, startDate, endDate, inLanguage, recordedIn, organizer, performer (reverse: performerIn for Person)
- additional properties not covered by schema.org: hashtag
- schemaorg property to be included later: additionalType (not from the start as we may need another SKOS scheme)

We decided to leave out other date information, e.g. CfP, registration deadline etc especially because needed schema.org properties are missing.

**Comment by acka47** [comment]
@literarymachine You said, I shouldn't do any work in the JSON schema for now because of some technical problems. Please let me know when this is possible again.

**Comment by acka47** [comment]
Another property to be included is `tag` (see also #437).

**Comment by literarymachine** [comment]
On https://oerworldmap.org/assets/json/schema.json. @acka47 note that before we can actually start using the `Event` type, we'll need to implement #463 and #464. Please don't add `Events` until at least #464 is done.
