### ISSUE TITLE
Tag resources

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#436]
As a user I want to tag resources, e.g. to classify entities according to special needs in my country or project.

**Comment by acka47** [comment]
We will have to enable tagging, e.g. for projects doing their data collection on the OER worldmap which want to add information not supported by the Worldmap (one of these projects soon will be "Open Educational Practices Scotland").

**Comment by literarymachine** [comment]
Not available for all resource types yet.

**Comment by acka47** [comment]
As far as I can see, this is missing from all resource types now.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=&filter.about.tag=example

**Comment by acka47** [comment]
Thanks. It is also back in the web forms.

**Comment by acka47** [comment]
+1 for the fix

**Comment by acka47** [comment]
Oups, I was a little hasty there. Sorry for that. Forget what I said. The tag field is still missing from webforms for Person (I think we haven't had this before), Service, Project/Action, Story/Article.

**Comment by literarymachine** [comment]
> The tag field is still missing from webforms for Person (I think we haven't had this before), Service, Project/Action, Story/Article.

Hmm. I can see it in all of them - have you scrolled to the very bottom?

**Comment by acka47** [comment]
I looked on production. Looks good on beta. Going to sleep now.

**Comment by trugwaldsaenger** [comment]
Sleep tight acka47 ;-)
I checked it for organizations, persons, services and projects and it works fine!  I think we can move it to production.
