### ISSUE TITLE
Only show linked resources in listed properties on map

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#441]
See https://github.com/hbz/oerworldmap/issues/424#issuecomment-155426937

Three obvious candidates are `mainEntity`, `mentions` and `member`. Which else?

**Comment by acka47** [comment]
Here is the complete list:

-  `mainEntity`
- `mentions`
- `member`
- `agent`
- `participant`
- `provider`

**Comment by acka47** [comment]
Closing this issue as the list is there.

**Comment by literarymachine** [comment]
@acka47 reopening this as it actually needs to be implemented, too.

**Comment by literarymachine** [comment]
#476 on beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:706b65ce-77eb-11e5-9f9f-c48e8ff4ea31 vs. https://oerworldmap.org/resource/urn:uuid:706b65ce-77eb-11e5-9f9f-c48e8ff4ea31

**Comment by acka47** [comment]
Looks good for individual OEC members. 

But the other issue @trugwaldsaenger described in https://github.com/hbz/oerworldmap/issues/424#issue-114557407 still is there: When I click on  [France on beta](https://beta.oerworldmap.org/country/fr), the OEC is listed as organization. Strangely, it isn't there [on production](https://oerworldmap.org/country/fr). I guess, as country views probably are created with another mechanism than actual entities, this should get its own issue, doesn't it? If so, I give a +1 for this one.

**Comment by literarymachine** [comment]
> I guess, as country views probably are created with another mechanism than actual entities, this should get its own issue, doesn't it?

Exactly!
