### ISSUE TITLE
"affiliation" is used instead of "memberOf" in instance data

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#452]
As of #367 we decided to link persons to organizations with the general property `memberOf`. This property was added with https://github.com/hbz/oerworldmap/commit/534d6744ae3a1c327aa54f9197e0638bb4fbc131. Unfortunately `affiliation` wasn't deleted from the JSON Schema (see [here](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L528-L540)) and is still used in the data, see e.g. https://oerworldmap.org/resource/urn:uuid:ca2bf8bb-8086-41b1-a674-b75f6fe678c9.

As a result, members of the Global OER Graduate Network aren't shown/linked to in its [profile](https://oerworldmap.org/resource/urn:uuid:c4a55240-bbdb-48fd-b40e-6bd96f4ba8f5).

I guess, there has a lot of stuff to be adjusted amongst these the data and the schema...

**Comment by acka47** [comment]
When this is done, we should remove `affiliation` from the current schema ([lines 621-634](https://github.com/hbz/oerworldmap/blob/0d419f99225b67fdec2d2b7ac09d0dc2029a40c8/public/json/schema.json#L621-L634)).

**Comment by acka47** [comment]
It looks like "affiliation" is no more part of the data. Thus, I will have removed it from the schema. PR coming.

**Comment by literarymachine** [comment]
> It looks like "affiliation" is no more part of the data.

This is not correct: https://oerworldmap.org/resource/?q=about.affiliation.@id:*

**Comment by acka47** [comment]
Now, https://oerworldmap.org/resource/?q=about.affiliation.@id:* gives zero results. Thus, #597 can be merged.
