### ISSUE TITLE
UI glitches

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#454]
Appears both in Firefox and Chromium, see e.g. https://oerworldmap.org/country/se. Screenshot:

![20151113_ui-glitch](https://cloud.githubusercontent.com/assets/160292/11144870/5323e578-8a00-11e5-8925-0827687a747f.png)

See also https://oerworldmap.org/resource/?sort=dateCreated:desc etc.

**Comment by literarymachine** [comment]
Not pretty, but expected behaviour: you are logged in as admin and thus see newsletter registrants which have no name.

**Comment by j0hj0h** [comment]
The list items just need a minimum height of one line. I'll fix it.

**Comment by literarymachine** [comment]
> The list items just need a minimum height of one line. I'll fix it.

Just writing a fix that shows the id if lacking name.
