### ISSUE TITLE
Boost field alternateName in result list

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#455]
Example search for "OEC" https://oerworldmap.org/resource/?q=oec doesn't give back [Open Education Consortium](https://oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f) as first hit, it even isn't under the first 25 hits. It should be , though.

There probably is no distinction made between the occurence of the string "OEC" in the OEC entry and in the members' entries. (All OEC member entries have some information – amongst others "alternateName" – of the OEC in their data.)

**Comment by acka47** [comment]
This is a sub-ticket of #461.

**Comment by literarymachine** [comment]
On beta, can't point you at OEC though because it is currently not in that index.

**Comment by acka47** [comment]
Tested with https://beta.oerworldmap.org/resource/?q=hbz vs. https://oerworldmap.org/resource/?q=hbz

Looks good. +1

**Comment by acka47** [comment]
This is fiexed with #578. Closing.
