### ISSUE TITLE
Acronym "OER" neither spelled out on start page nor on about page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#456]
We don't explain the akronym "OER" anywhere on the site it is only spelled out in individual entries. You can't assume most people know what it means, though.

**Comment by trugwaldsaenger** [comment]
I agree. Maybe we could do it like this:
instead of:
>Our goal is to provide the most complete and comprehensive picture of the global OER movement >and to develop a global network of partners and volunteers to guarantee ongoing data curation. We >currently gather data about people, organizations, services, projects and events related to OER. 

it could say:
>Open Educational Resources (OER) are open licensed media, which are useful for teaching and >learning. Our goal is to provide the most complete and comprehensive picture of the global OER >movement and to develop a global network of partners and volunteers to guarantee ongoing data >curation. We currently gather data about people, organizations, services, projects and events related >to OER.

**Comment by acka47** [comment]
+1 (It should read, "openly" instead of "open", though.)

**Comment by acka47** [comment]
What about the [About page](https://beta.oerworldmap.org/about): Shouldn't we explain the akronym there as well?

**Comment by acka47** [comment]
I can implement this with updating https://github.com/hbz/oerworldmap/blob/master/public/mustache/LandingPage/index.mustache and – if needed – https://github.com/hbz/oerworldmap/blob/master/public/pages/About.md

**Comment by acka47** [comment]
ping @trugwaldsaenger Still waiting for a response...

**Comment by trugwaldsaenger** [comment]
Hi Acka47, we should fix this next week after the conference!

**Comment by acka47** [comment]
Resolved. Closing.
