### ISSUE TITLE
Improve ranking of result list

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#461]
[Searching for "Creative Commons"](https://oerworldmap.org/resource/?q=creative+commons), only one of the two duplicate entries is ranked on top. This doesn't seem right.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=creative+commons. Please record any further ranking requirements at #571.

**Comment by acka47** [comment]
+1

**Comment by literarymachine** [comment]
@acka47 https://github.com/hbz/oerworldmap/pull/578 superseded the previous implementation, could you check it out?

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
This is fiexed with #578. Closing.
