### ISSUE TITLE
Alternate name not shown correctly in HTML

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#462]
See e.g. https://oerworldmap.org/resource/urn:uuid:da6d890e-2faa-11e5-ba96-001999ac7927.

**Comment by literarymachine** [comment]
#477 on beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:da6d890e-2faa-11e5-ba96-001999ac7927

**Comment by acka47** [comment]
+1
