### ISSUE TITLE
Implement view for Event type

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#464]
Task for #30.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:277db498-9901-11e5-960c-e72e56893d88

**Comment by acka47** [comment]
Here are some other small things I noticed:
- The `Duration` value should be renamed `Date`. Also, it isn't easily readable with the many hyphens. It might suffice to replace the middle hyphen by a "to".
- `Tags` should be clickable and result in a list of all entities with the clicked tag

Furthermore, I think some restructuring of the view would make sense though: Beneath the title we should directly show the date and the location followed by the description. Beneath that, the more specific other information should follow. 

Another thing that comes up looking at "Location": Many events are located not only at an addrss but in a venue with a name. We should probably add `name` as property to the `Place` entity in the JSON schema and show the field at least in the web form for events. I will make a separate issue for this.

**Comment by acka47** [comment]
I made three new issues out of the last comment. This leaves changing "Duration" to "Date". +1 from me as soon as this is changed.
