### ISSUE TITLE
"mentionedIn" relation not set as inverse for "mentions"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#465]
See e.g. https://oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0 which has no `mentionedIn` info although https://oerworldmap.org/resource/urn:uuid:10a0c842-2fa6-11e5-a60f-001999ac7927 `mention`s it.

**Comment by acka47** [comment]
I can't see a `mentionedIn` link in the profile at https://beta.oerworldmap.org/resource/urn:uuid:53dbfe26-26fd-11e5-b5c4-7f1fe654f2b0 or at other resources mentioned in an article. (I also can't see a `mentionedIn` field in the web form which is expected behaviour, though.)

**Comment by acka47** [comment]
As @literarymachine metnioned in a chat, the links aren't shown because the data wasn't re-indexed. Adding a new `mentions` link the `mentionedIn` link is shown. Thus, +1.

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/issues/313#issuecomment-234226964

**Comment by acka47** [comment]
Another related issue is #780.

**Comment by literarymachine** [comment]
On beta, see e.g. [this story](https://beta.oerworldmap.org/resource/urn:uuid:af322309-3542-4150-9bec-a2e1cbcf8601) and add some entities for `mentioned` and `mainEntity` to verify that back links are automatically added.

**Comment by acka47** [comment]
+1
