### ISSUE TITLE
JSON Schema: Add memberOf to Service template 

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#467]
As what we classify as services can be members of the OEC (for example http://www.oeconsortium.org/members/view/237/), we need the possibility to say so in our data. This currently is not possible, see https://oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927.

**Comment by literarymachine** [comment]
@acka47: this was not fixed in https://github.com/hbz/oerworldmap/pull/468.

**Comment by literarymachine** [comment]
https://github.com/hbz/oerworldmap/pull/475 deployed to beta

**Comment by acka47** [comment]
I see `memberOf` in the template on beta but when I add the OEC URN (`urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f`) into the field and hit "save", I get a long list of JSON schema errors which I uploaded [here](https://gist.github.com/acka47/e4786a20ccf8429560b7).

**Comment by literarymachine** [comment]
>  I get a long list of JSON schema errors

This is actually correct. To make this work as expected, you also have to allow `Service` as `member` for `Organization` (see https://github.com/hbz/oerworldmap/commit/0d419f99225b67fdec2d2b7ac09d0dc2029a40c8). On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:fc8036f4-f9bb-49c5-a7d0-0b4d3923ccbf

**Comment by acka47** [comment]
It works now, see https://beta.oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927.

+1
