### ISSUE TITLE
Setup Tile Server

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#472]

**Comment by literarymachine** [comment]
We might want to evaluate if it would make more sense to use vector tiles and render them client side: https://www.mapbox.com/blog/introducing-geojson-vt/

**Comment by j0hj0h** [comment]
I'd love to. Biggest problem is IE – no WebGL before IE11: http://caniuse.com/#search=webgl
Can you check PIWIK how many users would be effected?

**Comment by j0hj0h** [comment]
Since January 12. this year Microsoft stoppt support for older versions of Internet Explorer then IE11:
https://www.microsoft.com/de-de/WindowsForBusiness/End-of-IE-support
How lucky we are :-)

Now we can discuss client side map rendering again!

**Comment by literarymachine** [comment]
I took a look at the [Mapbox vector tiles](https://api.mapbox.com/styles/v1/literarymachine/cink8jyda022wd5m3q1ao9i7m.html?title=true&access_token=pk.eyJ1IjoibGl0ZXJhcnltYWNoaW5lIiwiYSI6ImNpZ3M1Y3pnajAyNGZ0N2tuenBjN2NkN2oifQ.TvQji1BZcWAQBfYBZcULwQ#0.9585526020638253/-1.4210854715202004e-13/0/0
) and think we should give them a try!

**Comment by j0hj0h** [comment]
+1
