### ISSUE TITLE
Treat countries and other administrative areas as worldmap entities

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#479]
Reviewing #441, I tried to get JSON from a country page (`curl -H "Accept: application/json" https://beta.oerworldmap.org/country/fr`) which – when I think of it: not very surprisingly – didn't work. I think we should discuss whether it makes sense to add countries to our data model as separate entities. It might come handy for people interested in country statistics and the like...

**Comment by acka47** [comment]
Another benefit of an additional entity type `Country` would be that we could move the country-specific relation `countryChampion` into the country form and remove `countryChampionFor` from Organization and Person templates where they are superfluous for most entries...

**Comment by acka47** [comment]
As discussed at today's physical meeting, having countries as separate entities with information (from wikidata or elsewhere) like continent, population and GDP would be great for creating different statistics.

**Comment by literarymachine** [comment]
The following `schema.org` types could be used to model this:

[AdministrativeArea](http://schema.org/AdministrativeArea): "A geographical region, typically under the jurisdiction of a particular government."
[Country](http://schema.org/Country): "A country."
[State](http://schema.org/State): "A state or province of a country."

The US could by modeled like this then:

    {
      "@id": "info:US",
      "@type": "Country",
      "name": [
        {
          "@language": "en",
          "@value": "United States of America"
        }
      ],
      "geo": {
        "@type": "GeoShape",
        "polygon": "... space separated list of points ..."
      },
      "containsPlace": [
        {
          "@id": "info:US-CA",
          "@type": "State",
          "name": [
            {
              "@language": "en",
              "@value": "California"
            }
          ],
          "geo": {
            "@type": "GeoShape",
            "polygon": "... space separated list of points ..."
          }
        }
      ]
    }

This obviously only covers the very basics; nevertheless identifying, mapping, converting and importing an external geographic data source could be a first step.

**Comment by literarymachine** [comment]
Ping @philboeselager.

**Comment by philboeselager** [comment]
+1

**Comment by philboeselager** [comment]
test

**Comment by literarymachine** [comment]
curl -H "Accept: application/json" https://oerworldmap.org/country/gb

**Comment by acka47** [comment]
Closing this for now as country pages have been supporting JSON for two years now an I think the JSON response delivers what makes sense for the OER world map.
