### ISSUE TITLE
Implement form data validation

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#48]
Task for #9

**Comment by literarymachine** [comment]
- Email address shall be syntactically correct
- Email address shall be unique
- Country code shall be valid

**Comment by acka47** [comment]
Currently, the validation doesn't seem to work.

- I was able to "register" with the"email address" `test@t-onlinede`. This doesn't seem valid to me.
- Also, I was able to register with a TLD that doesnt exist (`.stalker`). I don't know whether there is an up-to-date list of TLDs that could be used for validation purposes... ([Wikipedia]
(http://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) won't help here.)

Another thing: I am not sure whether the text "Please enter an email address." is the best choice to pop up when someone enters an invalid string. Definitely, "Please enter a vald email address." isn't much better. I'd suggest something like "Something didn't work. Please check the email address you provided."

**Comment by literarymachine** [comment]
> I was able to "register" with the"email address" test@t-onlinede. This doesn't seem valid to me.

Email addresses are validated twice: by the browser (at least if you have a recent one, which I assume given the error message you criticize below), and by the back-end schema. It passes both validations, because email addresses indeed can consist of single domain-parts, try sending a mail to `acka47@localhost` on your linux box. See https://tools.ietf.org/html/rfc2822 or http://en.wikipedia.org/wiki/Email_address#Examples.

> Also, I was able to register with a TLD that doesnt exist (.stalker). I don't know whether there is an up-to-date list of TLDs that could be used for validation purposes...

A valid list of top level domains are is not part of email syntax; again, see https://tools.ietf.org/html/rfc2822.

> Another thing: I am not sure whether the text "Please enter an email address." is the best choice to pop up when someone enters an invalid string.

As mentioned above, we are using HTML5 form validation because it is standardized. Thus, the message totally depends on your browser. I will look into possibilities of customization but would prefer to stick with the standards.
