### ISSUE TITLE
Add missing fields to test files

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#480]
For some entitiy types not all fields from the JSON schema are covered by their respective test file at https://github.com/hbz/oerworldmap/tree/master/test/resources/SchemaTest. These missing fields should be added.

**Comment by literarymachine** [comment]
Please make sure to not reuse UUIDs of existing entries for another type. E.g. in https://github.com/hbz/oerworldmap/blob/b41d1d93db58a7d0e0cdb651484978d5051043ff/test/resources/SchemaTest/testEvent.json#L3 the UUID of https://oerworldmap.org/resource/urn:uuid:dda9c992-427f-11e5-92ed-54ee7558c81f was reused for the test event. This leads to problems if we want to ingest test data along with existing data.
