### ISSUE TITLE
Include links to input templates

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#485]
It should be easy for registered users to find the input templates. I would propose including two links:

1) On the Contribute page (https://beta.oerworldmap.org/contribute)
Instead of:

> Collect data using templates (planned for Sept. 2015)
> Registered users who are providing an OER service, running an OER project or simply are interested >in collecting clean data can use the OER World Map input templates to directly input data into the >platform. This service is under construction and will be available by the mid of september.

the text should be:

> Collect data using templates 
> Registered users who are providing an OER service, running an OER project or simply are interested >in collecting clean data can use the [OER World Map input templates](https://beta.oerworldmap.org/resource/) to directly input data into the platform.

2) On the home page (https://beta.oerworldmap.org/)
Instead of

> If you have data you believe is relevant, please consider to contribute! 

it should say:

> Registered users can use our [input templates](https://beta.oerworldmap.org/resource/) to contribute data.

We might add a sentence, which explains who can register right now:

> At the time being, registration is limited to country champions and selected beta-testers. If you would like to get a test-account, please [contact us](info@oerworldmap.org).

**Comment by acka47** [comment]
I guess this issue can be closed. if yes, please do so @trugwaldsaenger .
