### ISSUE TITLE
Don't show all bi-directional links in web forms

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#495]
Already talked about this on the phone with @literarymachine. I think, bi-directional links should only be edited at the place where this piece of information is expected more or is "more informative". (E.g. it is moire natural to list members of a project or the provider of a service in the project/service description than in the organization/person description).

Starting a collection here of links that shouldn't be shown in web forms:

- `mainEntityOf`
- `mentionedIn`
- `participantIn`
- `agentIn`
- `member`
- `provides`

**Comment by acka47** [comment]
For now, the list above is complete.

**Comment by literarymachine** [comment]
Implementing this, I would suggest to also added `created` (pointing to an `Article`) to the list. What do you say, @acka47?

**Comment by acka47** [comment]
I think it makes sense to link to articles persons or organisations have written as it gives some insight into their work. So please leave it in there for now.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:7609a1b0-904b-4ed8-bb2b-48467ab09595

**Comment by acka47** [comment]
+1
