### ISSUE TITLE
Data is gone when submission introduces an error

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#498]
Editing an "Organization" entry, I created an error within the "Country Champion for" field which was shown to me as JSON schema error after hitting the "submit" button. Thus, I hit the "back" button in the browser but didn't arrive at the web form. Hitting "Add organization" again led to an empty form, thus the whole work was deleted.

**Comment by j0hj0h** [comment]
Agreed with @literarymachine to fix this via ajax form handling.

**Comment by acka47** [comment]
But how do I introduce an error by now?

**Comment by literarymachine** [comment]
> But how do I introduce an error by now?

No changes here, try adding an `Organization` without a name for example.

**Comment by acka47** [comment]
Ok, tested. Data doesn't go away now. +1
