### ISSUE TITLE
Alternate names are not taken into account for interlinking

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#499]
@acka47 reports: "For example, I expect that https://beta.oerworldmap.org/resource/urn:uuid:7609a1b0-904b-4ed8-bb2b-48467ab09595 is suggested when typing "hbz" e.g. in a memberOf field."

This is due to the fact that currently the front-end does the look-ups against the `name`. Quickfix by @j0hj0h will be to add `alternateName` to the lookup, long-term fix will be to use back-end search functionality.

**Comment by acka47** [comment]
+1
