### ISSUE TITLE
Set up mail server for oerworldmap.org

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#50]
Task for #9

**Comment by literarymachine** [comment]
@dr0i Do you happen to know what it would take to send and receive mail for oerworldmap.org at hbz?

**Comment by dr0i** [comment]
Felix Ostrowski wrote on 03.02.2015 12:01 :

> @dr0i Do you happen to know what it would take to send and receive mail for oerworldmap.org at hbz?

Just asked our IT department. Will post todo's.

**Comment by dr0i** [comment]
Fyi, if someone hits this issue:
@literarymachine is in contact with our IT. If the domain has changed ownership from @trugwaldsaenger to them, things will start to rumble.

**Comment by literarymachine** [comment]
@dr0i The Domain has changed ownership. We would need the possibility to send and receive from/to *@oerworldmap.org. How do we proceed?

**Comment by dr0i** [comment]
@literarymachine I think prerequisites are now done and our IT can handle the stuff. We'll do this by mail ...
