### ISSUE TITLE
Define field labels in translation file

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#500]
@acka47 reports:

> E.g. in the web form for editing a "Person", I have got "Email" and "URL" while in the resulting profile it reads "Email Address" and "Personal Website". We will definitely have to align these.

Will do this manually for now, field labels and descriptions could be pulled out of the JSON schema in the long run.

**Comment by literarymachine** [comment]
Decided to use the translation file for this. The question is if we would really need different label for different contexts, e.g. "Personal website" when using the `url` field for `Person` instances and "Institutional website" when using the `url` field for `Organization` instances. This would lead to some more work defining the labels, obviously:

    Person.url = "Personal website"
    Organization.url = "Institutional website"

vs

    url = "Website"

What do you think, @acka47?

**Comment by literarymachine** [comment]
Create labels.properties at https://github.com/hbz/oerworldmap/tree/master/conf

**Comment by acka47** [comment]
As discussed offline, we want to have the possibility to name labels differently for different types. How should I proceed. Should I create a labels.properties file then with lines like:

```
Person.url = "Personal website"
Organization.url = "Institutional website"
```

? Or should I rather create one file for each type, e.g. `personLabels.properties`, `organizationLabels.properties` etc?

**Comment by literarymachine** [comment]
Am 22.12.2015 09:48 schrieb "Adrian Pohl" <notifications@github.com>:
> As discussed offline, we want to have the possibility to name labels
differently for different types. How should I proceed. Should I create a
labels.properties file then with lines like:
>
> Person.url = "Personal website"
> Organization.url = "Institutional website"

I'd go with this, same goes for the descriptions.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
When adding the missing labels, also take into account https://github.com/hbz/oerworldmap/issues/525#issuecomment-170502867.
