### ISSUE TITLE
Add field descriptions to display as inline help on forms

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#506]
I suggest implementing these like the field names for #500, i.e. as a translation file. Again we will have to decide if a per-field granularity would suffice, or if a per field instance granularity is needed:

    url = "A URL e.g. of your homepage"

vs

    Person.url = "The URL of your personal homepage"
    Organization.url = "The URL of the organizations homepage"

@acka47 any thoughts on this?

**Comment by literarymachine** [comment]
Create description.properties at https://github.com/hbz/oerworldmap/tree/master/conf

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by acka47** [comment]
Doesn't work yet. Rather then the description for the field the value of the `description` field of the respective resource is show in the tooltip, e.g.:

![20160107_wrong-description-tooltip](https://cloud.githubusercontent.com/assets/160292/12166141/11c54c12-b524-11e5-8483-7b7c80ca11ef.png)

**Comment by literarymachine** [comment]
Sorry about that, I apparently only tested with empty forms - no `description`, no problem. Fixed.

**Comment by acka47** [comment]
+1
