### ISSUE TITLE
Error while data input via template on beta

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#510]
I tried to put in the OER World Map Project and received following error message: 

The data you entered is invalid
We are working hard on better error reporting. But until that is done, you are unfortunately stuck with this:
com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/endTime"}
    instance: {"pointer":"/agentIn/0/endTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/endTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"30.11.2015\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"30.11.2015","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/startTime"}
    instance: {"pointer":"/agentIn/0/startTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/startTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"01.12.2014\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"01.12.2014","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/endTime"}
    instance: {"pointer":"/agentIn/1/endTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/endTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/1/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/1/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/1/endTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"30.11.2015\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"30.11.2015","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/startTime"}
    instance: {"pointer":"/agentIn/1/startTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/startTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/1/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/1/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/1/startTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"01.12.2014\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"01.12.2014","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/endTime"}
    instance: {"pointer":"/endTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/endTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/endTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"30.11.2015\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"30.11.2015","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/startTime"}
    instance: {"pointer":"/startTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/startTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/startTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"01.12.2014\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"01.12.2014","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/endTime"}
    instance: {"pointer":"/agentIn/0/endTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/endTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"30.11.2015\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"30.11.2015"}],"/definitions/Action/properties/endTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/0/endTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"30.11.2015\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"30.11.2015","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
error: instance failed to match at least one required schema among 3
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action/properties/startTime"}
    instance: {"pointer":"/agentIn/0/startTime"}
    domain: "validation"
    keyword: "anyOf"
    nrSchemas: 3
    reports: {"/definitions/Action/properties/startTime/anyOf/0":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-fullyear"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/1":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/full-date"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"pattern","message":"ECMA 262 regex \"^[0-9]{4}-[0-9]{2}-[0-9]{2}$\" does not match input string \"01.12.2014\"","regex":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$","string":"01.12.2014"}],"/definitions/Action/properties/startTime/anyOf/2":[{"level":"error","schema":{"loadingURI":"#","pointer":"/definitions/date-time"},"instance":{"pointer":"/agentIn/0/startTime"},"domain":"validation","keyword":"format","attribute":"date-time","message":"string \"01.12.2014\" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.SSSZ]","value":"01.12.2014","expected":["yyyy-MM-dd'T'HH:mm:ssZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]}]}
---  END MESSAGES  ---
{
  "image" : "http://wp1025437.server-he.de/open-educational-resources/wp-content/uploads/sites/4/2015/09/logo-oer-world-map-225x225.png",
  "agent" : [ {
    "@id" : "urn:uuid:839897e6-178f-11e5-871b-3c970e4a9cbf"
  }, {
    "@id" : "urn:uuid:c39eab63-a28c-49d0-bfcb-7662b5557d45"
  }, {
    "@id" : "urn:uuid:f3ff41c6-46a0-4d63-b492-55966d68d6f3"
  } ],
  "@type" : "Action",
  "description" : [ {
    "@value" : "The goal of the OER World Map project is to provide the most complete and comprehensive picture of the global OER movement and to develop a global network of partners and volunteers to guarantee ongoing data curation. We currently gather data about people, organizations, services, projects and events related to OER. \r\n\r\nThe project is funded by the William and Flora Hewlett Foundation. ",
    "@language" : "en"
  } ],
  "alternateName" : [ ],
  "url" : "https://www.oerworldmap.org",
  "result" : [ {
    "@id" : "urn:uuid:fc8036f4-f9bb-49c5-a7d0-0b4d3923ccbf"
  } ],
  "name" : [ {
    "@value" : "OER World Map Project, Phase II",
    "@language" : "en"
  } ],
  "startTime" : "01.12.2014",
  "location" : {
    "geo" : {
      "lon" : 6.935474,
      "lat" : 50.934082
    },
    "address" : {
      "addressCountry" : "DE",
      "streetAddress" : "Jülicher Str. 6",
      "postalCode" : 50674,
      "addressLocality" : "Köln",
      "addressRegion" : "NRW"
    }
  },
  "@id" : "urn:uuid:5a1a5948-a0ae-47c7-8f7a-dd2e56168bb5",
  "endTime" : "30.11.2015",
  "email" : "info@oerworldmap.org",
  "sameAs" : [ "https://twitter.com/oerworldmap"

**Comment by literarymachine** [comment]
As in #507, this is not a bug. The data you entered is invalid, in this case the date. #504 will help clarify the expected input format.
