### ISSUE TITLE
"Tag" field missing in "Service" web form

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#512]
Working on #500 I noticed that there is not `tag` field shown in the `Service` template. I thought the existence of all fields in use would be checked using the [test file](https://github.com/hbz/oerworldmap/blob/master/test/resources/SchemaTest/testService.json)...

**Comment by literarymachine** [comment]
Am 22.12.2015 11:18 schrieb "Adrian Pohl" <notifications@github.com>:
>
> I thought the existence of all fields in use would be checked using the
test file...

The test files are used to test the schema and have nothing to do with the
forms. Form completeness tests will be implemented using the schema, not
instance data.

**Comment by acka47** [comment]
>  Form completeness tests will be implemented using the schema, not
instance data.

Understood. I won't check form completeness manually and will wait for the tests.

**Comment by literarymachine** [comment]
FYI: see [this template](https://github.com/hbz/oerworldmap/blob/b58811667f8acfd2959b9d5e14ca839482e12f48/public/mustache/ResourceIndex/Event/edit.mustache#L45) for an example of how to add a `tag` field to a form.

**Comment by acka47** [comment]
This was fixed with https://github.com/hbz/oerworldmap/pull/563. Closing.
