### ISSUE TITLE
Hide some properties from web from

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#524]
There are some fields in the current web forms that aren't used – either because they are not mature or they even don't make sense at all. For now, we should remove them from the forms.

Here is a list:

- `additionalType` for types `Project/Action` and ` Organization`
- `instrument` (`Action`)
- `result` (`Action`)
- `license` for type `Service` (will probably be obsolete with implementation of the openness indicator)

**Comment by acka47** [comment]
I am not sure whether we should also remove `serviceType` from web form until https://github.com/hbz/vocabs-edu/issues/25 is implemented. On the other hand, the controlled vocabulary could already be used. We will have to discuss this in January.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:9286f1c6-b8db-4800-8f09-b12141b3310b

**Comment by acka47** [comment]
Sorry, I forgot to include the other direction: `instrumentIn` and `resultOf` should also not be shown.

Also, I wonder why `Service` has the `member` property in the current JSON schema ([line 586-599](https://github.com/hbz/oerworldmap/blob/f4b044ab166e86e55d69d9d2d0d20094baa43860/public/json/schema.json#L586-L599)). @literarymachine Do you know why this is in there? Is it actually used?

**Comment by literarymachine** [comment]
> Also, I wonder why Service has the member property in the current JSON schema (line 586-599). @literarymachine Do you know why this is in there? Is it actually used?

Looks like it is never used: https://oerworldmap.org/resource/?filter.about.@type=Service&q=about.member.@id:*

In https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L653 it says though that a `Person` can be `memberOf` a `Service`. Thus, a `Service` needs a `member` property...

**Comment by acka47** [comment]
> Sorry, I forgot to include the other direction: `instrumentIn` and `resultOf` should also not be shown.

It isn't shonw anymore. Thus, +1. And I will add the missing labels (#500) this week...
