### ISSUE TITLE
Differ between organizational and individual participants in project

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#525]
Currently, we use `agent` and `participant` to relate persons and organizations to a project. (Although, in the web form it currently only says "Search Person...".) `agent` is used to indicate the project lead (individual or organizational) and `participant` to indicate other agents taking part somehow in the project.

@trugwaldsaenger pointed out that he would not differentiate these roles but would rather use `agent` and `participant` to differ between organizational and individual project members. Thus, `agent` would be used for organizations involved with the project and `participant` for persons. 

This differs a bit from the way the use of the schema.org properties is actually intended but doesn't break anything. Here are the schema.org explanations:

> agent
Thing > Property > agent
The direct performer or driver of the action (animate or inanimate). e.g. *John* wrote a book.

> participant
Thing > Property > participant
Other co-agents that participated in the action indirectly. e.g. John wrote a book with *Steve*.

**Comment by acka47** [comment]
@literarymachine We should also better fix this before opening the forms for country champions...

**Comment by acka47** [comment]
To Do:

- [ ] Maybe adjust existing data (although I can't think of a project on production where this is already used)
- [ ] Adjust the [JSON schema, lines 261-290](https://github.com/hbz/oerworldmap/blob/f4b044ab166e86e55d69d9d2d0d20094baa43860/public/json/schema.json#L261-L290) (Adjusting the descriptions and the items.
- [ ]Adjust the [labels](https://github.com/hbz/oerworldmap/blob/task/%23500-defineFieldLabels/conf/labels.properties) and [descriptions](https://github.com/hbz/oerworldmap/blob/task/%23506-addFieldDescriptions/conf/descriptions.properties) in the web form

**Comment by literarymachine** [comment]
> agent is used to indicate the project lead (individual or organizational) and participant to indicate other agents taking part somehow in the project.

I think this makes perfect sense and actually adds semantics, and that differentiating `Organization` and `Person` by field makes no sense and adds nothing. What is the rational behind this? Is this really necessary?

**Comment by acka47** [comment]
I understand your scepticism as I am not sure myself why we need this. As far as I recall the discussion with @trugwaldsaenger there were two problems:

1. at that point it only said in both fields that a `Person` should be added so that  @trugwaldsaenger missed organizations
2. I think, @trugwaldsaenger found the differentiation between lead and member too specific for the start.

The current field labels (`Project lead`, `Team members`) should be changed in any way as they don't really fit for organizations. To KISS, I propose  removing the field `agent` and just using `participant` to indicate persons and organizations involved in the project (and using a label like "Agents involved" or so). Will discuss this with @trugwaldsaenger .

**Comment by acka47** [comment]
I just discussed this qith @trugwaldsaenger. Here is the solution we came up with:

- Leave the properties used and the JSON schema as is.
- Adjust the field names and descriptions:
    - "Project lead": "A person or organization that is the driver or lead and primary contact point of the project"
    - "Participant": "A person or organization participating in the project"

Closing this one and linking to this comment in #500 .
