### ISSUE TITLE
Identify data sources for the map ontology

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#53]

**Comment by trugwaldsaenger** [comment]
Are you referring here to the OER data curation projects which might deliver data for the OER data hub?

**Comment by drrobertfarrow** [comment]
Yes - to identify all the currently existing maps and databases which can be used to populate OER World Map.  There is a list of some other maps at http://oermap.org/resources/, plus we can add the data from the POERUP project (http://poerup.referata.com/wiki/Mega_Map / http://poerup.referata.com/wiki/Maps).  There are most likely others out there...

**Comment by trugwaldsaenger** [comment]
We have an initial List in our internal Wiki: https://wiki1.hbz-nrw.de/display/OWM/OER+World+Map+Stakeholder

**Comment by drrobertfarrow** [comment]
It's a good list, but we must decide how to approach the organisations and convince them to share.  There is a strategic element to this as well as the technical requirements that enable automatic map population.

**Comment by acka47** [comment]
Closing
