### ISSUE TITLE
Add download button to search result list

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#539]
Task for #35.

**Comment by formimkontext** [comment]
Current layout showing the button and dropdown menu for "export / print search result list"

![20160405-oer-export-aggregation](https://cloud.githubusercontent.com/assets/15141949/14326357/eaae7e4a-fc2d-11e5-8e96-dd9dcc742731.jpg)

**Comment by acka47** [comment]
Export (iCal, CSV, JSON) is implemented. Closing.
