### ISSUE TITLE
Short biographies of team for the blog

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#54]

**Comment by trugwaldsaenger** [comment]
We have something like this in our proposal (https://wiki1.hbz-nrw.de/display/OWM/OER+World+Map+Proposal+%28final%29), but Philipp, Ben and Johannes are still missing.

**Comment by j0hj0h** [comment]
I already sent you my profile text a week ago, because I cannot edit the wiki page ... I just sended it again, hope it arrived?

**Comment by trugwaldsaenger** [comment]
Thanks for the reminder @j0hj0h! @philboeselager and Ben did so too, so the list is complete!

**Comment by drrobertfarrow** [comment]
Once this is ready we should create a new blog page: 'The Team'

**Comment by acka47** [comment]
I created such a page, see https://oerworldmap.wordpress.com/the-team/. There is only a picutre of Ben's missing. Closing.

**Comment by buschfeld** [comment]
sorry, for delayed delivery - here it is ...

/Users/benbuschfeld/Pictures/Privat/BenBuschfeld_Porträt.jpg/Buschfeld_SqF_200pxBreite.jpg

**Comment by acka47** [comment]
@buschfeld I can't see the image. You can also send it to my by mail (pohl[at]hbz[dash]nrw[dot]de).

**Comment by acka47** [comment]
Received the image and added it to the team page.
