### ISSUE TITLE
Add name of location to web form

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#542]
With #483 we added the name of a location to the JSON schema. It's not yet in the web form.

The question is whether we only add it to the event web form as mostly locations of events have a name? Or should we add it to all occurences of locations as organizations might also be placed in a building that has a name in addition to an address?

**Comment by literarymachine** [comment]
Closing since we don't have the `name` of a [`Place`](https://github.com/hbz/oerworldmap/blob/master/public/json/schema.json#L2970) in our schema any longer and there does not seem to be a real use case.
