### ISSUE TITLE
Branding guidelines for website, blog, etc

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#55]

**Comment by drrobertfarrow** [comment]
It would be useful to have hex values for colours as well as guidance on fonts

**Comment by buschfeld** [comment]
OK, we will provide them - in the meanwhile I post temporary layout including a first proposal for the color schemes shown on the right side
/Users/benbuschfeld/Desktop/OER_LandingPage_Samples/demo/OER_Launchpage_Basics.png

**Comment by literarymachine** [comment]
![uploads/7656b6e3-0bc6-4961-9954-dfb2614ba1b6/OER_Launchpage_Basics.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7656b6e3-0bc6-4961-9954-dfb2614ba1b6%2FOER_Launchpage_Basics.png)

**Comment by drrobertfarrow** [comment]
OK, we have had our corporate identity and branding for a long time now, so I propose this ticket is closed.
