### ISSUE TITLE
Making Lists with Markdown seems to be not working

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#552]
The OER16 entry does include two markdown lists, which are not displayed as such:
https://oerworldmap.org/resource/urn:uuid:2d2fa244-acce-42ac-8ce7-ea4af5947b1f

**Comment by literarymachine** [comment]
We do not support markdown in resource descriptions yet, see #496. For now, you will have to use HTML:

    <ul>
      <li>One</li>
      <li>Two</li>
      <li>Three</li>
    </ul>

**Comment by trugwaldsaenger** [comment]
This works, thanks!
