### ISSUE TITLE
Add delete functionality to UI

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#554]

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:2e007364-16b4-4643-95f7-b84ced51d4ea

![screenshot from 2016-09-30 12-34-49](https://cloud.githubusercontent.com/assets/149825/18989111/50248596-870a-11e6-88d7-81b14c21e2fa.png)

**Comment by acka47** [comment]
Works good. I imagined it to be more hidden, e.g. as a red bar at the buttom of the editing form. As it only is for admins, it doesn't matter mucht, though.

**Comment by literarymachine** [comment]
> I imagined it to be more hidden, e.g. as a red bar at the buttom of the editing form.

I took the position from https://github.com/hbz/oerworldmap/issues/600#issuecomment-206450598. Also, I just swapped the icon for the trash can to make it more clear. Given the fact that the admin is prompted and has to confirm deletion in a popup, chances of accidental deletion should be slim to none.

**Comment by acka47** [comment]
+1
