### ISSUE TITLE
Email Registration fails on adresses with same domain.

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#56]
Email addresses with same domain throw error "This e-mail is already registered"

**Comment by literarymachine** [comment]
This is an issue with the elasticsearch index. It is analyzing the email field, @philboeselager already created a mapping that takes care of this at https://github.com/hbz/oerworldmap/blob/story/%239/conf/index-config.json. Forgot to deploy this on staging, keeping ticket open as a reminder to document this.

**Comment by literarymachine** [comment]
Updated the README accordingly: https://github.com/hbz/oerworldmap/commit/ea7470fd8dad06a8e5a611ac5d1f81d687bc1651
