### ISSUE TITLE
Workflow for publishing stories

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#561]
As a registered user of the OER World Map I want to publish a story resp. submit a story/article so that editors are notified and review it for publication.

Acceptance criteria:
- [ ] Registered users see a button  "Submit story" besides the "Add event", "Add Project" etc. buttons
- [ ] When clicking the button a form opens to submit a story
- [ ] ArticleBody can be formatted using markdown at best with formatting help like on GitHub
- [ ] Save draft to be worked on later
- [ ] Choose draft from list of drafts associated with my user
-  One of:
  - [ ] Click "publish" button and story is listed on the World Map
  - [ ] When "submit" button is hit, story is saved for editors to review and mail is sent out to editors (probably best start with info [at] oerworldmap.org addres).

**Comment by drrobertfarrow** [comment]
I have just been trying to add a story and I have no option to add markup as far as I can tell.  Also, when I publish the story I lose all paragraph and line breaks. https://oerworldmap.org/resource/urn:uuid:0a56426f-1a4e-46e7-9c87-dc353cc3c690

**Comment by acka47** [comment]
Currently, you have to provide HTML for formatting. As a first step to improve this, we intend to support markdown formatting, see #496.

**Comment by literarymachine** [comment]
> . As a first step to improve this, we intend to support markdown formatting, see #496.

This has been implemented in #837.

**Comment by karindr** [comment]
At the Moment there is no reviewing process and it seems to work like this. 
But there are some points that are useful anyway:

> Save draft to be worked on later
> Choose draft from list of drafts associated with my user
> Click "publish" button and story is listed on the World Map

**Comment by literarymachine** [comment]
> At the Moment there is no reviewing process and it seems to work like this.

Closing.
