### ISSUE TITLE
Add "Help Button"  for editors to the edit formular

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#564]
For logged in users (editors) a help buttom should be placed next to the other buttons (add organization, etc). The buttom could be in a different colour (e.g. orange?) and should be linked to the FAQ`s for editors we wrote down in our wiki:
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors

**Comment by trugwaldsaenger** [comment]
@literarymachine @j0hj0h: I guess there will be a help button included in the layout of the next version. Depending on when we will publish the next version, it might make sense to include this in the existing version, since I guess it will take only a few minutes.

**Comment by formimkontext** [comment]
as discussed, we will add a link to the wiki in the edit-formular.

**Comment by karindr** [comment]
It would be really useful to have a link here.

Maybe we should change the wiki-page to a static page on www.oerworldmap.org at the same time. It would be less confusing for visitors.

**Comment by formimkontext** [comment]
Added a "Need Help?" link at the top of the layout. 
![20160831-formulare-story](https://cloud.githubusercontent.com/assets/15141949/18134739/b8299d3e-6f9f-11e6-997a-e6615d5a2cd7.jpg)

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
What about Karin'ssuggestion to "change the wiki-page to a static page on www.oerworldmap.org"? I think this is a good idea.

**Comment by karindr** [comment]
+1
I created a new issue for the static page: #905
