### ISSUE TITLE
Collapse address-fields for services & projects by default

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#565]
Background: The rule is that services should be recorded connected to an organization (provider). In some exceptions (services: one-man provider, which has not yet registered, projects: project runs in a different place than the mother organization operates in) we nevertheless need a seperate address field for services.

Solution: By making the address fields within the service and projects templates collapsable we can hide it as a standard, so that it does not confuse users, but make it available if needed.

**Comment by j0hj0h** [comment]
I agree. There should also be a note why it is collapsed and a link to the corresponding FAQ chapter:
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors#how-to-add-locations

**Comment by karindr** [comment]
Make sure that the field to choose the country remains visible for projects because a project does not inherit its location of its organiser. So you have to choose the country manually otherwise the project is not shown in the country view and is not found when filtering for the country. Maybe we should include a hint there too.

**Comment by literarymachine** [comment]
> Make sure that the field to choose the country remains visible for projects because a project does not inherit its location of its organiser.

This actually makes the collapsible `location` more complicated - both implementation-wise and IMHO for the end user, too. Maybe we actually should add the Organization/Person - Project relations to inherit locations?

**Comment by karindr** [comment]
Now projects inherit the location so it would be good to have the collapsed location fields for projects and services in the templates.

**Comment by literarymachine** [comment]
On beta.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
Looks good. I doubt that "inherited" in "The address of a service is inherited from the provider." and "The address of a project is inherited from the operator." is an easy to comprehend term for most people. Maybe just use "taken" instead. otherwise, +1.
