### ISSUE TITLE
Link and activate Facebook page

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#57]
I setup a Facebook page for the OER World Map (it's unpublished, just to have it ready when we launch landing page). The URL will be https://www.facebook.com/oerworldmap. We need a link with a call "Follow us on Facebook" or something like it.

Everyone from the team can ask Felix or me, to become an Administrator for the Facebook page.

![uploads/79e4474d-bf17-4689-aa19-abd4673fce44/Bildschirmfoto 2015-02-04 um 19.18.44.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F79e4474d-bf17-4689-aa19-abd4673fce44%2FBildschirmfoto+2015-02-04+um+19.18.44.png)

**Comment by literarymachine** [comment]
@j0hj0h We have a go from @trugwaldsaenger, so please add a link to the page to our landing page!
