### ISSUE TITLE
Filter educational agents, events & projects by educational sector

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#570]
One of the lessons learned of the OER Atlas is, that it makes sense to categorize Organizations by educational levels (or sectors). Actually I think that it will be much easier to categorize an organization than it is to categorize a service.

**Comment by acka47** [comment]
Story: As someone interested in OER I want to find organizations that are active on the same educational level as I am so that I can look at the services they provide and/or contact them if necessary.

**Comment by acka47** [comment]
@trugwaldsaenger Is the user story phrased correctly? Shouldn't we als add educational level to persons to enable finding _actors_ on a specific educational level?

**Comment by trugwaldsaenger** [comment]
I think we should come back to this issue soon! But the educational levels will not help us very much for this - I guess we will need something more simple and complete for all other datatypes then services. I will try to come up with a proposal for this ASAP.

**Comment by trugwaldsaenger** [comment]
> @trugwaldsaenger Is the user story phrased correctly? Shouldn't we als add educational level to persons to enable finding actors on a specific educational level?

Yes, that is correct. The educational sector (not the level see above) will be important also for persons. Actually I think it will be important for all data types...

**Comment by trugwaldsaenger** [comment]
https://github.com/hbz/oerworldmap/issues/412

**Comment by trugwaldsaenger** [comment]
This seems to be relevanta s well: https://github.com/hbz/oerworldmap/issues/366

**Comment by acka47** [comment]
@trugwaldsaenger will provide broader concepts for ISCE-1997 (see also https://github.com/hbz/vocabs-edu/issues/13) that can be used for associating persons, organizations, events & projects with an educational sector. Renaming the ticket as this is not only about organizations.

**Comment by trugwaldsaenger** [comment]
My proposal for a simple classification:
- Early Childhood education
- school
- higher education
- TVET
- Non- & Informal Education

**Comment by acka47** [comment]
Based on @trugwaldsaenger's proposal I made a first version of the vocab, see the PR at https://github.com/hbz/vocabs-edu/issues/28.

**Comment by acka47** [comment]
When the vocab is ready we will have to add an option to indicate the educational sector for organizations, persons and probably also events and projects (and stories?). For the sake of consistency, I would also switch services from ISCED-1997 to this sector classification but @trugwaldsaenger until now has been saying we should keep ISCED-1997 for services.

**Comment by trugwaldsaenger** [comment]
It would be great, if we could solve this issue soon, since we will need it for the UNESCOde report.

Let me summarize:

1.  The classification described above (ECE, School, HE, TVET, Nonformal)  still seems to make a good start.
2.  To simplify things, I would add this field to all datatypes, including services and stories.
3. I think we discussed, that we will need two fields: One for the primary sector and one for the secondary. Within the primary sector field, it should be possible to select only one primary sector. Within the secondary sector field it should be possible to select several sectors.
4. Our experience with the Atlas show, that there are a number of activities, which do not target at a special educational sector, but which claim to address all sectors in the same way. It might be necessary to add something like "general" to the primary sector field to make this very clear. Alternatively we could define that leaving the primary sector field empty is equal to "general" but I think this will the logic of the field harder to understand.

**Comment by acka47** [comment]
> 3. I think we discussed, that we will need two fields: One for the primary sector and one for the secondary sector. Within the primary sector field, it should be possible to select only one primary sector. Within the secondary sector field it should be possible to select several sectors. Example: A project aims primarily at the Higher Education Sector, but also affects the school- and the TVET-sector.

This looks too complex to me. I would just let people select more than one sector...

> 4. Our experience with the Atlas show, that there are a number of activities, which do not target at a special educational sector, but which claim to address all sectors in the same way. I guess it would make sense to add something like "general" to the primary sector field to make this very clear. Alternatively we could define that leaving the primary sector field empty is equal to "general" but I think this will the logic of the field harder to understand. @acka47: What is your opinion on this?

+1 for adding a "general" or similar option for cross-sectorial entries.

**Comment by trugwaldsaenger** [comment]
> This looks too complex to me. I would just let people select more than one sector...

You are right, that it is a bit complex. But it resultet out of practical needs. The OER Atlas is sorted arcording to educational sectors. So we need a unique primary sector. Otherwise, if you can choose several sectors, which one should be used for the Atlas or other reports?

I disussed this issue with @literarymachine. My original idea was to allow sorting of selected sectors. But using two fields is technically easier to implement, so we agreed to proceed in this direction...

**Comment by acka47** [comment]
One could think about another way of structuring the atlas But if you don't see another solution for this, then do this.

However, the primary/secondary differentiation won't work for some cases. What will those people do who equally address two or more sectors with their service/organization etc? They might just select them in the secondary sector field which would lead to the problem we wanted to sidestep. I am afraid we will be adding complexity that will lead to more people being confused about what to choose and might not lead to better quality of the data. Also, the World Map isn't just the web form for collecting Atlas data...

**Comment by acka47** [comment]
I added a new concept with the labels "Cross-sector" / "Sektorenübergreifend" to the vocabulary and also added German labels to all concepts.

**Comment by trugwaldsaenger** [comment]
> I added a new concept with the labels "Cross-sector" / "Sektorenübergreifend" to the vocabulary and also added German labels to all concepts.

+1 Thanks very much

>  One could think about another way of structuring the atlas But if you don't see another solution for this, then do this.

No other solution in sight....

> However, the primary/secondary differentiation won't work for some cases. What will those people do who equally address two or more sectors with their service/organization etc? They might just select them in the secondary sector field which would lead to the problem we wanted to sidestep. 

In this case we could choose "cross-sector" as primar sector and e.g "school" and "he" as secondary sectors. So I see no problem here...

> I am afraid we will be adding complexity that will lead to more people being confused about what to choose and might not lead to better quality of the data. Also, the World Map isn't just the web form for collecting Atlas data...

I think we should try things out. For the UNESCO OERde Report we will update the German data with sectors. So we can see how complex it is and how it works. If we come to the conclusion that it is too complex, not often needed or not helpful, we can still delete the second field and continue with just one field.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:9e57944d-efb2-494a-81d3-b30bfd2ee449

There also two new filters for "Primary educational sector" and "Secondary educational sector" e.g. at https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Service and the corresponding statistics at https://beta.oerworldmap.org/aggregation/

**Comment by trugwaldsaenger** [comment]
Cool, thanks very much. This will help to find the right solution!

I spoke with Ingo Bless two days ago. In order to import events to the OERInfo calendar they would need to split up "tvet" into "vocational training" and "adult- further education". 

I created a table to pin down the definitions: https://docs.google.com/document/d/1tjars-ga4pckZci-rC-9r5LD6urqH4hD9oo-In5qi3M/edit?usp=sharing

**Comment by acka47** [comment]
Is  "adult- further education" really a part of TVET? Doesn't this cover "Volkshochschule" where a lot of adults learn stuff that is not work-related?

In other words, shouldn't we just add "adult- further education" besides TVET and the rest?

**Comment by trugwaldsaenger** [comment]
I continued to work on the google doc: https://docs.google.com/document/d/1tjars-ga4pckZci-rC-9r5LD6urqH4hD9oo-In5qi3M/edit# and will invite external experts to participate in the discussion.

**Comment by acka47** [comment]
@trugwaldsaenger and me jist discussed that we will follow the approach from the google doc, combining the dimensions of educational sectors and degree of formalization (see https://github.com/hbz/vocabs-edu/issues/31). We should definitely think about resolving the problems mentioned in #412 when implementing this.

**Comment by trugwaldsaenger** [comment]
I did some reality testing with data for the UNESCOde report:
https://docs.google.com/spreadsheets/d/1C3M5CQOph0Dduaa4OWDsjUFQdqYLikKoDIy4k0MRcBA/edit?usp=sharing

As a result I would like to proceed like following:

1. Implementation of two fields: "primary educational sector" and "secondary educational sector"
2. Within the field "primary educational sector" only one value can be choosen, within the field "secondary educational sector" several values can be choosen.
3. The values for **both** fields should be:
- cross-sector (sektorenübergreifend)
- Early Childhood Education (Frühkindliche Erziehung)
- School (Schule)
- Higher Education (Hochschule)
- Vocational Education (Berufliche Bildung)
- Further Education (Weiterbildung)
4. Regarding the formal/non-formal/informal field there remain some open questions. We should leave this out and handle this classification via tags for the beginning. After doing so, we might include this field later.

The solution is very similar to the one we already had on beta. The differences are:
1. Slightly changed names for the values
2. "cross-sector is included in both fields (primary and secondary sector)

**Comment by karindr** [comment]
If we want other people to understand what we want them to add here, we have to add an explanation because primary and secondary could be easily misunderstood here. I suggest to add:

"Main educational sector the organisation is working for" (Bildungsbereich, für den die Organisation hauptsächlich tätig ist)

"Other educational sector(s) the organisation is working for" (Weitere Bildungsbereich(e), für den (die) die Organisation tätig ist)

"Main educational sector the service is built for" (Bildungsbereich, für den der Service hauptsächlich eingerichtet wurde)

"Other educational sector(s)  the service is built for" (Weitere Bildungsbereich(e), für den (die) der Service eingerichtet wurde)

"Main educational sector the project is working for" (Bildungsbereich, für den das Projekt hauptsächlich tätig ist)

"Other educational sector(s) the project is working for" (Weitere Bildungsbereich(e), für den (die) das Projekt tätig ist)

"Main educational sector the event is designed for" (Bildungsbereich, für den die Veranstaltung hauptsächlich konzipiert wurde)

"Other educational sector(s)  the event is designed for" (Weitere Bildungsbereich(e), für den (die) die Veranstaltung konzipiert wurde)
