### ISSUE TITLE
Migrate images to other server

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#572]
As a ~~workaround~~ temporary solution I used my personal copy.com account for hosting images of OER World Map stories etc. Copy.com will be discontinued on May, 1st, see https://techlib.barracuda.com/CudaDrive/EOL. We will need to implement another solution until then and move the current images there.

**Comment by acka47** [comment]
@literarymachine I guess it is time to think about a future-proof solution where we host the images ourselves...

**Comment by literarymachine** [comment]
Good timing, already mentioned this to @philboeselager. Could you look into this? A simple controller that allows uploads is sufficient for now, but we may want to add things like automatic resizing later on.

**Comment by philboeselager** [comment]
@literarymachine Is there anything missing from the backend side?

**Comment by philboeselager** [comment]
As there seems nothing more to be done from the backend side, I assign it to the frontend now.

**Comment by acka47** [comment]
Tomorrow is May 1st. I just received a final "end of life" notice. On production there are still pictures shown from my copy.com acount. They will be missing tomorrow. I hope you have already also stored them elsewhere.

**Comment by literarymachine** [comment]
> I hope you have already also stored them elsewhere.

Nobody has done that, as we have focused on implementing the functionality (also see #647). As nobody felt responsible to actually save the images (and perhaps upload them to GitHub as an interim solution), they are probably lost.

**Comment by acka47** [comment]
> As nobody felt responsible to actually save the images (and perhaps upload them to GitHub as an interim solution), they are probably lost.

I still have them on my hard drive resp. in another cloud (seafile). Here they are: https://app.seafile.de/d/c2849145a1/

**Comment by acka47** [comment]
Closing.
