### ISSUE TITLE
Adjust some labels and tool-tip information in Project form

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#574]
To be adjusted: Project lead, participant, funded by.

**Comment by acka47** [comment]
@trugwaldsaenger and me also discussed the labeling of the `agent` and `participant` fields as Jan is not happy with "Project lead" as it doesn't really fit for organizations. Generally, we agreed on the following as basis:

1. For projects carried out within organzations, it would make sense to add organizations to the "agent" field and associate individual project team members via "participant". 
2. As a) there  might be projects (e.g. free software tools) that are driven by a person with other persons contributing and b) there also might be organizations affiliated with a project but not driving it
we should maintain the possibility to add both orgs and person to both fields.

This leaves the question of labeling. I think, we both preferred the actual schema.org wording "agent" or "opearator" and  "participant".

To move this discussion to GitHub, I propose the following (in the form 'label: tooltip').

operator: The agent(s) driving the project.
participant: Co-agent(s) that participate in the project. 
funder: An agent providing funding for the project.

What do you think? /cc @drrobertfarrow

**Comment by trugwaldsaenger** [comment]
+1 As just discussed we can proceed like this. 

Nevertheless I guess that we will still have to refine this. Some irritation is cause by the fact that for both fields there is a rule and an exception:

1) From my point of view in the "operator" field the rule is that a project is driven by an organization (Example: hbz & graphthinking are operators of the OER World Map project). Nevertheless, especially for grassroots it makes sense that the operator can be a person as well.

2) Within the participant field it is the other way around: Here the rule is that participants are persons. (Example: Jan Neumann is a participant of the OER World Map project) Nevertheless in some cases it might also be possible that an organization is a participant. @acka47: Can you think of an example for this?

**Comment by acka47** [comment]
> @acka47: Can you think of an example for this?

For example, a software development project is lead by the developing organization but there might be partners that implement the software as early adopters.
