### ISSUE TITLE
Confirm list of countries for the landing page of map prototype

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#58]
When I added myself to the database by selecting my country I had to choose 'GB' for Great Britain.  Normally I would expect to choose 'UK' as in 'United Kingdom of Great Britain and Northern Ireland'.  I don't know if there may be other potentially confusing or controversial classifications in the list we have provided - perhaps the list reflects the boundaries as they are defined on the map?

**Comment by trugwaldsaenger** [comment]
Interesting. I guess we are reusing an external list here. Felix, can you tell us, where the list comes from? If I´m right it might mean that we cannot easily fix the bug by ourselves...

**Comment by j0hj0h** [comment]
The list with a country codes was just a quick solution before the skype meeting. We will replace it soon!

**Comment by literarymachine** [comment]
As of https://github.com/hbz/oerworldmap/commit/f13a2c110ab7f8c25175b4c54e054c766a4954fc we are using [ISO 3166-1 alpha-2](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) and (english) labels.

**Comment by literarymachine** [comment]
Most likely the previous list (added mainly for validation reasons by @philboeselager) was also based on these codes. Interestingly enough, `GB` actually is the correct  ISO 3166-1 alpha-2 code for the United Kingdom. @drrobertfarrow do you think this is OK? The human readable drop-down list reads "United Kingdom".

**Comment by drrobertfarrow** [comment]
That sounds fine to me - I see the reason for separating GB and NI for political reasons but UK is what people are likely to look for. I wonder whether it is worth mentioning in the (public) documentation somewhere that this is the list used in case others get confused - but maybe let's leave it for the time being.

**Comment by literarymachine** [comment]
As of https://github.com/hbz/oerworldmap/commit/74bc7df2c616a5e36b1297dc5f8b2d4b2aafcc91 we are auto-generating the list of countries from Java Locales. Besides the country codes, this provides us with localized country names.

**Comment by drrobertfarrow** [comment]
When the new list is rendered in English it does not follow alphabetical order

**Comment by literarymachine** [comment]
Interesting - list is ordered, but by country code which probably does not make too much sense. Created #93.
