### ISSUE TITLE
Buggy display of search results

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#583]
When you click on "You can search our database here" the displayed search result list is buggy.
![displayissue](https://cloud.githubusercontent.com/assets/6639965/13615089/f7fec3aa-e573-11e5-88fc-e407f6d3ff85.JPG)

**Comment by literarymachine** [comment]
Interesting here is the fact, that for those entries an empty name is supplied (as opposed to no name at all); see e.g. https://oerworldmap.org/resource/urn:uuid:0041b732-4dd4-4305-bdd8-462ea6b67c6a

**Comment by philboeselager** [comment]
Just a hint: this probably results from the "tall" icon left hand side of each of the entries below these empty lines. This icon size forces the graphical grid to insert some third of an empty row above, for otherwise the icon would overlap with the one above.
