### ISSUE TITLE
Services by Subject not reduced to top levels any more

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#586]
The services by subject aggregation now causes a long-running query that does not return only the top levels of the classification any more. I believe that this has either to do with #578 or #575.
 
![screenshot from 2016-03-09 16 28 29](https://cloud.githubusercontent.com/assets/149825/13640192/fcd0a72c-e613-11e5-962c-4149e51b9c6a.png)

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/

**Comment by acka47** [comment]
It now loads quickly on the home page. +1 for this.

But clicking on a subject results loads quite slowly (5-10 s). I haven't been using/testing this for some time (I obviously sould do this more often) so I am not sure whether this has been like that all along. Anyway, I think this could be improved but I would be happy to open another issue for this.

**Comment by literarymachine** [comment]
> But clicking on a subject results loads quite slowly (5-10 s).

@philboeselager I believe this is another case where something perhaps in #575 or #578 introduced performance issues?

**Comment by philboeselager** [comment]
> I believe this is another case where something perhaps in #575 or #578 introduced performance issues?

I can't imagine any effect of #575 on search performance, since it does not change algorithms, especially not sending queries to Elasticsearch. It only re-organizes Elasticsearch code.

I'm still investigating #578 .

**Comment by philboeselager** [comment]
Fixed by https://github.com/hbz/oerworldmap/pull/587#issuecomment-194418003

**Comment by literarymachine** [comment]
> But clicking on a subject results loads quite slowly (5-10 s).

@acka47 Can you confirm this is fixed on beta?

**Comment by acka47** [comment]
> @acka47 Can you confirm this is fixed on beta?

I can, I will and I do. +1
