### ISSUE TITLE
Map details disappear for high zoom levels

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#588]
While the initial view of a partial map, like e. g. a country view, e. g. https://oerworldmap.org/country/ly , shows details like country boarders, state boarders, country names and city names, all details but the country boarders disappear when zooming closely into the map.

I can't tell for sure, but my observation was that the number of disfunctional zoom levels varies from 5 to 9 depending on the loaded page. But that number doesn't seem to be predictable or reproducible. If this additional information is confusing, please ignore.

Browser is Firefox 44.0.2

**Comment by philboeselager** [comment]
Addendum: pins remain visible in high zoom levels.

**Comment by literarymachine** [comment]
As of 034da62c42fb0ca682c586be638be5ea03ea84f6 in #421, this is expected behavior. To allow raster details at high zoom levels, we need #472.
