### ISSUE TITLE
Wrong label for field "alternateName"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#599]
Strangely, in https://oerworldmap.org/resource/urn:uuid:81232d43-76e2-477a-8020-fe1092c0b2c1 the alternateName is shown in an additional "email" field:

![20160323_alternatename-bug](https://cloud.githubusercontent.com/assets/160292/13989062/0760fd94-f10f-11e5-836c-3736867269cc.png)

**Comment by acka47** [comment]
Note, that the alternate name is given in two languages for this project. From the JSON:

```json
  "alternateName" : [ {
    "@value" : "opened",
    "@language" : "de"
  }, {
    "@value" : "opened",
    "@language" : "en"
  } ],
```

This doesn't seem to be the cause though. I added a German alternateName to the [hbz entry](https://oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a) and the second email field isn't shown.

**Comment by literarymachine** [comment]
> This doesn't seem to be the cause though.

Nope, seems to be a simple copy-and-paster error in the template: https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Action/read.mustache#L83
