### ISSUE TITLE
Show list of maintaining and partnering organizations on landing page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#6]
As a member of the OER community or someone from the general public I want to easily get information on the landing page about curators of and contributors to the OER World Map.

**Comment by acka47** [comment]
A list with the logos and names of the participating organizations probably makes most sense here.

**Comment by acka47** [comment]
Part of epic #11.

**Comment by drrobertfarrow** [comment]
A bigger question here is what qualifies as association with the project, and what we call contributions.  Often the contributors will be individuals, since that is how they are registering.  Even if an individual works for a well known organisation, there can be issues with calling them 'collaborators'.

**Comment by literarymachine** [comment]
This is blocking the top of our "Ready" list. Please either provide information or re-prioritize.

**Comment by drrobertfarrow** [comment]
I think I need a clarification here:  when we refer to 'maintaining and partnering organizations' who do we mean exactly?

**Comment by acka47** [comment]
opening this issue I was thinking of the organisations that are building the oerworldmap and put resources into its amintenance. For now, this would be the project partners I think (hbz, Open University/IET/OER Research Hub and graphthinking.

**Comment by trugwaldsaenger** [comment]
We have the names and logos of the project partners on our about page: https://oerworldmap.org/about. So this issue can be closed.
