### ISSUE TITLE
Share permalinks for individual entries and result list via social media

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#600]
As a visitor or user I want to quickly share permalinks to interesting entries by mail or social media platforms.

**Comment by formimkontext** [comment]
Sharing permalinks to interesting entries by mail or social media platforms will be possible via …

… a dropdown menu (top right of the resource column)

![20160405-oer-edit-resource-01](https://cloud.githubusercontent.com/assets/15141949/14324293/7ec860c8-fc24-11e5-836c-447ac6cb58fc.jpg)

… or an icon bar (top right of the resource column)

![20160405-oer-edit-resource-02](https://cloud.githubusercontent.com/assets/15141949/14324311/899a5aec-fc24-11e5-88d2-aed1d68df504.jpg)

we may discuss the necessary functions (edit, delete, share, export, …) to integrate within the icon bar / dropdown menu the next days.

**Comment by acka47** [comment]
We discussed that it also should be possible to share result list – especially when you have used multiple filters etc. you might want to get a link to share etc. Thus, renaming the issue.
