### ISSUE TITLE
Add mentionedIn field to resources with possible input of external web pages

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#609]
This came up in the meeting with T J on 2016-04-01. Currently, we only have a "Mentions" field for OER World Map articles/stories, the inverse property "mentionedIn" is hidden from the resources template. It might make sense to also collect external stories – like blog posts – about a resource. For this, we should show the `mentionedIn` field and enable input of any URL.

**Comment by literarymachine** [comment]
We'll add the `mentions` field to the `Publication` template.

**Comment by literarymachine** [comment]
See #1276
