### ISSUE TITLE
Enable changing the type of a resource

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#611]
It should be possible to adjust the type of the resource in an editing form, e.g. making a project into a service.

**Comment by philboeselager** [comment]
With respect to the backend, everything seems done.

The idea is now to allow changing types by a selection dropdown in the frontend, whereby existing data that is validating with the new resource type is kept and non-validating data is simply left out. If the user requests to store non-validating data he will be presented the error ProcessingReport.

Handing this ticket to frontend.

**Comment by karindr** [comment]
As the newly made entries of visitors show, some visitors want to start directly and start editing a person’s page for their service or their organization. (They don’t read, that they should do a person’s page first and ask for editing rights.) It is a lot of work to copy the texts manually. It would be great to have a possibility to change the type without copying every entry!

**Comment by literarymachine** [comment]
> It would be great to have a possibility to change the type without copying every entry!

The problem here is that only `Person` entries should be associated with an account (the two are completely separate things). A `Person` is automatically created and linked with an account when somebody signs up. Changing the type of that profile would then suddenly link e.g. an `Organization` to the account. So there is more involved than simply changing a `@type`.

**Comment by karindr** [comment]
Maybe it would be a solution to copy the content automatically and afterwards to make the Person's entry an empty entry?
This entry is the original entry of eskp.de
https://oerworldmap.org/resource/?q=wissen#urn:uuid:5a336a94-bd05-4ed7-be46-a14e7a68b6cf
We now have an entry for a service with this information also
https://oerworldmap.org/resource/?q=wissen#urn:uuid:d786fac3-9598-4bf5-9fa7-047954a71afe
Should I delete the text in the template for the persons page? Does it disappear then?

**Comment by karindr** [comment]
I tested deleting the texts in such a persons profile on beta. The profile disappears and is no longer found in recent additions, but I did not find a way to get rid of the chosen country. In this test i have chosen Mongolia. The pin disappeared but clicking on Mongolia the profile is listed (but not counted), see:
https://beta.oerworldmap.org/country/mn

**Comment by literarymachine** [comment]
> but I did not find a way to get rid of the chosen country

I added a "None" option to the top of the country list that allows to deselect it. Probably not the prettiest approach in the world, but it works.

**Comment by acka47** [comment]
> As the newly made entries of visitors show, some visitors want to start directly and start editing a person’s page for their service or their organization. 

Do I understand correctly that they mistake their personal profile as an entry of their organization? We should think about how to better guide the user so that he doesn't describe an organization in a personal profile.

**Comment by karindr** [comment]
> I added a "None" option to the top of the country list that allows to deselect it. Probably not the prettiest approach in the world, but it works.

Yes, this works, good solution! I think it would be better to put the "None" as last option in the list. Than we can find it when we need it and other people won't be tempted to choose "None".

**Comment by karindr** [comment]
> Do I understand correctly that they mistake their personal profile as an entry of their organization? 

Yes, we had an organisation and a service entered as person. I think this happens when people get across the OER WM and want to enter their service or what ever quickly and don't want to appear as person on the map. These people don't read our FAQ and so on. In my opinion one way to get these entries correct would be to give these people the possibility to enter 1 person, 1 organisation and 1 service without having to ask for editing rights.

**Comment by acka47** [comment]
Could we at least enabling changing the type of something that is not a `Person` to something else that is also not a `Person`? @karindr has two requests for changing the type that don't involve persons:

- https://oerworldmap.org/resource/urn:uuid:7317b168-8ddb-4c3c-a438-33121ef68e3e -> from `Service` to `project`
- https://oerworldmap.org/resource/urn:uuid:483143d3-bc67-4682-bf2d-2a8b7b34cb2a -> from `Organization` to `Service`

**Comment by karindr** [comment]
And this one:
https://oerworldmap.org/resource/?q=oerfaq#urn:uuid:61733eee-e4c4-4dd3-973d-bc441bf801d5 -> from publication to project

**Comment by trugwaldsaenger** [comment]
This is still an important issue. Just had to change an publication into a service (https://oerworldmap.org/resource/urn:uuid:1111c470-c067-4dc6-816f-490839408eda).

**Comment by literarymachine** [comment]
> existing data that is validating with the new resource type is kept and non-validating data is simply left out.

Looks like the JSON schema validator we are using in the new UI actually has this built in: https://github.com/epoberezkin/ajv#filtering-data

**Comment by trugwaldsaenger** [comment]
Seems to get more important since we have more activity on the platform. So I`ll give this a Prio 1.

**Comment by karindr** [comment]
We have 8 new projects that should be changed to services. It would be great to have an easy way to do this.

**Comment by trugwaldsaenger** [comment]
> Looks like the JSON schema validator we are using in the new UI actually has this built in: https://github.com/epoberezkin/ajv#filtering-data

Sounds promising, @literarymachine! What does it mean in practice? Do you need any additional input?

**Comment by literarymachine** [comment]
As discussed with @trugwaldsaenger and @programmieraffe, changing the type of `Person` entries will not be supported for now.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:5c179e5b-e47a-4431-8f73-26b723e1d515#edit

Note: To change the type of a resource, you currently need to be an admin.
