### ISSUE TITLE
Indicate licensing for services with controlled values

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#612]
To do:
1. Show currently hidden "license" field with strings in production
2. Add controlled values based on existing license strings 
3. Hide – now empty – "license" field for strings.
4. Add licensing to services without any licensing information

**Comment by acka47** [comment]
For 1., we have to adjust https://github.com/hbz/oerworldmap/blob/master/public/mustache/ResourceIndex/Service/edit.mustache.

**Comment by acka47** [comment]
I completed step 3 with one exception, see https://github.com/hbz/oerworldmap/issues/538#issuecomment-211866685. I will talk to Karin so that she adds some licenses (step 4)..

**Comment by acka47** [comment]
I would like to get a list of services without a license indication. Unfortunately, https://oerworldmap.org/resource/?q=_missing_:about.license&filter.about.@type=Service doesn't work as well as other `_missing_` queries form which worked before e.g. one provided by @literarymachine in https://github.com/hbz/oerworldmap/issues/423#issuecomment-232060422

**Comment by acka47** [comment]
I think issue has been fixed for some time now, hasn't it? @karindr, please close this one if I am right.

**Comment by literarymachine** [comment]
What is the status of this, @acka47 @karindr

**Comment by acka47** [comment]
Closing.
