### ISSUE TITLE
Make Elasticsearch "internal or external node" configurable

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#616]
This is a backend test configuration thing only.

**Comment by philboeselager** [comment]
Still working on "internal" mode. Some kind of timing problem appears.

**Comment by philboeselager** [comment]
Internal mode generally works. Detected difficult timing problems for 3 new geo search tests after [merge](https://github.com/hbz/oerworldmap/commit/926750c4fd1e59b9030caf35b8b4ccb2566be987) - but only in "internal node" mode. Will ignore this problem for now, as "external node" mode shows, that tests are generally working. Will invest this issue after merging with #632 again.

**Comment by philboeselager** [comment]
Mausgerutscht.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap/pull/636
