### ISSUE TITLE
ghost email appears for projects

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#617]
![bildschirmfoto 2016-04-14 um 07 23 26](https://cloud.githubusercontent.com/assets/6639965/14517825/132dec86-0212-11e6-9260-fb0f943c064e.png)
After editing a new project without an email address the name of the project appears in the mail field.

**Comment by trugwaldsaenger** [comment]
OK, the problems seems to be that the field "alternative name" is wrongly displayed as "e mail". See

https://oerworldmap.org/resource/urn:uuid:6d45e9eb-b4cb-4f9b-ab99-9b46742017e5

**Comment by acka47** [comment]
> OK, the problems seems to be that the field "alternative name" is wrongly displayed as "e mail"

Duplicate of #599. Closing.
