### ISSUE TITLE
Number of pins decreases after opening search page

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#619]
![bildschirmfoto 2016-04-19 um 07 42 39](https://cloud.githubusercontent.com/assets/6639965/14629995/7e7b8dc4-0602-11e6-876b-48060e5d4a74.png)

**Comment by acka47** [comment]
We already discussed this in #376. Only pins for the resources with geo-coordinates in the right-hand column are shown.

**Comment by trugwaldsaenger** [comment]
You are completely right, thanks for reminding me. I should stop working on GIT before breakfast...
