### ISSUE TITLE
Transfer domain ownership

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#62]
Ownership of oerworldmap.org shall be transferred from @trugwaldsaenger to hbz.

**Comment by acka47** [comment]
I started the process and the domain should be transferred within the next 24 hours.

**Comment by literarymachine** [comment]
$ whois oerworldmap.org
    Domain Name:OERWORLDMAP.ORG
    Domain ID: D171217257-LROR
    Creation Date: 2014-02-24T11:00:21Z
    Updated Date: 2015-02-17T07:02:03Z
    Registry Expiry Date: 2016-02-24T11:00:21Z
    Sponsoring Registrar:united-domains AG (R1838-LROR)
    Sponsoring Registrar IANA ID: 1408
    WHOIS Server: 
    Registrant Fax: 
    Registrant Fax Ext: 
    Registrant Email:verwaltung@hbz-nrw.de
    Admin ID:C-HRA5104-DLBBRZ
    Admin Name:Rene Aden
    Admin Organization:Hochschulbibliothekszentrum NRW - Verwaltung
    Admin Street: Julicherstrasse 6
    Admin City:Koeln
    Admin State/Province:
    Admin Postal Code:50674
    Admin Country:DE
    Admin Phone:+49.221400750
    Admin Phone Ext: 
    Admin Fax: 
    Admin Fax Ext: 
    Admin Email:verwaltung@hbz-nrw.de
