### ISSUE TITLE
Add field "endDate" to service template

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#622]
I just stumbled over https://oerworldmap.org/resource/urn:uuid:c6390382-7f00-11e5-a636-c48e8ff4ea31 which hasn't been available in 2016. Obviously the service has been discontinued. I would like to state this somehow. `endDate` seems the right way to do this. It is not in the template although it is in [the current JSON schema in lines 497-509](https://github.com/hbz/oerworldmap/blob/9e02c6e421066b07ad1f58a7b444113adddd96c7/public/json/schema.json#L497-L509).

**Comment by philboeselager** [comment]
Done.
