### ISSUE TITLE
Kosovo is water

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#625]
Reported by K.D: The Kosovo is covered by water in OER World Map and can not be clicked. Screenshot:

![20160420_water-kosovo-bug](https://cloud.githubusercontent.com/assets/160292/14673222/f11ad3e4-06fc-11e6-806c-9392b1af5fc3.png)

**Comment by karindr** [comment]
On beta this issue is is still remaining using the new mapping layer. (Issue #659 is solved on beta: Both exclaves are shown coloured like the connected country.)

**Comment by literarymachine** [comment]
Current status on beta is not really a fix for this, see https://github.com/hbz/oerworldmap/issues/659#issuecomment-238217270 and #810.

**Comment by philboeselager** [comment]
Kosovo is missing in our countries lists. Not sure, whether this is part of the solution but it might be of some interest: add to countries.properties:

    XK=Kosovo

Add to all.json:

    {"name":"Kosovo","alpha-2":"XK","alpha-3":"XKX","iso_3166-2":"ISO 3166-2:RS-KM"}

I did not find information about

- UN "country-code"
- "region-code"
- "sub-region-code"

**Comment by philboeselager** [comment]
The world bank [assigns "KSV" as "country id" for Kosovo](http://api.worldbank.org/countries?page=4). Their "country id" is the same as [ISO_3166-1_alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) for other countries. So we could assign "KSV" to Kosovo without putting our heads above the parapet.

**Comment by j0hj0h** [comment]
Ok, I took a look and in our country vector data from natural earth, Kosovo has an id of "-99". Actually it should be painted white anyway, as this is the default and actually returned by the styling callback. Somehow I'll find the reason for it being transparent, but how will we deal with Kosovo, as it doesn't have an official "ISO 3166 ALPHA-2" code. Shell we take the informal one (XK)?

See: https://github.com/nvkelso/natural-earth-vector/issues/134

**Comment by philboeselager** [comment]
As long as we have no further information, I would go for:

    {"name":"Kosovo","alpha-2":"XK","alpha-3":"KSV","iso_3166-2":"ISO 3166-2:RS-KM"}

**Comment by j0hj0h** [comment]
For documentation (of https://github.com/hbz/oerworldmap/commit/14d82f44e0c2aa144f1ea88d3d80769a302e4e95 and https://github.com/hbz/oerworldmap/commit/37de5f7e1439ed0031dee12d2a74b74b890db9a3):

- There were 5 countries in ne_50m_admin_0_countries_topo.json with an `id` of "-99".
- These countries are:
  - Kosovo
  - Northern Cyprus
  - [Somaliland](https://en.wikipedia.org/wiki/Somaliland), an autonomous region of Somalia
  - [Cocos (Keeling) Islands](https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands) and [Christmas Island](https://en.wikipedia.org/wiki/Christmas_Island) (as one country)
  - A triangle at the border region of China, India and Pakistan, probably a disputed territory – see attached screenshot.
- The reason, that they are not painted, is that OpenLayers doesn't paint features, if the ID is not unique.
- I gave Kosovo the `id` "XK" and the others "X1" ... "X4", to have them unique at least.
- I added Kosovo to all.json in the form suggested by @philboeselager 
- ... and to conf/countries.properties – but it's still not appearing in `i18n.countries` ... @literarymachine any idea?
- I added a function to the map behaviour to find countries by id. It colors them red and sets the focus. I think this might be useful for various debugging and would keep it. One can use it by typing e.g. `Hijax.behaviours.map.debugShowCountry('XK')` in the console.

As it's not clear if we will work with the same country boundaries in case of switching the mapping library, I'd suggest to skip research about the other regions, until then.
