### ISSUE TITLE
Show hierarchy of subjects in service description

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#626]
Reported by K.D. Currently, we provide some classification context, i.e. broader and narrower concepts in the subject web form, e.g.:

![20160420_subject-hierarchy](https://cloud.githubusercontent.com/assets/160292/14673943/35ae6a3a-0701-11e6-9d8f-6515be559c3a.png)

In the single resource view this context is not provided, see e.g. https://oerworldmap.org/resource/urn:uuid:3307bf6b-c6c6-4327-96fd-f112d9fc5386

The three concepts "Services", "Personal Services" and "Travel, tourism and leisure" are listed under subject but their connection/hierarchy is not clear. I think we should somehow indicate the subjects of a resource by showing the subset of the classification in a tree style similar linke in the form.

**Comment by acka47** [comment]
Feedback with another example provided by K.D.:

> Discover the COSMOS
> https://oerworldmap.org/resource/urn:uuid:bc154338-df84-48a8-b640-979193b2d5ac
> Hier würde eine Einrückung der Art:
> ```
> Natural science
>      Physical science
>          Physics
> ```
> Deutlicher machen, dass das keine Dopplung ist, sondern verschiedene 
> Stufen. Bei langen Listen macht eine Einrückung die Listen auch 
> übersichtlicher.

**Comment by karindr** [comment]
This would be very useful now. More people should visit the site and enter date. We have to make it easy to understand and to handle.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:3307bf6b-c6c6-4327-96fd-f112d9fc5386 or https://beta.oerworldmap.org/resource/urn:uuid:bc154338-df84-48a8-b640-979193b2d5ac
