### ISSUE TITLE
Add "Copyright" to licenses list.

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#627]
From https://github.com/hbz/oerworldmap/issues/358#issuecomment-212394975:
> Working on #612 I realized that we should definitely add a `Copyright` option. We have a number of services in there that explicitly offer resources that have full copyright restrictions. Currently, I don't add any license information for these but thus is not satisfying.

**Comment by karindr** [comment]
@literarymachine, I also need this "copyright"-option for #612. I looked for it on oerworldmap.org and on beta, it is not there. Do you know anything about this?

**Comment by literarymachine** [comment]
On production.

**Comment by karindr** [comment]
The option is on production. But can you please change the position in the list? It is:
Other (Non-Commercial)
Copyright
Other (No-Derivates)
It should be:
Other (Non-Commercial)
Other (No-Derivates)
Copyright

**Comment by literarymachine** [comment]
On production. @karindr please don't close the issues manually, an "OK" or a "+1" is sufficient. Issues will be closed automatically when I merge the corresponding pull request into production. Thanks!

**Comment by karindr** [comment]
+1
