### ISSUE TITLE
Create data model documentation with hypothes.is

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#630]
We decided to document our data model annotating example entries with hypothes.is.

**Comment by acka47** [comment]
See also https://github.com/hbz/oerworldmap/issues/853#issuecomment-246263238.

**Comment by acka47** [comment]
BTW, I implemented this kind of documentation in lobid. If you are interested in what it looks like, install the [hypothes.is chrome plugin](https://chrome.google.com/webstore/detail/hypothesis-web-pdf-annota/bjfhmglciegochdpefhhlphglcehbmek) and take a look at http://lobid.org/organisations/DE-38M?format=json

**Comment by acka47** [comment]
See http://lobid.org/organisations/api/de#jsonld as example implementation that can be used without the crome plugin.

**Comment by acka47** [comment]
We decided to just add a static page under /api with an example file (I suggest https://oerworldmap.org/resource/urn:uuid:29056e88-727b-407e-b00a-16df279ac506.json for now) and embedded hypothes.is (see https://web.hypothes.is/for-publishers/). For now, the page won't be linked to from navigation panel.

**Comment by literarymachine** [comment]
@acka47 The page to annotate is available here: https://oerworldmap.org/api

**Comment by acka47** [comment]
I think I am through with this example, see https://oerworldmap.org/api @trugwaldsaenger @karindr please take a look.

Although, I could also add annotations for location information (address, geo) to an organization embedded in the current example as "provider" or "member", I think we should add a separate example organization for this. What do others think?

**Comment by karindr** [comment]
From my point of view, this is ok.

**Comment by literarymachine** [comment]
Done, closing.
