### ISSUE TITLE
Add timeline

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#631]
The OERWorldMap should provide a timeline view to have an easy-access intuitive way to look for events and other time-based resources.

In a first version, it may be sufficient to have all those resources side by side.

In a later version, "zooming" is desirable. When zoomed out, only the "most important" resources remain visible. This implies a data hierarchy.

**Comment by j0hj0h** [comment]
This is described in story #27, @formimkontext already made some drafts and we discussed it during the last team meeting. Zooming as you described wasn't considered so far, but I also don't see a practical solution to rank events.

**Comment by literarymachine** [comment]
The timeline is different from what we are planning as a calendar view, and not strictly limited to our `Event` type. It could also include e.g. start and end dates of projects etc and should probably look something like http://www.datavizcatalogue.com/methods/timeline.html.

**Comment by j0hj0h** [comment]
Got it. Sounds like this might be the moment to think about fullscreen views on aggregated resources.

**Comment by karindr** [comment]
Interesting example of timeline and map for oer:
http://timemapper.okfnlabs.org/okfnedu/open-education-timeline#11
