### ISSUE TITLE
Sort grade levels in input form

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#633]
The grade levels in the input form for services should be sorted this way:

Pre-primary education
Primary education ...
Lower secondary education ...
Upper secondary education ...
First stage of tertiary education
Second stage of tertiary education
Post-secondary non-tertiary education

By the way it should bei "Pre-primary education" instead of "Pre-Primary Education" (lower case as in the other levels).

**Comment by karindr** [comment]
It would be good if the grade levels on the web page of the service were also listed in this order.

**Comment by trugwaldsaenger** [comment]
+1

**Comment by karindr** [comment]
When people **now** start to enter data about their services, this would be really helpful for them. Otherwise the may stop entring data, because they think, they don't understand, what we want them to enter at this field.

**Comment by karindr** [comment]
Me again ;-).
It is really annoying to enter the grade levels this way! Could somebody please change the order?

**Comment by literarymachine** [comment]
Done.
