### ISSUE TITLE
Events seem to cause errors in displaying country color and informations

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#634]
The 5 countries with events (Germany, Belgium, UK, Austria and Poland) are displayed on the map in light grey respectively light green (Austria with its 2 Events). It seems as if only the number of events is used for choosing the color. I think, that’s not right, is it?
In addition to this only the number of events is displayed on the label when the mouse is hovering the country not the number of services etc. On the other hand events aren’t listed in the lists of the country views.

**Comment by karindr** [comment]
On the label when the mouse is hovering the country the information according to the country champions is also not shown in the correct way. E.g. UK has got a country champion but there is an x on the label.

**Comment by literarymachine** [comment]
This is an index problem that will be closed with #528; see https://beta.oerworldmap.org/ where the problem should already be solved.

**Comment by karindr** [comment]
OK.
