### ISSUE TITLE
Stories have disappeared

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#648]
Most of the stories have disappeared completely e.g.
https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=AF&filter.about.@type=Article
https://oerworldmap.org/resource/urn:uuid:2b709e3f-5d3c-4b5a-b0a5-838246f24c5c

Some story pages are still there but the text is missing e.g.
https://oerworldmap.org/resource/urn:uuid:878f36d6-15d5-11e5-bcc3-3700f09c76de

**Comment by literarymachine** [comment]
Fixed on production, see https://oerworldmap.org/resource/?filter.about.@type=Article

**Comment by karindr** [comment]
OK.
