### ISSUE TITLE
Change „Type: Action“ to „Type: Project“ and “Type: Article” to “Type: Story”

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#650]
When you are on the homepage and choose “Project” or “Story” from the little table on the right side on the next page there “Type: Action” and on the other hand “Type: Article” is shown. Same in the URL. That’s not really disturbing, but the other way it would be more consistent.
The other entities are shown correctly.

**Comment by literarymachine** [comment]
This is due to the fact "Project" and "Story" are our labels, but the internal (schema.org) types are "Action" and "Article". Labeling the filters will be easy to fix, but aliasing the types in the URL is a bit more involved.

**Comment by karindr** [comment]
Understood. The labeling of the filters is what the user will see, only few people will recognize the different names in the url. So maybe changing the label is enough.

**Comment by acka47** [comment]
I only see it in the mouseover pop up. Where can I adjust this, @literarymachine? If you tell me I will make a PR.

**Comment by literarymachine** [comment]
> I only see it in the mouseover pop up. Where can I adjust this, @literarymachine? If you tell me I will make a PR.

Currently working on #761, this should be done afterwards.

**Comment by karindr** [comment]
The screencasts Rob made showed again how useful it would be to have consistent names for our categories!

**Comment by acka47** [comment]
> The screencasts Rob made showed again how useful it would be to have consistent names for our categories!

This refers to the tooltips for the filter buttons that still read "Action" and "Article".

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
