### ISSUE TITLE
Searching for a Term with exclamation mark doesn't give expected result

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#652]
[SearchPhaseExecutionException: Failed to execute phase [dfs], all shards failed; shardFailures {[zCCyDUlERhCZw1eItq_XMw][oerworldmap.9004][0]: SearchParseException[[oerworldmap.9004][0]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"filtered":{"query":{"query_string":{"query":"OERUp!","fields":["about.agent.name.@value^4.0","about.participant.alternateName.@value^1.0","about.name.@value^9.0","about.provider.alternateName.@value^4.0","about.alternateName.@value^6.0","about.provider.name.@value^5.0","about.participant.name.@value^2.0","about.agent. alternateName.@value^3.0"]}},"filter":{"and":{"filters":[{"not":{"filter":{"and":{"filters":[{"term":{"about.@type":"Person"}},{"not":{"filter":{"exists":{"field":"about.email"}}}}]}}}},{"not":{"filter":{"or":{"filters":[{"term":{"about.@type":"Concept"}},{"term":{"about.@type":"ConceptScheme"}}]}}}},{"and":{"filters":[]}}]}}}},"_source":{"includes":["about.@id","about.@type","about.name","about.alternateName","about.location","about.image","about.provider.@id","about.provider.@type","about.provider.name","about.provider.location","about.participant.@id","about.participant.@type","about.participant.name","about.participant.location","about.agent.@id","about.agent.@type","about.agent.name","about.agent.location","about.mentions.@id","about.mentions.@type","about.mentions.name","about.mentions.location","about.mainEntity.@id","about.mainEntity.@type","about.mainEntity.name","about.mainEntity.location"],"excludes":[]},"aggregations":{"about.@type":{"terms":{"field":"about.@type","size":0}},"about.location.address.addressCountry":{"terms":{"field":"about.location.address.addressCountry","size":0},"aggregations":{"by_type":{"terms":{"field":"about.@type"}},"champions":{"filter":{"exists":{"field":"about.countryChampionFor"}}}}},"about.availableChannel.availableLanguage":{"terms":{"field":"about.availableChannel.availableLanguage","size":0}},"about.about.@id":{"terms":{"field":"about.about.@id","size":0}},"about.audience.@id":{"terms":{"field":"about.audience.@id","size":0}},"about.tag":{"terms":{"field":"about.tag","size":0}}}}]]]; nested: QueryParsingException[[oerworldmap.9004] Failed to parse query [OERUp!]]; nested: ParseException[Cannot parse 'OERUp!': Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; nested: ParseException[Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; }{[zCCyDUlERhCZw1eItq_XMw][oerworldmap.9004][1]: SearchParseException[[oerworldmap.9004][1]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"filtered":{"query":{"query_string":{"query":"OERUp!","fields":["about.agent.name.@value^4.0","about.participant.alternateName.@value^1.0","about.name.@value^9.0","about.provider.alternateName.@value^4.0","about.alternateName.@value^6.0","about.provider.name.@value^5.0","about.participant.name.@value^2.0","about.agent. alternateName.@value^3.0"]}},"filter":{"and":{"filters":[{"not":{"filter":{"and":{"filters":[{"term":{"about.@type":"Person"}},{"not":{"filter":{"exists":{"field":"about.email"}}}}]}}}},{"not":{"filter":{"or":{"filters":[{"term":{"about.@type":"Concept"}},{"term":{"about.@type":"ConceptScheme"}}]}}}},{"and":{"filters":[]}}]}}}},"_source":{"includes":["about.@id","about.@type","about.name","about.alternateName","about.location","about.image","about.provider.@id","about.provider.@type","about.provider.name","about.provider.location","about.participant.@id","about.participant.@type","about.participant.name","about.participant.location","about.agent.@id","about.agent.@type","about.agent.name","about.agent.location","about.mentions.@id","about.mentions.@type","about.mentions.name","about.mentions.location","about.mainEntity.@id","about.mainEntity.@type","about.mainEntity.name","about.mainEntity.location"],"excludes":[]},"aggregations":{"about.@type":{"terms":{"field":"about.@type","size":0}},"about.location.address.addressCountry":{"terms":{"field":"about.location.address.addressCountry","size":0},"aggregations":{"by_type":{"terms":{"field":"about.@type"}},"champions":{"filter":{"exists":{"field":"about.countryChampionFor"}}}}},"about.availableChannel.availableLanguage":{"terms":{"field":"about.availableChannel.availableLanguage","size":0}},"about.about.@id":{"terms":{"field":"about.about.@id","size":0}},"about.audience.@id":{"terms":{"field":"about.audience.@id","size":0}},"about.tag":{"terms":{"field":"about.tag","size":0}}}}]]]; nested: QueryParsingException[[oerworldmap.9004] Failed to parse query [OERUp!]]; nested: ParseException[Cannot parse 'OERUp!': Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; nested: ParseException[Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; }{[zCCyDUlERhCZw1eItq_XMw][oerworldmap.9004][2]: SearchParseException[[oerworldmap.9004][2]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"filtered":{"query":{"query_string":{"query":"OERUp!","fields":["about.agent.name.@value^4.0","about.participant.alternateName.@value^1.0","about.name.@value^9.0","about.provider.alternateName.@value^4.0","about.alternateName.@value^6.0","about.provider.name.@value^5.0","about.participant.name.@value^2.0","about.agent. alternateName.@value^3.0"]}},"filter":{"and":{"filters":[{"not":{"filter":{"and":{"filters":[{"term":{"about.@type":"Person"}},{"not":{"filter":{"exists":{"field":"about.email"}}}}]}}}},{"not":{"filter":{"or":{"filters":[{"term":{"about.@type":"Concept"}},{"term":{"about.@type":"ConceptScheme"}}]}}}},{"and":{"filters":[]}}]}}}},"_source":{"includes":["about.@id","about.@type","about.name","about.alternateName","about.location","about.image","about.provider.@id","about.provider.@type","about.provider.name","about.provider.location","about.participant.@id","about.participant.@type","about.participant.name","about.participant.location","about.agent.@id","about.agent.@type","about.agent.name","about.agent.location","about.mentions.@id","about.mentions.@type","about.mentions.name","about.mentions.location","about.mainEntity.@id","about.mainEntity.@type","about.mainEntity.name","about.mainEntity.location"],"excludes":[]},"aggregations":{"about.@type":{"terms":{"field":"about.@type","size":0}},"about.location.address.addressCountry":{"terms":{"field":"about.location.address.addressCountry","size":0},"aggregations":{"by_type":{"terms":{"field":"about.@type"}},"champions":{"filter":{"exists":{"field":"about.countryChampionFor"}}}}},"about.availableChannel.availableLanguage":{"terms":{"field":"about.availableChannel.availableLanguage","size":0}},"about.about.@id":{"terms":{"field":"about.about.@id","size":0}},"about.audience.@id":{"terms":{"field":"about.audience.@id","size":0}},"about.tag":{"terms":{"field":"about.tag","size":0}}}}]]]; nested: QueryParsingException[[oerworldmap.9004] Failed to parse query [OERUp!]]; nested: ParseException[Cannot parse 'OERUp!': Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; nested: ParseException[Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; }{[zCCyDUlERhCZw1eItq_XMw][oerworldmap.9004][3]: SearchParseException[[oerworldmap.9004][3]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"filtered":{"query":{"query_string":{"query":"OERUp!","fields":["about.agent.name.@value^4.0","about.participant.alternateName.@value^1.0","about.name.@value^9.0","about.provider.alternateName.@value^4.0","about.alternateName.@value^6.0","about.provider.name.@value^5.0","about.participant.name.@value^2.0","about.agent. alternateName.@value^3.0"]}},"filter":{"and":{"filters":[{"not":{"filter":{"and":{"filters":[{"term":{"about.@type":"Person"}},{"not":{"filter":{"exists":{"field":"about.email"}}}}]}}}},{"not":{"filter":{"or":{"filters":[{"term":{"about.@type":"Concept"}},{"term":{"about.@type":"ConceptScheme"}}]}}}},{"and":{"filters":[]}}]}}}},"_source":{"includes":["about.@id","about.@type","about.name","about.alternateName","about.location","about.image","about.provider.@id","about.provider.@type","about.provider.name","about.provider.location","about.participant.@id","about.participant.@type","about.participant.name","about.participant.location","about.agent.@id","about.agent.@type","about.agent.name","about.agent.location","about.mentions.@id","about.mentions.@type","about.mentions.name","about.mentions.location","about.mainEntity.@id","about.mainEntity.@type","about.mainEntity.name","about.mainEntity.location"],"excludes":[]},"aggregations":{"about.@type":{"terms":{"field":"about.@type","size":0}},"about.location.address.addressCountry":{"terms":{"field":"about.location.address.addressCountry","size":0},"aggregations":{"by_type":{"terms":{"field":"about.@type"}},"champions":{"filter":{"exists":{"field":"about.countryChampionFor"}}}}},"about.availableChannel.availableLanguage":{"terms":{"field":"about.availableChannel.availableLanguage","size":0}},"about.about.@id":{"terms":{"field":"about.about.@id","size":0}},"about.audience.@id":{"terms":{"field":"about.audience.@id","size":0}},"about.tag":{"terms":{"field":"about.tag","size":0}}}}]]]; nested: QueryParsingException[[oerworldmap.9004] Failed to parse query [OERUp!]]; nested: ParseException[Cannot parse 'OERUp!': Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; nested: ParseException[Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; }{[zCCyDUlERhCZw1eItq_XMw][oerworldmap.9004][4]: SearchParseException[[oerworldmap.9004][4]: from[0],size[25]: Parse Failure [Failed to parse source [{"from":0,"size":25,"query":{"filtered":{"query":{"query_string":{"query":"OERUp!","fields":["about.agent.name.@value^4.0","about.participant.alternateName.@value^1.0","about.name.@value^9.0","about.provider.alternateName.@value^4.0","about.alternateName.@value^6.0","about.provider.name.@value^5.0","about.participant.name.@value^2.0","about.agent. alternateName.@value^3.0"]}},"filter":{"and":{"filters":[{"not":{"filter":{"and":{"filters":[{"term":{"about.@type":"Person"}},{"not":{"filter":{"exists":{"field":"about.email"}}}}]}}}},{"not":{"filter":{"or":{"filters":[{"term":{"about.@type":"Concept"}},{"term":{"about.@type":"ConceptScheme"}}]}}}},{"and":{"filters":[]}}]}}}},"_source":{"includes":["about.@id","about.@type","about.name","about.alternateName","about.location","about.image","about.provider.@id","about.provider.@type","about.provider.name","about.provider.location","about.participant.@id","about.participant.@type","about.participant.name","about.participant.location","about.agent.@id","about.agent.@type","about.agent.name","about.agent.location","about.mentions.@id","about.mentions.@type","about.mentions.name","about.mentions.location","about.mainEntity.@id","about.mainEntity.@type","about.mainEntity.name","about.mainEntity.location"],"excludes":[]},"aggregations":{"about.@type":{"terms":{"field":"about.@type","size":0}},"about.location.address.addressCountry":{"terms":{"field":"about.location.address.addressCountry","size":0},"aggregations":{"by_type":{"terms":{"field":"about.@type"}},"champions":{"filter":{"exists":{"field":"about.countryChampionFor"}}}}},"about.availableChannel.availableLanguage":{"terms":{"field":"about.availableChannel.availableLanguage","size":0}},"about.about.@id":{"terms":{"field":"about.about.@id","size":0}},"about.audience.@id":{"terms":{"field":"about.audience.@id","size":0}},"about.tag":{"terms":{"field":"about.tag","size":0}}}}]]]; nested: QueryParsingException[[oerworldmap.9004] Failed to parse query [OERUp!]]; nested: ParseException[Cannot parse 'OERUp!': Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; nested: ParseException[Encountered "<EOF>" at line 1, column 6. Was expecting one of: <BAREOPER> ... "(" ... "*" ... <QUOTED> ... <TERM> ... <PREFIXTERM> ... <WILDTERM> ... <REGEXPTERM> ... "[" ... "{" ... <NUMBER> ... <TERM> ... "*" ... ]; }]

**Comment by acka47** [comment]
The error is gone, see https://beta.oerworldmap.org/resource/?q=OERup! The expected result isn't shown, though. Thus, I'd rename this issue to "Searching for a Term with exclamation mark doesn't give expected result". OK?

**Comment by literarymachine** [comment]
+1

**Comment by acka47** [comment]
By now, I also get the "Execution exception". I won't post the very long error message here. has something been reverted in the code?

**Comment by literarymachine** [comment]
On beta: [https://beta.oerworldmap.org/resource/?q=OERup!](https://beta.oerworldmap.org/resource/?q=OERup!)

**Comment by trugwaldsaenger** [comment]
Seems to be working now! +1
