### ISSUE TITLE
Add support for file extension in URLs

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#654]
Currently, JSON data is only available using content negotiation:

```
$ curl -H "Accept:application/json" https://oerworldmap.org/country/de

$ curl -H "Accept:application/json" https://oerworldmap.org/resource/?filter.about.@type=Organization

$ curl -H "Accept:application/json" https://oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a
```

In order to facilitate retrieval of raw data, JSON should also be exposed when adding `.json` to the URLs:

```
https://oerworldmap.org/country/de.json

https://oerworldmap.org/resource/?filter.about.@type=Organization.json

https://oerworldmap.org/resource/urn:uuid:e08975fe-acc0-4733-8496-2cfc034a120a.json
```

**Comment by acka47** [comment]
Looks good on production. https://oerworldmap.org/country/de.json doesn't work, though. (Which is not a big problem for me now. Just want to make sure as it is listed as example above.)
