### ISSUE TITLE
Adding membership is not possible and delete other page

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#655]
The Jožef Stefan Institute has two pages as organization, please delete this page:
https://oerworldmap.org/resource/urn:uuid:70696332-77eb-11e5-9f9f-c48e8ff4ea31

More complete page with link to service is this page:
https://oerworldmap.org/resource/urn:uuid:6af6b838-2655-11e5-80ee-033038be6ec9

I tried to add a membership to Open Education Consortium to this organization but it wasn’t possible. Could you fix this?

**Comment by literarymachine** [comment]
> The Jožef Stefan Institute has two pages as organization, please delete this page:
https://oerworldmap.org/resource/urn:uuid:70696332-77eb-11e5-9f9f-c48e8ff4ea31

Done.

**Comment by literarymachine** [comment]
> I tried to add a membership to Open Education Consortium to this organization but it wasn’t possible. Could you fix this?

There was an error in the validation process which is fixed now and deployed to production.

**Comment by karindr** [comment]
The problem with the membership is solved and the second page for the Institute is gone, but if you search for Joz*, there is still an entry for the deleted page:
https://oerworldmap.org/resource/?q=Joz*

**Comment by literarymachine** [comment]
> but if you search for Joz, there is still an entry for the deleted page

Fixed: https://oerworldmap.org/resource/?q=Jozef

**Comment by karindr** [comment]
OK
