### ISSUE TITLE
Data saving does not work on test system

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#657]
@karindr as well as a second test user I generated cannot save data on the development server. It`s possible to register, to log in and to open an input template. As soon as we want to save any changes we are asked to login again. Doing so does not help, after trying to save again you are asked to login again. 

The funny thing is that my first testuser seems not to be affected by this issue. I`m loged in since this morning and can still save new datasets. 

Unfortunatly this is a major issue, it will be hardly possible for us to continue testing, as long as this is not solved.

**Comment by trugwaldsaenger** [comment]
Interesting: It still works for me, but not for @karindr and @acka47.

**Comment by literarymachine** [comment]
Which email addresses are you using? You currently have to be a country champion to save anything, sorry. This means that you need to use the email address I sent the email "OER World Map v1.1" to, case sensitive. @karindr: I saw that you used all lower case letters. Sorry about this, I just realized this now.

**Comment by literarymachine** [comment]
@trugwaldsaenger is the only one who used that exact email address, which is why it is working for him.

**Comment by karindr** [comment]
Now it works for me. Thanks for the hint.
