### ISSUE TITLE
"Not found" when clicking on the chart

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#658]
http://oerworldmap.graphthinking.com/resource/Person
"Not found"
I went there clicking on the piece of the pie chart for persons. Same for the other pieces and for the other pie.

**Comment by literarymachine** [comment]
@j0hj0h this is something I messed up in the template, you need not worry about it.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
