### ISSUE TITLE
 Field to enter a search term is hard to find

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#660]
http://oerworldmap.graphthinking.com/?q=&filter.about.%40type=Person#urn:uuid:295b0fcb-4035-4de0-b26d-dfdc723c4b94
On the page for a person the field to enter a search term is hard to find. Also on other pages, when it is displayed in the middle column. Wouldn’t it be better to choose a background color for this field? The screenshots in #577 show a white background.

**Comment by karindr** [comment]
![image](https://cloud.githubusercontent.com/assets/18674205/15738111/033dd1f6-28aa-11e6-9b2f-12a4b30449e1.png)
A white or light grey background also would eliminate this effect: "Search the map" is displayed over the country label. Same effect below the bar for the found entities and the menu icons. Maybe a background for this area would be good to?

**Comment by karindr** [comment]
![image](https://cloud.githubusercontent.com/assets/18674205/15738320/063907d0-28ab-11e6-968e-2c4960ea716a.png)
This was the first screenshot

**Comment by trugwaldsaenger** [comment]
+1 This is an important usability aspect. Maybe it would also be possible to display "search the map..." in a strong orange.

**Comment by j0hj0h** [comment]
Sure, the redesign of the index column (search field, filter section, statistic column) isn't implemented yet. The current state is just a provisorical one to let you test the other major changes. If we need to go live before this is ready at least the search field will become a background for sure.
