### ISSUE TITLE
In the newsletter dialog there should be also a button „Cancel“ or „No, thank you!“

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#662]
http://oerworldmap.graphthinking.com/user/newsletter
In the newsletter dialog there should be also a button „Cancel“ or „No, thank you!“ Also on oerworldmap.org.

**Comment by j0hj0h** [comment]
All dialogs can be closed by clicking somewhere appart. We discussed if and what we want to provide in addition to that: a generic X, that sits in the upper right corner of every dialog or a button like @karindr suggested.

What do you think?

**Comment by karindr** [comment]
In the case of the newsletter I would prefer to show the user/visitor very clearly, that it is his choice and that we don’t want to push him to sign for the newsletter. If there is a second button similar to the “subscribe” button, it looks more friendly and “less commercial”.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
