### ISSUE TITLE
Help text for list- and chart view

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#663]
It would be useful to show little signs when the mouse hovers the two little buttons for list view and for the pie charts. Maybe “List view” and “Chart view”. The list view of results should be shown as default.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
"Statistic View" with capital "V" as in "List View", please.

**Comment by karindr** [comment]
OK

**Comment by literarymachine** [comment]
Not applicable any longer, statistics moved out of the list column.
