### ISSUE TITLE
Show labels when the mouse hovers the buttons for newsletter registration and for adding project/service etc.

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#664]
It would be useful to show labels when the mouse hovers the orange buttons for newsletter registration and for adding project/service etc. Text could be “newsletter” or “Register for our newsletter!” and “add data” or “Add organizations, projects, services, events or stories!”

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
