### ISSUE TITLE
Homepage text shown on persons page

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#666]
When I followed the link of the tag and went back, the homepage text is shown twice on a persons-page. Like in screenshot below. Reloading fixes the problem.
![image](https://cloud.githubusercontent.com/assets/18674205/15666802/085a0800-2713-11e6-92f4-eecaa17a5db7.png)
Another wrong place for the homepage text:
![image](https://cloud.githubusercontent.com/assets/18674205/15668157/20e9c1ba-271a-11e6-98b6-8e6c37b8e8b7.png)

**Comment by karindr** [comment]
![image](https://cloud.githubusercontent.com/assets/18674205/15736539/c24c2f5c-28a0-11e6-82d1-99e46bb5237f.png)
Same for service page.

**Comment by j0hj0h** [comment]
What do you mean by following the link of the tag? Cannot reproduce this ...

**Comment by karindr** [comment]
I tried the to reproduce the Screenshots above but it worked correct. (I clicked on the Tag "system thinking" in the column for Jan, got to the next page and went back by using the back button of the browser. Same with clicking on one the Tag "France" and going back for the Service.)
But there was again the homepage text in the wrong place, see below. 
![image](https://cloud.githubusercontent.com/assets/18674205/15814010/beee1174-2bc3-11e6-98c4-1999740be226.png)
Using the back button to reconstruct this, the homepage text appeared in the right column, like this:
![image](https://cloud.githubusercontent.com/assets/18674205/15814028/dc7d25ae-2bc3-11e6-8d31-7db015c5a3fb.png)
When I tried to reproduce this, but all worked correct. Strange.

**Comment by j0hj0h** [comment]
Got it, thanks.

**Comment by literarymachine** [comment]
Also, when clicking on a country, then the back button and finally the forward button, the homepage text appears in the right hand column; see https://github.com/hbz/oerworldmap/issues/669#issuecomment-225530034.

**Comment by karindr** [comment]
I used back and forward buttons quite a lot and the homepage text is no longer shown in the wrong place.
But look at this:
![image](https://cloud.githubusercontent.com/assets/18674205/16039459/3d297706-322a-11e6-9175-4ffedf9a1c2f.png)
I changed to a static page and used the back button (as you see in the url) but the static page is still shown in the browser window .
