### ISSUE TITLE
Persons page is shown instead of organizations page

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#667]
When I want to go to the page of the organization Test-Orga by clicking on the name in the list this page is shown, the page of an associated person and the list of organizations:
http://oerworldmap.graphthinking.com/resource/?q=&filter.about.%40type=Organization#urn:uuid:139d491a-802a-4244-8c5b-ddf100abe691
Nothing changes when clicking on the name of the organization.

**Comment by karindr** [comment]
Strange, next time I tried it worked correctly.

**Comment by trugwaldsaenger** [comment]
Not reproducable for me as well.
