### ISSUE TITLE
Error in displaying a persons page

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#668]
Klicking on the pin for Felix on the map results in this:
 
![image](https://cloud.githubusercontent.com/assets/18674205/15671044/00fa2958-2729-11e6-9a13-8f1b8f8d14b9.png)

Reload:
![image](https://cloud.githubusercontent.com/assets/18674205/15671053/0c4ee654-2729-11e6-8e3a-a78162c8ace3.png)

**Comment by j0hj0h** [comment]
Cannot reproduce it. Which exact click path would cause it?

**Comment by karindr** [comment]
This time it works correct. But clicking around I got this:
![image](https://cloud.githubusercontent.com/assets/18674205/15814979/3674d70e-2bca-11e6-8596-17533c1e2d6b.png)
Seems to be a similar case, but I cant reproduce it either.

**Comment by karindr** [comment]
I can't reproduce this. But I think using the back button of the browser sometimes lead to false columns. I used it now and got this:
![image](https://cloud.githubusercontent.com/assets/18674205/15818134/d19c1f24-2bdb-11e6-9a27-9c83d9c13ce6.png)

**Comment by karindr** [comment]
And again the back button, I think:
![image](https://cloud.githubusercontent.com/assets/18674205/15818761/6ba3b0c0-2bdf-11e6-8efe-0087b5497e08.png)

**Comment by j0hj0h** [comment]
Allright, will try it out

**Comment by karindr** [comment]
I tested the back button a lot of times everything is working fine.
