### ISSUE TITLE
Input template is not displayed sometimes

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#669]
Being on the country view of Germany, I clicked on the +-button for adding a service, I get to screen shown below. I can’t get into the white field. When reloading I’m back to the country view. Same for project, event etc.
![image](https://cloud.githubusercontent.com/assets/18674205/15671201/e7339a3a-2729-11e6-8220-93a91cbc0ad6.png)

**Comment by karindr** [comment]
I tested this, it is always this screen, when you click on the +-button being on a country page.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/country/de

**Comment by karindr** [comment]
![image](https://cloud.githubusercontent.com/assets/18674205/16002321/4ddea23e-3157-11e6-80cd-4c5fa8e6e6cd.png)
Beeing on this wrongly displayed page:
![image](https://cloud.githubusercontent.com/assets/18674205/16002346/73fcf4ca-3157-11e6-81d3-570f5ef7187f.png)
the error from above occurs again. Maybe again using the back button is the "reason" for the wrongly displayed page in the first time.
Except from this occurrence the template is displayed correctly.
