### ISSUE TITLE
Order of license icons

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#670]
It would be much easier for the user to get an overview of the different licenses of a Service, when, they were displayed in the same order as in the list you choose from. The order in this list reflects the openness of the licenses. In the moment there seems to be no order:
http://oerworldmap.graphthinking.com/resource/urn:uuid:c40ca1a8-3022-4d07-8d89-a0119285b401
it is the same on production, I think.

**Comment by trugwaldsaenger** [comment]
+1

**Comment by literarymachine** [comment]
No longer applicable in the new UI, closing.
