### ISSUE TITLE
Entities aren't found by clicking on tags on the pages of organisations etc

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#671]
http://oerworldmap.graphthinking.com/resource/?q=%22repository%22
This is the result of clicking on "repository" on this page:
http://oerworldmap.graphthinking.com/resource/urn:uuid:c40ca1a8-3022-4d07-8d89-a0119285b401
The other tag link works.

**Comment by trugwaldsaenger** [comment]
seems to work by now...

**Comment by karindr** [comment]
I tried it again on this page:
http://oerworldmap.graphthinking.com/resource/urn:uuid:c40ca1a8-3022-4d07-8d89-a0119285b401
If I click on the tag “oer” it works, but if I click on “repository” I get a view with no entries:
http://oerworldmap.graphthinking.com/resource/?q=%22repository%22
Maybe the problem only exists for tags witch are only mentioned once. I tried also students in the serlo column and library in the hbz column: Result: “Found 0 entities” witch is not correct.

**Comment by literarymachine** [comment]
Deployed to dev, see e.g. http://oerworldmap.graphthinking.com/resource/urn:uuid:c40ca1a8-3022-4d07-8d89-a0119285b401

**Comment by karindr** [comment]
OK. But look at this:
![image](https://cloud.githubusercontent.com/assets/18674205/16003216/d826f0fa-315b-11e6-8beb-d7924aae0617.png)
Clicking on the tag works fine:
![image](https://cloud.githubusercontent.com/assets/18674205/16003264/0880d892-315c-11e6-983e-69a1746271e8.png)
but again using the back button causes unexpected behavior. This page is shown instead of what is shown in the first screenshot:
![image](https://cloud.githubusercontent.com/assets/18674205/16003289/261a7d5e-315c-11e6-89cc-80b0cf4ed73b.png)

**Comment by literarymachine** [comment]
@j0hj0h another back-button weirdness.

**Comment by j0hj0h** [comment]
this back button weirdness should be fixed in d7539342f03fa6d3544acd821e520f1f23ac5c9c
