### ISSUE TITLE
Pin isn’t shown when location of organisation is entered

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#673]
The Pin should be in France, but only this part of the map is shown: 
 
![image](https://cloud.githubusercontent.com/assets/18674205/15705054/b5ae5c60-27ed-11e6-9191-e49749e1fa7d.png)

When page is reloaded the pin appears in France.
http://oerworldmap.graphthinking.com/resource/urn:uuid:d8f1b6ce-fc66-4763-b63e-831627019ea3

**Comment by j0hj0h** [comment]
So how does this happen? Cannot reproduce it ...

**Comment by karindr** [comment]
For a test I created a new organization and entered coordinates and the land and saved. The following screen is shown: The map without a pin in the US:
![image](https://cloud.githubusercontent.com/assets/18674205/15814737/d49e520e-2bc8-11e6-854b-6b89490477ec.png)
Reloading solves the problem and this part of the map is shown with the new pin:
![image](https://cloud.githubusercontent.com/assets/18674205/15814769/0d508ef0-2bc9-11e6-996d-bc09a6c140be.png)

**Comment by j0hj0h** [comment]
Allright, thanks for clarification.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
