### ISSUE TITLE
No fields for locating a story in template for stories

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#674]
On production there are these fields and therefore stories get pins on the map. In v1.1 there are no pins for stories (or I didn’t finde a way to get them).

**Comment by trugwaldsaenger** [comment]
@karindr Could you specify the fields you are refering to more precisely. The templates on production and on development look the same to me and I´m not aware that it is possible to locate stories...

**Comment by karindr** [comment]
Sorry, I mixed the template up.
I added an organization to my test story and now it has got a pin on the map.
