### ISSUE TITLE
Hashtag isn't shown for event

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#675]
http://oerworldmap.graphthinking.com/resource/urn:uuid:c34d6836-c60f-4387-a01d-43d65d2b9035
This event has got a hashtag, but it isn't shown. On production the hashtag is in the list, see for example:
https://oerworldmap.org/resource/urn:uuid:2d2fa244-acce-42ac-8ce7-ea4af5947b1f

**Comment by literarymachine** [comment]
Deployed to dev, see e.g. http://oerworldmap.graphthinking.com/resource/urn:uuid:c34d6836-c60f-4387-a01d-43d65d2b9035

**Comment by karindr** [comment]
OK
