### ISSUE TITLE
Country labels doesn’t disappear behind text columns

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#676]
… only behind the line and behind the little handle. 
![image](https://cloud.githubusercontent.com/assets/18674205/15707193/b2655d92-27f7-11e6-9fe9-0a59adb1c108.png)
(Nice bug ;)

**Comment by j0hj0h** [comment]
The popovers will go behind the columns again for now. They cannot be displayed in front easily. Cleanest solution would be to display them in different directions according to where the space is available. But this is not worse to spend time on before we switch the mapping library, as the new one might bring a solution natively.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
