### ISSUE TITLE
Sometimes service pages/columns aren’t shown

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#678]
Sometimes service pages/columns aren’t shown, see below. Clicking in the name of the service in the List highlights the name and the pin on the map, but the column for the service isn’t there.
![image](https://cloud.githubusercontent.com/assets/18674205/15736885/050301ac-28a3-11e6-9343-8ac76ec0fc3c.png)

**Comment by karindr** [comment]
Found the handle at the right side, clicking there the column appears. But, I think, not all users will take time to look for this solution.

**Comment by trugwaldsaenger** [comment]
Not reproducable for me at the moment. If I click on a an entry from the result list, the ressource view opens automatically.

**Comment by j0hj0h** [comment]
It happens when you have a collapsed detail column (you see the small arrow on the right to unfold it again) ... but the behaviour should be that in unfolds automatically when you go to another resource.

**Comment by literarymachine** [comment]
Deployed to http://oerworldmap.graphthinking.com/

**Comment by karindr** [comment]
OK
