### ISSUE TITLE
The pull down menu for audience isn’t shown completely at the right side

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#679]
See below:
![image](https://cloud.githubusercontent.com/assets/18674205/15737246/65881a1a-28a5-11e6-936d-e49f85ab14de.png)

**Comment by karindr** [comment]
Same for other pull down menus at this place, when the browser window is smaller:
![image](https://cloud.githubusercontent.com/assets/18674205/15737357/ea07182c-28a5-11e6-91e4-65467c51cc7c.png)
For subject menu also in a wide window.

**Comment by literarymachine** [comment]
Solved by new filter section layout.
