### ISSUE TITLE
Find organizations in input templates for services without having to use accent marks on characters

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#684]
You edit the data of a service for example and you want to add an organization to locate it on the map. To find the organizations in the list under “Provider” you have to enter the first characters. If there are accent marks above these characters and you don’t know how to get them on your keyboard it is sometime very hard to find the right organization for example “Délégation interministérielle pour l'éducation numérique en Afrique”. In my opinion it would be helpful to show "Délégation" also when “Dele” is entered. There are lots of possible accent marks in names of organizations.

Maybe it would also be useful for the search function?

**Comment by literarymachine** [comment]
See #605.

**Comment by philboeselager** [comment]
Work is included in branch [605-fortifyFuzzySearch](https://github.com/hbz/oerworldmap/tree/605-fortifyFuzzySearch).

**Comment by literarymachine** [comment]
@philboeselager: https://oerworldmap.org/resource/?q=Delegation is not working, but https://oerworldmap.org/resource/?q=Délégation is, although I recreated the index after merging #752.

**Comment by philboeselager** [comment]
Following https://github.com/hbz/oerworldmap/commit/49f581aeb9dadd5075856bafa2d09c92ea9a7c5e this doesn't seem to be a backend or at least not an Elasticsearch issue. @literarymachine Do you know of other possible reasons?

**Comment by literarymachine** [comment]
> https://oerworldmap.org/resource/?q=Delegation is not working

Interestingly, the back end side of this is now indeed working. Regarding the look up in the editing templates, this is a front end issue. Reassigning.

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1
