### ISSUE TITLE
Second-level typing for persons

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#686]
As an OER advocate/policy maker/researcher I would like to know what kind of people (in the sense of profession or background) the OER world map users are made of, so that I can see the development of special groups over time.

In order to do so, we should include a field to distinguis users into different groups. An initial scheme would be:
- Teachers
- Students
- Librarians
- Developers
- Policy maker
- advocates
- researcher

**Comment by philboeselager** [comment]
To be realized as a flat SKOS vocabulatory.
Should be selectable as tags.

**Comment by acka47** [comment]
See also https://github.com/dcmi/LRMI_Vocabs/blob/master/educationalAudienceRole.ttl

**Comment by drrobertfarrow** [comment]
I agree that tagging makes more sense. When we asked people to self-describe their role, the majority picked more than one option.

**Comment by drrobertfarrow** [comment]
To Jan's list I would add:
- instructional designer
- manager
- oer producer

**Comment by acka47** [comment]
So we currently have mentioned in this issue:

- teacher
- student
- librarian
- software developer
- policy maker
- advocate
- researcher
- instructional designer
- manager
- oer producer

 Furthermore, I referred to the educationalAudienceRole vocabulary that is intended for indicating the audience of an educational resource. As it serves another use case, the concepts mentioned don't all fit for our purpose. Nonetheless, I name them for sake of completeness:

- administrator ("A trainer or educator with administrative authority and responsibility.")
- general public
- mentor ("Someone who advises, trains, supports, and/or guides.")
- parent ("A father, mother, or legal guardian.")
- peerTutor ("The peer learner serving as tutor of another learner.")
- professional ("Someone already practicing a profession; an industry partner, or professional development trainer.")
- student
- teacher

We already have "student" and "teacher". For our purpose definitely not fitting is "general public". "Mentor" and "peer tutor" can also be ignored.

We might think about adding something like "administrator" and "professional" as well as maybe even "parent" to the list above.

**Comment by trugwaldsaenger** [comment]
Two points on this issue:

1) Do we all agree that - divergent from the comments above - the types should be included as a second level of the navigation and not as tags?
2) The list is already quite long. I guess we should consolidate it and generate a list which is as short as possible. It would be interesting to get some design proposals, how a "second level navigation" could look like and how many subcategories could be implemented, without getting to crowded.

**Comment by acka47** [comment]
I agree regarding 1). (The "tagging" might have been more about the possibility to add more than one and not about the possibility to define your own tag. )

Regarding 2.):
- What is the maximum number of elements for a practicable list? I think seven should be ok. 
- I think we don't need remove "advocate" as this is quite unspecific and probably most people will choose this.
- Couldn't "administrator" be used as a broad class which covers "policy maker", "manager" and "instructional designer"? 
- If we enable a feature on the world map for curating a collection of OER produced by yourself then we wouldn't need a type "oer producer" as this gets evident by the fact that there is a list of OER. 
- Having said this, maybe this could suffice: teacher, student, librarian, software developer, researcher, administrator, professional

**Comment by trugwaldsaenger** [comment]
Thanks for pushing this forward @acka47!

> What is the maximum number of elements for a practicable list? I think seven should be ok.
Agreed, we might go up until 9, but I would prefer 7 as well.
>I think we don't need remove "advocate" as this is quite unspecific and probably most people will choose this.
I have to think about this. You are right, that everyone could call himself an OER Advocate, nevertheless, I`m not sure that most people really do. Sometimes advocates are similar to lobbyists and I guess, these would have similar competences and interests like policy makers.
>Couldn't "administrator" be used as a broad class which covers "policy maker", "manager" and "instructional designer"?
Good idea to put these together. But my first association connected to "administrator" is more a technical one. So this might be easy to missunderstand. @drrobertfarrow: What is the mothertongue perspective on this?
>If we enable a feature on the world map for curating a collection of OER produced by yourself then we wouldn't need a type "oer producer" as this gets evident by the fact that there is a list of OER.
Good idea to reduce the number of subcategories. But I`m not sure if it will work in practise. We do not know yet when we will include the personal lists of OER. Also it is possible, that people will not use it... 
>Having said this, maybe this could suffice: teacher, student, librarian, software developer, researcher, administrator, professional
- teacher: *aggreed*, from a combination with the new field "educational sector" you can tell, if someone is a School teacher, or a University teacher.
- student: *agreed*
- librarian: *agreed*
- software developer: *agreed*
- researcher:*agreed*, 
- administrator:*TBC- see above*
- professional: This seems quite abstract to me. Probably any of the mentioned groups would consider themselves as professionals, wouldn`t they?

**Comment by trugwaldsaenger** [comment]
Looking for examples to orientate on:

- http://www.oeconsortium.org/directory/

**Comment by trugwaldsaenger** [comment]
@acka47 Do we include a category "other". If yes, we would not need to finalise the list and could start with the personas already identified...

**Comment by drrobertfarrow** [comment]
I agree that 'professional' is rather abstract and doesn't really work as a category since it is not exclusive.

I think we need to keep 'instructional designer' as this is a common role, especially in the USA.  Awareness of OER is sometimes higher among this group than faculty.  There can be some overlap here with 'software designer' but they are not the same thing.

'Educator' may be a more preferable term than 'teacher', not only because it applies more readily to all education levels but also because is has less didactic/authoritarian implications..

I agree it might make sense to have an 'other' option too - this would also work with out combined 'top-down' categories + 'bottom-up' folksonomy.

**Comment by acka47** [comment]
> @acka47 Do we include a sub-category "other". If yes, we would not need to finalise the list and could start with the personas already identified...

I don't like "Miscellaneous" classes in RDF. Should adding a subtype be mandatory? If we make it optional to add a subtype, people could just leave it blank when nothing fits their role.

**Comment by trugwaldsaenger** [comment]
> I don't like "Miscellaneous" classes in RDF.

I`m not surprised. I don`t think that the subtype must be mandatory, so making it optional and leaving it blank, when nothing fits is OK for me.

**Comment by acka47** [comment]
@trugwaldsaenger suggested to copare our ist with the list of personas reated at the OERCamp17 n Cologne. See the session pad at http://pad.o-e-r.de/p/oercamp17-west-A4-Raum321

**Comment by acka47** [comment]
http://pad.o-e-r.de/p/oercamp17-west-A4-Raum321 is not very helpful and the collaborative pptx – which probably had some more personas – isn't available anymore.

I propose to start with a list consisting of the following:

- educator (I followed @drrobertfarrow's suggestion to call it that instead of "teacher") 
- student
- librarian
- software developer
- researcher
- instructional designer
- manager

**Comment by literarymachine** [comment]
@acka47 SKOS version based on Google Doc here: https://github.com/hbz/oerworldmap-ui/blob/1545-SecondLevelNavigation/src/json/persons.json

**Comment by karindr** [comment]
I think we could close this issue because we have a second level by now. Closing.
