### ISSUE TITLE
Events are not counted in static chart for language

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#687]
http://oerworldmap.graphthinking.com/aggregation/
In the data on this server there are several events with languages assigned to their data sets, but in the language chart only the services are counted. If this is the intention the title should be “Services by Language”. But I would prefer if the events were included.

**Comment by literarymachine** [comment]
> but in the language chart only the services are counted

It is (and has been) indeed "Services by Language"; will fix the label. As for including events, we still don't have any definitions which statistics to generate and what they include - the current charts were very ad hoc just so something is there. I suggest to discuss this at the team meeting next week.

**Comment by trugwaldsaenger** [comment]
+1
