### ISSUE TITLE
process for saving persons is not finished correctly 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#689]
Normally, when I save a data set (e.g. an organization or a service) I receive first a temporally message ("created" or "updated"). Then the input templates closes automatically and the new entry is displayed.

This does not work for persons. When saving the data of a person, no temporally message is shown and the templates do not close automatically.

**Comment by literarymachine** [comment]
> This does not work for persons. When saving the data of a person, no temporally message is shown and the templates do not close automatically.

Can reproduce this for persons; creating person pages will be a different process (included in the registration process) with the next release so I suggest we resolve this with the deployment of the next release next week.

**Comment by trugwaldsaenger** [comment]
OK!

**Comment by literarymachine** [comment]
Fixed by #696
