### ISSUE TITLE
Show information on champions on landing page

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#7]
As an OER actor I want to see who is the OER World Map Champion in my country, so that I can get in touch with her, or – if there is no champion available yet – offer to become a national champion myself.

**Comment by acka47** [comment]
One way to go kight be: By clicking on a country/continent (or by mouse-over), an interested OER actor can see the name and contact details of the national/continental OER World Map champion.

**Comment by acka47** [comment]
Part of epic #11.

**Comment by literarymachine** [comment]
Country champions should be displayed on the individual country pages. @trugwaldsaenger and @acka47 are going to complete the information to at least include `name`, `email`. Ideallythere should be  an `image` and a `location` with a `streetAddress`.
