### ISSUE TITLE
Add share/export button to single resource view and result lists

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#710]
Decison from 2016-Q2 team meeting was to have one dropdown with export and sharing options. Goal is to start with those which are easy to implement:
- share on Twitter
- share on Facebook
- copy permalink
- export as json
- print (with print css)

More complex options:
- export as PDF
- export as CSV

**Comment by j0hj0h** [comment]
Also see #600

**Comment by formimkontext** [comment]
Layout showing edit, delete and dropdown with export and sharing options for individual entries and result list.

![20160411-oer-share-export-1](https://cloud.githubusercontent.com/assets/15141949/18126969/f453b370-6f7d-11e6-8190-8ac16440a014.jpg)

**Comment by j0hj0h** [comment]
If the resource or resource list contains events export to calendar is added

**Comment by j0hj0h** [comment]
oEmbed (http://oembed.com) seems to be worse a look in connection to this

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Service#urn:uuid:d65513c8-c745-4480-89d8-3fe00f7d7f46

Note the gear icons in the upper right corner of the individual resource and next to "entries shown" in the resource listing.

**Comment by karindr** [comment]
All seems to work fine except the facebook export, I get only links to main page oerworldmap.org there. twitter and mail works with the link to the specific page.
The delete option is only shown to administrators, isn't it?

**Comment by literarymachine** [comment]
> All seems to work fine except the facebook export, I get only links to main page oerworldmap.org there.

The problem here is that you probably postet a link from beta that does not exist on production (where the link points), and Facebook checks that.

> The delete option is only shown to administrators, isn't it?

Yes!

**Comment by karindr** [comment]
Then +1.
