### ISSUE TITLE
Sometimes country labels don’t show information

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#716]
Look at this: When I am in the country view for France for example, the label shown for Spain shows no entries although there are entries.
![image](https://cloud.githubusercontent.com/assets/18674205/16408890/2414f14a-3d1b-11e6-8f82-661c15cdc8b0.png) 
These are only show when I have ‘visited’ Spain, see below. Maybe it is a browser connected issue, because it works well for Jan. I’m using Chrome.
![image](https://cloud.githubusercontent.com/assets/18674205/16408921/486e08c4-3d1b-11e6-9022-1e51c0f07bf8.png)

**Comment by literarymachine** [comment]
Interesting issue. When visiting https://oerworldmap.org/country/fr directly, indeed only the aggregation (the data needed for the country labels) for France is loaded. When navigating to France from the [landing page](https://oerworldmap.org), the global aggregation is available. Will try to fix this by embedding the global aggregation in the individual country views.

**Comment by literarymachine** [comment]
Deployed to production, see e.g. https://oerworldmap.org/country/fr and hover over e.g. Spain.
