### ISSUE TITLE
title in browser tab does not change

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#717]
Look at this I am in Switzerland and in the browser tab still stands United Kingdom:
![image](https://cloud.githubusercontent.com/assets/18674205/16409087/19611df4-3d1c-11e6-96dc-e515e0187560.png)

**Comment by j0hj0h** [comment]
Same as #714

**Comment by literarymachine** [comment]
On production, see e.g. https://oerworldmap.org/country/ch and click on France.

**Comment by karindr** [comment]
+1
