### ISSUE TITLE
Some logos or pictures for country champions seems to be lost

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#718]
I don't know exactly, but I think there has been a picture for the Swiss champion.
![image](https://cloud.githubusercontent.com/assets/18674205/16409129/529ebcb6-3d1c-11e6-876b-e8faa9ec399b.png)
Same for United Kingdom, Germany works. it seems to be a problem for special references, because when I follow the 'open picture in a new tab' link I get here:
![image](https://cloud.githubusercontent.com/assets/18674205/16409296/0cded426-3d1d-11e6-97e5-2df9e6e36ba7.png)

**Comment by literarymachine** [comment]
The service @acka47 used to host the images has been discontinued, see #572. Until we have the file upload enabled in the UI, the images should be uploaded to `public/images` here on GitHub. Afterwards, the links will have to be corrected.

**Comment by karindr** [comment]
Is there any possibility to get some information about the lost pictures? The people gave us the possibility to use these pictures an now they are lost. Do we have to ask them wich picture was used? This issue is related also to pictures used in stories. You can't guess what picture was shown there.

Shouldn't we include alt information for pictures in general for knowing what has been there, wenn the url changes and also for accessibility?.

**Comment by literarymachine** [comment]
> Is there any possibility to get some information about the lost pictures?

AFAIK only those images that were hosted on copy.com are affected; this query should list all of them:

https://oerworldmap.org/resource/?q=about.image:*copy.com*

>  The people gave us the possibility to use these pictures an now they are lost.

No, they are not lost. @acka47 made them available, see https://github.com/hbz/oerworldmap/issues/572#issuecomment-220119813. I uploaded them to `public/images` which makes them available via e.g. https://oerworldmap.org/assets/images/avu.png

> Do we have to ask them wich picture was used? This issue is related also to pictures used in stories. You can't guess what picture was shown there.

If you edit the story, you can see the old URL in the `image` field. In that URL you can identify the name of the file that was used. See e.g. the [African Virtual University](https://beta.oerworldmap.org/resource/?q=about.image:*copy.com*#urn:uuid:7067ff60-77eb-11e5-9f9f-c48e8ff4ea31) on beta, where I fixed the link.

> Shouldn't we include alt information for pictures in general for knowing what has been there, wenn the url changes and also for accessibility?

Definitely.

The UI for uploading images did not make it into `v1.1`. I suggest that in cases where images need to be added, we upload them here on GitHub to `public/images`.

**Comment by karindr** [comment]
Ok, I will adjust the links on monday.

**Comment by karindr** [comment]
@literarymachine, could you please make it possible for me to login on beta . Without this I cant see the example link and can't start inserting the new links.

**Comment by literarymachine** [comment]
@karindr please just create an account on beta for your work email address.

**Comment by karindr** [comment]
OK, I can work on beta now, thanks.

**Comment by karindr** [comment]
Sorry, didn't want to close this issue.

**Comment by karindr** [comment]
There is another kind of lost image/broken link:
https://photos.google.com/album/AF1QipO3vC_KUCjmKjueCOIaGXCPkT_pAco8RZADWzIZ/photo/AF1QipOWG1Ftzns4nbuNOpGBOUBP_YBzyHpqeJ50Efd-
https://oerworldmap.org/resource/?q=&filter.about.%40type=Article#urn:uuid:72d250f7-ecba-4b29-a7bb-110145fce75a
Maybe the author moved/deleted the image? Or is it possible that the end of the link was cut?

**Comment by literarymachine** [comment]
> Maybe the author moved/deleted the image?

Absolutely possible! Since I have never edited any stories, I don't know where that link originated from.

>  Or is it possible that the end of the link was cut?

We do not automatically truncate links.

**Comment by karindr** [comment]
OK, I will ask the author.

**Comment by karindr** [comment]
I changed all links to copy.com, as seen here, only one is left:
https://oerworldmap.org/resource/?q=about.image:*copy.com*
Can't change this, see #742.
