### ISSUE TITLE
Going back to map with search area and not to welcome screen

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#719]
When I close a list with the little ‘>’-button:
 ![image](https://cloud.githubusercontent.com/assets/18674205/16409890/1e928444-3d20-11e6-9df8-9c4bca45b0e0.png)
I expect the list to go and to find the empty map. But I get the welcome screen back that is not a logic experience to me. Surely I can click ‘Don’t show me again’, but I think there should be the empty map to go on searching.
![image](https://cloud.githubusercontent.com/assets/18674205/16409984/93baef40-3d20-11e6-90c1-7c845d49062c.png)

**Comment by literarymachine** [comment]
No longer applies due to new UI, closing.
