### ISSUE TITLE
hide country champion field

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#731]
It seems as if it is possible for registered users to make themselves countrychampions:
https://oerworldmap.org/resource/urn:uuid:40667021-0003-4f06-80b2-62c90dcabc28
In order to avoid this we should hide the country champion field.

**Comment by literarymachine** [comment]
If we do this, nobody (not even Admins) will be able to set a country champion. We don't have individual field access control. My suggestion would be to see if people actually do this and react if things go wrong.

**Comment by literarymachine** [comment]
I mean, they obviously do this. But maybe we should contact them personally then and tell them what it means and if they are sure. Could be a way to get a bigger community of editors!

**Comment by trugwaldsaenger** [comment]
> If we do this, nobody (not even Admins) will be able to set a country champion.
Would it be possible for admins to set a country champion without using the templates? Or would it be completly impossible?

> Could be a way to get a bigger community of editors!
Making yourself a country champion does not give you automatically editing rights, does it? I would prefer to keep both roles (country champions and editors) seperate and not mix them up...

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org

**Comment by literarymachine** [comment]
> Making yourself a country champion does not give you automatically editing rights, does it? I would prefer to keep both roles (country champions and editors) seperate and not mix them up...

This is the way it is right now; being a country champion is a status reflected in the profile, being an editor is a completely separate question of permissions.

**Comment by trugwaldsaenger** [comment]
Country champion field is hidden now on beta for a "normal" user and still visible for administrators! +1!
