### ISSUE TITLE
Refine layout of "Forgot Password?" mail

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#733]
New passwords are received by mail. In the current mail the password is followed directly by a point marking the end of the sentence. It is pretty difficult to copy the password without the point. If you do not notice the point you will not get access to the side. 

I would propose to use three separate lines:

Your password has been reset to: 

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Please use it to log in once and change it immediately.

**Comment by literarymachine** [comment]
:+1:
