### ISSUE TITLE
URL label is hovering over template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#740]
Entering data I saw this:
![image](https://cloud.githubusercontent.com/assets/18674205/16557688/93346356-41e1-11e6-869e-5e474dc2b2db.png)
There is a label with the entered url of the logo, which is staying at it's place also when the underlying template is being moved. I think it should disappear.

**Comment by literarymachine** [comment]
@j0hj0h I think we can simply solve this for now by setting `autocomplete="off"` at least for URL inputs.

**Comment by j0hj0h** [comment]
This is not a bug of our frontend, but from the browser. I disabled autocompletion for all fields now. Let me know, if you'd prefer to have them in again ...

**Comment by literarymachine** [comment]
On beta

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
OK. +1
