### ISSUE TITLE
Following strange link causes endless loading

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#742]
![image](https://cloud.githubusercontent.com/assets/18674205/16578322/1fe08cd6-429a-11e6-9223-3a784eeef10a.png)
There is a strange looking link in the line for 'Project lead in'. If clicked it causes endless loading.

**Comment by karindr** [comment]
This is the link to the resource:
https://oerworldmap.org/country/za#urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927

There is another strange behavior of this resource. When I change the broken link to the image to 
https://oerworldmap.org/assets/images/saide.jpg (which works fine in the browser), there es an error message and after displaying this message the resource can't be saved again. 

Error message:

com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: object has missing required properties (["name"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Action"}
    instance: {"pointer":"/agentIn/0"}
    domain: "validation"
    keyword: "required"
    required: ["name"]
    missing: ["name"]
---  END MESSAGES  ---
{
  "image" : "https://copy.com/thumbs_public/1BuhEzdFlIXpBWlI/saide.jpg?size=1024",
  "@type" : "Organization",
  "provides" : [ {
    "audience" : [ {
      "@type" : "Concept",
      "name" : [ {
        "@value" : "Primary education or first stage of basic education",
        "@language" : "en"
      } ],
      "@id" : "https://w3id.org/isced/1997/level1"
    } ],
    "availableChannel" : [ {
      "serviceUrl" : "http://www.africanstorybook.org/",
      "availableLanguage" : [ "en" ]
    } ],
    "provider" : [ {
      "@type" : "Organization",
      "name" : [ {
        "@value" : "South African Institute of Distance Education",
        "@language" : "en"
      } ],
      "@id" : "urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927"
    } ],
    "@type" : "Service",
    "about" : [ {
      "@type" : "Concept",
      "name" : [ {
        "@value" : "Basic programmes and qualifications",
        "@language" : "en"
      } ],
      "@id" : "https://w3id.org/class/esc/n001"
    }, {
      "@type" : "Concept",
      "name" : [ {
        "@value" : "Generic programmes and qualifications",
        "@language" : "en"
      } ],
      "@id" : "https://w3id.org/class/esc/n00"
    }, {
      "@type" : "Concept",
      "name" : [ {
        "@value" : "Literacy and numeracy",
        "@language" : "en"
      } ],
      "@id" : "https://w3id.org/class/esc/n002"
    } ],
    "name" : [ {
      "@value" : "African Storybook Project",
      "@language" : "en"
    } ],
    "description" : [ {
      "@value" : "The Project aims to address the shortage of books in local African languages for early reading. The main reason why there are so few stories in local African languages is that it is not cost effective to publish and print stories for reading in languages that have a small readership. But if the stories are on the internet, and also can be translated by people themselves into local languages, the challenge can be overcome. The project thus created a website for people who work with children in African contexts. The purpose of the African Storybook Project (ASP) website is to provide stories in African languages as well as in English for young children as they are learning to read. This website is for parents and people working with children (such as teachers, librarians, community workers) in African contexts.",
      "@language" : "en"
    } ],
    "alternateName" : [ {
      "@value" : "ASP",
      "@language" : "en"
    } ],
    "@id" : "urn:uuid:0c066016-4807-11e5-8ec6-54ee7558c81f",
    "email" : "Africanstorybook@saide.org.za",
    "startDate" : "2013",
    "sameAs" : [ "https://twitter.com/africastorybook", "http://www.flickr.com/photos/106375792@N02/", "https://www.facebook.com/africanstorybookorg" ]
  } ],
  "agentIn" : [ {
    "agent" : [ {
      "@type" : "Organization",
      "name" : [ {
        "@value" : "South African Institute of Distance Education",
        "@language" : "en"
      } ],
      "@id" : "urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927"
    } ],
    "@id" : "urn:uuid:3e6fe134-4268-11e5-b186-54ee7558c81f"
  } ],
  "name" : [ {
    "@value" : "South African Institute of Distance Education",
    "@language" : "en"
  } ],
  "description" : [ {
    "@value" : "Saide, the South African Institute for Distance Education, is a non-governmental organization based in Johannesburg but conducting projects throughout South Africa and sub-Saharan Africa. Saide's task is to contribute to the development of new models of open and distance education practice, that accord with and take forward the values, principles, and goals of the evolving education systems in the Southern African region. It has also paid particular attention to the appropriate use of technology in education and most recently established a Kenya-based initiative, OER Africa, to promote the development and sharing of OER on the African continent.",
    "@language" : "en"
  } ],
  "alternateName" : [ {
    "@value" : "Saide",
    "@language" : "en"
  } ],
  "location" : {
    "geo" : {
      "lon" : 28.0373617,
      "lat" : -26.1905815
    },
    "address" : {
      "addressCountry" : "ZA",
      "streetAddress" : "4th Floor, Rennie House, 19 Ameshoff Street",
      "postalCode" : 2017,
      "addressLocality" : "Johannesburg, Braamfontein",
      "addressRegion" : "Gauteng"
    }
  },
  "@id" : "urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927",
  "@context" : "http://schema.org/",
  "email" : "info@saide.org.za",
  "url" : "http://www.saide.org.za/"
}

**Comment by literarymachine** [comment]
The Problem here is that the resource

https://oerworldmap.org/resource/urn:uuid:4d3f95c2-419d-11e5-aa5f-001999ac7927

references a non-existent resource as "Project lead in":

https://oerworldmap.org/resource/urn:uuid:3e6fe134-4268-11e5-b186-54ee7558c81f

I don't know how this happened, and there is no way to change this using the edit form because we simplified it a while ago and removed setting the `agent` link in this direction. I fixed the entry manually, you should be able to update the image link now.

**Comment by karindr** [comment]
Done.

Should I close such issues?

**Comment by literarymachine** [comment]
> Should I close such issues?

Yes, please. I made a more general technical issue related to this, see #743.
