### ISSUE TITLE
Display error in app on 404

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#743]
When following an invalid link (404) from within the app, no error is displayed. The loading spinner simply does not go away. See #742.

**Comment by j0hj0h** [comment]
Also applies to other http errors.

**Comment by literarymachine** [comment]
Error documents are currently configured as simple HTML strings in https://github.com/hbz/oerworldmap/blob/master/data/permissions/.system. Feel free to extend e.g. for `503` (when the app behind the proxy is down, e.g. for maintenance) and add any wrapping HTML or attributes such as `data-app="to-modal-on-load"` you may need.

**Comment by literarymachine** [comment]
You have to add `ProxyErrorOverride On` at the top to take control of e.g. 404 errors thrown by the app.

**Comment by j0hj0h** [comment]
As I thought it would be good to see the requested URL in the error modal I continued handling it inside the app behaviour.
