### ISSUE TITLE
Order subjects on service profile hierarchical

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#745]
![subjects](https://cloud.githubusercontent.com/assets/6639965/16586706/79c91e48-42c7-11e6-8365-4eab2a44760e.JPG)
Subjects should be ordered according to their hierarchy. In the example I guess it should be:
- Arts and humanities
- Languages
- Language acquisition
- Language acquistion\u2013 German

**Comment by karindr** [comment]
This would be a really useful enhancement! See also #626.

**Comment by literarymachine** [comment]
Duplicate of #626, closing.
