### ISSUE TITLE
Add license filter

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#746]
Story: As a user, looking for material with a special license, I would like to filter services according to the used license.

**Comment by literarymachine** [comment]
On beta, see

https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Service

and "Services by License" on

https://beta.oerworldmap.org/aggregation/

**Comment by karindr** [comment]
Looks good.

In this context it would be great to have the license icons for a service to be displayed in the order displayed in the template and in the filter, see #670.

**Comment by acka47** [comment]
+1
