### ISSUE TITLE
(Technical) workflow for uploading pictures to our server

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#747]
When I want to upload pictures to our server, is there somewhere a description what has to be done?

Today I uploaded two pictures (mediaprtal.jpg and Karin-Driesen-130.jpg) to github to oerworldmap/public/images/. Is this right or do I have to make a new branch first?

I tried to link to them from oerworldmap.org by using this link: 
https://oerworldmap.org/assets/images/Karin-Driesen-130.jpg

This link works for the other pictures in the directory, but not for the new ones. Do they have to be moved somewhere else? Do they have to be deployed in some way? What do I have to do?

**Comment by literarymachine** [comment]
> Is this right or do I have to make a new branch first?

As when editing markdown, please do not commit directly to the master branch but create a branch and open a pull request.

> Do they have to be moved somewhere else? Do they have to be deployed in some way?

Uploading the images to GitHub does not automatically make them available on our server, so yes they have to be deployed.

> What do I have to do?

Open a pull request and wait for deployment. I know this is not really ideal; I am thinking about creating a oerworldmap-assets for our images where they could be uploaded and directly accessed via GitHub. This could be an interim solution or even actually a replacement for #647. Thoughts?

**Comment by karindr** [comment]
It would be really helpful to have a possibility to upload images to our server and have them be directly available. Sometimes a visitor/author sends us images to put them on the map. It is not very satisfying for the visitor if it needs some days to be displayed. In addition to this it doesn’t make sense to have more than one person to be involved on our side in my opinion.

And connected with this issue: Look here 
https://oerworldmap.org/resource/?q=karin#urn:uuid:701c2bae-c918-45af-85dd-7805ad83ccab 
The width of the picture is 130 pixel but it is displayed much larger. Sure I can upload the picture with greater width, but shouldn’t it be displayed with its with unless it is too big? Photos and logos become blurry like this.

**Comment by acka47** [comment]
On 2016-07-16 @literarymachine provided a workflow via mail:

> Hi all,

> for the time being, I established the following file upload workflow:
- [upload] your file(s)
- commit directly to the [assets] branch
- use the URL provided [git content delivery network], e.g.
https://cdn.gitcdn.link/cdn/hbz/oerworldmap/assets/public/images/Karin-Driesen-130.jpg

>This get's rid of unnecessary deployments to our production server and
makes the images directly available.

[upload]: https://github.com/hbz/oerworldmap/upload/assets/public/images
[assets]: https://github.com/hbz/oerworldmap/tree/assets
[git content delivery network]: https://cdn.gitcdn.link/

**Comment by acka47** [comment]
I guess we can close this issue?

**Comment by acka47** [comment]
Closing.

**Comment by trugwaldsaenger** [comment]
I think we should add this information in a documentation or manual or likewise. I added the tag "manual/documentation", so that we can easily find it, when we start working on the manual.
