### ISSUE TITLE
Get consent from editors for CC licensing

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#748]
Currently, editors don't declare their consent for publishing their contributions under CC licenses. This is especially problematic for stories and the associated image.

This is – for example – how Wikipedia is prompting people to agree with the license conditions after editing: 

![20160706_wikipedia-licensing-consent-example](https://cloud.githubusercontent.com/assets/160292/16612347/cf053096-4366-11e6-9a0c-3fd2ee26074c.png)

(BTW, I added the OER World Map to https://en.wikipedia.org/wiki/Open_educational_resources. Feel free to improve it.)

**Comment by karindr** [comment]
In addition to this I don’t know if we have to make it possible to have a line under the pictures to write the source or author under the picture.
It makes a difference if we have the images on our server and on the other hand ‘frame’ pictures by referring to the url. Is this right?

**Comment by acka47** [comment]
Task for #628.

**Comment by acka47** [comment]
This is how it looks in wikidata which is more akin to the world map:

![save-wikidata](https://cloud.githubusercontent.com/assets/160292/24006583/88ef933a-0a6c-11e7-8a6b-5194ad9a56b0.png)

**Comment by acka47** [comment]
From #1069 (duplicate): 

Depends on #1068 .

- [ ] Rename "Save" button to "Publish"
- [ ] Add check box with something like "I accept the Terms & Conditions" next to publish button.

**Comment by acka47** [comment]
I think the notice should be coupled more with the publication button. I suggest moving the "publish" button into the frame with the license notice.

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
+1 It's alright for now, though looks kind of buggy. Would be great if @j0hj0h could improve it at some point.
