### ISSUE TITLE
'Gost picture' instead of question mark for country champion without uploaded picture

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#749]
At the moment for no country champion and for country champion without a own picture there is the same sign: the picture with the white question mark. It would be clearer to have a picture with a white silhouette for example for the champion without own picture. There will be always people who don’t want to upload a picture.

Maybe it would useful to install this feature for all person, in case we will have a comment or like function and want to show the pictures some day.

**Comment by acka47** [comment]
Example: https://oerworldmap.org/country/mx

**Comment by literarymachine** [comment]
If I understand @karindr correctly, this is not about changing the ?-image for countries _without_ champions, but the image of countries _with_ champions that have no profile picture.

Example: https://oerworldmap.org/country/GR

**Comment by acka47** [comment]
That's right and makes sense.

**Comment by formimkontext** [comment]
I think in this case it should be shown the icon we are using for persons.
![20160802-ghost-picture-cc](https://cloud.githubusercontent.com/assets/15141949/17332996/085110ac-58d1-11e6-8c39-6deee14d3647.jpg)

**Comment by karindr** [comment]
This would be fine.
