### ISSUE TITLE
'contact us' leads to 'page not found'

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#750]
On the FAQ page there are several links 'contact us' (code as shown below) which lead to a 'page not found', both in firefox and in chrome. Is this a setting issue or is it a bug? The links 'info@....org' on the Contribute page work fine for my combination of browser and mail client. 

'## What does it mean to become a country champion?
Country champions help to map the OER world by country – gathering data, assuring its quality and raising awareness of the project. Check out our [blog post](https://oerworldmap.wordpress.com/2015/04/17/what-does-it-mean-to-become-a-country-champion/) for more information about the country champion network. If you are interested in acting as champion for your country, please do not hesitate to [contact us](https://oerworldmap.org/info@oerworldmap.org).'

**Comment by literarymachine** [comment]
On beta: https://beta.oerworldmap.org/FAQ

**Comment by karindr** [comment]
+1
