### ISSUE TITLE
Make extended filter section more easy to use

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#751]
If you want to search using the included tags, this is quite difficult to do. If you enter an empty query, the extended filter section does not show up. If you include some search term, the extended filter section (including the tag-filter) shows up, but is limited to the search result. I managed to use the tags by serching for `*`. The search results included all data, therefore it was also possible to get a list of all existing tags. We should make the use of the extended filter section more easy, either by allowing to enter an empty query or by allowing to collapse/fold out the section explicitly (e.g. by including a button "extended search")

**Comment by trugwaldsaenger** [comment]
Since we are using tags more often now, we should improve searching with tags as well. One easy to realize solution would be to display the tag-filter constantly. I checked it and it is available for all data types. The only thing is that the tag filter probably does not fit into one row, so that the slim look of the filter section would be affected. I see three options to react to this:

1. accepting, that the tag filter appears in the second row
1. exchange the country filter by the tag filter, since the country filter can be activated by clicking on the map as well
1. add a tag cloud to the filter section

**Comment by karindr** [comment]
In my opinion the first option is a good solution. The tags should become more prominent in searching right from the start.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by acka47** [comment]
The current solution with both tag and country filter in the first row (only showing the icons) is ok for me. +1

**Comment by karindr** [comment]
I would prefer the written solution.
+1

**Comment by literarymachine** [comment]
Reopening because currently JSON is leaking into the typeahead when using up/down keys to navigate selections.

![screenshot from 2016-10-31 14-59-10](https://cloud.githubusercontent.com/assets/149825/19856638/a404d46c-9f7a-11e6-8986-9aabf6b88a62.png)

**Comment by literarymachine** [comment]
> Reopening because currently JSON is leaking into the typeahead when using up/down keys to navigate selections.

Fixed in the new UI, closing.
