### ISSUE TITLE
Use more dedicated icons in "Profiles elsewhere"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#758]
For ORCID, you aren't supposed to change the colour of the icon (it's green), though. See https://orcid.org/trademark-and-id-display-guidelines.

**Comment by literarymachine** [comment]
> You aren't supposed to change the colour of the icon (it's green), though.

IMHO this would be a reason to not use it then. What do you think @formimkontext and @j0hj0h?

**Comment by j0hj0h** [comment]
I'd say that using the icon in our text color doesn't violate their guidelines. They offer a black and white version and as all our text is dark blue this actually is our black.

**Comment by acka47** [comment]
Dark blue is the new black. ;-) Ok, then. We can go ahead and add this.

**Comment by j0hj0h** [comment]
Moved it to refactoring. Currently all our icons are from font awesome. They don't provide an icon for orcid ... as we might switch to a general solution to use additional icons during refactoring we will consider this later.

**Comment by acka47** [comment]
I added some links to wikidata, see e.g. , and will try to automatically add some more. We should add a dedicated logo for wikidata as well.

Here is a wikidata logo without the name: https://commons.wikimedia.org/wiki/File:Wikidata-logo.svg

**Comment by acka47** [comment]
A logo for GitHub is also missing. Just noticed it when setting a link to my profile on GitHub at https://oerworldmap.org/resource/urn:uuid:1fc889ad-28eb-496d-ad6a-3020b1380850

**Comment by formimkontext** [comment]
See #829

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/58fa7420e64d64370dfa44102ae22c3a397013d7
