### ISSUE TITLE
Enable internationalization and localization of website by third parties

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#761]
We received a request by someone who wants to translate the site into his native language:

> I am writing this letter to let you know that as a Country Champion I would like to Translate OER World Map web site pages into my native language Bengali

I guess all the stuff that needs to be translated is in these three places:
- [static pages](https://github.com/hbz/oerworldmap/tree/master/public/pages) about, faq, contribute, imprint
- labels.properties
- description.properties

Did I miss something? Anyway, how should people translate this? Just by providing the same files in their language? 

We probably should start looking at localization and internationalization platforms. There are lots of them. Here are ~~two~~  three that are open source and look promising:
- [Serge](https://serge.io/) by Evernote
- Zanata: http://zanata.org/
- http://pootle.translatehouse.org/

**Comment by literarymachine** [comment]
> Did I miss something?

- email.properties
- messages.properties

It should also be noted that especially in the front end there are a couple of places where there currently are hard coded English strings. It is going to take a while to identify all those places, but the offer to translate the UI is a good opportunity to do so.

**Comment by literarymachine** [comment]
> - Serge by Evernote
> - Zanata: http://zanata.org/

Both support Java properties files, which we need. Zanata might be easier to make accessible to authors because it is web based.

**Comment by acka47** [comment]
http://pootle.translatehouse.org/ also supports Java properties files. It has an online editor and enables people to work offline which is good for people without steady internet access.

**Comment by acka47** [comment]
Just read an [article about crowdsourced internationalization for the wire app](https://medium.com/wire-news/4-lessons-from-crowdsourcing-translations-at-wire-6fac0780ad50). Quite interesting also for our context. They use the [CrowdIn](https://crowdin.com/) for managing the translations. CrowdIn obviously gives free accounts for open source projects so it is also an option for the word map. (Also, we might need some T-Shirts. :wink:)

**Comment by trugwaldsaenger** [comment]
OK, lessons learned from Wire: Start early and provide T-Shirts! How do we proceed. I guess deciding on the used platform will be one of the next steps. Maybe we should put down our requirements for the platform in a Wiki-table?

By the way: The user story mentions a translation to Bengali. I guess we should start with German and then continue with Spanish. After we learned how to run the process we can move further and start some crowd sourced translations. Have a look at this nice diagram: https://twistedsifter.files.wordpress.com/2015/06/proportional-pie-chart-of-the-worlds-most-spoken-languages-1.png

**Comment by acka47** [comment]
A first round for a German translation has already been made by @literarymachine . It is quite easy possible to do this without an internationalization platform like CrowdIn. 

I can't estimate how many translations we will have besides the one to German and what are the plans to get in more translators. Thus, I am not sure if we need such a platform at the moment.

However, we should ask different people to work on different translations and then such a tool will come handy to have an easy overview how the progress is. Also, if we add new fields, we will need translations for and a platform will make it easy to track which languages are up-to-date with their translations.

**Comment by acka47** [comment]
@trugwaldsaenger We should soon make a request at CrowdIn to have the world map set up as an open source project: https://crowdin.com/page/open-source-project-setup-request Do you have time on Monday?
