### ISSUE TITLE
Recent additions list: Icon, more and missing ‘x’

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#763]
- The icon for the recent addition list is a bit misleading in my opinion. For me this icon is connected first to rrs feeds, as second maybe to other possibilities to get news in an automated way. In this way it is not connected to something new. 
- In the moment there is no possibility to show more entries on the list. This would be useful for us and for other users. (Later on it would be useful to filer this list for countries, services, languages, subjects and so on.)
- The window showing the list has no little x in the right corner to close it. It would be more consistent if it also has one.

**Comment by literarymachine** [comment]
> The icon for the recent addition list is a bit misleading in my opinion. For me this icon is connected first to rrs feeds, as second maybe to other possibilities to get news in an automated way. In this way it is not connected to something new.

IMO the icon is simply a feed icon, regardless of the format. RSS is also a pull technology, which simply lists entries in the order of appearance. Looking forward, we might actually also enable RSS at that URL. For me, the icon is OK but if you, @formimkontext or @j0hj0h come up with something else it can quickly be dropped in.

> In the moment there is no possibility to show more entries on the list. This would be useful for us and for other users. (Later on it would be useful to filer this list for countries, services, languages, subjects and so on.)

The list is [available](https://oerworldmap.org/resource/?sort=dateCreated:desc), I added a link from the feed in #764. See https://beta.oerworldmap.org/feed/

> The window showing the list has no little x in the right corner to close it. It would be more consistent if it also has one.

Currently, the newsletter registration has a "Cancel" button, the statistics and the feed have no explicit closing functionality and the welcome message has the "x". I'll leave it to @formimkontext and @j0hj0h to make this consistent.

**Comment by karindr** [comment]
In my opinion it is not a question of design whether there should be a cancel button or a little x to close a window. It is more a content related issue: If there is an offer or a question in a window the user should see at the first glance that he has the choice either to accept or to reject the offer. In this case there should be two buttons, one for yes or accept and the other one for no or cancel. If on the other hand the window shows some information (like a statistic chart) to the user he should have the possibility to close the window by using the little x. This is not the same as saying no to an offer.

**Comment by dobladov** [comment]
The _x_ and _more_ buttons are present, since we are using **/feed** as the URL and we agree with the new redesign I think this issue can be closed.

![image](https://user-images.githubusercontent.com/1938043/43723776-bf2f2304-9998-11e8-83aa-c9c18570bb01.png)
