### ISSUE TITLE
Administer permissions

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#768]
As an administrator of the OER World Map, I want to appoint permissions to users so that I can build a community of editors.

**Comment by karindr** [comment]
Maybe it would be an easy way to make it the same way as making somebody to a country champion? I just learned it, it is quite easy ;-). As admin you just have to edit the profile of the person and chose him as champion. If there would be a checkbox 'Give editing rights' this would be great.

**Comment by literarymachine** [comment]
> As admin you just have to edit the profile of the person and chose him as champion. If there would be a checkbox 'Give editing rights' this would be great.

While this works for our current (simple) permission system, it is not very flexible if we add more roles / permissions in the future. I will draft an extra admin section soon, which will include the permissions.

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/user/groups. You have to be admin to access that area, which @karindr and @trugwaldsaenger are and @acka47 will automatically be when he creates an account with his work email.

**Comment by karindr** [comment]
Works for me. I can change checks, send and they stay changed. At the moment I cant go to 'home' by clicking on the logo.

**Comment by acka47** [comment]
I made an acoount on beta with my work email but can not access https://beta.oerworldmap.org/user/groups.

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
Hey, I did nothing to @acka47! But now I cant access https://beta.oerworldmap.org/user/groups anymore.

**Comment by literarymachine** [comment]
> Hey, I did nothing to @acka47!

Ah, it could well be that using the new UI kicked out non-existent users automatically.

> But now I cant access https://beta.oerworldmap.org/user/groups anymore.

Did you get a permission error, or was it an internal server error? For some reason, the beta instance was shut down.

**Comment by karindr** [comment]
It works again.

**Comment by literarymachine** [comment]
I added a button to the upper left corner to access the group administration. Deployed to https://beta.oerworldmap.org/

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
The button is there, the window opens and I can change and save the entries.
But, there will be much more people in the real world and all will have to be displayed, so there has to be a order to find the person we want to change easily. I suggest an alphabetical order (Firstname would be ok). I think this is not ready by now, but how can I say of which country a person should be champion?

**Comment by acka47** [comment]
Regarding finding a person you can start with Ctrl+f and searching the page. Alphabetical order is not so important then...

> I think this is not ready by now, but how can I say of which country a person should be champion?

This can still be done when editing a person entry in the "Country champion for" field.

**Comment by karindr** [comment]
> This can still be done when editing a person entry in the "Country champion for" field.

Yes, but if I have to assign championship over the personal profile, for what purpose is there a second place to administer this property. I think it can cause more confusion than benefit to have such a second place where you can't do the whole process of assigning somebody to the championship of a country.

**Comment by literarymachine** [comment]
> Yes, but if I have to assign championship over the personal profile, for what purpose is there a second place to administer this property.

As previously discussed with @trugwaldsaenger, being a country champion is a "social" status. I will rename "champion" to "editor" in the administration to make it clear that it is a matter of permissions there. You can assign write permissions to people without them being country champions.

**Comment by karindr** [comment]
This makes everything understandable.
