### ISSUE TITLE
Display logos in original size (or smaller if necessary)

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#773]
At the moment small logos are displayed larger than their original size. This makes them look blurry. See:
https://oerworldmap.org/resource/urn:uuid:8b5bc4e0-df9d-4f40-98ea-6d4971ff4f86
Same for pictures for persons.

**Comment by tamielbr** [comment]
Example here does not resize large logo (https://oerworldmap.org/resource/urn:uuid:cb2bb13e-6e1d-46aa-9ff9-377f45e0e5ab)

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:b56b4fe7-87b2-4be2-87cd-fa0cadffed4c

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1
This really makes a difference, also for small logos, see:
https://beta.oerworldmap.org/resource/urn:uuid:a85298e2-3f35-4847-a9cd-e3c26bf230a9

**Comment by literarymachine** [comment]
Reopening because this currently does not work for SVG images, see e.g. https://oerworldmap.org/resource/urn:uuid:d8777c6f-d3ef-4639-a422-0c5aeb41220e
