### ISSUE TITLE
Stories need to have author(s) and date

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#774]
In my opinion it should not be possible to save a story without entering a person (or maybe an organisation) as author. It is one of the characteristics of a story that it is kind of personal and has to be related to the author. Do you agree? 
If so this has to be changes in the template. In the moment it is possible to save without author, see:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Article#urn:uuid:72d250f7-ecba-4b29-a7bb-110145fce75a
In addition to this stories should have a date. Do you think it is necessary to make this obligatory too?

**Comment by acka47** [comment]
I agree and I am thus removing the "question" label. I guess, I just have to add this to the "Article" object in the JSON schema:
```
"required": [
        "creator",
        "dateCreated"
      ]
```

Am I right @literarymachine ? Then just assign me and I will take care of it.

**Comment by karindr** [comment]
The thing with the author seems to be clear. I open a new issue for the date #938
.

**Comment by acka47** [comment]
Can we close this ticket then?

**Comment by karindr** [comment]
I tried on beta to save a story without creator, but this still works.

**Comment by literarymachine** [comment]
On beta

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
