### ISSUE TITLE
Insert pictures in stories in html displayed in the width of the text column

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#775]
Sometimes the pictures for stories should be displayed bigger than the standard picture of a story. If I use &lt;img alt=" " src="https://oerworldmap.org/assets/images/mediaportal.jpg" /&gt; in the text field the image is shown in its original size, see: 
https://beta.oerworldmap.org/resource/?q=&filter.about.%40type=Article#urn:uuid:af4b9930-360a-11e5-aeb3-eb256dea4251
What needs to be added that the image is displayed only as wide as the column?
I would add this info to a list of tips for authors too.

**Comment by literarymachine** [comment]
> What needs to be added that the image is displayed only as wide as the column?

    <img src="https://oerworldmap.org/assets/images/mediaportal.jpg" width="100%" />

**Comment by karindr** [comment]
+1
Thanks.
