### ISSUE TITLE
Find organisation by names in all languages in the template for services

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#777]
Example: I wanted to connect this service:
https://oerworldmap.org/resource/?q=rvp#urn:uuid:c655b27a-7f00-11e5-a636-c48e8ff4ea31
to this organization:
https://oerworldmap.org/resource/?q=rvp#urn:uuid:c655b27a-7f00-11e5-a636-c48e8ff4ea31
But when I enter the English name to the template of the service the organization isn’t found. This is because of its Czech name:
zařízením pro další  vzdělávání pedagogických pracovníků
But if I haven’t been the person who entered this name just 5 minutes before, I wouldn’t be able to know the second name because it does not appear in the column for the organization. And in addition it is very puzzling that the English name show there doesn’t work in the template.

Maybe there is an issue concerning this problem, but I didn't find it.

**Comment by acka47** [comment]
Looks like this works by now. Closing.
