### ISSUE TITLE
Input template lookups and schema out of sync

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#782]
E.g. the drop down for the `affiliation` of a `Person` includes `Action` entities, which is not allowed by the JSON schema.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
Sorry, don't understand what I should look at.

**Comment by literarymachine** [comment]
Nevermind @karindr, @acka47 reviewed.

**Comment by karindr** [comment]
:)
