### ISSUE TITLE
Implement data migration via API

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#784]
Steps:

  - select triples to delete
  - select triples to add
  - create diff
  - commit

**Comment by literarymachine** [comment]
On beta, see e.g. [this story](https://beta.oerworldmap.org/resource/urn:uuid:af322309-3542-4150-9bec-a2e1cbcf8601) and [this person](https://beta.oerworldmap.org/resource/urn:uuid:d7c441e2-60ad-4f4b-812f-591a74c97f34) which are currently only linked in one direction. Use [this query](https://beta.oerworldmap.org/sparql/update?delete=&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FmentionedIn%3E+%3Fo&where=%3Fo+%3Chttp%3A%2F%2Fschema.org%2Fmentions%3E+%3Fs) to generate the back link and apply the patch.

**Comment by acka47** [comment]
+1 Have you already repaired the other missing mention-relations?

**Comment by literarymachine** [comment]
> Have you already repaired the other missing mention-relations?

We did that together last week, remember?

**Comment by acka47** [comment]
Yes, I remember but I wrongly thought the current fix already was in production...
