### ISSUE TITLE
_missing_ queries don't work anymore

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#785]
From https://github.com/hbz/oerworldmap/issues/612#issuecomment-234250653:

> I would like to get a list of services without a license indication. Unfortunately, https://oerworldmap.org/resource/?q=_missing_:about.license&filter.about.@type=Service doesn't work as well as other `_missing_` queries form which worked before e.g. one provided by @literarymachine in https://github.com/hbz/oerworldmap/issues/423#issuecomment-232060422

**Comment by literarymachine** [comment]
By now, I am heavily in favor of reverting 06ce8e758e515ace2ab48d5c8165a7e557a30cf8. What do you think, @philboeselager?

**Comment by philboeselager** [comment]
Well, yeah, looks like, if we find a better solution. And we must increase our test coverage.

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?q=_missing_:about.license&filter.about.@type=Service

**Comment by acka47** [comment]
+1
