### ISSUE TITLE
Make tag search case insensitive

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#793]
Currently tag search is case sensitive e.g. https://beta.oerworldmap.org/resource/?filter.about.keywords=mooc doesn't give back https://beta.oerworldmap.org/resource/urn:uuid:e07be540-07ed-401b-bf5b-295589821971 where the tag reads "mOOC".

**Comment by literarymachine** [comment]
Ok - I always assumed that tags actually are case sensitive.

**Comment by acka47** [comment]
I just checked some services. At Flickr, result list doesn't seem to bother with case but it might have influence on the order of results. Bibsonomy is case insensitive. Same holds for twitter hashtags. 

Also, we agreed on simplicity for tags (see #753) and I think case sensitivity adds complexity...

**Comment by literarymachine** [comment]
We need an analyzer with 
```
"tokenizer":"keyword",
"filter":"lowercase"
```
for this.

**Comment by philboeselager** [comment]
Exactly. Done in https://github.com/hbz/oerworldmap/commit/f46c621d432ec38384f4f8065c1f8c895eb2c919 .

**Comment by literarymachine** [comment]
Fixed in f46c621, closing
