### ISSUE TITLE
Columns not visible in safari 8 and IE 11

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#797]

**Comment by formimkontext** [comment]
What about this issue? I just noticed, that the columns and the search bar are still not visible in safari 8.

**Comment by literarymachine** [comment]
Please take a look, @j0hj0h

**Comment by literarymachine** [comment]
On beta.

**Comment by acka47** [comment]
I have neither of these browsers, thus can't give a review on this.

**Comment by formimkontext** [comment]
It works, search bar and columns are now visible in safari 8.

**Comment by karindr** [comment]
Looks ok on IE 11.
