### ISSUE TITLE
Easily assess coverage of partnering programme

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#8]
As an active member of the OER (world map) community I want a simple mechanism to assess which countries and which continents already have country champion for the OER World Map project so that I can easily see where champions have to be found and I am able to show the progress of the partnering programm to the community.

**Comment by literarymachine** [comment]
How does this relate to #7?

**Comment by literarymachine** [comment]
https://oerworldmap.org/resource/?q=about.countryChampionFor:*

**Comment by literarymachine** [comment]
TODO: Link to this from e.g. the FAQ or other Documentation /cc @karindr @trugwaldsaenger

**Comment by karindr** [comment]
Not to myself: Look at the different static pages to find where to place a link to this list and write a sentence for this link.
