### ISSUE TITLE
"Public domain" option

### ISSUE THREAD

**Issue by tamielbr** [hbz/oerworldmap#801]
The map only allows for Public Domain associated with a CC license. Some sites only mention PD without a specific license. Would this be a reasonable option to add?

**Comment by trugwaldsaenger** [comment]
@tamielbr, thanks very much for your comment. Sounds very reasonalbe to me. I think we should add an option "other (public domain)". @acka47:  what do you think?

**Comment by acka47** [comment]
+1 I will add such an option.
