### ISSUE TITLE
Allow `YYYY-MM` and `YYYY` as `startDate` and `endDate` of `Event`

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#803]

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:1f5bf9c0-e18b-43a9-b56e-98affcafb6b3

**Comment by karindr** [comment]
It works.
It is possible to enter numbers > 12 as month. Shouldn't there be an error message too?

**Comment by literarymachine** [comment]
> It is possible to enter numbers > 12 as month. Shouldn't there be an error message too?

Indeed. Note to self: see http://www.pelagodesign.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/

**Comment by literarymachine** [comment]
> It is possible to enter numbers > 12 as month. Shouldn't there be an error message too?

On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:1f5bf9c0-e18b-43a9-b56e-98affcafb6b3

The date format now applied to all date inputs is [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) because it allows the flexibility we need (e.g. only year, year-month, year-month-day, year-month-day-time).

**Comment by karindr** [comment]
+1
