### ISSUE TITLE
Trim whitespaces from text input

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#806]
To display a complete list of the included tags I search for "*" and open the tags filter. There several tags appear twice, e.g. "Scotland" and "Open Data". 

"Scotland" appears one time with three entries (Edutalk, Open Glasgow, Gathering the voices) and one time with four entries (Open Knowledge Scotland, Tags Explorer, 2x Open Caledonian University Games On Even). If I now open one entry from the second group, e.g. Open Knowledge Scotland) and than click on the Scotland tag on the profile page, always the entries from the first group are displayed.

**Comment by literarymachine** [comment]
This seams to be a bug on the data-side of things. While the tags appear to be the same, they are indeed not; sometimes, a trailing space was entered:

https://oerworldmap.org/resource/?q=*&filter.about.keywords=Scotland+

vs

https://oerworldmap.org/resource/?q=*&filter.about.keywords=Scotland
