### ISSUE TITLE
Sort entries in tag filter list alphabetically without distinction of capitalization

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#807]
Right now first the tags with capital letters appear, followed by the tags with small letters.

**Comment by karindr** [comment]
That is really important because nobody will finde the second alphabet with small letters below the first alphabet.

**Comment by trugwaldsaenger** [comment]
@literarymachine: You might have a look at this. I would assume, that it is not hard to solve, but will bring great improvement.

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?q=*

**Comment by trugwaldsaenger** [comment]
GREAT!  1+

**Comment by acka47** [comment]
If the number of tags increases significantly, sorting by usage (number of applications of a tag on a resource) might make more sense.
