### ISSUE TITLE
Help visitors find their newly entered profiles

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#817]
(I think there was an issue with a similar topic, but I can’t find it.)
You as visitor just entered data for example for a service and after this entered data for an organization and you want to connect them by choosing the organisation in the template of the service. Then you search for the service by its name, but it does not appear in the list of result. I remember that this is an indexing issue, but I am wondering what we can do to let the visitors find their newly made entries before they may leave or start creating the entry twice. Is a text like “Newly entered profiles aren’t found immediately, look at recent additions ((with link to the list)).” displayed over the list of results a solution?

**Comment by literarymachine** [comment]
We had a similar problem in #685. Usually a new entry should be available in the template right away, but heavily interlinked entries (e.g. if OEC is involved) can take a while. Can you provide me with details about where the look up failed in this case?

**Comment by karindr** [comment]
I think it was
https://oerworldmap.org/resource/urn:uuid:69dfbe6d-5328-4a49-872e-005435481640
or
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:d786fac3-9598-4bf5-9fa7-047954a71afe
But I am remembering that I had this often when I entered Data from the EU-List, mostly the entries are with a lot of subjects, grande levels and profiles on twitter and facebook.

**Comment by literarymachine** [comment]
Fixed by single resource views.
