### ISSUE TITLE
Please delete a resource

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#818]
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:7ed9bee6-f748-4416-b030-79ce965ffe17
it was a double entry, I deleted all text, but I can't delete it totally. Please delete it.
(It was the double of this:
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:4ec24594-b5ef-4a4c-854f-e290aead372a )

**Comment by acka47** [comment]
Done. Closing.
