### ISSUE TITLE
Enhance story layout via the css file

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#820]
Once again I did some editing in stories. There are some points that should be included in the sites css file to make the stories look good and standardized.
- The teaser should be displayed bold automatically. (At the moment I did this with the `<strong>` tag.)
- The font size of the figure caption (`<figcaption>`) should be 0.9em to make it slightly different from the standard text.
- Citations in these Texts are often like scientific citations so they should not be displayed with lager fontsize and a bar at the left side. The tag `<blockquote>` in stories should be displayed without border at the left and same font size as text, only indented on the left same as now.

See as example the following story where I did these changes by inline css: https://oerworldmap.org/resource/urn:uuid:80b5a3df-756f-4499-b64f-a33dcbd2a4cd

**Comment by karindr** [comment]
This would be really good. I assigned it to you, @j0hj0h because I think you are responsible for the css, if not please assign it to the master of the css.

**Comment by j0hj0h** [comment]
Overlooked this. Will take a look next week ...

**Comment by formimkontext** [comment]
i allready started to work on this. @j0hj0h, lets take a look on this together.
