### ISSUE TITLE
Make story field bigger in stories template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#821]
The field for the story content has to be much larger, at least 4 times or more. It is very time consuming to do even simple corrections with this little field.

**Comment by acka47** [comment]
I guess you are talking about the "Body" field. Are you aware of the fact that you can at least increase the length of the window by pulling the lower right corner? There is no possibility to increase the width, though.

**Comment by karindr** [comment]
Yes, I was talking about the "Body" field. And no, I did not know this. But maybe some visitors are like me and don't realize this possibility? I think it would be better if the field is at least 4 times longer by default.

**Comment by karindr** [comment]
When somebody is editing a story he will make some changes and every time he has to resize the window. This is annoying and won't help getting nicely layouted stories.

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/

**Comment by karindr** [comment]
+1
