### ISSUE TITLE
Make application of chosen tags, languages etc. more intuitively

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#823]
![image](https://cloud.githubusercontent.com/assets/18674205/17697929/30b8b0bc-63b8-11e6-991b-e837c777d23f.png)
In my opinion the "apply filter" field should look more like a button or could have an other colour. If you are not reading (not everybody is reading ;-)) you don't finde how to apply your chosen tag, language etc.

**Comment by trugwaldsaenger** [comment]
+1 I had to learn how this works, too. Maybe we could simply change the colour of the "apply filter" buttom to orange?

**Comment by karindr** [comment]
+1
