### ISSUE TITLE
Possibility to search events by date

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#828]
For example:
- by year
- by month of year
- upcoming
- next 3/6 months

**Comment by formimkontext** [comment]
My suggestion would be, to implement those three as type specific extended event filter: 
- year
- month
- upcoming (next month / 3 months / 6 months/ …)

**Comment by literarymachine** [comment]
The `upcoming` filter is enough for now. Also, filtering can be done using the query syntax.
