### ISSUE TITLE
Only show linked icons of "profiles elsewhere"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#829]
See https://github.com/hbz/oerworldmap/issues/482#issuecomment-240965183

This is how many sites do it, e.g. about.me, see e.g. https://about.me/philosopher1978. (We should use smaller icons, though.)

**Comment by karindr** [comment]
Good Idea!

**Comment by karindr** [comment]
This is done now and is really good.

But is there a possibility to show the linked url when you hover the "other" icon? Sometimes there is more than one of these icons and you don't know where you will be led! For example:
https://oerworldmap.org/resource/?q=colorado#urn:uuid:d2ab36e8-4de0-4abf-b32d-bba7e3405cf0

**Comment by formimkontext** [comment]
In this case the we can use the icons (Google+, Pinterest) included in the FontAwesome icon set. But the general problem persists. I wouldn’t mind to show the linked URL, because not every icon is self-explanatory or even known and we probably won’t find icons for all profiles elsewhere. Furthermore a neatly arranged table is more informative and user friendly, than a line of icons without further informion.

**Comment by literarymachine** [comment]
> Furthermore a neatly arranged table is more informative and user friendly, than a line of icons without further informion.

But this is precisely what we had until https://github.com/hbz/oerworldmap/issues/482#issuecomment-288657577.

**Comment by karindr** [comment]
Please don't go back to the lists! The icons are fine! It only would be a bit better if the url was shown hovering the icons.

**Comment by formimkontext** [comment]
Just checked the registration flow at about.me. The ›profiles elsewhere‹ at there website are called ›social links‹ which i found more appropriate. You can set those social links by chosing the social network at first, selecting one of 50 displayed social network logos. This makes it easy to only show dedicated icons of ›profiles elsewhere‹. We could change the ›profile elsewhere‹ field in our forms to a dropdown list from which the user can select the social network first.

**Comment by formimkontext** [comment]
#758

**Comment by literarymachine** [comment]
Fixed in the new UI: 
![image](https://user-images.githubusercontent.com/149825/43527361-c062337e-95a6-11e8-892c-d828462f2cbf.png)
