### ISSUE TITLE
Strange behavior in searching

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#831]
Searching for "ariadne": no results
![image](https://cloud.githubusercontent.com/assets/18674205/17886129/b9a4e130-6920-11e6-9250-dc992366114d.png)
Searching for "ariadn": 2 results
![image](https://cloud.githubusercontent.com/assets/18674205/17886368/b67a6b28-6921-11e6-80ca-74941e93bc8e.png)

And later on "ariadne": 2 results.
Strange but maybe not reproducible?

**Comment by karindr** [comment]
Same for "banco":
![image](https://cloud.githubusercontent.com/assets/18674205/17887055/f1846b3a-6924-11e6-9655-71c5f41ba573.png)
After "banc" "banco" also works.

**Comment by karindr** [comment]
Sometimes searching of incomplete words causes wrong results, see:
![image](https://cloud.githubusercontent.com/assets/18674205/18082384/f313cd9a-6e9e-11e6-8782-12abf2038dcc.png)
![image](https://cloud.githubusercontent.com/assets/18674205/18082428/2a3d12f4-6e9f-11e6-9617-ced6b2092e3f.png)

**Comment by philboeselager** [comment]
Perfect bug report - thanks!

I could not reproduce the two bugs described first, at all ("ariadn" https://github.com/hbz/oerworldmap/issues/831#issue-172647608 and "banc" https://github.com/hbz/oerworldmap/issues/831#issuecomment-241677459 ). When I've started a new OERWorldMap instance, the first search attempt for both "ariadne" and "banco" succeeds, without having searched for "ariadn" or "banc". Furthermore, I couldn't reproduce this behaviour by the means of unit testing. I've asked @jprante - that doesn't appear to him as an Elasticsearch problem or behaviour. It might have been a frontend problem, but that is quite vague.

For the third case ("e-pai", https://github.com/hbz/oerworldmap/issues/831#issuecomment-243374287) : this problem only occurs for query strings containing a special character ("-" in this case) or if something similar effects a multi token operation in Elasticsearch. Searching for "pai" will work. There's nothing provided by Elasticsearch that would solve this quite special problem. Anyway, I could write a routine like (pseudo code):

    if (searchResult.size == 0){
      if (isMultiToken(queryString)){
        String[] split = queryString.split();
        split.forEach(doElasticsearchQuery());
        // and collect each query's result
        // and return all collected results
      }
    }

@literarymachine : the loss of performance should be very small. Do you agree?

**Comment by literarymachine** [comment]
> I could not reproduce the two bugs described first, at all

I suspect they might have been caused by an indexing job in the background. If we want the performance gain (which is huge), we have to accept that sometimes the index is slightly behind the main database.

**Comment by literarymachine** [comment]
> Do you agree?

With regards to performance, probably. But merging the result list is probably not trivial, especially with regards to Elasticsearchs relevance ranking. Maybe we really do need two query parameters, one of which is always escaped as in #827 while the other never is ("expert search");

**Comment by jprante** [comment]
>this problem only occurs for query strings containing a special character ("-" in this case) or if something similar effects a multi token operation in Elasticsearch. Searching for "pai" will work. There's nothing provided by Elasticsearch that would solve this quite special problem.

Sure there is. The solution is to index hyphenated words ("Bindestrichwörter") with an analyzer like https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/test/java/org/xbib/elasticsearch/index/analysis/hyphen/HyphenTokenizerTests.java

**Comment by philboeselager** [comment]
> Sure there is. The solution is to index hyphenated words ("Bindestrichwörter") with an analyzer like https://github.com/jprante/elasticsearch-plugin-bundle/blob/master/src/test/java/org/xbib/elasticsearch/index/analysis/hyphen/HyphenTokenizerTests.java

AnalysisService was introduced in 2015, based on Elasticsearch 2.0. Currently, we are still on ES 1.3.6. Therefore, this issue is blocked by https://github.com/hbz/oerworldmap/issues/703 .

**Comment by jprante** [comment]
I can backport my plugin to Elasticsearch 1.3.6 but I strongly suggest to update to Elasticsearch 2.x as soon as possible. 1.x has many flaws and has been unsupported for over a year by Elastic company (except last 1.7 release to support index migration).

**Comment by drrobertfarrow** [comment]
I had the same issue last night - I ended up creating two erroneous records because the entries did not appear when I did a search.  
![screen shot 2016-09-01 at 18 46 08](https://cloud.githubusercontent.com/assets/10849418/18196024/e6fa0ad4-70e6-11e6-8312-68069cb06bb0.png)
![screen shot 2016-09-01 at 18 44 18](https://cloud.githubusercontent.com/assets/10849418/18196027/ea15c9b0-70e6-11e6-9959-12ce2acc827a.png)

**Comment by literarymachine** [comment]
@drrobertfarrow I don't quite understand the screen shots - the second one has the type filter set to `Service` so it naturally has less hits than the first one.

**Comment by literarymachine** [comment]
@philboeselager: what is the status of this?

**Comment by philboeselager** [comment]
I have a local branch for this issue but due to other tickets I didn't work on this since September 14th. I can push it on github if you like - or take it as my next task after I have fixed the test for https://github.com/hbz/oerworldmap/pull/926.

**Comment by literarymachine** [comment]
> take it as my next task after I have fixed the test for #926.

:+1:

**Comment by literarymachine** [comment]
> For the third case ("e-pai", #831 (comment)) : this problem only occurs for query strings containing a special character ("-" in this case) or if something similar effects a multi token operation in Elasticsearch.

On beta, see https://beta.oerworldmap.org/resource/?q=e-pai (unclick "Restrict results to map").

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
beta is not available at the moment.

**Comment by literarymachine** [comment]
Yes, working on something else there. This is deployed to production though: https://oerworldmap.org/resource/?q=e-pai
