### ISSUE TITLE
Same language for name in tab and in right column

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#833]
At the moment the name of for example a service is displayed in different languages in the tab and in the column, see:
![image](https://cloud.githubusercontent.com/assets/18674205/17962050/368324c0-6aaf-11e6-9bd6-49f92413c34a.png)
I think it would be better to display the name in the chosen language also in the tab.

**Comment by karindr** [comment]
The number of  entries with names in different languages or even different characters is growing constantly so this enhancement is becoming more important.

**Comment by dobladov** [comment]
Fixed in the new UI, closing.

With language **de**

![image](https://user-images.githubusercontent.com/1938043/44334848-f5b05080-a472-11e8-9ff6-77fddb95b5a6.png)

With language **en**
![image](https://user-images.githubusercontent.com/1938043/44334862-01037c00-a473-11e8-8523-b74ce05a9dca.png)
