### ISSUE TITLE
Display copyright icon in the size of the other icons

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#834]
... it is shown much larger

**Comment by karindr** [comment]
Also the Icons for the other non cc licenses. In addition to this the background of the question mark has to be white too. See:
![image](https://cloud.githubusercontent.com/assets/18674205/18047545/c1ade496-6ddd-11e6-8461-02f6e1442352.png)

**Comment by formimkontext** [comment]
There has allready been a layout showing the licence-icons. Is it possible to only use the round cc-icons without the grey box around?
![20160411-oer-world-map](https://cloud.githubusercontent.com/assets/15141949/18125643/aa1e3bdc-6f77-11e6-8548-70656aae474c.jpg)

**Comment by karindr** [comment]
I agree that the using the round icons without the grey box would be nicer but I would prefer staying with the grey box icon because it is in my experience used more often and can be recognized more quickly. Since we need to have all the corresponding licenses without cc the grey box would make the distinction between the different types easier.

**Comment by karindr** [comment]
I would prefer if the license icons weren't displayed above the description, better above the table below the profile icons. See also #482.
Sometimes the licensing for the resources of a service is hard to find and only represents kind of random sampling. Because of this the place below the title gives the icons to much weight in my opinion.

**Comment by karindr** [comment]
(Me again ;-)
Do you have in mind, that the order of the icons should be changed? See #670
