### ISSUE TITLE
Can't link service to newly entered organisation 

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#835]
I want to link Education Group to Land Oberösterreich, but this is not shown in the drop down list, see:
![image](https://cloud.githubusercontent.com/assets/18674205/18045906/8cb01672-6dd5-11e6-99e1-568f20646f98.png)
When searching Land Oberösterreich is found, see:
![image](https://cloud.githubusercontent.com/assets/18674205/18045941/b96737b8-6dd5-11e6-9566-beedb8d83409.png)

**Comment by acka47** [comment]
It's there now. Obviously indexing took some time...

**Comment by karindr** [comment]
Yes, it is there now. But what is new on this problem is this:

- normally the newly made entries don't appear when searching for them, but this entry is found by searching
- the new entry is **not** heavily linked as you can see above

If we want people to locate services via organisations it is really important, that this workflow works for them directly and not only five minutes later.

- 

-

**Comment by karindr** [comment]
Today with the same service I had to wait nearly 3 minutes till the newly entered organisation appeared in the drop down list.

Because we want the visitors to locate new services by connecting them to an organisation they entered it is really not good when the organisation isn't shown. If there is no technical solution we have to think about a not like "If the newly entered organisation is not shown in this drop down list please try again later."

**Comment by literarymachine** [comment]
> If there is no technical solution

There is a technical solution: let the user wait for three minutes until the index has been built. Because these enormously long saving times are unacceptable, we switched to an asychronous approach in the first place. Of course I understand the difficulties with this, though. I suggest to add a note as a quick fix and look into speeding up indexing in some way in the long run. Ok?

**Comment by literarymachine** [comment]
> normally the newly made entries don't appear when searching for them, but this entry is found by searching

This is interesting as it cannot have anything to do with indexing taking long. The look ups in the form to exactly the same queries as the search field on the map.

> the new entry is not heavily linked as you can see above

Sometimes it is the case that a previous indexing job is still running.
