### ISSUE TITLE
More "other" licence types needed

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#836]
It would be good to have all cc license types also as other license type, because sometimes the people make their own license with elements of the cc licenses. See for example the following information which I would assume as “other by nc nd”:

The assodiut reserves the right to correct at any time and without notice, the content of this website. In addition, it disclaims all liability for delays, errors or omissions in the content of these pages, and in the event of interruption or unavailability of service. Reproduction of material from this site on paper is authorized, particularly for educational purposes, subject to the following three conditions:
- Free distribution, 
- respect for the integrity of the documents reproduced: no modifications or alterations of any kind,
- clear and readable quotation of the source in the following form - for example - "This document comes from the website http://www.iutenligne.net Reproduction rights are reserved and strictly limited.". The website address Iutenligne must appear in the reference.
  http://www.iutenligne.net/mentions-legales.html (mit google translate übersetzt)

**Comment by literarymachine** [comment]
![image](https://user-images.githubusercontent.com/149825/54695011-85150380-4b29-11e9-8deb-9ab48d60d99f.png)
