### ISSUE TITLE
inconsistent number of persons 

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#840]
On the "Welcome to the OER World Map" screen currently 101 persons are mentioned. When I set a filter to persons in our search, I receive 73 entries. I suspect that 101 have registered alltogether and that 73 out of them created a personal profile. I guess we should make this consistent, propably by showing the smaller number also on the Welcome-screen...

**Comment by literarymachine** [comment]
> I suspect that 101 have registered alltogether and that 73 out of them created a personal profile.

This is indeed the problem!

**Comment by trugwaldsaenger** [comment]
Are there any problems to show only the number of (users with) profiles?

**Comment by literarymachine** [comment]
> Are there any problems to show only the number of (users with) profiles?

No. Fix deployed to beta, where the `Person` count was 48 vs 46.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
+1

**Comment by literarymachine** [comment]
wow. three +1s. can't remeber that happening before ;)

**Comment by trugwaldsaenger** [comment]
Just one question, before closing this issue: Are there any obligatory reasons for the distinction between an account and an profile?

**Comment by literarymachine** [comment]
> Are there any obligatory reasons for the distinction between an account and an profile?

Yes. An account is a security related thing; from an architectural point of view, people authorize before they even hit the world map application. A profile is a simply a type of entry (`Person`). They just happen to be linked.

**Comment by literarymachine** [comment]
> They just happen to be linked.

But in our sign up workflow what happens is that an empty profile is always created when an account is created. It is initially empty though, and thus should not appear in the stats or search result. It is this way because initially we thought that every account should have at least a name and email address but then saw the legal implications of forcing people to publish information when signing up. The code underneath is still the same though.

If it is really important, we could decouple things. I don't see any urgency in this though.

**Comment by trugwaldsaenger** [comment]
No, no urgency. I just thought that might want to make sure in the future that every editor has a profile, so that it becomes transparent who edited what. But if I understand things right, we still might need the account for people, who want to register to the newsletter, whithout any deeper involvement...

**Comment by literarymachine** [comment]
> But if I understand things right, we still might need the account for people, who want to register to the newsletter, whithout any deeper involvement

No. The newsletter is completely independent. Our legal adviser just said that it is easiest for the privacy statement to not require users to fill in any data if they don't want to when they sign up. Since empty profiles are non-informative though, they should not be displayed or counted.

**Comment by trugwaldsaenger** [comment]
This is quite strange. Today the welcome screen on production tells that we have 99 users, and the search result list mentiones only 57 users. So compared to the numbers from the beginning of September (101/73 users), we have been loosing users! Is this true? Also the numbers are still inconstistent.

**Comment by acka47** [comment]
Didn't the September numbers say: 101 have registered for the newsletter and 73 have made an account?

And the new numbers mean 99 people have made an account of which 57 have created a profile?

**Comment by literarymachine** [comment]
This is actually a side effect of #933. Right now, only entries that have a pin on the map are listet. Probably not what we want, @j0hj0h and I talked about putting a checkbox that says "Restrict results to map" above the list to trigger this behavior.

**Comment by acka47** [comment]
Fixed. CLosing.
