### ISSUE TITLE
created service is not indexed

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#841]
Following service:
https://oerworldmap.org/resource/urn:uuid:a33f6044-bb46-462c-bee1-fb1823dfd01c
has been created. But it is not shown under "recently updated" nor is it possible to mention it as an entitiy within a story. I guess indexing must have gone wrong.

**Comment by acka47** [comment]
Could be a problem with the `@` in the title.

**Comment by literarymachine** [comment]
> Could be a problem with the @ in the title.

No, it is an error in the elasticsearch mapping. Will update, but this needs re-indexing which I will carry out later tonight.

Note to self:

    org.elasticsearch.index.mapper.MapperParsingException: failed to parse [about.mainEntity.location.address.postalCode]

**Comment by literarymachine** [comment]
Deployed to production; see e.g. https://oerworldmap.org/resource/?q=edShare%40GCU and https://oerworldmap.org/feed/
