### ISSUE TITLE
Allow countries to become a provider of services?

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#846]
This is interesting:
https://oerworldmap.org/resource/urn:uuid:8dde383f-4e45-487e-bc6f-d4ce25342aff
Here we have a country (in this case a "Bundesland") which runs a service. So we added it as an organization, which, from my point of view, it is since it is a social systems. But wouldn`t it be better in this case, if we would allow countries (and its subdivisions) to run services directly?

**Comment by literarymachine** [comment]
>But wouldn`t it be better in this case, if we would allow countries (and its subdivisions) to run services directly?

At a first glance, and looking at the footer of https://www.edugroup.at/, I would rather say that "EDUCATION GROUP GMBH" is the provider.

**Comment by karindr** [comment]
Following the "Open Education Europe: OER repositories list" the organizor is "Land Oberösterreich". I added "Amt der Oberöstereichischen Landesregierung" as description to make clear that it is an institution of the "Bundesland" as we have many other similar institutions as providers.

**Comment by trugwaldsaenger** [comment]
Well, after some reflexion I guess we do not need to allow countries to become service provider. Countries cannot act on themself, they always need an agency or administrative body. It`s the same with hbz: Oficially the contry NRW is acting,  hbz is only a representer. So there will always be a representing organization, which we can add to the map.

**Comment by karindr** [comment]
I added Education Group GmbH as second provider and changed the  name of the service to "Education Group Website" to make a difference.
