### ISSUE TITLE
Plan for improved mobile functionality

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#849]
At the team meeting in Milton Keynes we reviewed some ideas for Phase IV, one of which was a fully operational mobile version of OER World Map.

It was agreed that we would think about whether there was some potential to make use of the affordances of mobile devices to improve the experience of using OER World Map.
- A functional mobile experience would be advantageous for demonstrating the site
- A streamlined mobile experience could make importing data more efficient
- Mobile devices are set up to share content 

Extra functionality is not a priority for Phase IV, but Phase V could provide opportunities to explore this.  Can we collect ideas/use cases here?

**Comment by karindr** [comment]
As often said at conferences and barcamps and so on it would be very useful to have a basic mobile version. This basic version should be able to be used for:

- having a first look on the map and search for entries, click on pins and so on

- registration (people who want to register should be able to do this immediately and should not get frustrated)

Entering data and generating statistics would be not necessary for the fist step.
