### ISSUE TITLE
Create Twitter account for the project

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#85]

**Comment by acka47** [comment]
We already have a twitter account: https://twitter.com/oerworldmap

**Comment by drrobertfarrow** [comment]
Great.  I will add it to the blog.  Who is responsible for tweeting on the account?

**Comment by trugwaldsaenger** [comment]
Just send you the needed information. Do you need anything else?

**Comment by literarymachine** [comment]
Assuming this is done, closing.
