### ISSUE TITLE
Create statistics by URL parameters

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#850]
Create a generic statistics widget that can be integrated into different surroundings.

From a technical point of view, this could imply a statistics controller that facilitates the statistics' configuration and visualization.

**Comment by literarymachine** [comment]
http://www.tableau.com/

**Comment by drrobertfarrow** [comment]
This issue has a lot of overlap with #843

**Comment by acka47** [comment]
Clarification: This story  is about controllers and URL parameters but not about a user tool for creating widgets. Such a tool will be part of phase IV.

**Comment by literarymachine** [comment]
We are now using Kibana, see https://github.com/hbz/oerworldmap-ui/pull/459 for an example how to use URL parameters for visualizations.
