### ISSUE TITLE
Visualize geographical distribution of project participants

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#852]
See #843

**Comment by literarymachine** [comment]
On https://beta.oerworldmap.org/aggregation/, see "Projects by Participant's Countries" there.

Also on beta is "Projects by Funders", showing how many projects individual funders fund. Currently due to our data basis not very exciting, but might be an incentive to add more `funder` relations to projects.

**Comment by karindr** [comment]
Maybe this is an other issue? The doughnut is cut of at the bottom in some views, see:
![image](https://cloud.githubusercontent.com/assets/18674205/18508409/56090b00-7a74-11e6-9bbf-cbe7412d1f91.png)

**Comment by literarymachine** [comment]
> Maybe this is an other issue? The doughnut is cut of at the bottom in some views

This is indeed another issue.

**Comment by karindr** [comment]
New issue #866

**Comment by literarymachine** [comment]
> New issue #866

Excellent. This will be solved separately. Other than that, should I deploy what is mentioned in https://github.com/hbz/oerworldmap/issues/852#issuecomment-246696031?

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
