### ISSUE TITLE
Export event data

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#855]
Task for #541. Using iCal.

**Comment by acka47** [comment]
Acceptance criteria:

- [ ] Export single event entries as iCal
- [ ] Export a list of events (all events or with filters set)

**Comment by literarymachine** [comment]
> Export a list of events (all events or with filters set)

- Add `format` parameter for queries: `/resource/?filter.about.@type=Event&format=ics`
- Allow arbitrary queries to be exported as `ics`, ignore any non-Event data in this representation

**Comment by philboeselager** [comment]
@literarymachine : backend development looks like done. See https://github.com/hbz/oerworldmap/commits/855-exportEvents.

**Comment by literarymachine** [comment]
Please open a pull request in such cases, see https://github.com/hbz/oerworldmap/pull/926

**Comment by literarymachine** [comment]
Reopening, see https://github.com/hbz/oerworldmap/pull/926#issuecomment-263933051
