### ISSUE TITLE
Put disclaimer at the top of person form of empty profiles

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#859]
As some people misuse their personal profile to enter an organization or service there should be a disclaimer at the top of the person form if the profile is edited the first time saying something like

> This is your personal profile. If you want to enter data about an organization, service or something else, please write to info@oerworldmap.org to request editing rights. After you'll see a plus button on the upper left to add any type of resource.

**Comment by acka47** [comment]
I suggest another wording:

> This is your personal profile. Go ahead and share some information about you with the OER community!
>
>  If you want to enter data about an organization, service, event or project, please write to info@oerworldmap.org to request editing rights.

I think we should put the focus on encouragin users to add some details about themselves. Then we should point to the possibility of getting editing rights. The detail information on how to add other resources is better supplied when people sign up as editors.

**Comment by literarymachine** [comment]
Oops, I accidentally assigned the PR for review. See https://github.com/hbz/oerworldmap/pull/876#issuecomment-248863472 for @karindr suggestion.

**Comment by acka47** [comment]
That's similar to my suggestion. However, I think we should also omit the last sentence. People don't need the information there.

**Comment by acka47** [comment]
Maybe @trugwaldsaenger will provide the final wording?

**Comment by literarymachine** [comment]
It would be great to get the final wording ASAP so that this can be deployed before more people use their personal profile to add an organization etc to the map.

**Comment by trugwaldsaenger** [comment]
Both version look fine to me! I would go for the following:

> This is your personal profile. We appreciate very much if you want to share information about yourself with the oer community. If you want to enter data about an organization, service or something else, please write to info@oerworldmap.org to request editing rights.

**Comment by trugwaldsaenger** [comment]
closed by accident...
