### ISSUE TITLE
Clarify Merlot Mess

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#860]
Merlot is quite interesting to model. Currently it is on the map as a service (https://oerworldmap.org/resource/urn:uuid:b084ddc2-313a-11e5-a56e-001999ac7927) as well as as an organization (https://oerworldmap.org/resource/?q=merlot#urn:uuid:70696b2a-77eb-11e5-9f9f-c48e8ff4ea31).

According to my understanding, it is a service, which is provided by CSU, so we could simply delete the organization entry. But this would cause some problems:
1. Merlot is a member of OEC. This information would be lost, if we deleted the organization. So obviously OEC allows services to become a member. Should we do so as well? 
2. Merlot is also a community, which you can become a member of (https://www.merlot.org/merlot/index.htm?action=communities). Again this is hard for us to model, since we do not include a member-field for services. I guess it happens quite often that services have such a community part, so it would be great to find a solution how to model this...

We could also add Merlot as a project, using the description provided on the Merlot site: http://info.merlot.org/merlothelp/index.htm#who_we_are.htm, which also included information about funding. Since this might be importet automatically via the Hewlett Data set, I did not include it manually yet...

**Comment by acka47** [comment]
We already adjusted the JSON schema to allow membership of a Service in an organization, see #467 where I also point to MERLOT as example. I can't remember why I didn't make the Service a member of OEC – perhaps I just forgot. As far as I can see, terminology isn't clear on MERLOT's sides, where boundaries between the service, the community and the MERLOT consortium aren't clear. We might just delete the org entry and add OEC membership to the service...

**Comment by karindr** [comment]
I deleted the name and data in the personal profile COOL4Ed to make it disappear without deleting the registration of tdykes@calstate.edu. See
https://oerworldmap.org/resource/?q=&filter.about.%40type=Person#urn:uuid:af939204-44b2-4aea-b139-b1289de7e553

**Comment by karindr** [comment]
I think so, closing.
