### ISSUE TITLE
Add registration notice

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#861]
During the last weeks it happened several times that personal profiles where created for organizations or services. (latest example: https://oerworldmap.org/resource/urn:uuid:af939204-44b2-4aea-b139-b1289de7e553). In order to avoid these wrong entries, we should make a notice in the text on the registration page (https://oerworldmap.org/user/register) as following:

"No personal account yet? Leave your email address and choose a password to setup your profile on the OER World Map. Please notice, that registration is for personal profiles only. If you want to bring your project or service to the map, please create a personal profile and send us a mail to info@oerworldmap.org in order to achieve full editing rights."

**Comment by literarymachine** [comment]
Probably a duplicate of #859?

**Comment by j0hj0h** [comment]
At least connected. My suggestion was to place the note at the form where you actually enter the profile data as described in the other issue. We could do both, but I'd rather opt for the form only as this is the point where the information should be better understandable and people have to go that far anyway.

**Comment by literarymachine** [comment]
> We could do both, but I'd rather opt for the form only as this is the point where the information should be better understandable and people have to go that far anyway.

+1

**Comment by acka47** [comment]
From my point of view we can close this one now as it actually is redundant with #859.

**Comment by trugwaldsaenger** [comment]
I think we can close it by now. If #859 does not bring the exspected improvement - we can reopen it again!
