### ISSUE TITLE
Embed video in a story

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#862]
Today I found on Twitter a link to this video about OER programmes at NOVA.  https://www.youtube.com/watch?v=ZARLHWL_6Lc

We have NOVA on the map at https://oerworldmap.org/resource/?q=virginia#urn:uuid:706a595e-77eb-11e5-9f9f-c48e8ff4ea31.  It would be great if we could add the video as a story, but at the moment we have no way to embed content like this.  I can see how this might be a way of encouraging contribution:  people who don't want to type a story but have some video content available could just embed content hosted elsewhere.

I don't know whether this is simple or complicated to implement, but obviously the code for HTML/iFrame embedding is easy to find.

**Comment by literarymachine** [comment]
> I don't know whether this is simple or complicated to implement, but obviously the code for HTML/iFrame embedding is easy to find.

Given this, you simply have to copy that HTML/iFrame into the `body` field of a story: https://beta.oerworldmap.org/resource/urn:uuid:fb73e2c7-d2b0-45c4-8c45-a1a72e3fe28f

**Comment by drrobertfarrow** [comment]
It seems to be working perfectly! https://oerworldmap.org/resource/urn:uuid:9af4551b-8b8d-4be6-88af-1f055d450bf7

![screen shot 2016-09-13 at 13 53 10](https://cloud.githubusercontent.com/assets/10849418/18474265/3153883c-79b9-11e6-9807-72cc89a7ce7d.png)
