### ISSUE TITLE
Add ISO 3166-2 code to locations

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#864]
The [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) defines codes for administrative division similar to the ones ISO 3166-1 provides for countries (e.g. `DE.NW` is the ISO 3166-2 for North Rhine-Westphalia). Adding these in the `addressRegion` field of the `PostalAddress` data we have allows us to build the sub-national heat maps in the same way as we now do for countries.

In order to add ISO 3166-2 code to locations, we need to (a) add the code when a new entry is made and (b) migrate our existing data. (a) will be implemented in #64 and is on its way. For (b) we could simply index [natural earth GeoJSON](https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_10m_admin_1_states_provinces.geojson.gz) in Elasticsearch and use [GeoShape Queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-shape-query.html) for the coordinates in the existing data.

**Comment by acka47** [comment]
Done. Closing
