### ISSUE TITLE
The doughnut is cut of at the bottom in some views

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#866]
See this chart on beta:
![image](https://cloud.githubusercontent.com/assets/18674205/18509864/58f53e2c-7a7b-11e6-9cf9-0f68448e4744.png)

**Comment by dobladov** [comment]
Fixed in the new UI, closing

![image](https://user-images.githubusercontent.com/1938043/44333876-59854a00-a470-11e8-883c-9e2375790ba8.png)
