### ISSUE TITLE
Find a way to map adoption of OER

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#867]
The map at https://www.google.com/maps/d/viewer?mid=1AB7EuOHQ_jmb0FOX4PvhXVBIIF0 shows adoption of open textbooks produced by BC Campus.  I don't know how BC Campus generated this data - probably manually. I sent them a tweet to find out more.

It would be good if we had a way to incorporate data like this.  It might not be something that we include as a basic data type, since it would overtake the map.

There is some history of showing impact of this type on a map.  
http://track.olnet.org/
http://www.mura.org/tag/capret/
https://www.openhub.net/p/track-oer

These approaches used web analytics to gather data.  I am not proposing we do this. 

But if we had data similar to the BC Campus data for several different OER producers, then perhaps this could be used to draw feint lines on the map. Different colours could be used for different producers - this would show the impact without being too overpowering.  It might be a good incentive for OER producers to share their data like this, and I imagine OER advocates would find such a presentation useful.

This work is not currently planned as far as I know, but it might be worth thinking about it for a future phase.
![screen shot 2016-09-17 at 16 14 52](https://cloud.githubusercontent.com/assets/10849418/18609157/fb48bd9c-7cf2-11e6-83fb-8a68c5a0b82d.png)

**Comment by literarymachine** [comment]
Out of scope.
