### ISSUE TITLE
Consortia/associations appear in the country of its members

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#870]
This issues follows the earlier discussion about displaying OEC members in #424 and #474. The issue here was that the OEC is shown e.g. on the countryview of the Netherlands since some dutch universities are members of the OEC: https://oerworldmap.org/country/nl. This still seems to be the case, though the original issue has been closed.

A similar problem now occured with the GOGN network, which is displayed e.g. on the country view in Sweden: https://oerworldmap.org/country/se

I`m not sure if I understood all details of the former discussion. I do agree, that showing all members of a consortia/accociation makes sense. But it might be necessary to implement a special functionality for this. E.G.: On each profil of an organization, which has members, you can presson "show members on map". Members and mother institution should then both be displayed on the map, 

What I guess is wrong is, that the mother institution is displayed in all the countries of its members.

**Comment by acka47** [comment]
This would be solved with implementing #479. But it might be easier to just adjust the query for a country view. @literarymachine, what do you think?

**Comment by literarymachine** [comment]
> But it might be easier to just adjust the query for a country view. @literarymachine, what do you think?

Actually it is currently a matter of the Elasticsearch mapping, where the locations of referenced entities are copied to the parent. Needs re-indexing, will ping @acka47 afterwards.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/nl where the OEC does not appear any longer.

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
+1
