### ISSUE TITLE
Delete GO-GN duplicate

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#871]
https://oerworldmap.org/resource/?q=Global+Graduate+Network#urn:uuid:706952ac-77eb-11e5-9f9f-c48e8ff4ea31

**Comment by acka47** [comment]
Done, see https://oerworldmap.org/resource/urn:uuid:706952ac-77eb-11e5-9f9f-c48e8ff4ea31. Closing.

**Comment by drrobertfarrow** [comment]
When I click on Adrian's link I get an error page 
![screen shot 2016-09-20 at 08 43 25](https://cloud.githubusercontent.com/assets/10849418/18661515/08dca2c6-7f0e-11e6-9aba-db302c61882e.png)

**Comment by literarymachine** [comment]
> When I click on Adrian's link I get an error page 

Yes. Because he deleted it and thus fixed this issue. Closing.
