### ISSUE TITLE
Delete resistant duplicate

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#873]
Following entry has to be deleted, since it is a duplicate:
https://oerworldmap.org/resource/urn:uuid:403e5b56-8af7-4ec4-8d5d-5295296101b5

What is quite interesting about it: @karindr and me tried to change it by adding "to be deleted" in the name, but both failed to save the changed dataset. Simply nothing happened after clicking "save". Changing other datasets works fine.

**Comment by literarymachine** [comment]
> Simply nothing happened after clicking "save".

See #877.

**Comment by literarymachine** [comment]
Deleted, see https://oerworldmap.org/resource/urn:uuid:403e5b56-8af7-4ec4-8d5d-5295296101b5. Closing.
