### ISSUE TITLE
Add "country report" section to country view

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#875]
When clicking on a country view, there should be a section "country report" included, e.g. between the country statistic and the search field:
![country report](https://cloud.githubusercontent.com/assets/6639965/18708840/27bccc62-7ffd-11e6-952d-70fd3540b90f.JPG)
This new section should include all stories, which are tagged as countryreport:nameofcontry. So if there is a story tagged "countryreport:sweden, it should be displayed on the swedish country view. If there is no story, the section should not be shown at all.

This functionality is part of a small project, which we are currently running with our swedish country champion and the OE Working Group. Goal will be to publish the new country report on Sweden: http://education.okfn.org/open-education-sweden/ on the OER World Map. Other reports from OE Working Group, or by the POERUp project will follow.

**Comment by karindr** [comment]
We have the first country report:
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:c466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0
Soon there will be a second edition of this. If there is more than one report, the latest should be on top of the list.

**Comment by karindr** [comment]
We also could link to a blog article from Jan "Germany in numbers" as country report.

**Comment by literarymachine** [comment]
> We have the first country report:
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:c466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0

I noticed that instead of one tag `countryreport:sweden` as @trugwaldsaenger suggested, you used two separate tags `country report` and `sweden`. If we want to use tags to associate country reports with countries, it would make it much more precise to (a) use a single tag and (b) use the ISO-3166 code instead of the English name for the country. In this case, the tag would thus be `countryreport:SE`. Would that be ok?

**Comment by literarymachine** [comment]
Actually using two tags would not be a problem. Using the ISO-3166 code is the important part.

**Comment by karindr** [comment]
I will use countryreport:SE, no problem. I will use country report too, for the human visitors to find things.

What about blog articles as country reports? How could we handle them?

**Comment by literarymachine** [comment]
> What about blog articles as country reports? How could we handle them?

I think we would need #1032 for that. What do you think, @acka47?

**Comment by acka47** [comment]
Either #1032 or we just add the possibility to link any resource with `mentionedIn` or [`mainEntityOfPage`](https://schema.org/mainEntityOfPage) to a web page about the thing as outlined in #609.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/country/de

**Comment by karindr** [comment]
This is the case country report as story on the map, that is OK.

This is a link to a country report as article in a blog (this time our own):
https://oerworldmap.wordpress.com/2016/03/18/the-german-speaking-oer-landscape-in-numbers/
How will you realise this?

**Comment by literarymachine** [comment]
> How will you realise this?

As said in https://github.com/hbz/oerworldmap/issues/875#issuecomment-281624163 we can't do this right now. Perhaps by republishing the blog post on the OER World Map.

**Comment by literarymachine** [comment]
> Either #1032 or we just add the possibility to link any resource with mentionedIn or mainEntityOfPage to a web page about the thing as outlined in #609.

But how would we link an external country report to a country using that approach?

**Comment by karindr** [comment]
Since republishing is a lot of detail work and for longer articles the story layout with the small column is not very well to read it would be good if there would be a possibility to link to external articles.

**Comment by literarymachine** [comment]
> Since republishing is a lot of detail work and for longer articles the story layout with the small column is not very well to read it would be good if there would be a possibility to link to external articles.

Does that mean I should not deploy this? This is not the use case of this issue!

**Comment by karindr** [comment]
We have and will have country reports as stories, so please deploy this. 

We could open a new issue for additional links to external country reports. Should we do this?

**Comment by literarymachine** [comment]
> We could open a new issue for additional links to external country reports. Should we do this?

See #1103

**Comment by literarymachine** [comment]
> We have the first country report:
https://oerworldmap.org/resource/?sort=dateCreated:desc#urn:uuid:c466ee13-ad4c-4a1f-b5ee-6200c7f5a5b0

I tagged it with `countryreport:se`: https://oerworldmap.org/country/se
