### ISSUE TITLE
Delay reaction of address-map

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#880]
It happened several times to me within the last days, that I just wanted to scroll down on an input template. Doing so, I placed by accident my browser on the fabulous new address-map, which zoomed out. This was rather irritating. Would it be possible to integrate a mechanism, which avoids this? Maybe it would be possible to delay the reaction of the address-map, so that it reacts only if the cursor stays on the map for a certain time...

**Comment by karindr** [comment]
I agree with @trugwaldsaenger, this is irritating and makes the template slower. Would be nice if it does not happen. Maybe it would be enough to zoom in and out the little map by using the + and - buttons?

**Comment by literarymachine** [comment]
> Maybe it would be enough to zoom in and out the little map by using the + and - buttons?

I agree. When using the address search, the maps zooms in automatically anyways. Deployed to https://beta.oerworldmap.org/

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1
