### ISSUE TITLE
Making it easier to format stories

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#882]
I worked on a story that should be transfered from another website to our website. I have chosen to take the source code and to clean it from elements we don’t need. I used brackets as editor an inserted tab to have an overview about the structure of the document. Entering the text on beta I get this result:
https://beta.oerworldmap.org/resource/urn:uuid:1a4cec12-2af9-449b-ae95-c3839627d733

I think the tabs result in the code-like appearance. Could this be suppressed? If we want to insert code there would be other ways, i.e. using the html-tag? Other people also may use html-editors with tabs.

**Comment by drrobertfarrow** [comment]
Hi Karin, I think this is because you are using HTML rather than markdown.  Maybe Felix can clarify.

I think HTML is more familiar to people, although Markdown is easy to use when you know how.  It occurs to me that asking people to learn Markdown before they can enter information is potentially a bit of a barrier.  Perhaps we should work towards including a WYSIWYG editor or something like that in the long run?

**Comment by karindr** [comment]
Yes a WYSIWYG editor would be great, because most people want to do the things in a way they already know.

I know I can use markdown. But if you have to copy an article from a website it is quicker to take the source code and modify it. Normally HTML works very well, but for markdown tabs are markers for code. I just could delete the tabs here. But I think there might be other people working with HTML and tabs for their stories. It would be good if there was a possibility that the world map understands: this is markdown an this is HTML.

**Comment by acka47** [comment]
> I know I can use markdown. But if you have to copy an article from a website it is quicker to take the source code and modify it.

You can then – or before modification – run the html through a converter like https://domchristie.github.io/to-markdown/ or http://pandoc.org/try/ or to get the markdown you need. I just did that for the article in question.

**Comment by acka47** [comment]
Regarding WYSIWYG I rather suggest an approach like GitHub has taken: adding "bold", "italic" and other buttons on top of the editing window that help you with formatting in markdown.

**Comment by karindr** [comment]
Yes I can convert HTML to markdown. But why make something worse and then make it better again? ;-)

This is not about me an this article. I think we should give people entering stories the possibility to do it in ways closest to their experience. If someone wants to use markdown he can use markdown, if someone wants to use HTML he can use HTML.

**Comment by literarymachine** [comment]
> If someone wants to use markdown he can use markdown, if someone wants to use HTML he can use HTML.

People can simply use HTML rights now, the only thing they cannot use is indention.

**Comment by literarymachine** [comment]
> Regarding WYSIWYG I rather suggest an approach like GitHub has taken: adding "bold", "italic" and other buttons on top of the editing window that help you with formatting in markdown.

Absolutely. I am strongly against WYSIWYG editors; the results they produce are mediocre at best. And it is hard to force them into following our style. People tend to format everything the way they want to, but we want our layout in the articles. Also, people tend to mix up structure and format when using WYSIWYG. As stated above, pros can use HTML if they want to (though I have no idea why you would, especially when writing a new article).

**Comment by karindr** [comment]
Talking about a WYSIWYG editor I had something in mind like the two editing windows in wordpress. I think they don’t give the users the possibility to format everything the way they want, do they? More of our visitors are used to wordpress than to github in my opinion.

**Comment by drrobertfarrow** [comment]
This is mainly going to arise as an issue where content already published online is being reappropriated for OER World Map - so it's probably an issue for our team primarily.  

For people like ourselves who are part of the editorial team it's a reasonable expectation to run copy through a markdown converter, but it raises two barriers for the causal user:

1) Understanding what markdown is and the process they have to follow to convert HTML
2) Actually being bothered to follow the process

I don't have a problem with markdown as such, but it took me a few tries before I got it looking as I expected it to.  (Most of the HTML did not seem to be recognised as far as I recall.)

Maybe there are good reasons against adopting a WYSIWYG editor, but perhaps we could give a little bit more guidance on the data entry template to help people who are not familiar with it.

**Comment by literarymachine** [comment]
> Maybe there are good reasons against adopting a WYSIWYG editor, but perhaps we could give a little bit more guidance on the data entry template to help people who are not familiar with it.

All fields that have [Markdown supported](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) have a link pointing to documentation.

**Comment by literarymachine** [comment]
Fixed in https://github.com/hbz/oerworldmap-ui/commit/da5b734e7289ba29f6692e5927f7d9e16b9ac415
