### ISSUE TITLE
Add "Tweet this" button to signup process

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#890]
As a new user of the OER World Map, I would like to send out a tweet after having registered.

**Comment by literarymachine** [comment]
Thinking about this, the tweet should be sent after creating the personal profile.

**Comment by literarymachine** [comment]
@acka47 Please also check this while reviewing #1067 and #789.

**Comment by acka47** [comment]
Just tried this out and it works. I don't think many people will use it, though. Doesn't make much sense to link to a profile with name and (perhaps) email address in it... Anyway, +1
