### ISSUE TITLE
Don't clear search term when clearing filters

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#891]
As user I search for XY as service for example, no results. Because I am sure that the search term is correct I want to search for this term without any selected filter. I press the 'clear filter' button. I expect that all filters are cleared but the search term would be still there. At the moment the term is also cleared and I have to enter it again.

**Comment by karindr** [comment]
It is the same in the new UI on beta.

**Comment by karindr** [comment]
I also want to be able to set a filter without the search term being deleted. For example I search for OERinfo and see there are to much hits so I want to search only for services. I want to be able to add the filter and don't want to have to put in the term again.

**Comment by literarymachine** [comment]
Deployed to production.
