### ISSUE TITLE
Delete a personal profile and account

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#893]
At the moment there is a delete button also on the personal profile pages. I am not sure about the consequences of this deletion. Does it only delete the page or does it affect the  registration of the person?
There are (at least) two cases for wanting to delete a personal profile for me as administrator:
1. a person registered and added spam so I really want to delete person and profile
2. a person registered and used the persons profile to enter information about his organisation
   In the second case I transfer the data to an organisations page and than want to delete the wrong persons profile but I don't want to affect the registration of the person. Can I use the delete button in this case?

**Comment by karindr** [comment]
See also #892. At the Moment it is not possible to "empty" the profile because of this.

**Comment by literarymachine** [comment]
> Does it only delete the page or does it affect the registration of the person?

Strictly speaking, it only deletes the page, i.e. the profile. But deleting the profile currently does lead to the account not being able to log in any more.

> 1. a person registered and added spam so I really want to delete person and profile

As mentioned above, this is probably what you would want to do in this case.

> 2. a person registered and used the persons profile to enter information about his organisation

A person always needs to have a profile, it may be empty though. So you would not want to use the delete button in this case.

> See also #892. At the Moment it is not possible to "empty" the profile because of this.

True. But deleting the name and the coordinates is enough to make it invisible.

**Comment by literarymachine** [comment]
Currently, only admins are allowed to delete entries. At least for personal profiles, this should probably also be possible for the corresponding account owners.

**Comment by philboeselager** [comment]
Our [imprint page](https://oerworldmap.org/imprint) currently says: "You can view, change, and delete the information at any later point in time. In order to delete your profile, please send us a mail to info@oerworldmap.org." Please amend this accordingly.

**Comment by literarymachine** [comment]
On beta, the deletion of a Person entry now also deletes the corresponding account. Admins and profile owners may delete Person entries.

**Comment by acka47** [comment]
As a user I could delete my account and the URI wouldn't resolve anymore and I could register again with the same address. So this seems to work. (Interestingly, the verification token was exactly the same when re-registering with the same name, email address, and location. I don't know whether this might be problematic...)

As an admin I currently can not delete other people's account on beta. It gives an error:

 ![bildschirmfoto vom 2017-03-22 10 14 40](https://cloud.githubusercontent.com/assets/160292/24190944/6d256530-0eea-11e7-861a-141c7768f237.png)

**Comment by literarymachine** [comment]
> As an admin I currently can not delete other people's account on beta. It gives an error:

This was due to some inconsistencies on beta; anyhow, it is fixed there now.

**Comment by acka47** [comment]
Now it works. Page load after a deletion takes an eternity, though. However, this will be fixed with the refactoring.

**Comment by acka47** [comment]
+1

**Comment by literarymachine** [comment]
> Page load after a deletion takes an eternity, though.

This is actually a problem due to the setup on beta and should not be present on production.
