### ISSUE TITLE
New line not possible in editing form

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#898]
Reported by @trugwaldsaenger. Currently it is not possible to hit enter to get in a new line in an editing form – whether in a story or entity description. Thus, you can't create paragraphs with markdown.

**Comment by literarymachine** [comment]
Sorry about that, in 42020e21ed37865bf233377d5ecd566319150cb9 I prevented accidental form submission but forgot to exclude `textarea` elements. On beta.

**Comment by acka47** [comment]
+1
