### ISSUE TITLE
Change the wiki-page  Editor-FAQ to a static page on www.oerworldmap.org

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#905]
It would be more consistent to have this FAQ:
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors
as static page on www.oerworldmap.org because the visitor does not have to use the back button to go on working on the map, he can also follow the links on the page.

**Comment by formimkontext** [comment]
New draft of the FAQ page. The answers are hidden in the akkordeon and will be shown by clicking on the +-button. 

![20171107-desktop-faq](https://user-images.githubusercontent.com/15141949/32516505-df5245be-c403-11e7-8713-c9c345d012fa.png)

**Comment by karindr** [comment]
So much better!

**Comment by karindr** [comment]
This issue was originally about the "FAQ for editors" which should be transferred, so I reopen it.
