### ISSUE TITLE
Circles with numbers are transparent

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#906]
It looks like an error, see the two circles east from China:
![image](https://cloud.githubusercontent.com/assets/18674205/19642349/3158f8ac-99e5-11e6-9431-1d46936a7681.png)

**Comment by literarymachine** [comment]
Sorry, the resolution of the screenshot is to low for me to see what you mean.

**Comment by karindr** [comment]
Today all is fine. If one circle is lying over an other circle it is not transparent. So I close this issue.
