### ISSUE TITLE
Remove strange abbreviation in adresses

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#907]
As example here
https://oerworldmap.org/resource/?q=gln#urn:uuid:771abe8f-f38c-4cc6-90f1-f7bdb8b03d9d
is a line in the adress with GR.AT on the site but not in the template. Where does it come from and shouldn't it be removed? Maybe it is result of the new way to get coardinates? I have seen such abbreviations sometimes on the map.

17 Grammou Str. 
Athens 
15235 
GR.AT 
Greece

**Comment by literarymachine** [comment]
This is the [ISO 3166-2](https://de.wikipedia.org/wiki/ISO_3166-2) code for sub-national divisions. In the edit template it is implicitly selected then the pin is placed on the map. We should probably also hide it in the display.

**Comment by literarymachine** [comment]
Done, closing.
