### ISSUE TITLE
Reference to original publication for republished articles

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#912]
We want to ‚republish‘ articles published on other websites as stories on the world map. I wonder if we need a field in the template for the link to the original publication together with something like “Published on:” or “This article was published on “. The second question is where to put this information. On beta I put it at the end of an article but maybe on top under “Created by” is more appropriate? See:
https://beta.oerworldmap.org/resource/urn:uuid:e8653d67-1ad9-40ea-b228-704ebb7339d0

**Comment by acka47** [comment]
I think it should be on on top of the text in italics. I put a version in the example post at https://beta.oerworldmap.org/resource/urn:uuid:e8653d67-1ad9-40ea-b228-704ebb7339d0.

**Comment by formimkontext** [comment]
Since this information isn’t a part of the story itself it should be shown in the table below the artikel. Just like "Location" or "Entities mentioned".

**Comment by karindr** [comment]
That's right, this information does not belong to to story itself, so the place between teaser and text is not so good. But at the end it it is nearly hidden. The idea of writing it in italics for the moment is good because it makes it different to the text. For the moment I will put it at the end of the text in italics.

But what do you think of an own field for this information in the template and put it in a line just below "Contributed by:"?

**Comment by karindr** [comment]
Talked to Adrian: We both think that a prominent place above the text would be appropriate. Maybe in the same line as "Contributed by:" or below it. There has to be the possibility to enter a URL for the source and as Adrian mentioned a field for the licence. The text around could be:
_This article was originally published at ##www.ccsso.org## under a CC-By license._

**Comment by karindr** [comment]
I tested the first line of the teaser as place:
https://beta.oerworldmap.org/resource/urn:uuid:e8653d67-1ad9-40ea-b228-704ebb7339d0
This solution has two disadvantages: 

- There is too much space to the "Contributed by:"-line wich it belongs to and to less space to the teaser which it does not belong to.

- If we use the teasers in any different setting it may be inappropriate to have the new line as part of the teaser.

For the texts I'm working on I will choose this solution nonetheless and change them when there is a better solution.

**Comment by formimkontext** [comment]
Maybe we should discuss this in reference to #482 ? There @trugwaldsaenger provided a document to define the hierarchical structure of information in different single resource views.

**Comment by literarymachine** [comment]
Die einfachste Variante wäre ein Freitextfeld und eine Erläuterung. Man kann aber auch mehr Logik aufsetzen und für bestimmte Standardlizenzen Lösungen vorsehen – was den Vorteil hätte, dass Ihr leichter Auswertungen fahren könntet.

**Comment by acka47** [comment]
+1

**Comment by trugwaldsaenger** [comment]
+1 looks pretty good to me! 

Maybe we should rename the field "creator" into "contributor"?

**Comment by acka47** [comment]
> Maybe we should rename the field "creator" into "contributor"?

The thing is that the property `http://schema.org/creator` is behind it. So this should contain the actual creator of the story.

**Comment by karindr** [comment]
To make it totally clear, we could rename the field to "author". And we should be able to enter a name of a person that is not registered on the map, so we can republish articles from people who agree to this but are not registered to the map.

**Comment by karindr** [comment]
What makes the case a bit more complicated is the Log page, see:
![image](https://user-images.githubusercontent.com/18674205/27119272-80061a00-50df-11e7-9449-c7d011e9d725.png)
There the person who contributed the story to the map is named author. Any idea for this? "Autor of changes", "... of page" or "contibuted by"?

**Comment by acka47** [comment]
Regarding the log page, we should further discuss this on the approriate issue: #1235. I think only admins can currently see it. So it is not that important to have a coherent wording for now.

**Comment by acka47** [comment]
> To make it totally clear, we could rename the field to "author". And we should be able to enter a name of a person that is not registered on the map

Allowing free text instead of links to persons on the world map in the `creator` field would mean fundamental changes to the data model and/or how it controls the input possibilities. Thus, we decided to go ahead and add the free text name for people not on the world map in the "license notice" field.

Looking at list of people who have added a story to the world map we know/are all of the frequent story contributors. So I think there is no priority to approach this right now. Or are there any serious plans to have more people adding stories soon?

**Comment by acka47** [comment]
I just took a look at some republished stories and noticed that we have a similar problem with "date created". Cathy Jordan puts herself into "Creator" of a re-published story and writes into "Date created" the date when she republished a story on the OER World Map. The date when a story was originally published isn't named at all. See e.g. https://oerworldmap.org/resource/urn:uuid:4407d715-bbaf-4490-9142-c084dbb3ea45 which was originally published in 2010.

Regarding that we didn't have in mind republication of stories when building the data model and UI this is all not very surprising. We should probably make a separate issue to improve this. However, I am afraid that stories aren't read by anybody anyway and I find it more important to improve the presentation of stories first as it is not very comfortable to read them in a small column on the right of the screen.

We should contact Cathy and tell her about our thoughts and the changes to the story UI.

**Comment by karindr** [comment]
No, there is no plan to add more stories from our side at the moment. But as Katy showed stories can be a good starting point to cover countries we have no information about!
