### ISSUE TITLE
Visualize selected list item

### ISSUE THREAD

**Issue by philboeselager** [hbz/oerworldmap#916]
When clicking through a list (e. g. middle column in https://oerworldmap.org/resource/?q=&filter.about.%40type=Event), it is easy to lose the knowledge of which item had been clicked - especially when you scroll the content of a selected item in the right column in the mean time, as the mouse loses track. Therefore a visualization of the current selected item would be helpful.

(As font colour orange is already used to indicate a link by a hovering effect, a bold font or darker background or even an inverted font / background colour scheme might be preferable.)

**Comment by karindr** [comment]
I think a bold font would be good.

**Comment by dobladov** [comment]
Fixed in the new UI. Closing
