### ISSUE TITLE
Country champion information has disappeared from roll-over

### ISSUE THREAD

**Issue by drrobertfarrow** [hbz/oerworldmap#917]
When you hover over a country on the map they all show an 'X' indicating there is no country champion.  But the information about country champions is still in the database, as the attached screenshot shows.  This is happening in both Chrome and Safari for me this morning...

![screen shot 2016-11-03 at 08 24 42](https://cloud.githubusercontent.com/assets/10849418/19965825/2f42dcb0-a19f-11e6-9777-ca5aa5dca622.png)

**Comment by literarymachine** [comment]
Fix deployed to https://beta.oerworldmap.org/

@drrobertfarrow I can deploy this to production now, but this requires a brief downtime. Let me know if I should go ahead or wait until your presentation is over.
