### ISSUE TITLE
Log out is not working on production an on beta

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#922]
For me clicking on "Log out" doesn't have any consequences. Production and beta seems to log out automatically after some time.

**Comment by literarymachine** [comment]
@j0hj0h this is also because of #919

**Comment by literarymachine** [comment]
On beta

@j0hj0h fixed in d1e4dedb04a7fca88873ac1f48c20917e76539c1

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
