### ISSUE TITLE
Program Management

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#925]
As a Program Manager (Hewlett, BMBF)/project funder I would like to add a set of projects funded by me to the World Map in order to increase visibility of the projects and their achievements.

**Comment by trugwaldsaenger** [comment]
This is an initial specification document in German, which describes potential functionalities:
[161110_concept_programmmanagement.docx](https://github.com/hbz/oerworldmap/files/583345/161110_concept_programmmanagement.docx)

**Comment by trugwaldsaenger** [comment]
Additional to the fields mentioned in the specification document, it is likely that a field for an identifyer will be needed.

**Comment by acka47** [comment]
Tasks as discussed in the physical team meeting:

- Add subtype "Programme" to type "Project".
- Enable hierarchical links between projects/actions ("isPartOf" or similar).
- Define project core data elements, add missing properties
   - URL of  RSS feed
   - FTE in project
   - results: lessons learned, Projektabschlussbericht
   - project leader? -> better at a contactPoint (= Person) to type Action
   - enable projects to be an organizer of an event
- Create HTML templates with markup for describing projects and events
- Plan displaying updates form RSS feeds on programme and project profiles
-  Plan import of events from project event pages
- Contact IA regarding archival of resources linked to on the World Map

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/milestone/13
