### ISSUE TITLE
Can't add Pin for Montevideo, Urugay

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#929]
I added "Montevideo" as location and chose "Montevideo, Urugay", than a pin ist shown on the little map, but I can' save this. Error message is:
--- BEGIN MESSAGES ---
error: instance value ("UR") not found in enum (possible values: ["AD","AE","AF","AG","AI","AL","AM","AN","AO","AQ","AR","AS","AT","AU","AW","AX","AZ","BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR","BS","BT","BV","BW","BY","BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN","CO","CR","CU","CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","EH","ER","ES","ET","FI","FJ","FK","FM","FO","FR","GA","GB","GD","GE","GF","GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY","HK","HM","HN","HR","HT","HU","ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE","JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ","LA","LB","LC","LI","LK","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME","MF","MG","MH","MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ","NA","NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ","OM","PA","PE","PF","PG","PH","PK","PL","PM","PN","PR","PS","PT","PW","PY","QA","RE","RO","RS","RU","RW","SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","SS","ST","SV","SX","SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN","TO","TR","TT","TV","TW","TZ","UA","UG","UM","US","UY","UZ","VA","VC","VE","VG","VI","VN","VU","WF","WS","YE","YT","ZA","ZM","ZW"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Country"}
    instance: {"pointer":"/location/address/addressCountry"}
    domain: "validation"
    keyword: "enum"
    value: "UR"
    enum: ["AD","AE","AF","AG","AI","AL","AM","AN","AO","AQ","AR","AS","AT","AU","AW","AX","AZ","BA","BB","BD","BE","BF","BG","BH","BI","BJ","BL","BM","BN","BO","BQ","BR","BS","BT","BV","BW","BY","BZ","CA","CC","CD","CF","CG","CH","CI","CK","CL","CM","CN","CO","CR","CU","CV","CW","CX","CY","CZ","DE","DJ","DK","DM","DO","DZ","EC","EE","EG","EH","ER","ES","ET","FI","FJ","FK","FM","FO","FR","GA","GB","GD","GE","GF","GG","GH","GI","GL","GM","GN","GP","GQ","GR","GS","GT","GU","GW","GY","HK","HM","HN","HR","HT","HU","ID","IE","IL","IM","IN","IO","IQ","IR","IS","IT","JE","JM","JO","JP","KE","KG","KH","KI","KM","KN","KP","KR","KW","KY","KZ","LA","LB","LC","LI","LK","LR","LS","LT","LU","LV","LY","MA","MC","MD","ME","MF","MG","MH","MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ","NA","NC","NE","NF","NG","NI","NL","NO","NP","NR","NU","NZ","OM","PA","PE","PF","PG","PH","PK","PL","PM","PN","PR","PS","PT","PW","PY","QA","RE","RO","RS","RU","RW","SA","SB","SC","SD","SE","SG","SH","SI","SJ","SK","SL","SM","SN","SO","SR","SS","ST","SV","SX","SY","SZ","TC","TD","TF","TG","TH","TJ","TK","TL","TM","TN","TO","TR","TT","TV","TW","TZ","UA","UG","UM","US","UY","UZ","VA","VC","VE","VG","VI","VN","VU","WF","WS","YE","YT","ZA","ZM","ZW"]
---  END MESSAGES  ---

**Comment by acka47** [comment]
It seems as somehow the wrong country code for Uruguay is submitted to the API ("UR" instead of "UY"). Did you choose the country with the dropdown? I just tried to select and save "Uruguay" on beta and it worked (see https://beta.oerworldmap.org/resource/urn:uuid:53ffda91-eebb-4e08-8ab3-eb55b04b8899).

**Comment by literarymachine** [comment]
> I tried it there too: enter "Monte..." chose from list "Montevideo, Uruguay" error message as above.

@acka47 is referring not to the autocompletion dropdown, but the actual country list dropdown:

![screenshot from 2016-11-14 12-22-34](https://cloud.githubusercontent.com/assets/149825/20263006/0c8851fe-aa65-11e6-99fb-43a83e7338b4.png)

There seems to be some kind of mismatch between our list of country codes and the one provided by the [Pelias API](https://pelias.mapzen.com/v1). Until we figure out what is going on, please simply (re-)select the country from the drop down manually in such cases.

**Comment by literarymachine** [comment]
The `ISO 3166-1 alpha-2` code for Uruguay is `UY` while the `ISO 3166-1 alpha-3` code is `URY`. In [place.js](https://github.com/hbz/oerworldmap/blob/master/public/javascripts/behaviours/resource-form-widgets/place.js#L238) alpha-3 codes are simply truncated, which apparently works in most but not all cases.

**Comment by karindr** [comment]
Ok. It works like this.

**Comment by acka47** [comment]
Closing.
