### ISSUE TITLE
Enable linking to arbitrary map views

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#934]
Mentioned in https://github.com/hbz/oerworldmap/issues/581#issuecomment-260902203. As a user I want to easily get a URL to my current view of a map (with zoom and corresponding result list) so that I can share it with others.

I see three options:
1. Update the URL in the browser bar when zomming in and out so that people can just copy and paste this URL.
2. Add a button to copy a link (ideally a short link) for a map view while keeping the URL in the browser from changing when zooming in and out but.
3. Both adjust the URL in the browser and offer a shortened link for sharing.

**Comment by dobladov** [comment]
Fixed in the new UI using the share button. Closing

![image](https://user-images.githubusercontent.com/1938043/43711695-e0d6dd00-9973-11e8-83dd-912968b2e071.png)
