### ISSUE TITLE
Expose record metadata to frontend

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#935]
To show "last modified" as in layout posted here: https://github.com/hbz/oerworldmap/issues/710#issuecomment-243735054

**Comment by literarymachine** [comment]
In https://github.com/hbz/oerworldmap/pull/1036 the metadata is now exposed to the front end, see 925490a4be7eb150aa5f2124841ab489b26af1ea.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:6dd760a6-d841-4e24-be46-04e2a2c3ff5b where the last modified date is now displayed on top of the entry, linked to the log for logged in users.

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
Cool.
