### ISSUE TITLE
Stories must have a date

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#938]
There should be an automatic displaying of the date. Something like:
Contributed by "author" , "November 2016", last modification "December 2016".
I think month and year is sufficient. It would be a nice feature to have the modification text displayed only if the month is different (not "Nov 16, last modification Nov 16").

On the other hand, we as administrators should be able to give a date non automatically, because we republish stories that have been published some time ago, so the actual date of contribution would give a wrong information. This should be part of the sentence referring to the original source, see issue #912.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1
