### ISSUE TITLE
Allow Persons to be Service Providers

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#939]
Persons should be able to be providers for services. Currently only organizations can become a service provider. Though this seems to be the normal case, there are some services (e.g. memucho), which are provided by persons. I guess this will be typical for startups as well, which at the beginning often do not have constituted an legal organization yet.

**Comment by acka47** [comment]
The JSON schema allowas persons to be providers of a service. But in the "provider" field it only says "Search Organization..." and if you search, persons are not listed in the results.

Thus, the following has to be adjusted.

- [ ] Write "Search for Organization or Person..." in the "provider" field
- [ ] Search for Organizations and Persons when somebody starts typing in the "provider" field

**Comment by karindr** [comment]
This possibility is really necessary.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:6ad8d2da-0ef6-40c1-a84c-5f22e394955d for a `Service` with a `Person` as `provider`.

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1
