### ISSUE TITLE
Separate "members" and "affiliates" in organization profile

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#942]
Example: https://oerworldmap.org/resource/?q=Open+Education+Consortium#urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f

Currently the organizations profile does not distinguish between "members" (=organizations) and "affiliates" (=persons). Because of this right now the members of the OEC are displayed together with its employees.

Both groups should be seperated by including in the displayed profile an additional field "affiliation". The data input will keep as it is: Persons will add an "affiliation" on their profile, organisations will add information per the "member of" field.

**Comment by literarymachine** [comment]
Required data migration:

https://oerworldmap.org/sparql/update?delete=%3Fs+%3Chttp%3A%2F%2Fschema.org%2FmemberOf%3E+%3Fo+.+%3Fo+%3Chttp%3A%2F%2Fschema.org%2Fmember%3E+%3Fs&insert=%3Fs+%3Chttp%3A%2F%2Fschema.org%2Faffiliation%3E+%3Fo+.+%3Fo+%3Chttp%3A%2F%2Fschema.org%2Faffiliate%3E+%3Fs&where=%3Fs+a++%3Chttp%3A%2F%2Fschema.org%2FPerson%3E+.+%3Fs+%3Chttp%3A%2F%2Fschema.org%2FmemberOf%3E+%3Fo+.+%3Fo+a+%3Ftype+.+FILTER+%28%3Ftype+%3D++%3Chttp%3A%2F%2Fschema.org%2FOrganization%3E+%7C%7C+%3Ftype+%3D++%3Chttp%3A%2F%2Fschema.org%2FService%3E%29+.

**Comment by literarymachine** [comment]
> Both groups should be seperated by including in the displayed profile an additional field "affiliation". The data input will keep as it is: Persons will add an "affiliation" on their profile, organisations will add information per the "member of" field.

On beta, see https://beta.oerworldmap.org/resource/urn:uuid:ff56c436-7e76-11e5-b76b-54ee7558c81f

**Comment by trugwaldsaenger** [comment]
+1

**Comment by acka47** [comment]
+1. I suggest to move the affiliates and events organized before the members (ping #482 ).

**Comment by karindr** [comment]
+1
