### ISSUE TITLE
ZIP field in address in input template cuts of first number if it is 0

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#943]
Some addresses have an 0 as first number of the ZIP, e.i.:
Thomas Edison State University
111 W. State St.
Trenton, NJ 08608
When you enter this the 0 is cut of while saving, see:
https://oerworldmap.org/resource/urn:uuid:82c244df-f9b2-4a75-a57c-7322d0dc93cf

**Comment by karindr** [comment]
Also relevant for Rome:
e.g. 00186 – Roma – Italy
see:
https://oerworldmap.org/resource/urn:uuid:cfef010f-eac8-46a1-8dbe-3e2e62943b6e

**Comment by karindr** [comment]
Jens Bemme a user from Dresden mentioned this again.

**Comment by literarymachine** [comment]
> Jens Bemme a user from Dresden mentioned this again.

Ok. As the tag "refactoring" shows, we are handling this in the new UI.

**Comment by karindr** [comment]
OK. I thought, refactoring was done.

**Comment by literarymachine** [comment]
> OK. I thought, refactoring was done.

No, actually "refactoring" is the wrong word. "Rewrite" is correct, as it involves rewriting the entire front-end code.

**Comment by literarymachine** [comment]
Fixed on production, see e.g. https://oerworldmap.org/resource/urn:uuid:cfef010f-eac8-46a1-8dbe-3e2e62943b6e
