### ISSUE TITLE
Is colour of a country already related to number of inhabitants?

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#944]
When searching for example for oer there is one entity in New Zealand and one in India, but New Zealand is displayed green and India is displayed white.

**Comment by literarymachine** [comment]
No, the color of a country is not based on the population yet (and it remains open if it actually should be). But it is also not based on the exact coordinates (the pins), either. What gets counted is the data in the field `location.address.addressCountry`, so the country given as part of the address. This goes back to the very first version of the heat map, which was based on the country that users selected when they signed up for our newsletter.

**Comment by karindr** [comment]
Just to make sure that I did get this right: When there is a strange colouring in the map next to a search list there are two possible ways the data of the results is incorrect or incomplete: 

1. `location.address.addressCountry` is there but the coordinates for a pin are missing (colour is darker than number of pins may suggest)
2. the pin is there but `location.address.addressCountry` is missing (colour is lighter)

If it is this way this may be a good opportinity to check the data while doing things on the map.
