### ISSUE TITLE
Meet me @ for profiles

### ISSUE THREAD

**Issue by trugwaldsaenger** [hbz/oerworldmap#945]
As an OER professional (but also as an organization, project or service) I would like to show followers on which OER events they can meet me personal:

![meetmeat](https://cloud.githubusercontent.com/assets/6639965/20561478/223a3578-b17f-11e6-88bd-a53188a7ed49.JPG)

To realize this functionality we have to implement:
- the possibility to connect yourself to an event ("participates in")
- include automatically a list of all future events you are participating in your personal profile

**Comment by literarymachine** [comment]
Also, it should be possible to set `participatesIn` in #27.

**Comment by literarymachine** [comment]
In profiles, events should be sorted reverse chronological

**Comment by literarymachine** [comment]
See https://github.com/hbz/oerworldmap/issues/27#issuecomment-267321204 for the UI to connect to an event via the calendar list. @formimkontext will provide a solution for individual events.

**Comment by formimkontext** [comment]
Draft of the single resource column for events showing the i-am-attending-action-button below the subline. Active button could change wording to ›XX People attending‹. 

![20170511-singleresource event](https://cloud.githubusercontent.com/assets/15141949/25960556/9414634e-3677-11e7-8cf7-18d177aa61f2.png)
