### ISSUE TITLE
Explain and sort search result list

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#946]
The order of the search result list should be

- [ ] indicated, e.g. as in "24 entries shown (ordered by relevance)"
- [ ] modifiable by the user

**Comment by karindr** [comment]
The explanation is really important for our useres.

Please add possibility to sort by alphabet. This is what useres ask for as additional possibility.

**Comment by literarymachine** [comment]
Fixed in 32bf459e8c2feeb8edd1ef9ff6e5ed41cd84a59b and https://github.com/hbz/oerworldmap-ui/commit/837a3c7bf7ba2420dcc95a64f0fd84521d28ba0c, deployed to production.
