### ISSUE TITLE
Don't differentiate between "Main Entity" and "Entities mentioned"

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#951]
Currently, you can choose a main entity and and "entities mentioned". At the physical meeting we discussed that we can probably give up this distinction as it probably confuses users.

**Comment by karindr** [comment]
And it should not be named "entity". I don't remember our solution, "entry" seems not to fit here very well, but I think it is better than "entity".

**Comment by literarymachine** [comment]
Necessary SPARQL update: https://oerworldmap.org/sparql/update?delete=%3Fentity+%3Chttp%3A%2F%2Fschema.org%2FmainEntityOf%3E+%3Fstory+.+%3Fstory+%3Chttp%3A%2F%2Fschema.org%2FmainEntity%3E+%3Fentity+.&insert=%3Fentity+%3Chttp%3A%2F%2Fschema.org%2FmentionedIn%3E+%3Fstory+.+%3Fstory+%3Chttp%3A%2F%2Fschema.org%2Fmentions%3E+%3Fentity+.&where=%3Fentity+%3Chttp%3A%2F%2Fschema.org%2FmainEntityOf%3E+%3Fstory+.+%3Fstory+%3Chttp%3A%2F%2Fschema.org%2FmainEntity%3E+%3Fentity+.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
I just patched it. After #990 is done I would clean up the schema.json and that would be it. Or do I forget something?
