### ISSUE TITLE
Migrate funder data according to new Grant schema

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#952]
With #924, `funder` should be replaced by `isFundedBy` a `Grant` which in turns points to the funder using `isAwardedBy`.

**Comment by literarymachine** [comment]
https://oerworldmap.org/sparql/update?delete=%3Fproject+%3Chttp%3A%2F%2Fschema.org%2Ffunder%3E+%3Ffunder+.&insert=%3Fproject+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FisFundedBy%3E+%5B+a+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FGrant%3E+%3B+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FisAwardedBy%3E+%3Ffunder+%5D&where=%3Fproject+%3Chttp%3A%2F%2Fschema.org%2Ffunder%3E+%3Ffunder+.

**Comment by literarymachine** [comment]
Afterwards, we should remove the `funder` property from the JSON schema.

**Comment by literarymachine** [comment]
https://oerworldmap.org/sparql/update?delete=%3Fproject+%3Chttp%3A%2F%2Fschema.org%2Ffunder%3E+%3Ffunder+.+%3Ffunder+%3Chttp%3A%2F%2Fschema.org%2Ffunder%3E+%3Fproject+.&insert=%3Fproject+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FisFundedBy%3E+_%3Agrant+.+_%3Agrant+a+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FGrant%3E+%3B+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2FisAwardedBy%3E+%3Ffunder+%3B++%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2Ffunds%3E+%3Fproject+.+%3Ffunder+%3Chttp%3A%2F%2Fpurl.org%2Fcerif%2Ffrapo%2Fawards%3E+_%3Agrant+.&where=%3Fproject+%3Chttp%3A%2F%2Fschema.org%2Ffunder%3E+%3Ffunder+.

**Comment by literarymachine** [comment]
@acka47: done on beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd.json where the intermediate `Grant` replaced the direct link to the `funder`. Also visible in the HTML as `Action.fundedBy`. See https://beta.oerworldmap.org/resource/urn:uuid:0801e4d4-3c7e-11e5-9f0e-54ee7558c81f.json and `Organization.funds` for the inverse direction.

**Comment by acka47** [comment]
This is done. Closing.
