### ISSUE TITLE
Enable hierarchical links between projects/actions

### ISSUE THREAD

**Issue by acka47** [hbz/oerworldmap#953]
Task for #925.

Basically, this is an isPartOf/hasPart relation: a project is part of a program and a project might also have sub-projects as its parts.

schema:isPartOf/hasPart are only intended to be used on relating things of type CreativeWork (see also https://github.com/schemaorg/schemaorg/issues/1097). We might use dcterms instead.

**Comment by literarymachine** [comment]
On beta, `Projects` can now have a "Superordinate Project" and "Sub Projects" (at the very bottom of the input form). This only covers the very basics of linking projects to each other, sub-types of `Action` such as `Funding Programme` have not been introduced yet.

> schema:isPartOf/hasPart are only intended to be used on relating things of type CreativeWork (see also schemaorg/schemaorg#1097). We might use dcterms instead.

@acka47 this is what I went with for now.

**Comment by acka47** [comment]
Thanks for taking this over. (I have been covered with different other stuff this week.) Looks good. I suggest two things:

1. To only enable adding a sub-project to a superordinated project, i.e. to omit the "Superordinated Project" field from the template. 
2. To show superordinated projects (or programmes) in the project profile I'd use another wording. The best thing that comes to mind is "Part of". Perhaps somebody has a better idea...

**Comment by trugwaldsaenger** [comment]
> Thanks for taking this over. (I have been covered with different other stuff this week.) Looks good. I suggest two things:
I agree - it looks good, so thanks very much!

> To only enable adding a sub-project to a superordinated project, i.e. to omit the "Superordinated Project" field from the template.
+1 I think this will be enough for the beginning and nobody will be confused. If we see a need to expand the structure in the future, we still can add the Superordinated Field.

>To show superordinated projects (or programmes) in the project profile I'd use another wording. The best thing that comes to mind is "Part of". Perhaps somebody has a better idea...
No better idea from my side. What would be the wording for the profile of the superordinated project/program? "Includes"?

Just one minor issue: Right now a project can become part of itself:
https://beta.oerworldmap.org/resource/urn:uuid:b929a757-7848-4122-a56e-c45a6855aa7a
I guess we have to block this.

**Comment by literarymachine** [comment]
> I guess we have to block this.

Do we really have to? It does not break anything (expect for logic maybe).

**Comment by acka47** [comment]
> What would be the wording for the profile of the superordinated project/program? "Includes"?

What about "Subproject"?

**Comment by literarymachine** [comment]
> What about "Subproject"?

What we have right now is: "Sub project".

**Comment by acka47** [comment]
This must be the reason I didn't talk about it in the first place. :-) But I think you write it as one word, see https://en.wiktionary.org/wiki/subproject and https://www.google.de/search?q=%22sub+project%22 vs. https://www.google.de/search?q=%22subproject%22

**Comment by literarymachine** [comment]
> To only enable adding a sub-project to a superordinated project, i.e. to omit the "Superordinated Project" field from the template.
To show superordinated projects (or programmes) in the project profile I'd use another wording. The best thing that comes to mind is "Part of". Perhaps somebody has a better idea...

Deployed to beta and, as discussed offline with @trugwaldsaenger, to production. To be continued.

**Comment by literarymachine** [comment]
To be continued.

**Comment by karindr** [comment]
It would be good to have the possibility to connect a project to a superordinated project by choosing the superordinated project in the template for the project itself. People won't like having to go to the superordinated project and edit this entry to get this result.

**Comment by literarymachine** [comment]
> It would be good to have the possibility to connect a project to a superordinated project by choosing the superordinated project in the template for the project itself. People won't like having to go to the superordinated project and edit this entry to get this result.

I totally agree, but up there in https://github.com/hbz/oerworldmap/issues/953#issuecomment-265817529, @acka47 and @trugwaldsaenger asked me to remove it.

**Comment by acka47** [comment]
We decided  again include the possibility to add a superordinated project to a project.
