### ISSUE TITLE
Show funding information in Project profiles

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#955]

**Comment by literarymachine** [comment]
@acka47 a first iteration of the additions to `Project` views and forms is now on beta. Not requesting a pull yet because stuff like labels for the properties are missing. I kept it this way to demonstrate the structure; each `Project` no implicitly has one grant with a duration, a funder, a momentary value etc. Edit e.g. https://beta.oerworldmap.org/resource/urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd and note the `Grant.*` fields at the bottom.

We can make this a one to many or even many to many relation at some point, but I believe `Grant`s should then be first class citizens, i.e. have their own IDs and be linkable etc.

**Comment by literarymachine** [comment]
@acka47 with the new intermediate `Grant` introduced, we have some fields in the input template that we might want to simplify. On the one hand, we have `startTime` and `endTime` for the project itself, but we also have `hasAwardDate` and `duration` for the Grant. To keep things simple, I would suggest only using one of these to start with.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:e3435387-e904-453f-b3fe-6a8794b396e5. Because I reset the database, you will have to create new accounts to test the input templates, sorry about that!

**Comment by karindr** [comment]
+1

But do we really want the time to be displayed here? I think there should be only the date.
