### ISSUE TITLE
Translate UI to German

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#957]

**Comment by acka47** [comment]
Has #761 as prerequisite.

**Comment by karindr** [comment]
Gute Vorarbeit, steige dann morgen ein.

**Comment by karindr** [comment]
For countries and languages in the dropdown lists in the templates and in the filter section there are allready lists in German. What about the licences, subjects and audience? These lists are our own and have to be translated, is this right?

**Comment by literarymachine** [comment]
> What about the licences, subjects and audience? These lists are our own and have to be translated, is this right?

Yes, you are right! The translations for these would have to be added to the corresponding [vocabs](https://github.com/hbz/vocabs-edu). /cc @acka47

**Comment by karindr** [comment]
All lists are now in German, so +1.

**Comment by acka47** [comment]
Closing.
