### ISSUE TITLE
Making error message easier to understand

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#958]
Even experienced users as Werner Westermann have sometimes problems with the error message. For the first step it may help if it is clearly indicated which field is wrong. Knowing this the users can leave this field empty but can save the rest of the work they did.
As also mentioned in the FAQ for Editors it is mostly the date format. If there was a clear error message for this case we maybe have covered 50 % of all errors.
In a second step later on there should be an explication about the right format for the field with the wrong input adjusted to all different fields.

**Comment by literarymachine** [comment]
> As also mentioned in the FAQ for Editors it is mostly the date format. If there was a clear error message for this case we maybe have covered 50 % of all errors.

On beta, try e.g. adding an `Event` with an invalid `startDate`.

**Comment by karindr** [comment]
That is a good idea!
But the little pointing window disappears after 5 seconds, this is to quick. First time I only realized that there is something. 
I think it should not disappear by itself at all. And it could have the exclamation mark on a red background because it is not really catching the eye at the moment. The text could be "Invalid entry. It has to be YYYY-MM-DD."

**Comment by literarymachine** [comment]
> But the little pointing window disappears after 5 seconds, this is to quick.

The current solution is based on native browser functionality which means I cannot alter the behavior. What I could easily do is something like on beta now where the input is validated right away when being entered. Let me know if I should deploy this, for anything more advanced I will have to sit down with @formimkontext and @j0hj0h.

**Comment by karindr** [comment]
That's sad, it would have been so nice and easy. OK, I think it is a good interims solution anyway. 
Can you make the sign more striking (i.e. red)? Can you change the text (see above)? The other text seem to be in German (Geben Sie eine URL ein). Or is this also my browser choosing the language?

**Comment by literarymachine** [comment]
> Can you make the sign more striking (i.e. red)?

No, as said above the sign is an internal browser feature.

> The other text seem to be in German (Geben Sie eine URL ein). Or is this also my browser choosing the language?

Yes, exactly. I would say we deploy this because as it is now, the input is validated while typing. Not to many people will leave the input with a red background and submit the form anyways. But if they do, the input is still red plus there is the popup.

**Comment by karindr** [comment]
+1
