### ISSUE TITLE
Two services are not listed in spite of the correct location of the provider

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#965]
When searching with filter Canada and service there are 6 entries found restricted to map and 8 without restriction. But I can’t find any difference, both missing entries have providers with pin in Canada:

- https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=CA&filter.about.@type=Service#urn:uuid:6fdf0de5-8d03-4adc-8429-427d8fb1e43d
- https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=CA&filter.about.@type=Service#urn:uuid:c1c9fe50-7f00-11e5-a636-c48e8ff4ea31

**Comment by literarymachine** [comment]
Deployed to production, see e.g. https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=CA&filter.about.@type=Service

**Comment by literarymachine** [comment]
@karindr you might need to force refresh the browser by pressing CTRL and F5.

**Comment by karindr** [comment]
+1
