### ISSUE TITLE
Dark background for white logos

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#966]
Often logos of organisations are white on a dark background. Is there an easy way to make the background for these logos on the map dark as well?

**Comment by formimkontext** [comment]
Currently logos and pictures have a 10 px padding. I guess that is, what you talking about. In newer drafts pictures are shown without a padding to the border. I think we will fix this by reorganising the single resource view.

**Comment by karindr** [comment]
Sorry, I did not make it very clear. I was speaking of logos with white letters and transparent background designed for dark backgrounds. These logos are nearly not visible on the map, see below. Maybe there could be a checkbox in the input template  to change the background of the logo on the map to dark grey or something like that.
https://oerworldmap.org/resource/urn:uuid:4de8f800-ddc0-4372-a8e3-6a61ce3086f9

**Comment by j0hj0h** [comment]
I had the same idea, but think this isn't  good solution. On the one hand side our content should work independent of a specific stylesheet (in any data exports, style information wouldn't be available and e.g. for printing, browsers ignore background colors) and on the other hand logos actually should always have a version that work on white backgrounds.

In case of your example @karindr, dark-on-white versions of the logo are available here: http://www.tru.ca/brandguide/logos.html and I guess in most cases they should be available. If not we could think about a function to invert image files as part of the planned media uploader/manager.

**Comment by karindr** [comment]
I agree that it might be a problem for the export. But I think that changing logos while uploading them could be critical with regard to copyright issues. In most cases we only link to the logos and this is in my opinion saver. But maybe displaying the linked logo on a dart background is also problematic. 

I think I will search for a other version of the logo or otherwise skip the logo.
