### ISSUE TITLE
Unset type specific filters when switching type

### ISSUE THREAD

**Issue by j0hj0h** [hbz/oerworldmap#977]
... currently this is not happening, which leads to invisible filters and empty results.

**Comment by j0hj0h** [comment]
Solution doesn't respect, that there could be type specific filters that exist for different types. But this only applies to services and events currently. Maybe this could be handled in a cleaner way backend-wise where filters that don't apply to a specific type could cause a redirect.

**Comment by literarymachine** [comment]
> Maybe this could be handled in a cleaner way backend-wise where filters that don't apply to a specific type could cause a redirect.

I would opt for a solution that simply unsets all other filters when selecting a type.

**Comment by literarymachine** [comment]
> Solution doesn't respect, that there could be type specific filters that exist for different types. But this only applies to services and events currently. 

I don't understand; when I filter for e.g. `Service` type, then set a `license` filter and then switch the type to `Event`, the `license` filter is correctly unset!

**Comment by j0hj0h** [comment]
Yes, and the subject filter gets unset as well. But it exists for both: events and services. So someone could expect it would stay. In the current filter setup, this is not a problem, I think. I wrote the comment more for documentation and in case we come to a point where the different types have more filters in common.

**Comment by literarymachine** [comment]
Fixed and deployed to production.
