### ISSUE TITLE
Behaviour Restrict-results-to-map-Button

### ISSUE THREAD

**Issue by formimkontext** [hbz/oerworldmap#979]
Once i deactivated the Restrict-results-to-map-Button it should not be activated automatically with a new or adjusted request.

**Comment by karindr** [comment]
I agree!
But please remember: For the start it should not be activated, see our protocol:
"B. Restriction of search results to map display (Pin Aggregation Issue) 
Question: activate "restrict to map" by default, or not?
Answer: If using the map (zoom in, clicking on a cluster) it should be activated, if you access the data using the search or filters, it will be deactivated.
New Wording: "List mapped result only" alternative "Search, as I move the map""

**Comment by karindr** [comment]
At the moment users often will get not all results when searching because the check box is "restricted to the map". I have to remove this check on every search I am doing. It is totally misleading. Please change this as we decided in the team meeting (see above).
@literarymachine: I assign you to this. If it is not your job, please assign someone else. Thanks!

**Comment by literarymachine** [comment]
On beta, "Search as I move the map" is now disabled by default, and the status is saved in the session so if you enable it it stays enabled and if you disable it again, it stays disabled.

As for automatically enabling it when zooming into to the map etc, we have to put some more thought into this as this can be very confusing if enabled / disabled automatically.

**Comment by acka47** [comment]
+1

**Comment by karindr** [comment]
+1

 In my opinion "Search as I move the map" is not really clear. I would suggest to use "Restrict results to shown part of the map".

**Comment by literarymachine** [comment]
> In my opinion "Search as I move the map" is not really clear. I would suggest to use "Restrict results to shown part of the map".

We basically had this initially and decided to use the new wording at our last meeting because "Restrict results..." was unclear for some.

**Comment by karindr** [comment]
No, it was "Restrict results to map". The difference is "shown part of the map".
