### ISSUE TITLE
German and English name are shown both in label

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#981]
... although the are correctly entered as German and English: 
![image](https://cloud.githubusercontent.com/assets/18674205/21095623/9e213466-c05c-11e6-9a14-36db4360b5a3.png)
https://oerworldmap.org/resource/urn:uuid:b1b88050-8808-4fc5-90b5-b6a6f5dc53b8

**Comment by literarymachine** [comment]
On beta:

![screenshot from 2016-12-13 12-10-32](https://cloud.githubusercontent.com/assets/149825/21138200/423779c2-c12d-11e6-86a7-fe059a89be8f.png)

**Comment by karindr** [comment]
+1
