### ISSUE TITLE
Rename "action" to "project" on project pages

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#982]
Next to the gear wheel icon on the top ther is "action" instead of "project", see for example:
https://oerworldmap.org/resource/urn:uuid:ef4ed9cd-ec9c-46bc-981a-01cabefb66bc

**Comment by literarymachine** [comment]
On beta:

![screenshot from 2016-12-13 12-10-58](https://cloud.githubusercontent.com/assets/149825/21138241/61a0031a-c12d-11e6-9c8e-e5b5fb0cb045.png)

**Comment by karindr** [comment]
+1
