### ISSUE TITLE
&sup3; does not work in name and alternate name field

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#983]
See in alternate name (name did not work either):
https://oerworldmap.org/resource/urn:uuid:5f023a27-3975-41a6-bd29-b94970b7bc9d
In the text it works.

**Comment by literarymachine** [comment]
Why not simply use unicode as in `Mat³`?

https://beta.oerworldmap.org/resource/urn:uuid:78f4554a-37a9-43b5-827e-107592ed250b

**Comment by literarymachine** [comment]
`alt gr + 3`

**Comment by karindr** [comment]
OK, I did not expect that this would work so I did not try it.

(To understand the difference in reaction between the name field and the body field: Does only the body field support HTML?)

**Comment by literarymachine** [comment]
> To understand the difference in reaction between the name field and the body field: Does only the body field support HTML?

Exactly, the body of an article (and also other `description` fields) support markdown/HTML, including HTML entities.

**Comment by karindr** [comment]
Thanks!
