### ISSUE TITLE
Navigation bar hides navigation elements below on iPad

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#986]
See:
![img_0119](https://cloud.githubusercontent.com/assets/18674205/21175507/e8265186-c1e2-11e6-8139-6e1e80f622e9.PNG)
(This is a hint of a user.)

**Comment by literarymachine** [comment]
Has to be tested on iOS Firefox ... nevertheless, header has fixed height now, so worst case the "map" will be lost in the logo. On beta.

**Comment by karindr** [comment]
I will test it on  iOS Firefox at home later.

**Comment by karindr** [comment]
If the window is small on Firefox om IOS the browser puts "Join us in mapping OER" into a second line and hides the search field.
