### ISSUE TITLE
Add attendee property for Events

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#988]
For #945, `Person` must be linkable to `Event` as an `http://schema.org/attendee`.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/urn:uuid:d9f68f2c-fb43-47f5-94f0-8c305c203788

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
+1 What about using "Attendees" instead of "People attending" at [event profile](https://beta.oerworldmap.org/resource/urn:uuid:d9f68f2c-fb43-47f5-94f0-8c305c203788)?

**Comment by literarymachine** [comment]
> What about using "Attendees" instead of "People attending"

I thought that it might be a good idea to

**Comment by literarymachine** [comment]
oops
