### ISSUE TITLE
Include keywords and description when searching

### ISSUE THREAD

**Issue by literarymachine** [hbz/oerworldmap#994]
In bda7bbceb39b80e2d0545e8a0ffcc5e8a3235e55 I tried adding

    "boost:about.keywords"=1

to conf/search.conf. While this does work for most keywords, it does not work for "TVET". @philboeselager do you have any idea what might cause this?

**Comment by literarymachine** [comment]
> Search for TVET works as a UnitTest - see f9c137e.

On my machine, this test is failing. Same on Travis: https://travis-ci.org/hbz/oerworldmap/builds/187481679#L1014

**Comment by literarymachine** [comment]
> On beta searching for "TVET" does not deliver any results:

Yes, because we are still working on this issue and have thus not deployed a fix anywhere yet. As stated in the title of this issue, neither `keywords` nor `description` is currently evaluated when searching.

**Comment by literarymachine** [comment]
> Maybe something to do with an older mapping?

@philboeselager : it was not an older mapping, but the mapping is indeed involved. The search analyzer, see e7ee438791349d763efa32d53b58b4efa3529ef0, caused the zero results for `TVET`. But removing that analyzer then broke the test for #831. I re-added the analyzer settings, but on a per-field basis in the mapping instead of for all fields as it was in `ElasticsearchRepository`, see f222c4ccd962a86acfcd8712c632730e7cbe1dd1. That fixed it.

**Comment by literarymachine** [comment]
On beta, see https://beta.oerworldmap.org/resource/?q=TVET

**Comment by literarymachine** [comment]
@trugwaldsaenger I also went ahead and re-indexed on production, see e.g. https://oerworldmap.org/resource/?q=TVET which now includes the previously missing result "Federal Institute for Vocational Education and Training". Hope that's ok!

**Comment by philboeselager** [comment]
> On my machine, this test is failing. Same on Travis: https://travis-ci.org/hbz/oerworldmap/builds/187481679#L1014

I've re-checked that on my machine. While the test works when run in the IDE, it does fail when run by `sbt test`. I didn't expect that at all (that's why I didn't check it beforehand).

**Comment by trugwaldsaenger** [comment]
Looks good to me - thanks very much! The search result list needs some more refinement - I will open another ticket for this!
