### ISSUE TITLE
Add resulting service to project template

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#995]
Sometimes the goal of a project is to create a service as for example mentioned in the FAQ for editors for the OER World Map project and the OER World Map as service, see:
https://github.com/hbz/oerworldmap/wiki/FAQs-for-OER-World-Map-editors#service-organization-or-project
Why is there no direct way to connect them?
In an other example the connection over the provider is even weaker than the connection over the hbz for project and service mentioned above: 
http://www.refrer.licef.ca/
This is a Canadian portal which I think is to be classified as service and there is also the the project REFERER which aimed to build this portal. Both are linked to TELUQ but in my opinion this is a weak link because only a little part of this institution is connected to the service and to the project.

**Comment by literarymachine** [comment]
We actually have http://schema.org/result to link a Service to a Project in our schema. For some reason, the corresponding form fields have been hidden so far. Should I show them?

**Comment by karindr** [comment]
In my opinion the fields should be shown at in the template for the projects.

**Comment by acka47** [comment]
I adjusted the title of the issue and removed the "question" label. Should we start with only allowing services as result of a project? I think this makes sense and we can then add resources at a later point as soon as you are able to recor them on the map. Remains the question how to name the field and what help text to add. I suggest: 

> Resulting Service – an online offer that is the result of the project

**Comment by karindr** [comment]
+1

**Comment by karindr** [comment]
It is done.
