### ISSUE TITLE
project does not appear in country view

### ISSUE THREAD

**Issue by karindr** [hbz/oerworldmap#996]
I added a project to the map and liked it to a Canadian organisation, but the project is not shown in the list for Canada nor is it counted in the summary. The project is:
https://oerworldmap.org/resource/urn:uuid:38449de3-9e52-4716-86e6-b69f47c62b4f
The organisation linked to is shown and counted:
https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=CA&filter.about.@type=Organization#urn:uuid:3a625a9c-95ea-4f93-b174-a45b99539a5b

**Comment by karindr** [comment]
This one is also missing:
https://oerworldmap.org/resource/?q=&filter.about.%40type=Action#urn:uuid:e5579da0-ff00-4db2-ab70-90640ab92ddc

**Comment by literarymachine** [comment]
This is not a bug, see https://github.com/hbz/oerworldmap/pull/872#issue-178019987. It would be great if @karindr @acka47 and @trugwaldsaenger could agree on and document an expected behavior with regards to which relations should "inherit" the `location` of it's parents.

**Comment by karindr** [comment]
Ok, now I remember the discussions we had when talking about the new version in the summer. I think we should leave it the way it is. @acka47 @trugwaldsaenger agreed.

I added the country manually to the projects, now they are shown for Canada.

**Comment by literarymachine** [comment]
As discussed with @acka47, we will "inherit" all the same relations as [here](https://github.com/hbz/oerworldmap/blob/master/public/javascripts/behaviours/map.js#L651).

**Comment by karindr** [comment]
Could you explain this? Did you change the behavior? Does projects inherit the location now or not?

**Comment by acka47** [comment]
@literarymachine will deploy the changes (projects inheriting the locations from  agent/operator in the search index) and we will check out whether there are any bigger problems with this approach.

**Comment by literarymachine** [comment]
On beta, see e.g. https://beta.oerworldmap.org/resource/?q=some+project&filter.about.location.address.addressCountry=DE#urn:uuid:ed95f8cc-23a8-4eb6-a147-c40b7062fe7b for a project that does not have a location of its own but is yet displayed in the country of its operator.

**Comment by karindr** [comment]
+1

**Comment by acka47** [comment]
Looks good. I am not sure but it probably is the right behaviour that pins are only highlighted for a project while pins of other entries nearb are also shown? See for example the World Map project with two operators: https://beta.oerworldmap.org/resource/urn:uuid:43526b28-66f8-49bb-bf1c-c3cb8d4bbbcd

**Comment by karindr** [comment]
I think this is clear. It is similar to the behavior when choosing one entry from a list, e.g.:
https://oerworldmap.org/resource/?filter.about.location.address.addressCountry=SE&filter.about.@type=Service#urn:uuid:0642e71f-ca55-409b-a5b4-c4384b4e67c9
I think it is a good thing when things behave in a similar way.

**Comment by acka47** [comment]
Ok, I couldn't remember and didn't just look for myself (sorry). I think the behaviour is good, also when two or more agents are operator, thus:

+1
